import type { SaintSeedData } from './types';

export const augustSaints: SaintSeedData[] = [
  {
    name: 'Santo Afonso de Ligório',
    slug: 'santo-afonso-de-ligorio',
    feastMonth: 8,
    feastDay: 1,
    birthDate: '1696-09-27',
    deathDate: '1787-08-01',
    birthPlace: 'Marianella',
    deathPlace: 'Pagani',
    country: 'Itália',
    century: 18,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos moralistas', 'confessores'],
    biographyShort: 'Bispo, fundador dos Redentoristas e Doutor da Igreja, Afonso dedicou-se à evangelização dos pobres e é célebre por sua teologia moral.',
    biographyFull: 'Santo Afonso nasceu em Nápoles em 1696, numa família nobre. Advogado brilhante, abandonou a carreira jurídica após uma derrota no tribunal e abraçou o sacerdócio.\n\nFundou a Congregação do Santíssimo Redentor em 1732 para evangelizar os mais abandonados do campo. Sua obra de teologia moral tornou-se referência na Igreja, equilibrando rigorismo e laxismo.\n\nFoi nomeado bispo de Sant\'Agata dei Goti e, mesmo sofrendo de graves enfermidades, governou com zelo pastoral. Faleceu em 1787 e foi proclamado Doutor da Igreja em 1871.',
    biographyKids: null,
    quotes: [{ text: 'Quem reza se salva, quem não reza se condena.', source: 'Santo Afonso de Ligório' }],
    prayer: null,
    imageUrl: null,
    latitude: 40.8518,
    longitude: 14.2681,
  },
  {
    name: 'Santo Eusébio de Vercelli',
    slug: 'santo-eusebio-de-vercelli',
    feastMonth: 8,
    feastDay: 2,
    birthDate: '283-01-01',
    deathDate: '371-08-01',
    birthPlace: 'Sardenha',
    deathPlace: 'Vercelli',
    country: 'Itália',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Vercelli', 'catequistas'],
    biographyShort: 'Primeiro bispo de Vercelli, Eusébio combateu o arianismo com firmeza e sofreu o exílio por defender a fé nicena.',
    biographyFull: 'Eusébio nasceu na Sardenha por volta de 283 e foi o primeiro bispo de Vercelli, no norte da Itália. Introduziu a vida comunitária entre o clero diocesano, unindo vida monástica e pastoral.\n\nDefensor incansável da ortodoxia contra o arianismo, foi exilado pelo imperador Constâncio II após o Concílio de Milão de 355. Sofreu maus-tratos durante o exílio na Palestina, Capadócia e Tebaida.\n\nApós a morte de Constâncio, retornou a Vercelli e continuou seu trabalho pastoral até falecer em 371, venerado como confessor da fé.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.3252,
    longitude: 8.4283,
  },
  {
    name: 'São Domingos de Gusmão',
    slug: 'sao-domingos-de-gusmao',
    feastMonth: 8,
    feastDay: 3,
    birthDate: '1170-08-08',
    deathDate: '1221-08-06',
    birthPlace: 'Caleruega',
    deathPlace: 'Bolonha',
    country: 'Espanha',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['astrônomos', 'pregadores'],
    biographyShort: 'Fundador da Ordem dos Pregadores (dominicanos), Domingos combateu a heresia cátara no sul da França com a pregação e a oração do Rosário.',
    biographyFull: 'Domingos nasceu em Caleruega, Castela, por volta de 1170. Estudou teologia em Palência e tornou-se cônego regular. Durante uma viagem pela França, deparou-se com a heresia albigense e sentiu-se chamado à pregação itinerante.\n\nEm 1216 fundou a Ordem dos Pregadores, combinando vida contemplativa, estudo teológico e pregação apostólica. A tradição atribui-lhe a difusão do Rosário, recebido da Virgem Maria.\n\nSua ordem espalhou-se rapidamente pela Europa, formando grandes teólogos como Santo Tomás de Aquino. Domingos faleceu em Bolonha em 1221 e foi canonizado em 1234.',
    biographyKids: null,
    quotes: [{ text: 'Falava com Deus ou de Deus.', source: 'Lema sobre São Domingos' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.8221,
    longitude: -3.4482,
  },
  {
    name: 'São João Maria Vianney',
    slug: 'sao-joao-maria-vianney',
    feastMonth: 8,
    feastDay: 4,
    birthDate: '1786-05-08',
    deathDate: '1859-08-04',
    birthPlace: 'Dardilly',
    deathPlace: 'Ars-sur-Formans',
    country: 'França',
    century: 19,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['párocos', 'sacerdotes'],
    biographyShort: 'Conhecido como o Cura d\'Ars, João Maria Vianney transformou a paróquia de Ars com sua santidade, passando até 18 horas por dia no confessionário.',
    biographyFull: 'João Maria Vianney nasceu em Dardilly, perto de Lyon, em 1786. Enfrentou grandes dificuldades nos estudos, mas foi ordenado sacerdote em 1815 graças à sua piedade exemplar.\n\nNomeado pároco de Ars em 1818, encontrou uma comunidade indiferente à fé. Com oração, penitência e dedicação incansável ao confessionário, converteu toda a paróquia. Peregrinos de toda a França acorriam para confessar-se com ele.\n\nSofreu ataques espirituais que atribuía ao demônio. Faleceu em 1859 e foi proclamado padroeiro dos párocos por Pio XI em 1929.',
    biographyKids: null,
    quotes: [{ text: 'O sacerdócio é o amor do Coração de Jesus.', source: 'São João Maria Vianney' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.8167,
    longitude: 4.7167,
  },
  {
    name: 'Dedicação Basílica Santa Maria Maior',
    slug: 'dedicacao-basilica-santa-maria-maior',
    feastMonth: 8,
    feastDay: 5,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['devoção mariana', 'Roma'],
    biographyShort: 'A Basílica de Santa Maria Maior em Roma foi dedicada no século V, sendo a mais antiga igreja do Ocidente consagrada à Virgem Maria.',
    biographyFull: 'A festa celebra a dedicação da Basílica de Santa Maria Maior, no monte Esquilino em Roma. Segundo a tradição, a Virgem Maria apareceu ao papa Libério e ao patrício João, pedindo que construíssem uma igreja no local onde nevasse.\n\nEm 5 de agosto de 358, neve milagrosa cobriu o cume do Esquilino em pleno verão, marcando o lugar escolhido. A basílica atual foi construída pelo papa Sisto III após o Concílio de Éfeso (431), que proclamou Maria como Mãe de Deus.\n\nÉ uma das quatro basílicas papais de Roma e guarda a relíquia do presépio de Belém. Sua dedicação recorda a importância da devoção mariana na vida da Igreja.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.8976,
    longitude: 12.4984,
  },
  {
    name: 'Transfiguração do Senhor',
    slug: 'transfiguracao-do-senhor',
    feastMonth: 8,
    feastDay: 6,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Monte Tabor',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['contemplação', 'vida espiritual'],
    biographyShort: 'A Transfiguração de Jesus no Monte Tabor revelou sua glória divina a Pedro, Tiago e João, confirmando-os na fé antes da Paixão.',
    biographyFull: 'A festa da Transfiguração celebra o episódio em que Jesus subiu ao Monte Tabor com Pedro, Tiago e João, e seu rosto brilhou como o sol enquanto suas vestes tornaram-se brancas como a luz. Moisés e Elias apareceram conversando com ele.\n\nPedro, extasiado, propôs erguer três tendas. Uma nuvem luminosa os cobriu e a voz do Pai declarou: "Este é meu Filho amado, escutai-o." Os apóstolos caíram por terra, mas Jesus os levantou e pediu que guardassem segredo até a ressurreição.\n\nA festa, celebrada desde o século V no Oriente, foi estendida à Igreja universal pelo papa Calisto III em 1457, em ação de graças pela vitória de Belgrado contra os turcos.',
    biographyKids: null,
    quotes: [{ text: 'Este é o meu Filho amado, em quem me comprazo. Escutai-o.', source: 'Mt 17,5' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.6863,
    longitude: 35.3931,
  },
  {
    name: 'São Caetano de Thiene',
    slug: 'sao-caetano-de-thiene',
    feastMonth: 8,
    feastDay: 7,
    birthDate: '1480-10-01',
    deathDate: '1547-08-07',
    birthPlace: 'Vicenza',
    deathPlace: 'Nápoles',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['desempregados', 'trabalhadores'],
    biographyShort: 'Fundador dos Teatinos, Caetano dedicou-se à reforma do clero e à caridade para com os pobres na Itália do século XVI.',
    biographyFull: 'Caetano nasceu em Vicenza em 1480, numa família nobre. Formou-se em Direito em Pádua e serviu na cúria romana antes de ser ordenado sacerdote em 1516.\n\nEm 1524, fundou a Ordem dos Clérigos Regulares (Teatinos) junto com o bispo Gian Pietro Carafa, futuro papa Paulo IV. Os Teatinos viviam em pobreza radical, sem pedir esmolas, confiando inteiramente na Providência.\n\nCaetano fundou hospitais e montes de piedade para combater a usura. Faleceu em Nápoles em 1547, consumido pelo zelo apostólico, e foi canonizado em 1671.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.5455,
    longitude: 11.5354,
  },
  {
    name: 'São Domingos',
    slug: 'sao-domingos',
    feastMonth: 8,
    feastDay: 8,
    birthDate: '1170-08-08',
    deathDate: '1221-08-06',
    birthPlace: 'Caleruega',
    deathPlace: 'Bolonha',
    country: 'Espanha',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['ordem dominicana', 'astrônomos'],
    biographyShort: 'Nesta data a Igreja celebra a memória litúrgica de São Domingos, fundador da Ordem dos Pregadores, apóstolo do Rosário e combatente da heresia.',
    biographyFull: 'São Domingos de Gusmão, celebrado nesta data litúrgica, nasceu em Caleruega, Espanha, por volta de 1170. Após conhecer a devastação da heresia cátara no sul da França, dedicou-se à pregação itinerante com pobreza e estudo.\n\nFundou a Ordem dos Pregadores em 1216, unindo contemplação, estudo e apostolado. Seus frades espalharam-se pelas universidades e cidades da Europa, formando grandes santos e teólogos.\n\nFaleceu em Bolonha em 6 de agosto de 1221. Sua ordem continua presente em todo o mundo, fiel ao carisma de pregar a verdade com caridade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.8221,
    longitude: -3.4482,
  },
  {
    name: 'Santa Teresa Benedita da Cruz',
    slug: 'santa-teresa-benedita-da-cruz',
    feastMonth: 8,
    feastDay: 9,
    birthDate: '1891-10-12',
    deathDate: '1942-08-09',
    birthPlace: 'Breslávia',
    deathPlace: 'Auschwitz',
    country: 'Alemanha',
    century: 20,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['Europa', 'mártires'],
    biographyShort: 'Filósofa judia convertida ao catolicismo, Edith Stein tornou-se carmelita e foi assassinada em Auschwitz, sendo proclamada copadroeira da Europa.',
    biographyFull: 'Edith Stein nasceu em Breslávia em 1891, numa família judia. Brilhante filósofa, foi discípula de Edmund Husserl. Converteu-se ao catolicismo em 1922 após ler a autobiografia de Santa Teresa de Ávila.\n\nEntrou no Carmelo de Colônia em 1933, recebendo o nome Teresa Benedita da Cruz. Com a perseguição nazista, foi transferida para o Carmelo de Echt, na Holanda, mas em 1942 foi presa pela Gestapo.\n\nFoi deportada para Auschwitz, onde morreu na câmara de gás em 9 de agosto de 1942. João Paulo II canonizou-a em 1998 e proclamou-a copadroeira da Europa.',
    biographyKids: null,
    quotes: [{ text: 'Quem busca a verdade busca a Deus, quer o saiba ou não.', source: 'Santa Teresa Benedita da Cruz' }],
    prayer: null,
    imageUrl: null,
    latitude: 51.1079,
    longitude: 17.0385,
  },
  {
    name: 'São Lourenço Diácono',
    slug: 'sao-lourenco-diacono',
    feastMonth: 8,
    feastDay: 10,
    birthDate: '225-01-01',
    deathDate: '258-08-10',
    birthPlace: 'Huesca',
    deathPlace: 'Roma',
    country: 'Espanha',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['cozinheiros', 'bibliotecários'],
    biographyShort: 'Diácono da Igreja de Roma, Lourenço distribuiu os bens da Igreja aos pobres e sofreu o martírio na grelha durante a perseguição de Valeriano.',
    biographyFull: 'Lourenço nasceu em Huesca, Espanha, por volta de 225. Foi para Roma, onde o papa Sisto II o nomeou arquidiácono, responsável pelos bens da Igreja e pelo cuidado dos pobres.\n\nQuando o imperador Valeriano exigiu que entregasse os tesouros da Igreja, Lourenço reuniu os pobres, doentes e viúvas e apresentou-os ao prefeito dizendo: "Estes são os tesouros da Igreja."\n\nFoi condenado a morrer assado numa grelha em 10 de agosto de 258. Segundo a tradição, disse ao carrasco: "Vira-me, que deste lado já estou assado." Seu martírio inspirou muitas conversões em Roma.',
    biographyKids: null,
    quotes: [{ text: 'Estes são os verdadeiros tesouros da Igreja.', source: 'São Lourenço' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.1401,
    longitude: -0.4089,
  },
  {
    name: 'Santa Clara de Assis',
    slug: 'santa-clara-de-assis',
    feastMonth: 8,
    feastDay: 11,
    birthDate: '1194-07-16',
    deathDate: '1253-08-11',
    birthPlace: 'Assis',
    deathPlace: 'Assis',
    country: 'Itália',
    century: 13,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['televisão', 'bordadeiras'],
    biographyShort: 'Fundadora das Clarissas, Clara seguiu o ideal de pobreza de São Francisco e viveu em contemplação e penitência no mosteiro de São Damião.',
    biographyFull: 'Clara nasceu em Assis em 1194, numa família nobre. Inspirada pela pregação de São Francisco, fugiu de casa na noite do Domingo de Ramos de 1212 para abraçar a vida religiosa na pobreza radical.\n\nFrancisco instalou-a no mosteiro de São Damião, onde fundou a Ordem das Damas Pobres (Clarissas). Clara lutou durante toda a vida pelo "Privilégio da Pobreza", o direito de não possuir propriedades, concedido pelo papa.\n\nMesmo acamada por longos anos de doença, governou seu mosteiro com sabedoria. Defendeu Assis dos sarracenos com a custódia eucarística. Faleceu em 1253 e foi canonizada dois anos depois.',
    biographyKids: null,
    quotes: [{ text: 'Olhai-o, contemplai-o, desejando imitá-lo.', source: 'Santa Clara de Assis' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.0707,
    longitude: 12.6196,
  },
  {
    name: 'Santa Joana Francisca de Chantal',
    slug: 'santa-joana-francisca-de-chantal',
    feastMonth: 8,
    feastDay: 12,
    birthDate: '1572-01-28',
    deathDate: '1641-12-13',
    birthPlace: 'Dijon',
    deathPlace: 'Moulins',
    country: 'França',
    century: 17,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['viúvas', 'pais separados dos filhos'],
    biographyShort: 'Viúva e mãe, Joana Francisca cofundou com São Francisco de Sales a Ordem da Visitação, dedicada à vida contemplativa acessível a mulheres frágeis.',
    biographyFull: 'Joana Francisca Frémyot nasceu em Dijon em 1572. Casou-se com o barão de Chantal, com quem teve seis filhos. Após a morte trágica do marido num acidente de caça, consagrou-se inteiramente a Deus.\n\nSob a direção espiritual de São Francisco de Sales, fundou em 1610 a Ordem da Visitação de Santa Maria, aberta a mulheres cuja saúde não permitia os rigores das ordens contemplativas tradicionais.\n\nFundou 87 mosteiros durante sua vida. Sofreu provações interiores intensas, mas manteve firme confiança em Deus. Faleceu em Moulins em 1641 e foi canonizada em 1767.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.3220,
    longitude: 5.0415,
  },
  {
    name: 'Santos Ponciano e Hipólito',
    slug: 'santos-ponciano-e-hipolito',
    feastMonth: 8,
    feastDay: 13,
    birthDate: null,
    deathDate: '235-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Sardenha',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['prisioneiros', 'guardas prisionais'],
    biographyShort: 'O papa Ponciano e o sacerdote Hipólito, antes adversários, reconciliaram-se no exílio na Sardenha e morreram mártires sob o imperador Maximino.',
    biographyFull: 'Ponciano foi papa de 230 a 235, enquanto Hipólito era um presbítero culto que se opusera aos papas anteriores, chegando a ser considerado o primeiro antipapa da história.\n\nO imperador Maximino Trácio deportou ambos para as minas da Sardenha em 235. No sofrimento do exílio, Hipólito reconciliou-se com a Igreja e Ponciano renunciou ao papado para permitir a eleição de um novo pontífice em Roma.\n\nAmbos morreram pelos maus-tratos recebidos nas minas. Seus corpos foram trasladados para Roma e sepultados com honras de mártires. São celebrados juntos desde o século IV.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'São Maximiliano Kolbe',
    slug: 'sao-maximiliano-kolbe',
    feastMonth: 8,
    feastDay: 14,
    birthDate: '1894-01-08',
    deathDate: '1941-08-14',
    birthPlace: 'Zduńska Wola',
    deathPlace: 'Auschwitz',
    country: 'Polônia',
    century: 20,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['prisioneiros políticos', 'jornalistas'],
    biographyShort: 'Frade franciscano, Maximiliano ofereceu sua vida no lugar de um pai de família no campo de concentração de Auschwitz.',
    biographyFull: 'Maximiliano Kolbe nasceu em Zduńska Wola, Polônia, em 1894. Entrou na Ordem dos Frades Menores Conventuais e fundou a Milícia da Imaculada, movimento de evangelização que usava a imprensa como instrumento apostólico.\n\nFundou o convento de Niepokalanów, que se tornou o maior convento franciscano do mundo, e missionou no Japão. Com a invasão nazista, foi preso e enviado a Auschwitz em 1941.\n\nQuando um prisioneiro foi selecionado para morrer de fome como represália, Maximiliano ofereceu-se em seu lugar. Morreu com uma injeção de ácido fênico em 14 de agosto de 1941. Foi canonizado por João Paulo II em 1982.',
    biographyKids: null,
    quotes: [{ text: 'O ódio não é uma força criativa. Somente o amor é criativo.', source: 'São Maximiliano Kolbe' }],
    prayer: null,
    imageUrl: null,
    latitude: 51.5986,
    longitude: 18.9370,
  },
  {
    name: 'Assunção de Nossa Senhora',
    slug: 'assuncao-de-nossa-senhora',
    feastMonth: 8,
    feastDay: 15,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['morte feliz', 'vida eterna'],
    biographyShort: 'A Assunção celebra a elevação de Maria, corpo e alma, à glória celeste, dogma proclamado pelo papa Pio XII em 1950.',
    biographyFull: 'A solenidade da Assunção de Nossa Senhora é a mais antiga e importante festa mariana da Igreja. Celebra a crença de que Maria, ao término de sua vida terrena, foi elevada de corpo e alma à glória celestial.\n\nEssa fé esteve presente na tradição cristã desde os primeiros séculos, tanto no Oriente como no Ocidente. Em 1º de novembro de 1950, o papa Pio XII proclamou solenemente o dogma da Assunção pela constituição apostólica Munificentissimus Deus.\n\nA festa recorda que o destino de Maria é também a esperança de todos os cristãos: a ressurreição do corpo e a vida eterna junto de Deus.',
    biographyKids: null,
    quotes: [{ text: 'A minha alma engrandece o Senhor e o meu espírito exulta em Deus, meu Salvador.', source: 'Lc 1,46-47' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'Santo Estêvão da Hungria',
    slug: 'santo-estevao-da-hungria',
    feastMonth: 8,
    feastDay: 16,
    birthDate: '975-01-01',
    deathDate: '1038-08-15',
    birthPlace: 'Esztergom',
    deathPlace: 'Székesfehérvár',
    country: 'Hungria',
    century: 11,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['Hungria', 'reis'],
    biographyShort: 'Primeiro rei cristão da Hungria, Estêvão unificou as tribos magiares e evangelizou seu povo, tornando-se o fundador da nação húngara.',
    biographyFull: 'Estêvão nasceu por volta de 975, filho do chefe magiar Géza. Foi batizado na infância e recebeu educação cristã. Ao suceder seu pai, unificou as tribos húngaras e recebeu a coroa real do papa Silvestre II no ano 1000.\n\nOrganizou a Igreja na Hungria, fundando dioceses, mosteiros e escolas. Promulgou leis inspiradas no Evangelho e incentivou a peregrinação a Jerusalém. Sofreu com a morte prematura de seu filho Emerico.\n\nConsagrou a Hungria à Virgem Maria e é venerado como o pai da nação. Faleceu em 1038 e foi canonizado em 1083.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.7856,
    longitude: 18.7372,
  },
  {
    name: 'Santa Jacinta de Fátima',
    slug: 'santa-jacinta-de-fatima',
    feastMonth: 8,
    feastDay: 17,
    birthDate: '1910-03-11',
    deathDate: '1920-02-20',
    birthPlace: 'Aljustrel',
    deathPlace: 'Lisboa',
    country: 'Portugal',
    century: 20,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['crianças doentes', 'meditação'],
    biographyShort: 'Uma das três pastorinhas de Fátima, Jacinta ofereceu seus sofrimentos pela conversão dos pecadores e faleceu aos nove anos.',
    biographyFull: 'Jacinta Marto nasceu em Aljustrel, Portugal, em 1910. Em 1917, junto com seu irmão Francisco e sua prima Lúcia, recebeu as aparições de Nossa Senhora em Fátima, que pediu oração e penitência pela conversão dos pecadores.\n\nA visão do inferno impressionou profundamente Jacinta, que passou a oferecer todos os seus sacrifícios pelas almas. Adoeceu com a gripe espanhola em 1918 e sofreu longamente.\n\nFoi levada a Lisboa para tratamento, onde morreu sozinha num hospital em 20 de fevereiro de 1920, aos nove anos. Foi canonizada pelo papa Francisco em 2017.',
    biographyKids: null,
    quotes: [{ text: 'Ó meu Jesus, é por vosso amor e pela conversão dos pecadores.', source: 'Oração de Fátima' }],
    prayer: null,
    imageUrl: null,
    latitude: 39.6318,
    longitude: -8.6739,
  },
  {
    name: 'Santa Helena',
    slug: 'santa-helena',
    feastMonth: 8,
    feastDay: 18,
    birthDate: '248-01-01',
    deathDate: '330-01-01',
    birthPlace: 'Drépano',
    deathPlace: 'Roma',
    country: 'Turquia',
    century: 4,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['arqueólogos', 'casamentos difíceis'],
    biographyShort: 'Mãe do imperador Constantino, Helena peregriu à Terra Santa onde, segundo a tradição, encontrou a Verdadeira Cruz de Cristo.',
    biographyFull: 'Helena nasceu por volta de 248 em Drépano, na Bitínia (atual Turquia). De origem humilde, casou-se com o oficial romano Constâncio Cloro, que a repudiou por razões políticas. Seu filho Constantino tornou-se imperador.\n\nConvertida ao cristianismo, Helena usou sua influência para promover a fé. Por volta de 326, já octogenária, peregrinou à Terra Santa, onde mandou escavar o Calvário e, segundo a tradição, encontrou a Cruz de Cristo.\n\nMandou construir basílicas no Santo Sepulcro e em Belém. Praticou grande caridade com os pobres e prisioneiros. Faleceu em Roma por volta de 330.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.6430,
    longitude: 29.2780,
  },
  {
    name: 'São João Eudes',
    slug: 'sao-joao-eudes',
    feastMonth: 8,
    feastDay: 19,
    birthDate: '1601-11-14',
    deathDate: '1680-08-19',
    birthPlace: 'Ri',
    deathPlace: 'Caen',
    country: 'França',
    century: 17,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['pregadores de missões', 'seminários'],
    biographyShort: 'Apóstolo dos Sagrados Corações, João Eudes fundou a Congregação de Jesus e Maria e promoveu a devoção litúrgica ao Coração de Jesus e ao Coração de Maria.',
    biographyFull: 'João Eudes nasceu em Ri, Normandia, em 1601. Ordenado no Oratório de Bérulle, dedicou-se a missões populares na França durante mais de quarenta anos, percorrendo paróquias e pregando a conversão.\n\nFundou a Congregação de Jesus e Maria (Eudistas) para a formação do clero e a Ordem de Nossa Senhora da Caridade para acolher mulheres em dificuldade. Foi o primeiro a promover a celebração litúrgica dos Sagrados Corações.\n\nEnfrentou grande oposição dos jansenistas, mas perseverou em sua missão. Faleceu em Caen em 1680 e foi canonizado em 1925.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.8350,
    longitude: -0.0730,
  },
  {
    name: 'São Bernardo de Claraval',
    slug: 'sao-bernardo-de-claraval',
    feastMonth: 8,
    feastDay: 20,
    birthDate: '1090-01-01',
    deathDate: '1153-08-20',
    birthPlace: 'Fontaine-lès-Dijon',
    deathPlace: 'Claraval',
    country: 'França',
    century: 12,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['apicultores', 'fabricantes de velas'],
    biographyShort: 'Doutor da Igreja e abade de Claraval, Bernardo foi o mais influente monge cisterciense, pregador da Segunda Cruzada e grande devoto da Virgem Maria.',
    biographyFull: 'Bernardo nasceu em Fontaine-lès-Dijon em 1090, numa família nobre da Borgonha. Em 1112 entrou no mosteiro cisterciense de Cîteaux com trinta companheiros, incluindo irmãos e parentes.\n\nEm 1115 fundou a abadia de Claraval, que se tornou centro irradiador da reforma cisterciense. Sob sua liderança, a ordem expandiu-se para mais de 300 mosteiros. Seus escritos sobre o amor de Deus e seus sermões sobre o Cântico dos Cânticos são obras-primas da mística cristã.\n\nConselheiro de papas e reis, pregou a Segunda Cruzada a pedido do papa Eugênio III. Faleceu em 1153 e foi proclamado Doutor da Igreja em 1830.',
    biographyKids: null,
    quotes: [{ text: 'A medida do amor a Deus é amá-lo sem medida.', source: 'São Bernardo de Claraval' }],
    prayer: null,
    imageUrl: null,
    latitude: 47.3297,
    longitude: 5.0135,
  },
  {
    name: 'São Pio X',
    slug: 'sao-pio-x',
    feastMonth: 8,
    feastDay: 21,
    birthDate: '1835-06-02',
    deathDate: '1914-08-20',
    birthPlace: 'Riese',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 20,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['catequistas', 'primeiras comunhões'],
    biographyShort: 'Papa da renovação litúrgica e da comunhão frequente, Pio X combateu o modernismo e antecipou a idade da primeira comunhão das crianças.',
    biographyFull: 'Giuseppe Sarto nasceu em Riese, norte da Itália, em 1835, filho de uma família humilde. Percorreu todos os graus do ministério: vigário, pároco, cônego, bispo de Mântua e patriarca de Veneza, antes de ser eleito papa em 1903.\n\nComo papa, promoveu a comunhão frequente e antecipou a primeira comunhão para a idade da razão. Reformou a música sacra, codificou o direito canônico e combateu os erros do modernismo.\n\nSeu lema era "Restaurar tudo em Cristo". Morreu em 20 de agosto de 1914, poucos dias após o início da Primeira Guerra Mundial. Foi canonizado em 1954.',
    biographyKids: null,
    quotes: [{ text: 'Restaurar todas as coisas em Cristo.', source: 'Lema de São Pio X' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.7280,
    longitude: 11.8590,
  },
  {
    name: 'Santa Maria Rainha',
    slug: 'santa-maria-rainha',
    feastMonth: 8,
    feastDay: 22,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['realeza de Maria', 'paz no mundo'],
    biographyShort: 'A memória de Maria Rainha celebra a realeza da Virgem sobre toda a criação, instituída por Pio XII em 1954.',
    biographyFull: 'A festa de Santa Maria Rainha foi instituída pelo papa Pio XII em 1954, pela encíclica Ad Caeli Reginam, e inicialmente celebrada em 31 de maio. A reforma litúrgica de 1969 transferiu-a para 22 de agosto, oitava da Assunção.\n\nA realeza de Maria fundamenta-se em sua maternidade divina: sendo Mãe do Rei dos reis, ela participa da realeza de seu Filho. Os Padres da Igreja e a tradição sempre a honraram com o título de Rainha.\n\nMaria é Rainha não pelo poder terreno, mas pelo serviço e pela intercessão. Sua realeza é inseparável de sua maternidade espiritual sobre todos os fiéis.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'Santa Rosa de Lima',
    slug: 'santa-rosa-de-lima',
    feastMonth: 8,
    feastDay: 23,
    birthDate: '1586-04-20',
    deathDate: '1617-08-24',
    birthPlace: 'Lima',
    deathPlace: 'Lima',
    country: 'Peru',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['América Latina', 'floristas'],
    biographyShort: 'Primeira santa canonizada das Américas, Rosa viveu em Lima com extraordinária penitência e mística, sendo modelo de santidade no Novo Mundo.',
    biographyFull: 'Isabel Flores de Oliva nasceu em Lima, Peru, em 1586. Recebeu o apelido de Rosa pela beleza de seu rosto. Desde jovem praticou rigorosa penitência e oração, recusando pretendentes ao casamento.\n\nTerciária dominicana, viveu numa pequena cela no jardim de sua casa, onde se entregava à contemplação e ao cuidado dos pobres e doentes. Experimentou grandes consolações místicas, mas também períodos de aridez espiritual.\n\nFaleceu em Lima em 24 de agosto de 1617, aos 31 anos. Foi a primeira pessoa nascida nas Américas a ser canonizada, em 1671, e é padroeira da América Latina.',
    biographyKids: null,
    quotes: [{ text: 'Fora da Cruz não há outra escada por onde subir ao céu.', source: 'Santa Rosa de Lima' }],
    prayer: null,
    imageUrl: null,
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    name: 'São Bartolomeu Apóstolo',
    slug: 'sao-bartolomeu-apostolo',
    feastMonth: 8,
    feastDay: 24,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Caná',
    deathPlace: 'Armênia',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['curtidores', 'encadernadores'],
    biographyShort: 'Identificado com Natanael do Evangelho, Bartolomeu pregou na Armênia onde foi martirizado por esfolamento.',
    biographyFull: 'Bartolomeu, um dos Doze Apóstolos, é geralmente identificado com Natanael de Caná, apresentado a Jesus por Filipe. Jesus disse dele: "Eis um verdadeiro israelita, em quem não há fingimento."\n\nSegundo a tradição, Bartolomeu pregou o Evangelho na Índia, Mesopotâmia e Armênia. É considerado o apóstolo que levou o Evangelho de São Mateus ao Oriente.\n\nFoi martirizado na Armênia, onde o rei Astíages mandou esfolá-lo vivo e depois decapitá-lo. É frequentemente representado na arte segurando sua própria pele, como na Capela Sistina de Michelangelo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.7468,
    longitude: 35.3390,
  },
  {
    name: 'São Luís IX',
    slug: 'sao-luis-ix',
    feastMonth: 8,
    feastDay: 25,
    birthDate: '1214-04-25',
    deathDate: '1270-08-25',
    birthPlace: 'Poissy',
    deathPlace: 'Túnis',
    country: 'França',
    century: 13,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['França', 'terciários franciscanos'],
    biographyShort: 'Rei da França de 1226 a 1270, Luís IX governou com justiça, piedade e caridade, sendo modelo de santidade entre os leigos.',
    biographyFull: 'Luís IX nasceu em Poissy em 1214 e tornou-se rei da França aos 12 anos, sob a regência de sua mãe, Branca de Castela. Foi educado na fé e dizia preferir a lepra ao pecado mortal.\n\nGovernou com justiça exemplar, administrando pessoalmente a justiça sob o carvalho de Vincennes. Fundou hospitais, a Sainte-Chapelle para abrigar as relíquias da Paixão, e a Sorbonne. Era terciário franciscano.\n\nLiderou duas cruzadas. Na primeira foi capturado no Egito e resgatado. Na segunda, morreu de peste em Túnis em 25 de agosto de 1270. Foi canonizado em 1297.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.9296,
    longitude: 2.0373,
  },
  {
    name: 'São Cesário de Arles',
    slug: 'sao-cesario-de-arles',
    feastMonth: 8,
    feastDay: 26,
    birthDate: '470-01-01',
    deathDate: '542-08-27',
    birthPlace: 'Chalon-sur-Saône',
    deathPlace: 'Arles',
    country: 'França',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Arles', 'pregadores'],
    biographyShort: 'Arcebispo de Arles por quarenta anos, Cesário foi grande pregador e legislador eclesiástico, promovendo a evangelização do povo simples.',
    biographyFull: 'Cesário nasceu em Chalon-sur-Saône, na Borgonha, por volta de 470. Monge em Lérins, foi chamado para governar a arquidiocese de Arles em 502, cargo que exerceu por quarenta anos.\n\nFoi o mais importante pregador do seu tempo na Gália. Seus sermões, simples e diretos, eram destinados ao povo comum. Presidiu o Concílio de Orange (529), que condenou o semipelagianismo e definiu a doutrina da graça.\n\nFundou um mosteiro feminino para sua irmã Cesária e redigiu uma regra monástica influente. Resgatou cativos com os bens da Igreja. Faleceu em Arles em 542.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.7813,
    longitude: 4.8548,
  },
  {
    name: 'Santa Mônica',
    slug: 'santa-monica',
    feastMonth: 8,
    feastDay: 27,
    birthDate: '332-01-01',
    deathDate: '387-01-01',
    birthPlace: 'Tagaste',
    deathPlace: 'Óstia',
    country: 'Argélia',
    century: 4,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['mães', 'mulheres casadas'],
    biographyShort: 'Mãe de Santo Agostinho, Mônica orou e chorou durante anos pela conversão do filho, tornando-se modelo de perseverança materna na fé.',
    biographyFull: 'Mônica nasceu em Tagaste, na Numídia (atual Argélia), por volta de 332. Cristã fervorosa, casou-se com Patrício, pagão de temperamento violento, a quem converteu pela paciência e oração.\n\nSeu maior sofrimento foi ver o filho Agostinho afastar-se da fé, viver em concubinato e aderir ao maniqueísmo. Durante dezessete anos, Mônica orou sem cessar por sua conversão. Um bispo consolou-a dizendo: "É impossível que pereça o filho de tantas lágrimas."\n\nEm Milão, sob a influência de Santo Ambrósio, Agostinho finalmente converteu-se e foi batizado em 387. Pouco depois, Mônica faleceu em Óstia, dizendo que nada mais a prendia a esta vida.',
    biographyKids: null,
    quotes: [{ text: 'Nada está longe de Deus.', source: 'Santa Mônica, Confissões de Santo Agostinho' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.1900,
    longitude: 7.9500,
  },
  {
    name: 'Santo Agostinho de Hipona',
    slug: 'santo-agostinho-de-hipona',
    feastMonth: 8,
    feastDay: 28,
    birthDate: '354-11-13',
    deathDate: '430-08-28',
    birthPlace: 'Tagaste',
    deathPlace: 'Hipona',
    country: 'Argélia',
    century: 5,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'cervejeiros'],
    biographyShort: 'Convertido do maniqueísmo, Agostinho tornou-se bispo de Hipona e o maior Doutor da Igreja latina, cuja obra moldou o pensamento cristão ocidental.',
    biographyFull: 'Agostinho nasceu em Tagaste, Numídia, em 354. Brilhante intelectual, viveu anos de busca inquieta: aderiu ao maniqueísmo, estudou neoplatonismo e manteve uma relação de concubinato. Sua mãe Mônica rezava sem cessar por sua conversão.\n\nEm Milão, ouvindo os sermões de Santo Ambrósio e lendo São Paulo, converteu-se e foi batizado na Vigília Pascal de 387. Voltou à África, tornou-se sacerdote e depois bispo de Hipona em 395.\n\nSuas obras — Confissões, A Cidade de Deus, Sobre a Trindade — são pilares da teologia cristã. Combateu o donatismo, pelagianismo e maniqueísmo. Faleceu em 430 enquanto os vândalos sitiavam Hipona.',
    biographyKids: null,
    quotes: [{ text: 'Fizeste-nos para ti, Senhor, e o nosso coração está inquieto enquanto não repousar em ti.', source: 'Confissões, I, 1' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.1900,
    longitude: 7.9500,
  },
  {
    name: 'Martírio de São João Batista',
    slug: 'martirio-de-sao-joao-batista',
    feastMonth: 8,
    feastDay: 29,
    birthDate: null,
    deathDate: '29-01-01',
    birthPlace: 'Ain Karim',
    deathPlace: 'Maqueronte',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['condenados à morte', 'presidiários'],
    biographyShort: 'A festa recorda a decapitação de João Batista por ordem de Herodes Antipas, após a dança de Salomé e o pedido de Herodíades.',
    biographyFull: 'São João Batista, o precursor de Cristo, batizou Jesus no Jordão e pregou a conversão no deserto da Judeia. Sua coragem em denunciar o pecado público custou-lhe a vida.\n\nJoão repreendeu Herodes Antipas por viver com Herodíades, mulher de seu irmão Filipe. Herodes prendeu-o na fortaleza de Maqueronte, mas temia matá-lo por reconhecer sua santidade.\n\nDurante um banquete, Salomé, filha de Herodíades, dançou tão bem que Herodes prometeu dar-lhe o que pedisse. Instigada pela mãe, pediu a cabeça de João Batista numa bandeja. Herodes cumpriu o juramento e João foi decapitado.',
    biographyKids: null,
    quotes: [{ text: 'É preciso que ele cresça e que eu diminua.', source: 'Jo 3,30' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.5670,
    longitude: 35.6284,
  },
  {
    name: 'Santa Margarida Ward',
    slug: 'santa-margarida-ward',
    feastMonth: 8,
    feastDay: 30,
    birthDate: '1550-01-01',
    deathDate: '1588-08-30',
    birthPlace: 'Congleton',
    deathPlace: 'Londres',
    country: 'Inglaterra',
    century: 16,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['perseguidos pela fé', 'liberdade religiosa'],
    biographyShort: 'Leiga católica inglesa, Margarida ajudou um sacerdote a escapar da prisão e foi martirizada em Londres por recusar abandonar a fé católica.',
    biographyFull: 'Margarida Ward nasceu em Congleton, Cheshire, por volta de 1550. Era uma mulher católica devota que servia como criada em Londres durante o reinado de Isabel I, quando a prática do catolicismo era proibida.\n\nAjudou o padre William Watson a escapar da prisão de Bridewell, fornecendo-lhe uma corda. Foi presa, torturada e interrogada, mas recusou revelar o paradeiro do sacerdote.\n\nCondenada à morte, ofereceram-lhe o perdão se frequentasse os serviços anglicanos, mas recusou firmemente. Foi enforcada em Tyburn em 30 de agosto de 1588. Foi canonizada por Paulo VI em 1970 entre os Quarenta Mártires da Inglaterra e País de Gales.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 53.1628,
    longitude: -2.2165,
  },
  {
    name: 'São Raimundo Nonato',
    slug: 'sao-raimundo-nonato',
    feastMonth: 8,
    feastDay: 31,
    birthDate: '1200-01-01',
    deathDate: '1240-08-31',
    birthPlace: 'Portell',
    deathPlace: 'Cardona',
    country: 'Espanha',
    century: 13,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['parturientes', 'recém-nascidos'],
    biographyShort: 'Chamado "Nonato" por ter nascido após a morte de sua mãe, Raimundo foi mercedário que se entregou como refém para resgatar cristãos cativos dos mouros.',
    biographyFull: 'Raimundo nasceu em Portell, Catalunha, por volta de 1200. Recebeu o sobrenome "Nonato" (não nascido) porque foi extraído do ventre de sua mãe já falecida. Ingressou na Ordem da Mercê, dedicada ao resgate de cativos cristãos.\n\nViajou ao norte da África, onde se ofereceu como refém para libertar prisioneiros. Os mouros perfuraram seus lábios com ferro em brasa e os fecharam com cadeado para impedi-lo de pregar.\n\nFoi resgatado e o papa Gregório IX nomeou-o cardeal, mas Raimundo morreu a caminho de Roma em 1240, em Cardona. É invocado como padroeiro das parturientes.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.6470,
    longitude: 1.0940,
  },
];
