import type { SaintSeedData } from './types';

export const decemberSaints: SaintSeedData[] = [
  {
    name: 'São Carlos de Foucauld',
    slug: 'sao-carlos-de-foucauld',
    feastMonth: 12,
    feastDay: 1,
    birthDate: '1858-09-15',
    deathDate: '1916-12-01',
    birthPlace: 'Estrasburgo',
    deathPlace: 'Tamanrasset',
    country: 'França',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['fraternidades universais', 'eremitas'],
    biographyShort:
      'Militar e explorador francês convertido, tornou-se eremita no deserto do Saara, vivendo entre os tuaregues em pobreza radical. Foi assassinado em 1916 e canonizado em 2022.',
    biographyFull:
      'Carlos de Foucauld nasceu em 1858 em Estrasburgo, numa família aristocrática. Após uma juventude mundana e carreira militar, converteu-se profundamente em 1886 sob orientação do padre Huvelin. Viajou à Terra Santa e ingressou na Trapa, mas desejava uma vida ainda mais radical de pobreza.\n\nPartiu para o Saara argelino, onde viveu como eremita em Tamanrasset, dedicando-se à oração, ao estudo da língua e cultura tuaregue e ao serviço dos mais pobres. Desejava fundar uma fraternidade, mas nunca conseguiu atrair companheiros em vida.\n\nFoi assassinado em 1º de dezembro de 1916 durante um ataque ao seu eremitério. Após sua morte, seu exemplo inspirou a fundação de diversas congregações religiosas. Foi canonizado pelo Papa Francisco em 2022.',
    biographyKids: null,
    quotes: [
      {
        text: 'Quero habituar todos os habitantes a me verem como seu irmão, o irmão universal.',
        source: 'São Carlos de Foucauld',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 22.785,
    longitude: 5.5228,
  },
  {
    name: 'Santa Bibiana',
    slug: 'santa-bibiana',
    feastMonth: 12,
    feastDay: 2,
    birthDate: null,
    deathDate: '363-12-02',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['epilépticos', 'doentes mentais'],
    biographyShort:
      'Virgem e mártir romana do século IV, foi flagelada até a morte por recusar renunciar à fé cristã durante a perseguição do imperador Juliano.',
    biographyFull:
      'Santa Bibiana pertencia a uma família cristã de Roma. Seu pai Flaviano, sua mãe Dafrosa e sua irmã Demétria também foram martirizados durante a perseguição do imperador Juliano, o Apóstata.\n\nApós a morte de seus familiares, Bibiana foi entregue a uma mulher chamada Rufina, que tentou corrompê-la e fazê-la abandonar a fé. A jovem permaneceu firme em sua virgindade e em sua confissão cristã.\n\nFoi condenada a ser amarrada a uma coluna e flagelada com chicotes com pontas de chumbo até a morte. O Papa Simplício ergueu uma igreja sobre o local de seu sepultamento em Roma.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.8967,
    longitude: 12.5082,
  },
  {
    name: 'São Francisco Xavier',
    slug: 'sao-francisco-xavier',
    feastMonth: 12,
    feastDay: 3,
    birthDate: '1506-04-07',
    deathDate: '1552-12-03',
    birthPlace: 'Javier',
    deathPlace: 'Ilha de Sanchoão',
    country: 'Espanha',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['missões', 'navegadores'],
    biographyShort:
      'Cofundador da Companhia de Jesus e o maior missionário da era moderna, evangelizou a Índia, o Sudeste Asiático e o Japão. Morreu às portas da China em 1552.',
    biographyFull:
      'Francisco Xavier nasceu em 1506 no Castelo de Javier, em Navarra. Estudou na Universidade de Paris, onde conheceu Inácio de Loyola e tornou-se um dos primeiros companheiros na fundação da Companhia de Jesus em 1534.\n\nEnviado como missionário ao Oriente em 1541, trabalhou incansavelmente na Índia, Malásia, Indonésia e Japão, batizando milhares de pessoas. Sua capacidade de adaptação cultural e seu zelo apostólico foram extraordinários.\n\nMorreu em 3 de dezembro de 1552 na ilha de Sanchoão, quando tentava entrar na China. Foi canonizado em 1622 e é padroeiro das missões católicas.',
    biographyKids: null,
    quotes: [
      {
        text: 'É grande o número dos que se perdem por não haver quem se sacrifique pela sua salvação.',
        source: 'São Francisco Xavier',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 42.5924,
    longitude: -1.2113,
  },
  {
    name: 'São João Damasceno',
    slug: 'sao-joao-damasceno',
    feastMonth: 12,
    feastDay: 4,
    birthDate: '676-01-01',
    deathDate: '749-12-04',
    birthPlace: 'Damasco',
    deathPlace: 'Mar Saba',
    country: 'Síria',
    century: 8,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'pintores de ícones'],
    biographyShort:
      'Monge e Doutor da Igreja, foi o último dos grandes Padres do Oriente. Defendeu a veneração das imagens sagradas contra o iconoclasmo.',
    biographyFull:
      'João Damasceno nasceu por volta de 676 em Damasco, numa família cristã influente sob domínio muçulmano. Seu pai servia como alto funcionário do califa. Após sucedê-lo no cargo, João renunciou à vida pública para tornar-se monge no mosteiro de Mar Saba, na Palestina.\n\nSua obra teológica mais importante é a "Fonte do Conhecimento", uma síntese da doutrina cristã. Destacou-se como o principal defensor da veneração das imagens sagradas contra a heresia iconoclasta do imperador Leão III.\n\nFaleceu por volta de 749. Foi declarado Doutor da Igreja pelo Papa Leão XIII em 1890, reconhecido como ponte entre a teologia patrística e a escolástica.',
    biographyKids: null,
    quotes: [
      {
        text: 'Não venero a matéria, mas o Criador da matéria que se fez matéria por minha causa.',
        source: 'São João Damasceno',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 33.5138,
    longitude: 36.2765,
  },
  {
    name: 'São Sabas',
    slug: 'sao-sabas',
    feastMonth: 12,
    feastDay: 5,
    birthDate: '439-01-01',
    deathDate: '532-12-05',
    birthPlace: 'Mutalaska',
    deathPlace: 'Mar Saba',
    country: 'Turquia',
    century: 6,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'eremitas'],
    biographyShort:
      'Monge capadócio que fundou o célebre mosteiro de Mar Saba na Palestina, tornando-se um dos maiores organizadores do monaquismo oriental.',
    biographyFull:
      'Sabas nasceu em 439 na Capadócia. Aos oito anos ingressou num mosteiro e mais tarde partiu para a Terra Santa, onde viveu como eremita no deserto da Judeia por muitos anos.\n\nEm 483 fundou a Grande Laura, conhecida como Mar Saba, no vale do Cédron, que se tornou um dos mais importantes centros monásticos do Oriente. Organizou a vida litúrgica e monástica com regras que influenciaram toda a tradição oriental.\n\nDefendeu a ortodoxia contra diversas heresias e foi nomeado arquimandrita de todos os eremitas da Palestina. Faleceu em 532, aos noventa e três anos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.6587,
    longitude: 35.3356,
  },
  {
    name: 'São Nicolau de Mira',
    slug: 'sao-nicolau-de-mira',
    feastMonth: 12,
    feastDay: 6,
    birthDate: '270-03-15',
    deathDate: '343-12-06',
    birthPlace: 'Patara',
    deathPlace: 'Mira',
    country: 'Turquia',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['crianças', 'marinheiros'],
    biographyShort:
      'Bispo de Mira no século IV, célebre por sua generosidade com os pobres e pela defesa da fé no Concílio de Niceia. É a figura histórica por trás da tradição do Papai Noel.',
    biographyFull:
      'Nicolau nasceu por volta de 270 em Patara, na Lícia (atual Turquia). Órfão desde jovem, herdou uma grande fortuna que distribuiu generosamente aos necessitados. O episódio mais famoso narra como salvou três jovens da prostituição ao jogar secretamente bolsas de ouro pela janela de sua casa.\n\nFoi eleito bispo de Mira e participou do Concílio de Niceia em 325, onde defendeu a divindade de Cristo contra o arianismo. Durante a perseguição de Diocleciano, foi preso e torturado, mas sobreviveu.\n\nFaleceu em 343 e suas relíquias foram trasladadas para Bari, Itália, em 1087. Sua fama de generosidade originou a tradição do Papai Noel em diversas culturas.',
    biographyKids: null,
    quotes: [
      {
        text: 'O que damos aos pobres, emprestamos a Deus.',
        source: 'Atribuída a São Nicolau',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 36.2605,
    longitude: 29.9867,
  },
  {
    name: 'Santo Ambrósio de Milão',
    slug: 'santo-ambrosio-de-milao',
    feastMonth: 12,
    feastDay: 7,
    birthDate: '340-01-01',
    deathDate: '397-04-04',
    birthPlace: 'Tréveris',
    deathPlace: 'Milão',
    country: 'Itália',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['apicultores', 'bispos'],
    biographyShort:
      'Doutor da Igreja e bispo de Milão, foi aclamado pelo povo ainda catecúmeno. Combateu o arianismo e batizou Santo Agostinho.',
    biographyFull:
      'Ambrósio nasceu por volta de 340 em Tréveris, filho do prefeito pretoriano das Gálias. Formou-se em direito e tornou-se governador da Emília e Ligúria. Em 374, ao tentar mediar a eleição do bispo de Milão, foi aclamado pelo povo, embora ainda fosse catecúmeno.\n\nComo bispo, tornou-se um dos mais influentes líderes da Igreja. Combateu firmemente o arianismo, enfrentou o imperador Teodósio exigindo-lhe penitência pública pelo massacre de Tessalônica e exerceu profunda influência na conversão de Santo Agostinho.\n\nSeus escritos teológicos e seus hinos litúrgicos enriqueceram a tradição da Igreja. Faleceu em 397 e foi declarado Doutor da Igreja.',
    biographyKids: null,
    quotes: [
      {
        text: 'Quando estiveres em Roma, vive como os romanos; quando estiveres em outro lugar, vive como se vive lá.',
        source: 'Santo Ambrósio',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 49.7557,
    longitude: 6.6396,
  },
  {
    name: 'Imaculada Conceição',
    slug: 'imaculada-conceicao',
    feastMonth: 12,
    feastDay: 8,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['padroeira de Portugal', 'pureza'],
    biographyShort:
      'Solenidade que celebra a concepção de Maria sem pecado original, dogma definido pelo Papa Pio IX em 1854.',
    biographyFull:
      'A Imaculada Conceição é o dogma que proclama que a Virgem Maria foi preservada do pecado original desde o primeiro instante de sua concepção, por singular graça de Deus, em vista dos méritos de Jesus Cristo.\n\nEmbora crida desde os primeiros séculos, a doutrina foi solenemente definida pelo Papa Pio IX na bula Ineffabilis Deus, de 8 de dezembro de 1854. Quatro anos depois, as aparições de Lourdes confirmaram o dogma quando Maria se apresentou a Bernadete dizendo: "Eu sou a Imaculada Conceição."\n\nA festa é celebrada em 8 de dezembro e é dia santo de guarda. Maria Imaculada é padroeira de Portugal, do Brasil e de muitas nações.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.6996,
    longitude: 35.3035,
  },
  {
    name: 'São Juan Diego',
    slug: 'sao-juan-diego',
    feastMonth: 12,
    feastDay: 9,
    birthDate: '1474-01-01',
    deathDate: '1548-05-30',
    birthPlace: 'Cuautitlán',
    deathPlace: 'Cidade do México',
    country: 'México',
    century: 16,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['indígenas', 'leigos'],
    biographyShort:
      'Indígena mexicano que recebeu as aparições de Nossa Senhora de Guadalupe em 1531. Foi o primeiro santo indígena das Américas, canonizado em 2002.',
    biographyFull:
      'Juan Diego Cuauhtlatoatzin nasceu em 1474 em Cuautitlán, próximo à Cidade do México. Era um indígena nahua que se converteu ao cristianismo após a chegada dos missionários franciscanos.\n\nEm dezembro de 1531, Nossa Senhora apareceu-lhe no monte Tepeyac, pedindo-lhe que solicitasse ao bispo a construção de uma igreja naquele local. Como prova, rosas milagrosamente floresceram no inverno e, ao abrir sua tilma diante do bispo, a imagem de Nossa Senhora estava impressa no tecido.\n\nJuan Diego viveu o resto de sua vida como guardião da ermida de Guadalupe. Foi canonizado pelo Papa João Paulo II em 2002, sendo o primeiro santo indígena das Américas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 19.4847,
    longitude: -99.1171,
  },
  {
    name: 'Nossa Senhora de Loreto',
    slug: 'nossa-senhora-de-loreto',
    feastMonth: 12,
    feastDay: 10,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Itália',
    century: 13,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['aviadores', 'viajantes'],
    biographyShort:
      'Devoção mariana ligada à Santa Casa de Nazaré, que segundo a tradição foi transportada por anjos até Loreto, na Itália, no século XIII.',
    biographyFull:
      'A devoção a Nossa Senhora de Loreto está ligada à Santa Casa, a morada onde Maria teria recebido a Anunciação do anjo Gabriel em Nazaré. Segundo a tradição, a casa foi transportada por anjos até a cidade de Loreto, nas Marcas italianas, em 1294.\n\nEstudos históricos sugerem que as pedras foram trasladadas por cruzados da família Ângelo (Angeli em italiano, o que pode ter originado a lenda dos anjos). O Santuário de Loreto tornou-se um dos mais importantes centros de peregrinação mariana do mundo.\n\nEm 1920, o Papa Bento XV proclamou Nossa Senhora de Loreto padroeira dos aviadores, pela associação com o transporte aéreo da Santa Casa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.4406,
    longitude: 13.6078,
  },
  {
    name: 'São Dâmaso I',
    slug: 'sao-damaso-i',
    feastMonth: 12,
    feastDay: 11,
    birthDate: '305-01-01',
    deathDate: '384-12-11',
    birthPlace: 'Idanha-a-Nova',
    deathPlace: 'Roma',
    country: 'Portugal',
    century: 4,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['arqueólogos', 'contra febres'],
    biographyShort:
      'Papa de origem portuguesa que encomendou a São Jerônimo a tradução da Bíblia para o latim (Vulgata) e restaurou as catacumbas romanas.',
    biographyFull:
      'Dâmaso nasceu por volta de 305, provavelmente em Idanha-a-Nova, na Lusitânia (atual Portugal). Mudou-se para Roma, onde seguiu carreira eclesiástica e foi eleito Papa em 366, enfrentando o antipapa Ursino.\n\nSeu pontificado foi marcado por importantes contribuições à Igreja. Encomendou a São Jerônimo a revisão e tradução das Escrituras para o latim, que resultou na Vulgata. Também restaurou e embelezou as catacumbas e túmulos dos mártires romanos com belas inscrições em verso.\n\nCombateu diversas heresias e promoveu o primado de Roma. Faleceu em 384 e é considerado um dos papas mais importantes do século IV.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 39.9228,
    longitude: -7.2356,
  },
  {
    name: 'Nossa Senhora de Guadalupe',
    slug: 'nossa-senhora-de-guadalupe',
    feastMonth: 12,
    feastDay: 12,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'México',
    century: 16,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Américas', 'México'],
    biographyShort:
      'Aparição da Virgem Maria ao indígena Juan Diego no monte Tepeyac em 1531, deixando sua imagem milagrosamente impressa em sua tilma.',
    biographyFull:
      'Em dezembro de 1531, a Virgem Maria apareceu ao indígena Juan Diego no monte Tepeyac, próximo à Cidade do México. Apresentou-se como Mãe do verdadeiro Deus e pediu a construção de um templo naquele lugar.\n\nComo sinal para o bispo, fez florescer rosas em pleno inverno. Quando Juan Diego abriu sua tilma para mostrá-las, a imagem de Nossa Senhora estava miraculosamente impressa no tecido de agave, que se conserva até hoje sem deterioração explicável pela ciência.\n\nA devoção provocou milhões de conversões entre os indígenas. O Santuário de Guadalupe é o mais visitado do mundo católico. Nossa Senhora de Guadalupe foi proclamada padroeira das Américas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 19.4853,
    longitude: -99.1184,
  },
  {
    name: 'Santa Luzia',
    slug: 'santa-luzia',
    feastMonth: 12,
    feastDay: 13,
    birthDate: '283-01-01',
    deathDate: '304-12-13',
    birthPlace: 'Siracusa',
    deathPlace: 'Siracusa',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['cegos', 'problemas de visão'],
    biographyShort:
      'Virgem e mártir siciliana do século IV, foi denunciada pelo pretendente rejeitado e morta durante a perseguição de Diocleciano. É invocada como protetora da visão.',
    biographyFull:
      'Luzia nasceu em Siracusa, Sicília, por volta de 283, numa família cristã nobre. Consagrou sua virgindade a Deus e, após a cura milagrosa de sua mãe no túmulo de Santa Ágata, distribuiu seus bens aos pobres.\n\nSeu pretendente, furioso com a recusa do casamento e a doação dos bens, denunciou-a como cristã ao governador Pascásio. Luzia enfrentou o julgamento com firmeza inabalável. Segundo a tradição, nem bois nem soldados conseguiram movê-la do lugar.\n\nFoi martirizada em 304, durante a perseguição de Diocleciano. Seu nome, derivado de "lux" (luz), e a tradição sobre seus olhos a tornaram padroeira da visão e dos cegos.',
    biographyKids: null,
    quotes: [
      {
        text: 'Quem vive em castidade e piedade é templo do Espírito Santo.',
        source: 'Atribuída a Santa Luzia',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 37.0755,
    longitude: 15.2866,
  },
  {
    name: 'São João da Cruz',
    slug: 'sao-joao-da-cruz',
    feastMonth: 12,
    feastDay: 14,
    birthDate: '1542-06-24',
    deathDate: '1591-12-14',
    birthPlace: 'Fontiveros',
    deathPlace: 'Úbeda',
    country: 'Espanha',
    century: 16,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['poetas', 'místicos'],
    biographyShort:
      'Doutor da Igreja e poeta místico, reformou a Ordem Carmelita junto com Santa Teresa de Ávila. Autor de obras-primas da literatura espiritual como "A Noite Escura".',
    biographyFull:
      'João da Cruz nasceu em 1542 em Fontiveros, Espanha, numa família pobre. Ingressou na Ordem Carmelita e, a convite de Santa Teresa de Ávila, empreendeu a reforma da ordem masculina, fundando os Carmelitas Descalços.\n\nSua reforma encontrou forte oposição. Foi preso por seus próprios confrades em Toledo por nove meses, período em que compôs seus mais belos poemas místicos, incluindo o "Cântico Espiritual". Suas obras — "A Subida do Monte Carmelo", "A Noite Escura" — são consideradas o ápice da mística cristã.\n\nMorreu em Úbeda em 1591, em condições de pobreza e abandono. Foi declarado Doutor da Igreja em 1926, reconhecido como o Doutor Místico.',
    biographyKids: null,
    quotes: [
      {
        text: 'No entardecer da vida, seremos julgados no amor.',
        source: 'São João da Cruz',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 40.9772,
    longitude: -4.9861,
  },
  {
    name: 'São Valeriano',
    slug: 'sao-valeriano',
    feastMonth: 12,
    feastDay: 15,
    birthDate: null,
    deathDate: '457-12-15',
    birthPlace: null,
    deathPlace: 'Abbenza',
    country: 'Itália',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Abbenza', 'pastores'],
    biographyShort:
      'Bispo do norte da Itália no século V, destacou-se pela defesa da fé contra as heresias e pelo cuidado pastoral em tempos de invasões bárbaras.',
    biographyFull:
      'São Valeriano foi bispo na região do norte da Itália durante o conturbado século V, quando o Império Romano do Ocidente sofria constantes invasões bárbaras.\n\nDistinguiu-se pela firmeza na defesa da ortodoxia católica e pelo zelo pastoral com seu rebanho, mantendo a fé e a disciplina eclesiástica em tempos de grande instabilidade política e social.\n\nFaleceu por volta de 457, sendo venerado como confessor da fé pela tradição da Igreja.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.4642,
    longitude: 9.19,
  },
  {
    name: 'Santa Adelaide',
    slug: 'santa-adelaide',
    feastMonth: 12,
    feastDay: 16,
    birthDate: '931-01-01',
    deathDate: '999-12-16',
    birthPlace: 'Borgonha',
    deathPlace: 'Seltz',
    country: 'Alemanha',
    century: 10,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['viúvas', 'prisioneiros'],
    biographyShort:
      'Imperatriz do Sacro Império Romano, foi presa e exilada, mas reconquistou sua posição e dedicou-se à caridade e à fundação de mosteiros.',
    biographyFull:
      'Adelaide nasceu em 931, filha do rei Rodolfo II da Borgonha. Casou-se com Lotário II da Itália, que morreu envenenado. Foi presa pelo usurpador Berengário II, mas escapou e casou-se com o imperador Otão I, tornando-se imperatriz.\n\nApós a morte de Otão I, enfrentou conflitos com seu filho Otão II e sua nora, sendo exilada da corte. Reconciliou-se mais tarde e exerceu a regência em nome de seu neto Otão III.\n\nNos últimos anos dedicou-se à fundação de mosteiros e obras de caridade. Faleceu em 999 no mosteiro de Seltz, na Alsácia, e foi canonizada pelo Papa Urbano II.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.8717,
    longitude: 8.1083,
  },
  {
    name: 'São Lázaro',
    slug: 'sao-lazaro',
    feastMonth: 12,
    feastDay: 17,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Betânia',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['leprosos', 'coveiros'],
    biographyShort:
      'Amigo de Jesus, irmão de Marta e Maria, foi ressuscitado por Cristo quatro dias após sua morte, conforme narrado no Evangelho de São João.',
    biographyFull:
      'Lázaro de Betânia era irmão de Marta e Maria Madalena, e amigo íntimo de Jesus. Sua casa em Betânia, próxima a Jerusalém, era frequentemente visitada pelo Senhor.\n\nSeu episódio mais célebre é a ressurreição narrada no Evangelho de São João (capítulo 11). Lázaro adoeceu e morreu; quando Jesus chegou, já estava sepultado havia quatro dias. Jesus chorou diante do túmulo e ordenou: "Lázaro, vem para fora!" — e ele saiu vivo.\n\nSegundo tradições posteriores, Lázaro teria ido para Chipre ou para a Provença, onde teria sido bispo. É venerado como padroeiro dos leprosos e doentes.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7631,
    longitude: 35.2586,
  },
  {
    name: 'São Graciano de Tours',
    slug: 'sao-graciano-de-tours',
    feastMonth: 12,
    feastDay: 18,
    birthDate: null,
    deathDate: '301-12-18',
    birthPlace: 'Roma',
    deathPlace: 'Tours',
    country: 'França',
    century: 3,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Tours', 'evangelização'],
    biographyShort:
      'Primeiro bispo de Tours, foi enviado de Roma como missionário para evangelizar a Gália no século III.',
    biographyFull:
      'Graciano foi um dos primeiros missionários enviados de Roma para evangelizar a Gália. Segundo a tradição, chegou a Tours por volta do ano 250, durante um período de grande expansão do cristianismo nas províncias romanas.\n\nEstabeleceu a primeira comunidade cristã em Tours e tornou-se seu primeiro bispo, lançando os fundamentos da diocese que mais tarde seria ilustrada por São Martinho de Tours.\n\nFaleceu por volta de 301, após décadas de trabalho missionário. É venerado como o fundador da Igreja em Tours.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.3941,
    longitude: 0.6848,
  },
  {
    name: 'Bem-aventurado Urbano V',
    slug: 'bem-aventurado-urbano-v',
    feastMonth: 12,
    feastDay: 19,
    birthDate: '1310-01-01',
    deathDate: '1370-12-19',
    birthPlace: 'Grizac',
    deathPlace: 'Avinhão',
    country: 'França',
    century: 14,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['universidades', 'educação'],
    biographyShort:
      'Papa beneditino do período de Avinhão, tentou reconduzir a sede papal a Roma e foi grande promotor da educação e das universidades.',
    biographyFull:
      'Guillaume de Grimoard nasceu em 1310 em Grizac, no Languedoc. Monge beneditino e professor de direito canônico, foi eleito Papa em 1362 com o nome de Urbano V, embora não fosse cardeal.\n\nSeu pontificado destacou-se pela tentativa de devolver a sede papal a Roma em 1367, após mais de sessenta anos em Avinhão. Permaneceu em Roma por três anos, mas a instabilidade política forçou-o a retornar. Também fundou e apoiou diversas universidades pela Europa.\n\nManteve a vida monástica mesmo como Papa, vestindo o hábito beneditino. Faleceu em Avinhão em 1370 e foi beatificado pelo Papa Pio IX em 1870.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.3742,
    longitude: 3.5833,
  },
  {
    name: 'São Domingos de Silos',
    slug: 'sao-domingos-de-silos',
    feastMonth: 12,
    feastDay: 20,
    birthDate: '1000-01-01',
    deathDate: '1073-12-20',
    birthPlace: 'Cañas',
    deathPlace: 'Silos',
    country: 'Espanha',
    century: 11,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['pastores', 'prisioneiros'],
    biographyShort:
      'Abade beneditino que restaurou o mosteiro de Silos, transformando-o num grande centro espiritual e cultural da Espanha medieval.',
    biographyFull:
      'Domingos nasceu por volta de 1000 em Cañas, La Rioja. Foi pastor na juventude antes de ingressar na vida monástica. Tornou-se prior do mosteiro de San Millán de la Cogolla, mas conflitos com o rei de Navarra levaram-no ao exílio.\n\nO rei Fernando I de Castela acolheu-o e confiou-lhe a restauração do decadente mosteiro de San Sebastián de Silos. Sob sua liderança, o mosteiro renasceu como importante centro de espiritualidade, cultura e acolhimento de peregrinos e cativos resgatados.\n\nFaleceu em 1073. O mosteiro passou a levar seu nome — Santo Domingo de Silos — e é famoso até hoje pelo canto gregoriano de seus monges.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9614,
    longitude: -3.4183,
  },
  {
    name: 'São Pedro Canísio',
    slug: 'sao-pedro-canisio',
    feastMonth: 12,
    feastDay: 21,
    birthDate: '1521-05-08',
    deathDate: '1597-12-21',
    birthPlace: 'Nimega',
    deathPlace: 'Friburgo',
    country: 'Holanda',
    century: 16,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['Alemanha', 'catequistas'],
    biographyShort:
      'Jesuíta e Doutor da Igreja, foi o principal defensor do catolicismo nos países de língua alemã durante a Reforma Protestante. Autor de catecismos amplamente difundidos.',
    biographyFull:
      'Pedro Canísio nasceu em 1521 em Nimega, nos Países Baixos. Foi o primeiro jesuíta da província germânica e dedicou sua vida à defesa e renovação do catolicismo nos territórios ameaçados pela Reforma Protestante.\n\nSeus catecismos, publicados em três versões de diferentes tamanhos, tiveram mais de duzentas edições e foram traduzidos para quinze idiomas. Fundou colégios e universidades jesuítas por toda a Alemanha, Áustria e Suíça.\n\nFaleceu em 1597 em Friburgo, na Suíça. Foi canonizado e declarado Doutor da Igreja pelo Papa Pio XI em 1925.',
    biographyKids: null,
    quotes: [
      {
        text: 'Prefiro mil vezes errar por excesso de bondade do que por excesso de severidade.',
        source: 'São Pedro Canísio',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 51.8126,
    longitude: 5.8372,
  },
  {
    name: 'Santa Anastácia',
    slug: 'santa-anastacia',
    feastMonth: 12,
    feastDay: 22,
    birthDate: null,
    deathDate: '304-12-25',
    birthPlace: 'Roma',
    deathPlace: 'Sirmium',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['tecelãs', 'viúvas'],
    biographyShort:
      'Santa Anastácia foi uma nobre romana martirizada durante a perseguição de Diocleciano. É uma das santas mencionadas no Cânon Romano da Missa.',
    biographyFull:
      'Santa Anastácia era uma cristã nobre de Roma, filha de Pretextato, um romano pagão, e de Fausta, uma cristã. Foi instruída na fé por São Crisógono.\n\nDurante a perseguição de Diocleciano, visitava e consolava os cristãos presos. Por sua fé, foi presa e enviada para Sirmium (atual Sérvia), onde sofreu o martírio, possivelmente queimada viva, por volta de 304.\n\nSeu culto é muito antigo em Roma, onde a segunda Missa de Natal era celebrada em sua basílica. É mencionada no Cânon Romano da Missa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.5,
  },
  {
    name: 'São João de Kety',
    slug: 'sao-joao-de-kety',
    feastMonth: 12,
    feastDay: 23,
    birthDate: '1390-06-23',
    deathDate: '1473-12-24',
    birthPlace: 'Kęty',
    deathPlace: 'Cracóvia',
    country: 'Polônia',
    century: 15,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['professores', 'estudantes'],
    biographyShort:
      'Professor da Universidade de Cracóvia, destacou-se pela caridade com os pobres e pela vida austera. Peregriu quatro vezes a Roma a pé.',
    biographyFull:
      'João nasceu em 1390 em Kęty, na Polônia. Estudou na Universidade de Cracóvia, onde se tornou professor de teologia e Sagradas Escrituras, lecionando por grande parte de sua vida.\n\nEra conhecido por sua extrema generosidade: doava suas roupas e comida aos pobres, chegando a ficar descalço no inverno. Fez quatro peregrinações a Roma a pé e uma a Jerusalém, sempre em espírito de penitência.\n\nFaleceu em 1473 em Cracóvia. Foi canonizado pelo Papa Clemente XIII em 1767 e é padroeiro dos professores universitários na Polônia.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.8811,
    longitude: 19.2236,
  },
  {
    name: 'Santa Paula Isabel Cerioli',
    slug: 'santa-paula-isabel-cerioli',
    feastMonth: 12,
    feastDay: 24,
    birthDate: '1816-01-28',
    deathDate: '1865-12-24',
    birthPlace: 'Soncino',
    deathPlace: 'Comonte',
    country: 'Itália',
    century: 19,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['órfãos', 'viúvas'],
    biographyShort:
      'Viúva e mãe que, após perder o marido e os filhos, fundou as Irmãs da Sagrada Família de Bérgamo para acolher órfãos do campo.',
    biographyFull:
      'Constanza Cerioli nasceu em 1816 em Soncino, Lombardia. Casou-se aos dezesseis anos com um homem muito mais velho. Dos quatro filhos, apenas um sobreviveu à infância, mas também morreu aos dezesseis anos. Ficou viúva em 1854.\n\nTomou o nome de Paula Isabel e, em 1857, fundou o Instituto das Irmãs da Sagrada Família de Bérgamo, dedicado à educação e acolhimento de órfãos rurais. Posteriormente fundou também um ramo masculino.\n\nFaleceu em 1865, aos quarenta e nove anos. Foi canonizada pelo Papa Bento XVI em 2004.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.4017,
    longitude: 9.8706,
  },
  {
    name: 'Natal do Senhor',
    slug: 'natal-do-senhor',
    feastMonth: 12,
    feastDay: 25,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Belém',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['famílias', 'crianças'],
    biographyShort:
      'Solenidade do nascimento de Jesus Cristo em Belém, celebrada em 25 de dezembro desde o século IV. É a festa central do ciclo litúrgico do Natal.',
    biographyFull:
      'O Natal celebra o nascimento de Jesus Cristo, o Filho de Deus feito homem, em Belém da Judeia. Segundo os Evangelhos, Maria e José viajaram a Belém por causa do recenseamento ordenado por César Augusto, e o menino nasceu numa manjedoura, pois não havia lugar na hospedaria.\n\nAnjos anunciaram o nascimento aos pastores, e uma estrela guiou os magos do Oriente, que vieram adorá-lo oferecendo ouro, incenso e mirra. A data de 25 de dezembro foi fixada pela Igreja de Roma no século IV.\n\nO Natal é a celebração do mistério da Encarnação: Deus se fez homem para a salvação da humanidade. É a segunda maior solenidade do calendário litúrgico, após a Páscoa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7054,
    longitude: 35.2024,
  },
  {
    name: 'Santo Estêvão Protomártir',
    slug: 'santo-estevao-protomartir',
    feastMonth: 12,
    feastDay: 26,
    birthDate: null,
    deathDate: '36-12-26',
    birthPlace: null,
    deathPlace: 'Jerusalém',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['diáconos', 'pedreiros'],
    biographyShort:
      'Primeiro mártir cristão, foi um dos sete diáconos escolhidos pelos Apóstolos. Morreu apedrejado em Jerusalém após proclamar sua visão de Cristo à direita do Pai.',
    biographyFull:
      'Estêvão foi um dos sete diáconos escolhidos pelos Apóstolos para servir a comunidade cristã de Jerusalém, conforme narrado nos Atos dos Apóstolos. Era descrito como homem "cheio de fé e do Espírito Santo".\n\nSua pregação poderosa provocou a ira do Sinédrio. Levado a julgamento, pronunciou um longo discurso repassando a história de Israel e acusando seus juízes de resistirem ao Espírito Santo. Ao declarar que via os céus abertos e o Filho do Homem à direita de Deus, foi arrastado para fora da cidade.\n\nMorreu apedrejado, perdoando seus algozes à semelhança de Cristo: "Senhor, não lhes imputeis este pecado." Saulo de Tarso, o futuro São Paulo, era testemunha e guardava as vestes dos executores.',
    biographyKids: null,
    quotes: [
      {
        text: 'Senhor, não lhes imputeis este pecado.',
        source: 'Atos dos Apóstolos 7,60',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 31.7767,
    longitude: 35.2345,
  },
  {
    name: 'São João Evangelista',
    slug: 'sao-joao-evangelista',
    feastMonth: 12,
    feastDay: 27,
    birthDate: null,
    deathDate: '100-12-27',
    birthPlace: 'Betsaida',
    deathPlace: 'Éfeso',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['escritores', 'teólogos'],
    biographyShort:
      'Apóstolo amado de Jesus, autor do quarto Evangelho e do Apocalipse. Foi o único apóstolo que permaneceu ao pé da Cruz e o único que não morreu mártir.',
    biographyFull:
      'João, filho de Zebedeu e irmão de Tiago, era pescador em Betsaida quando foi chamado por Jesus. Tornou-se parte do círculo mais íntimo do Senhor, junto com Pedro e Tiago, presenciando a Transfiguração e a agonia no Getsêmani.\n\nIdentificado como "o discípulo amado", recostou-se no peito de Jesus na Última Ceia e foi o único apóstolo presente ao pé da Cruz, onde recebeu de Cristo a missão de cuidar de Maria. Após Pentecostes, evangelizou a Ásia Menor, estabelecendo-se em Éfeso.\n\nSegundo a tradição, foi exilado na ilha de Patmos, onde escreveu o Apocalipse. É autor do quarto Evangelho e de três epístolas. Foi o único apóstolo a morrer de causa natural, em idade avançada, por volta do ano 100.',
    biographyKids: null,
    quotes: [
      {
        text: 'Filhinhos, amai-vos uns aos outros.',
        source: 'Tradição sobre São João Evangelista',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 32.9094,
    longitude: 35.5728,
  },
  {
    name: 'Santos Inocentes',
    slug: 'santos-inocentes',
    feastMonth: 12,
    feastDay: 28,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Belém',
    deathPlace: 'Belém',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['crianças', 'bebês'],
    biographyShort:
      'Os meninos de Belém massacrados por ordem do rei Herodes, que buscava eliminar o Menino Jesus. São venerados como os primeiros mártires do cristianismo.',
    biographyFull:
      'Segundo o Evangelho de São Mateus, quando os Magos do Oriente não retornaram para informar Herodes sobre o paradeiro do recém-nascido Rei dos Judeus, o monarca ordenou o massacre de todos os meninos de Belém e arredores com menos de dois anos.\n\nJosé, avisado por um anjo em sonho, já havia fugido com Maria e o Menino Jesus para o Egito. As crianças inocentes de Belém, porém, foram mortas pela crueldade de Herodes.\n\nA Igreja venera esses meninos como mártires desde os primeiros séculos, pois deram suas vidas, ainda que inconscientemente, pelo Cristo. A festa é celebrada em 28 de dezembro.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7054,
    longitude: 35.2024,
  },
  {
    name: 'São Tomás Becket',
    slug: 'sao-tomas-becket',
    feastMonth: 12,
    feastDay: 29,
    birthDate: '1118-12-21',
    deathDate: '1170-12-29',
    birthPlace: 'Londres',
    deathPlace: 'Cantuária',
    country: 'Inglaterra',
    century: 12,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['clero secular', 'liberdade religiosa'],
    biographyShort:
      'Arcebispo de Cantuária, foi assassinado na catedral por cavaleiros do rei Henrique II após defender os direitos da Igreja contra a coroa inglesa.',
    biographyFull:
      'Tomás Becket nasceu em 1118 em Londres, filho de comerciantes normandos. Tornou-se chanceler da Inglaterra e grande amigo do rei Henrique II, que o fez arcebispo de Cantuária em 1162, esperando ter um aliado dócil.\n\nPorém, Tomás transformou-se radicalmente, abandonando a vida mundana e dedicando-se inteiramente à defesa dos direitos da Igreja contra as pretensões reais. O conflito com Henrique II levou-o ao exílio na França por seis anos.\n\nAo retornar em 1170, o conflito reacendeu-se. Quatro cavaleiros, interpretando uma frase irada do rei, assassinaram Tomás na catedral de Cantuária em 29 de dezembro. Foi canonizado em 1173 e Cantuária tornou-se o maior centro de peregrinação da Inglaterra.',
    biographyKids: null,
    quotes: [
      {
        text: 'Por o nome de Jesus e a proteção da Igreja, estou pronto a abraçar a morte.',
        source: 'São Tomás Becket',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    name: 'São Félix I',
    slug: 'sao-felix-i',
    feastMonth: 12,
    feastDay: 30,
    birthDate: null,
    deathDate: '274-12-30',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['diocese de Roma', 'papas'],
    biographyShort:
      'Papa do século III que governou a Igreja durante um período de relativa paz e definiu a doutrina sobre a dupla natureza de Cristo.',
    biographyFull:
      'Félix I foi eleito Papa em 269, sucedendo a São Dionísio. Governou a Igreja durante o reinado do imperador Aureliano, num período de relativa tranquilidade para os cristãos.\n\nSeu pontificado foi marcado pela afirmação teológica da união das naturezas divina e humana em Cristo, contribuindo para os debates cristológicos que marcariam os séculos seguintes.\n\nFaleceu em 274 e foi sepultado nas catacumbas de São Calisto, em Roma. Embora tradicionalmente venerado como mártir, historiadores modernos consideram que morreu em paz.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.8967,
    longitude: 12.4822,
  },
  {
    name: 'São Silvestre I',
    slug: 'sao-silvestre-i',
    feastMonth: 12,
    feastDay: 31,
    birthDate: null,
    deathDate: '335-12-31',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['noite de Ano Novo', 'pedreiros'],
    biographyShort:
      'Papa durante o reinado de Constantino, presidiu a Igreja na transição do cristianismo perseguido para religião tolerada. Seu pontificado coincidiu com o Concílio de Niceia.',
    biographyFull:
      'Silvestre I foi eleito Papa em 314, pouco após o Edito de Milão (313) que concedeu liberdade de culto aos cristãos. Seu pontificado de vinte e um anos foi um dos mais longos da história.\n\nDurante seu governo, o imperador Constantino mandou construir as grandes basílicas de Roma: São Pedro, São João de Latrão e Santa Cruz de Jerusalém. O Concílio de Niceia (325), que condenou o arianismo e formulou o Credo, ocorreu durante seu pontificado, embora ele tenha sido representado por legados.\n\nFaleceu em 31 de dezembro de 335. Sua festa na véspera de Ano Novo deu origem à tradição de chamar essa noite de "Noite de São Silvestre" em muitos países.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9022,
    longitude: 12.4539,
  },
];
