import type { SaintSeedData } from './types';

export const februarySaints: SaintSeedData[] = [
  {
    name: 'Santa Brígida da Irlanda',
    slug: 'santa-brigida-da-irlanda',
    feastMonth: 2,
    feastDay: 1,
    birthDate: '451',
    deathDate: '525',
    birthPlace: 'Faughart, Irlanda',
    deathPlace: 'Kildare, Irlanda',
    country: 'Irlanda',
    century: 5,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['Irlanda', 'leiteiras'],
    biographyShort: 'Fundadora do mosteiro de Kildare, Santa Brígida é uma das padroeiras da Irlanda e uma das santas mais veneradas da tradição celta.',
    biographyFull: 'Santa Brígida nasceu em meados do século V na Irlanda. Desde jovem demonstrou grande piedade e caridade para com os pobres, distribuindo alimentos e bens da família aos necessitados.\n\nFundou o mosteiro de Kildare, um dos mais importantes centros monásticos da Irlanda, que se tornou referência de vida religiosa e cultura. Sua influência foi tão grande que é considerada, ao lado de São Patrício, padroeira da Irlanda.\n\nFaleceu por volta de 525, deixando um legado de fé, caridade e devoção que perdura até hoje na tradição católica irlandesa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 53.7128,
    longitude: -6.5948,
  },
  {
    name: 'Apresentação do Senhor',
    slug: 'apresentacao-do-senhor',
    feastMonth: 2,
    feastDay: 2,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Belém, Israel',
    deathPlace: 'Jerusalém, Israel',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['vida consagrada', 'luz'],
    biographyShort: 'A Apresentação do Senhor celebra o momento em que Maria e José levaram o Menino Jesus ao Templo de Jerusalém, quarenta dias após seu nascimento.',
    biographyFull: 'A festa da Apresentação do Senhor, também conhecida como Dia de Nossa Senhora da Candelária, celebra o episódio narrado no Evangelho de São Lucas em que Maria e José apresentaram Jesus no Templo de Jerusalém.\n\nNo Templo, o velho Simeão reconheceu em Jesus a "luz para iluminar as nações" e a "glória de Israel". A profetisa Ana também louvou a Deus pela chegada do Redentor.\n\nEsta festa é marcada pela bênção das velas, simbolizando Cristo como luz do mundo. É também o dia dedicado à vida consagrada na Igreja Católica.',
    biographyKids: null,
    quotes: [{ text: 'Agora, Senhor, podeis deixar vosso servo ir em paz, porque meus olhos viram a vossa salvação.', source: 'Cântico de Simeão (Lc 2,29-30)' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7767,
    longitude: 35.2345,
  },
  {
    name: 'São Brás',
    slug: 'sao-bras',
    feastMonth: 2,
    feastDay: 3,
    birthDate: null,
    deathDate: '316',
    birthPlace: 'Sebaste, Armênia',
    deathPlace: 'Sebaste, Armênia',
    country: 'Armênia',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['doenças de garganta', 'otorrinolaringologistas'],
    biographyShort: 'Bispo de Sebaste e mártir, São Brás é invocado como protetor contra males da garganta por ter salvo milagrosamente um menino que engasgou com uma espinha de peixe.',
    biographyFull: 'São Brás foi bispo de Sebaste, na Armênia, no início do século IV. Médico de formação, dedicou-se ao cuidado dos enfermos tanto no corpo quanto na alma.\n\nDurante a perseguição de Licínio, retirou-se para uma caverna onde animais selvagens vinham até ele para serem curados. O milagre mais conhecido é a cura de um menino que estava morrendo engasgado com uma espinha de peixe.\n\nFoi preso e martirizado por volta de 316. Até hoje, no dia de sua festa, é tradição a bênção das gargantas com duas velas cruzadas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.3,
    longitude: 36.85,
  },
  {
    name: 'São José de Leonessa',
    slug: 'sao-jose-de-leonessa',
    feastMonth: 2,
    feastDay: 4,
    birthDate: '1556',
    deathDate: '1612',
    birthPlace: 'Leonessa, Itália',
    deathPlace: 'Amatrice, Itália',
    country: 'Itália',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['missionários', 'pregadores'],
    biographyShort: 'Frade capuchinho italiano, São José de Leonessa dedicou-se à pregação e às missões, chegando a ir a Constantinopla para evangelizar os muçulmanos.',
    biographyFull: 'São José nasceu em 1556 em Leonessa, na região da Úmbria, Itália. Entrou na Ordem dos Capuchinhos ainda jovem, destacando-se pela austeridade e pelo zelo missionário.\n\nFoi enviado como missionário a Constantinopla, onde pregou corajosamente aos muçulmanos. Foi preso e condenado à morte, mas sobreviveu milagrosamente ao suplício e foi libertado.\n\nDe volta à Itália, continuou pregando missões populares até sua morte em 1612. Foi canonizado em 1746 pelo Papa Bento XIV.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.5667,
    longitude: 12.9667,
  },
  {
    name: 'Santa Ágata',
    slug: 'santa-agata',
    feastMonth: 2,
    feastDay: 5,
    birthDate: '231',
    deathDate: '251',
    birthPlace: 'Catânia, Sicília, Itália',
    deathPlace: 'Catânia, Sicília, Itália',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['enfermeiras', 'vítimas de abuso'],
    biographyShort: 'Virgem e mártir siciliana, Santa Ágata foi torturada e morta por recusar as investidas do cônsul Quintiano, mantendo firme sua consagração a Cristo.',
    biographyFull: 'Santa Ágata nasceu em Catânia, na Sicília, em uma família nobre. Consagrou sua virgindade a Deus desde jovem. O cônsul romano Quintiano, atraído por sua beleza, tentou forçá-la ao casamento.\n\nDiante de sua recusa, Ágata foi submetida a torturas terríveis, incluindo a mutilação de seus seios. Segundo a tradição, São Pedro apareceu-lhe no cárcere e curou suas feridas.\n\nMorreu na prisão em 251. É padroeira de Catânia e invocada contra incêndios e erupções do Etna. Seu nome está no Cânon Romano da Missa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 37.5079,
    longitude: 15.083,
  },
  {
    name: 'São Paulo Miki',
    slug: 'sao-paulo-miki',
    feastMonth: 2,
    feastDay: 6,
    birthDate: '1562',
    deathDate: '1597',
    birthPlace: 'Quioto, Japão',
    deathPlace: 'Nagasáqui, Japão',
    country: 'Japão',
    century: 16,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Japão', 'missionários no Oriente'],
    biographyShort: 'Jesuíta japonês, São Paulo Miki foi um dos 26 mártires crucificados em Nagasáqui em 1597, pregando do alto da cruz até a morte.',
    biographyFull: 'São Paulo Miki nasceu em 1562 em uma família nobre japonesa convertida ao cristianismo. Entrou na Companhia de Jesus e tornou-se um pregador eloquente, conhecido por sua capacidade de dialogar com monges budistas.\n\nEm 1597, durante a perseguição ordenada pelo governante Toyotomi Hideyoshi, Paulo Miki e outros 25 cristãos foram presos e condenados à morte. Marcharam de Quioto a Nagasáqui, onde foram crucificados.\n\nDo alto da cruz, Paulo Miki ainda pregou ao povo, perdoando seus algozes. Os 26 mártires do Japão foram canonizados em 1862.',
    biographyKids: null,
    quotes: [{ text: 'Do alto desta cruz, eu vos declaro que não há outro caminho de salvação senão o dos cristãos.', source: 'Último sermão na cruz' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.7503,
    longitude: 129.8779,
  },
  {
    name: 'Santa Coleta',
    slug: 'santa-coleta',
    feastMonth: 2,
    feastDay: 7,
    birthDate: '1381',
    deathDate: '1447',
    birthPlace: 'Corbie, França',
    deathPlace: 'Gante, Bélgica',
    country: 'França',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['mulheres grávidas', 'crianças doentes'],
    biographyShort: 'Religiosa francesa que reformou a Ordem das Clarissas, restaurando a observância da regra original de Santa Clara em diversos conventos da Europa.',
    biographyFull: 'Santa Coleta nasceu em 1381 em Corbie, na Picardia, França. Órfã desde cedo, experimentou diversas formas de vida religiosa antes de sentir o chamado para reformar a Ordem das Clarissas.\n\nAutorizada pelo Papa Bento XIII, Coleta fundou e reformou dezessete conventos, restaurando a pobreza e austeridade originais da regra de Santa Clara. Sua reforma se espalhou por toda a França, Bélgica e Espanha.\n\nFaleceu em 1447 em Gante. As Clarissas Coletinas, ramo que leva seu nome, continuam presentes na Igreja até hoje.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.9089,
    longitude: 2.5128,
  },
  {
    name: 'Santa Josefina Bakhita',
    slug: 'santa-josefina-bakhita',
    feastMonth: 2,
    feastDay: 8,
    birthDate: '1869',
    deathDate: '1947',
    birthPlace: 'Olgossa, Darfur, Sudão',
    deathPlace: 'Schio, Itália',
    country: 'Sudão',
    century: 19,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['vítimas de tráfico humano', 'Sudão'],
    biographyShort: 'Nascida no Sudão e escravizada na infância, Josefina Bakhita encontrou a liberdade e a fé na Itália, tornando-se religiosa canossiana e símbolo de esperança.',
    biographyFull: 'Josefina Bakhita nasceu em 1869 no Darfur, Sudão. Aos sete anos foi sequestrada por traficantes de escravos e vendida várias vezes, sofrendo torturas e humilhações. O nome "Bakhita" (afortunada) lhe foi dado por seus captores.\n\nLevada à Itália por um cônsul, conheceu as Irmãs Canossians e a fé católica. Batizada em 1890, recusou-se a voltar à escravidão e, com apoio da justiça italiana, conquistou sua liberdade. Entrou na vida religiosa em 1896.\n\nViveu mais de 50 anos como religiosa em Schio, encantando a todos com sua bondade e alegria. Faleceu em 1947 e foi canonizada por João Paulo II em 2000.',
    biographyKids: null,
    quotes: [{ text: 'Se eu encontrasse aqueles negreiros que me raptaram e torturaram, eu me ajoelharia e beijaria suas mãos, pois sem eles eu não teria encontrado Deus.', source: 'Autobiografia' }],
    prayer: null,
    imageUrl: null,
    latitude: 13.5,
    longitude: 25.0,
  },
  {
    name: 'Santa Apolônia',
    slug: 'santa-apolonia',
    feastMonth: 2,
    feastDay: 9,
    birthDate: null,
    deathDate: '249',
    birthPlace: 'Alexandria, Egito',
    deathPlace: 'Alexandria, Egito',
    country: 'Egito',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['dentistas', 'dor de dente'],
    biographyShort: 'Virgem e mártir de Alexandria, Santa Apolônia teve os dentes arrancados durante a perseguição e lançou-se ao fogo antes de negar a fé.',
    biographyFull: 'Santa Apolônia era uma diaconisa idosa de Alexandria, no Egito. Durante a perseguição do imperador Décio, foi presa por uma turba pagã que lhe arrancou todos os dentes como forma de tortura.\n\nAmeaçada de ser queimada viva se não renunciasse à fé, Apolônia pediu um instante, e então se lançou voluntariamente às chamas, preferindo a morte à apostasia.\n\nSeu martírio, ocorrido em 249, é relatado pelo bispo Dionísio de Alexandria. Tornou-se padroeira dos dentistas e é invocada contra dores de dente em toda a tradição católica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.2001,
    longitude: 29.9187,
  },
  {
    name: 'Santa Escolástica',
    slug: 'santa-escolastica',
    feastMonth: 2,
    feastDay: 10,
    birthDate: '480',
    deathDate: '543',
    birthPlace: 'Núrsia, Itália',
    deathPlace: 'Monte Cassino, Itália',
    country: 'Itália',
    century: 6,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['monjas beneditinas', 'crianças com convulsões'],
    biographyShort: 'Irmã gêmea de São Bento, Santa Escolástica fundou um mosteiro feminino perto de Monte Cassino e é considerada a primeira monja beneditina.',
    biographyFull: 'Santa Escolástica nasceu por volta de 480 em Núrsia, Itália, irmã gêmea de São Bento. Consagrou-se a Deus desde a infância e fundou um mosteiro feminino nos arredores de Monte Cassino.\n\nVisitava o irmão uma vez por ano. No último encontro, pediu que ele ficasse conversando sobre Deus durante a noite. Quando Bento recusou, Escolástica rezou e uma tempestade impediu sua partida. Três dias depois, ela faleceu.\n\nSão Bento viu a alma da irmã subir ao céu em forma de pomba. Santa Escolástica é venerada como modelo de vida contemplativa e amor fraterno.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.8166,
    longitude: 13.0956,
  },
  {
    name: 'Nossa Senhora de Lourdes',
    slug: 'nossa-senhora-de-lourdes',
    feastMonth: 2,
    feastDay: 11,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'França',
    century: 19,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['enfermos', 'Dia Mundial do Enfermo'],
    biographyShort: 'Em 1858, a Virgem Maria apareceu dezoito vezes a Santa Bernadette Soubirous na gruta de Massabielle, em Lourdes, identificando-se como a Imaculada Conceição.',
    biographyFull: 'Em 11 de fevereiro de 1858, a jovem Bernadette Soubirous, de 14 anos, viu uma "Senhora vestida de branco" na gruta de Massabielle, em Lourdes, sul da França. As aparições se repetiram dezoito vezes.\n\nA Senhora pediu oração, penitência e a construção de uma capela no local. Quando questionada sobre sua identidade, respondeu: "Eu sou a Imaculada Conceição". Uma fonte de água brotou na gruta, e numerosas curas inexplicáveis foram relatadas.\n\nLourdes tornou-se um dos maiores santuários marianos do mundo, recebendo milhões de peregrinos anualmente. A festa é também o Dia Mundial do Enfermo, instituído por São João Paulo II.',
    biographyKids: null,
    quotes: [{ text: 'Eu sou a Imaculada Conceição.', source: 'Palavras da Virgem a Bernadette (25 de março de 1858)' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.0986,
    longitude: -0.0563,
  },
  {
    name: 'Santa Eulália de Barcelona',
    slug: 'santa-eulalia-de-barcelona',
    feastMonth: 2,
    feastDay: 12,
    birthDate: '290',
    deathDate: '303',
    birthPlace: 'Barcelona, Espanha',
    deathPlace: 'Barcelona, Espanha',
    country: 'Espanha',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['Barcelona', 'marinheiros'],
    biographyShort: 'Jovem mártir de Barcelona, Santa Eulália sofreu treze torturas durante a perseguição de Diocleciano, uma para cada ano de sua vida.',
    biographyFull: 'Santa Eulália nasceu por volta de 290 em Barcelona. Durante a perseguição de Diocleciano, aos treze anos, apresentou-se voluntariamente ao governador Daciano para professar sua fé cristã.\n\nA tradição narra que sofreu treze torturas diferentes, correspondentes aos seus treze anos de idade, incluindo ser colocada em um barril com pregos e rolada morro abaixo.\n\nFoi martirizada em 303. Seus restos foram encontrados no século IX e depositados na catedral de Barcelona, que leva seu nome. É co-padroeira da cidade de Barcelona.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.3839,
    longitude: 2.1764,
  },
  {
    name: 'São Benigno',
    slug: 'sao-benigno',
    feastMonth: 2,
    feastDay: 13,
    birthDate: null,
    deathDate: '178',
    birthPlace: 'Esmirna, Turquia',
    deathPlace: 'Dijon, França',
    country: 'França',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Dijon', 'evangelização'],
    biographyShort: 'Discípulo de São Policarpo, São Benigno foi enviado como missionário à Gália, onde evangelizou a região de Dijon e sofreu o martírio no século II.',
    biographyFull: 'São Benigno foi, segundo a tradição, um discípulo de São Policarpo de Esmirna, enviado como missionário para evangelizar a Gália. Estabeleceu-se na região de Dijon, na Borgonha.\n\nSua pregação converteu muitos pagãos ao cristianismo, o que provocou a ira das autoridades romanas. Foi preso e submetido a diversas torturas antes de ser martirizado.\n\nA basílica de São Benigno em Dijon, construída sobre seu túmulo, tornou-se um importante centro de peregrinação. Sua memória é venerada especialmente na diocese de Dijon.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.3216,
    longitude: 5.0415,
  },
  {
    name: 'São Cirilo e São Metódio',
    slug: 'sao-cirilo-e-sao-metodio',
    feastMonth: 2,
    feastDay: 14,
    birthDate: '826',
    deathDate: '885',
    birthPlace: 'Tessalônica, Grécia',
    deathPlace: 'Roma, Itália',
    country: 'Grécia',
    century: 9,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Europa', 'unidade dos cristãos'],
    biographyShort: 'Irmãos gregos, Santos Cirilo e Metódio evangelizaram os povos eslavos, criaram o alfabeto glagolítico e traduziram a liturgia para a língua eslava.',
    biographyFull: 'Cirilo e Metódio eram irmãos nascidos em Tessalônica, Grécia, no século IX. Altamente instruídos, foram enviados pelo imperador bizantino para evangelizar os povos eslavos da Morávia.\n\nPara facilitar a missão, Cirilo criou o alfabeto glagolítico (precursor do cirílico) e traduziu os textos litúrgicos e bíblicos para a língua eslava, dando origem à tradição literária de diversos povos.\n\nSão venerados como "Apóstolos dos Eslavos" e foram proclamados co-padroeiros da Europa por São João Paulo II em 1980, junto com São Bento.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.6401,
    longitude: 22.9444,
  },
  {
    name: 'São Cláudio de la Colombière',
    slug: 'sao-claudio-de-la-colombiere',
    feastMonth: 2,
    feastDay: 15,
    birthDate: '1641',
    deathDate: '1682',
    birthPlace: 'Saint-Symphorien-d\'Ozon, França',
    deathPlace: 'Paray-le-Monial, França',
    country: 'França',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['devoção ao Sagrado Coração', 'diretores espirituais'],
    biographyShort: 'Jesuíta francês, São Cláudio foi o diretor espiritual de Santa Margarida Maria Alacoque e grande promotor da devoção ao Sagrado Coração de Jesus.',
    biographyFull: 'São Cláudio de la Colombière nasceu em 1641 na França e entrou na Companhia de Jesus. Homem de profunda vida interior, tornou-se um pregador renomado.\n\nEm 1675, foi nomeado superior da casa jesuíta de Paray-le-Monial, onde se tornou diretor espiritual de Santa Margarida Maria Alacoque. Foi o primeiro a acreditar nas revelações do Sagrado Coração e a promover esta devoção.\n\nEnviado à Inglaterra como capelão, foi preso por causa da fé e exilado. Voltou à França com saúde debilitada e faleceu em 1682. Foi canonizado em 1992 por João Paulo II.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.4514,
    longitude: 4.1209,
  },
  {
    name: 'Santa Juliana de Nicomédia',
    slug: 'santa-juliana-de-nicomedia',
    feastMonth: 2,
    feastDay: 16,
    birthDate: null,
    deathDate: '304',
    birthPlace: 'Nicomédia, Turquia',
    deathPlace: 'Nicomédia, Turquia',
    country: 'Turquia',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['mulheres doentes', 'parturientes'],
    biographyShort: 'Virgem e mártir de Nicomédia, Santa Juliana recusou o casamento com um pagão e enfrentou torturas e a morte por amor a Cristo durante a perseguição de Diocleciano.',
    biographyFull: 'Santa Juliana nasceu em Nicomédia, na Ásia Menor, filha de pai pagão. Convertida ao cristianismo, recusou o casamento com o senador Evilásio por ele ser pagão.\n\nSeu pai a entregou ao governador, que a submeteu a torturas cruéis. Segundo a tradição, resistiu a todas as provações mantendo firme sua fé e sua virgindade consagrada.\n\nFoi decapitada por volta de 304, durante a perseguição de Diocleciano. Seu culto se espalhou pelo Oriente e Ocidente, sendo especialmente popular na Itália e nos Países Baixos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.7627,
    longitude: 29.9207,
  },
  {
    name: 'Sete Santos Fundadores Servitas',
    slug: 'sete-santos-fundadores-servitas',
    feastMonth: 2,
    feastDay: 17,
    birthDate: null,
    deathDate: '1310',
    birthPlace: 'Florença, Itália',
    deathPlace: 'Monte Senário, Itália',
    country: 'Itália',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Ordem dos Servitas', 'devoção à Virgem Dolorosa'],
    biographyShort: 'Sete mercadores florentinos que, em 1233, abandonaram tudo para se retirar ao Monte Senário, fundando a Ordem dos Servos de Maria (Servitas).',
    biographyFull: 'Em 1233, sete jovens comerciantes de Florença — Bonfílio, Bonajunta, Amadeu, Maneto, Hugo, Sosteneo e Aleixo — renunciaram às riquezas e se retiraram ao Monte Senário para viver em oração e penitência.\n\nLá fundaram a Ordem dos Servos de Maria (Servitas), dedicada à contemplação das dores da Virgem Maria. A ordem recebeu aprovação papal e se espalhou pela Europa.\n\nO último sobrevivente, Santo Aleixo Falconieri, morreu em 1310 com 110 anos. Os sete fundadores foram canonizados juntos pelo Papa Leão XIII em 1888, caso único na história da Igreja.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.7696,
    longitude: 11.2558,
  },
  {
    name: 'São Simeão',
    slug: 'sao-simeao',
    feastMonth: 2,
    feastDay: 18,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Jerusalém, Israel',
    deathPlace: 'Jerusalém, Israel',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['idosos', 'profetas'],
    biographyShort: 'Ancião justo e piedoso de Jerusalém, São Simeão recebeu do Espírito Santo a promessa de que não morreria antes de ver o Messias, e reconheceu Jesus no Templo.',
    biographyFull: 'São Simeão é descrito no Evangelho de São Lucas como um homem justo e piedoso de Jerusalém que aguardava a consolação de Israel. O Espírito Santo lhe revelara que não morreria antes de ver o Cristo do Senhor.\n\nQuando Maria e José levaram o Menino Jesus ao Templo, Simeão o tomou nos braços e pronunciou o cântico "Nunc Dimittis": "Agora, Senhor, podeis deixar vosso servo ir em paz".\n\nProfetizou também que Jesus seria "sinal de contradição" e que uma espada transpassaria a alma de Maria. É venerado como profeta e modelo de esperança na velhice.',
    biographyKids: null,
    quotes: [{ text: 'Meus olhos viram a vossa salvação, que preparastes diante de todos os povos: luz para iluminar as nações e glória de vosso povo, Israel.', source: 'Lucas 2,30-32' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7767,
    longitude: 35.2345,
  },
  {
    name: 'São Conrado de Piacenza',
    slug: 'sao-conrado-de-piacenza',
    feastMonth: 2,
    feastDay: 19,
    birthDate: '1290',
    deathDate: '1351',
    birthPlace: 'Piacenza, Itália',
    deathPlace: 'Noto, Sicília, Itália',
    country: 'Itália',
    century: 14,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['penitentes', 'hérnias'],
    biographyShort: 'Nobre italiano que, após causar acidentalmente um incêndio, vendeu tudo e abraçou a vida eremítica como terciário franciscano na Sicília.',
    biographyFull: 'São Conrado nasceu em 1290 em Piacenza, Itália, em família nobre. Durante uma caçada, provocou acidentalmente um incêndio florestal. Quando um inocente foi acusado em seu lugar, Conrado confessou a culpa e pagou todos os danos.\n\nO episódio o levou a uma profunda conversão. Com a esposa, decidiu abandonar tudo: ela entrou num convento de Clarissas e ele se tornou terciário franciscano eremita, retirando-se para a Sicília.\n\nViveu em oração e penitência perto de Noto, onde realizou diversos milagres. Faleceu em 1351 e é venerado como padroeiro de Noto.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.0526,
    longitude: 9.6928,
  },
  {
    name: 'São Jacinto de Cesareia',
    slug: 'sao-jacinto-de-cesareia',
    feastMonth: 2,
    feastDay: 20,
    birthDate: null,
    deathDate: '108',
    birthPlace: 'Cesareia, Capadócia, Turquia',
    deathPlace: 'Cesareia, Capadócia, Turquia',
    country: 'Turquia',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['jovens mártires', 'perseguidos pela fé'],
    biographyShort: 'Jovem cristão de Cesareia da Capadócia, São Jacinto foi martirizado por recusar oferecer sacrifício aos ídolos, morrendo na prisão após longa tortura.',
    biographyFull: 'São Jacinto era um jovem cristão que vivia em Cesareia da Capadócia, no início do século II. Durante a perseguição do imperador Trajano, foi preso por professar publicamente a fé cristã.\n\nAs autoridades romanas tentaram forçá-lo a oferecer sacrifício aos deuses pagãos, mas Jacinto recusou firmemente. Foi submetido a torturas e encarcerado, morrendo na prisão por causa dos ferimentos.\n\nSeu culto é antigo e difundido tanto no Oriente quanto no Ocidente. É venerado como modelo de coragem e fidelidade juvenil a Cristo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.7312,
    longitude: 35.4787,
  },
  {
    name: 'São Pedro Damião',
    slug: 'sao-pedro-damiao',
    feastMonth: 2,
    feastDay: 21,
    birthDate: '1007',
    deathDate: '1072',
    birthPlace: 'Ravena, Itália',
    deathPlace: 'Faenza, Itália',
    country: 'Itália',
    century: 11,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['reformadores da Igreja', 'monges'],
    biographyShort: 'Doutor da Igreja e cardeal, São Pedro Damião foi um dos maiores reformadores do século XI, combatendo a simonia e a corrupção no clero com firmeza e erudição.',
    biographyFull: 'São Pedro Damião nasceu em 1007 em Ravena. Órfão desde criança, foi educado por seu irmão mais velho, o arcipreste Damião, de quem adotou o sobrenome. Tornou-se monge camaldulense e prior do eremitério de Fonte Avellana.\n\nFoi nomeado cardeal-bispo de Óstia pelo Papa Estêvão IX. Dedicou-se com vigor à reforma da Igreja, denunciando a simonia, o nicolaísmo e a corrupção clerical em obras como o "Liber Gomorrhianus".\n\nMorreu em 1072 em Faenza. Foi declarado Doutor da Igreja em 1828 por Leão XII, reconhecido por sua contribuição teológica e seu zelo reformador.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.4184,
    longitude: 12.2035,
  },
  {
    name: 'Cátedra de São Pedro',
    slug: 'catedra-de-sao-pedro',
    feastMonth: 2,
    feastDay: 22,
    birthDate: null,
    deathDate: '64',
    birthPlace: 'Betsaida, Israel',
    deathPlace: 'Roma, Itália',
    country: 'Israel',
    century: 1,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['papado', 'unidade da Igreja'],
    biographyShort: 'A festa da Cátedra de São Pedro celebra a autoridade doutrinária e pastoral que Cristo confiou ao apóstolo Pedro como fundamento da Igreja.',
    biographyFull: 'A festa da Cátedra de São Pedro não celebra um evento histórico, mas o ministério de ensino e governo que Cristo confiou a Pedro com as palavras: "Tu és Pedro, e sobre esta pedra edificarei a minha Igreja".\n\nA "cátedra" simboliza a cadeira do mestre, a autoridade de ensinar a verdade da fé. Na Basílica de São Pedro, no Vaticano, Bernini criou o monumental trono de bronze que guarda a antiga cadeira atribuída ao apóstolo.\n\nEsta festa é uma celebração da unidade da Igreja em torno do sucessor de Pedro e do carisma da infalibilidade pontifícia em matéria de fé e moral.',
    biographyKids: null,
    quotes: [{ text: 'Tu és o Cristo, o Filho do Deus vivo.', source: 'Mateus 16,16' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.9022,
    longitude: 12.4539,
  },
  {
    name: 'São Policarpo',
    slug: 'sao-policarpo',
    feastMonth: 2,
    feastDay: 23,
    birthDate: '69',
    deathDate: '155',
    birthPlace: 'Esmirna, Turquia',
    deathPlace: 'Esmirna, Turquia',
    country: 'Turquia',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['contra dor de ouvido', 'vítimas de queimaduras'],
    biographyShort: 'Discípulo do apóstolo São João e bispo de Esmirna, São Policarpo foi martirizado aos 86 anos, queimado vivo por recusar negar a Cristo.',
    biographyFull: 'São Policarpo foi discípulo direto do apóstolo São João e tornou-se bispo de Esmirna. Era considerado o principal elo entre os apóstolos e a geração seguinte de cristãos.\n\nEm 155, durante a perseguição, foi preso e levado ao estádio. O procônsul exigiu que blasfemasse contra Cristo, ao que Policarpo respondeu: "Há oitenta e seis anos eu o sirvo e nenhum mal me fez. Como posso blasfemar contra meu Rei e Salvador?"\n\nFoi condenado à fogueira. Segundo o relato, as chamas formaram um arco ao redor dele sem queimá-lo, sendo então traspassado por uma espada. Seu martírio é um dos mais antigos e bem documentados da história da Igreja.',
    biographyKids: null,
    quotes: [{ text: 'Há oitenta e seis anos eu o sirvo e nenhum mal me fez. Como posso blasfemar contra meu Rei e Salvador?', source: 'Martírio de Policarpo' }],
    prayer: null,
    imageUrl: null,
    latitude: 38.4189,
    longitude: 27.1287,
  },
  {
    name: 'São Modesto',
    slug: 'sao-modesto',
    feastMonth: 2,
    feastDay: 24,
    birthDate: null,
    deathDate: '634',
    birthPlace: 'Palestina',
    deathPlace: 'Jerusalém, Palestina',
    country: 'Palestina',
    century: 7,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Jerusalém', 'reconstrução de igrejas'],
    biographyShort: 'Patriarca de Jerusalém, São Modesto reconstruiu os lugares santos destruídos pela invasão persa de 614, restaurando a vida cristã na Terra Santa.',
    biographyFull: 'São Modesto foi um monge que se tornou patriarca de Jerusalém no início do século VII. Após a devastadora invasão persa de 614, que destruiu igrejas e mosteiros e massacrou milhares de cristãos, coube a Modesto a tarefa de reconstrução.\n\nCom energia e fé, restaurou a Basílica do Santo Sepulcro e outros santuários, recolhendo os restos dos mártires e reorganizando a vida religiosa na cidade santa.\n\nGovernou a diocese com sabedoria e caridade até sua morte em 634, pouco antes da conquista árabe de Jerusalém. É venerado como pastor exemplar em tempos de crise.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7767,
    longitude: 35.2345,
  },
  {
    name: 'São Cesário de Nazianzo',
    slug: 'sao-cesario-de-nazianzo',
    feastMonth: 2,
    feastDay: 25,
    birthDate: '330',
    deathDate: '369',
    birthPlace: 'Nazianzo, Capadócia, Turquia',
    deathPlace: 'Bitínia, Turquia',
    country: 'Turquia',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['médicos', 'cientistas'],
    biographyShort: 'Irmão de São Gregório Nazianzeno, São Cesário foi médico da corte imperial em Constantinopla e, após sobreviver a um terremoto, consagrou-se inteiramente a Deus.',
    biographyFull: 'São Cesário nasceu em Nazianzo, Capadócia, por volta de 330, filho dos santos Gregório e Nona e irmão de São Gregório Nazianzeno. Estudou medicina em Alexandria e tornou-se médico na corte do imperador Constâncio.\n\nManteve sua fé mesmo sob o imperador Juliano, o Apóstata, que tentou atraí-lo ao paganismo. Após sobreviver ao terremoto de Niceia em 368, decidiu abandonar a vida na corte e dedicar-se totalmente a Deus.\n\nFaleceu pouco depois, em 369. Seu irmão Gregório pronunciou um célebre discurso fúnebre em sua honra, elogiando sua fé e suas virtudes cristãs.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.3,
    longitude: 34.1,
  },
  {
    name: 'São Porfírio de Gaza',
    slug: 'sao-porfirio-de-gaza',
    feastMonth: 2,
    feastDay: 26,
    birthDate: '347',
    deathDate: '420',
    birthPlace: 'Tessalônica, Grécia',
    deathPlace: 'Gaza, Palestina',
    country: 'Palestina',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Gaza', 'luta contra a idolatria'],
    biographyShort: 'Bispo de Gaza, São Porfírio dedicou-se a converter a cidade, ainda fortemente pagã, conseguindo com apoio imperial a destruição dos templos e a construção de igrejas.',
    biographyFull: 'São Porfírio nasceu em Tessalônica por volta de 347. Após anos como monge no Egito e na Palestina, foi ordenado e nomeado bispo de Gaza em 395, cidade onde o paganismo ainda dominava.\n\nEnfrentou forte oposição dos pagãos, que o perseguiram e ameaçaram. Com apoio da imperatriz Eudóxia, obteve um decreto imperial para fechar os templos pagãos. Sobre o principal deles, ergueu uma grande igreja dedicada a Cristo.\n\nGovernou a diocese de Gaza por 25 anos, convertendo a maioria da população ao cristianismo. Faleceu em 420, sendo lembrado como pastor corajoso e evangelizador incansável.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.5,
    longitude: 34.4667,
  },
  {
    name: 'São Gabriel dell\'Addolorata',
    slug: 'sao-gabriel-delladdolorata',
    feastMonth: 2,
    feastDay: 27,
    birthDate: '1838',
    deathDate: '1862',
    birthPlace: 'Assis, Itália',
    deathPlace: 'Isola del Gran Sasso, Itália',
    country: 'Itália',
    century: 19,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['jovens', 'seminaristas'],
    biographyShort: 'Jovem religioso passionista italiano, São Gabriel viveu uma breve mas intensa vida de oração e devoção à Virgem Dolorosa, morrendo de tuberculose aos 24 anos.',
    biographyFull: 'Francisco Possenti nasceu em 1838 em Assis, Itália. Jovem alegre e sociável, após duas graves doenças sentiu o chamado à vida religiosa. Entrou na Congregação dos Passionistas em 1856, recebendo o nome de Gabriel da Virgem das Dores.\n\nNo noviciado e no estudantado, destacou-se por sua profunda devoção a Nossa Senhora das Dores, pela alegria e pela obediência heroica. Vivia cada pequeno dever com extraordinário amor.\n\nContraiu tuberculose e faleceu em 1862, com apenas 24 anos, em Isola del Gran Sasso. Foi canonizado em 1920 e tornou-se padroeiro da juventude católica italiana.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.0707,
    longitude: 12.6196,
  },
  {
    name: 'São Romano de Condat',
    slug: 'sao-romano-de-condat',
    feastMonth: 2,
    feastDay: 28,
    birthDate: '390',
    deathDate: '463',
    birthPlace: 'Ain, França',
    deathPlace: 'Condat, Jura, França',
    country: 'França',
    century: 5,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'montanheses'],
    biographyShort: 'Eremita e fundador monástico, São Romano se retirou para as montanhas do Jura, onde fundou os mosteiros de Condat e Lauconne com seu irmão São Lupicino.',
    biographyFull: 'São Romano nasceu por volta de 390 na região de Ain, na França. Aos 35 anos, inspirado pela leitura da vida dos Padres do Deserto, retirou-se para a solidão das montanhas do Jura.\n\nSeu irmão Lupicino juntou-se a ele, e logo outros discípulos vieram. Fundaram os mosteiros de Condat (atual Saint-Claude) e Lauconne, que se tornaram importantes centros de vida monástica na Gália.\n\nRomano governou suas comunidades com mansidão e sabedoria até sua morte, por volta de 463. Os mosteiros que fundou persistiram por séculos como faróis de fé e cultura na região do Jura.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.3867,
    longitude: 5.8633,
  },
];
