import type { SaintSeedData } from './types';

export const januarySaints: SaintSeedData[] = [
  {
    name: 'Santa Maria Mãe de Deus',
    slug: 'santa-maria-mae-de-deus',
    feastMonth: 1,
    feastDay: 1,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['mães', 'gestantes', 'Igreja Católica'],
    biographyShort:
      'Maria de Nazaré é a Mãe de Jesus Cristo, o Filho de Deus. Escolhida por Deus para ser a Theotokos, viveu com humildade e fé inabalável. É venerada como a maior de todos os santos e modelo perfeito de discipulado.',
    biographyFull:
      'Maria nasceu em Nazaré, na Galileia, provavelmente no século I a.C. Segundo a tradição, era filha de São Joaquim e Santa Ana. Foi escolhida por Deus para ser a Mãe do Salvador e recebeu o anúncio do Anjo Gabriel com plena obediência.\n\nCasou-se com São José e deu à luz Jesus em Belém. Acompanhou seu Filho ao longo de toda a sua vida pública e esteve ao pé da Cruz no Calvário, unindo seu sofrimento ao sacrifício redentor de Cristo.\n\nA solenidade de Santa Maria Mãe de Deus, celebrada em 1º de janeiro, afirma o dogma proclamado no Concílio de Éfeso em 431. Maria é honrada como Mãe da Igreja e intercessora de todos os fiéis.\n\nSua vida de fé, obediência e amor materno é modelo para todos os cristãos. O título de Mãe de Deus expressa a realidade da Encarnação: o Filho que ela gerou é verdadeiro Deus e verdadeiro homem.',
    biographyKids: null,
    quotes: [
      {
        text: 'Fazei tudo o que Ele vos disser.',
        source: 'Evangelho de São João 2,5',
      },
    ],
    prayer:
      'Santa Maria, Mãe de Deus, rogai por nós pecadores, agora e na hora da nossa morte. Amém.',
    imageUrl: null,
    latitude: 32.699,
    longitude: 35.304,
  },
  {
    name: 'São Basílio Magno',
    slug: 'sao-basilio-magno',
    feastMonth: 1,
    feastDay: 2,
    birthDate: '329-01-01',
    deathDate: '379-01-01',
    birthPlace: 'Cesareia da Capadócia',
    deathPlace: 'Cesareia da Capadócia',
    country: 'Turquia',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['monges', 'educadores', 'hospitaleiros'],
    biographyShort:
      'São Basílio Magno foi bispo de Cesareia e um dos grandes Padres da Igreja do século IV. Combateu o arianismo e organizou a vida monástica no Oriente com sua famosa Regra.',
    biographyFull:
      'Basílio nasceu por volta de 329 em Cesareia da Capadócia, numa família profundamente cristã que produziu vários santos. Estudou em Constantinopla e Atenas, onde conheceu São Gregório Nazianzeno.\n\nApós sua conversão à vida ascética, visitou comunidades monásticas no Egito e na Síria. Fundou mosteiros e redigiu regras monásticas que são a base do monaquismo oriental até hoje.\n\nOrdenado bispo de Cesareia em 370, enfrentou o imperador Valente na defesa da fé nicena contra o arianismo. Também se dedicou à caridade, fundando o Basilíades, um complexo hospitalar para pobres e doentes.\n\nFaleceu em 1º de janeiro de 379 e é venerado como Doutor da Igreja. Sua teologia trinitária foi decisiva para o Concílio de Constantinopla de 381.',
    biographyKids: null,
    quotes: [
      {
        text: 'O pão que guardas pertence ao faminto; o casaco que trancas no armário pertence ao nu.',
        source: 'Homilia sobre a riqueza',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 38.73,
    longitude: 35.48,
  },
  {
    name: 'Santa Genoveva',
    slug: 'santa-genoveva',
    feastMonth: 1,
    feastDay: 3,
    birthDate: '422-01-01',
    deathDate: '502-01-03',
    birthPlace: 'Nanterre',
    deathPlace: 'Paris',
    country: 'França',
    century: 6,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Paris', 'pastoras', 'contra desastres'],
    biographyShort:
      'Santa Genoveva foi uma virgem consagrada que se tornou padroeira de Paris. Com suas orações, salvou a cidade da invasão dos hunos de Átila no século V.',
    biographyFull:
      'Genoveva nasceu em Nanterre, perto de Paris, por volta de 422. Aos sete anos, foi consagrada a Deus por São Germano de Auxerre, que reconheceu nela uma vocação especial.\n\nQuando Átila e seus hunos ameaçaram Paris em 451, Genoveva exortou os parisienses a permanecerem na cidade e confiarem em Deus. O exército huno desviou-se de Paris, e o povo atribuiu a salvação às orações da santa.\n\nDedicou sua vida à oração, penitência e caridade, ajudando os pobres e resgatando prisioneiros. Exerceu grande influência junto aos reis francos, especialmente Clóvis, a quem encorajou na conversão ao cristianismo.\n\nFaleceu em Paris por volta de 502. Uma igreja foi erguida sobre seu túmulo, que mais tarde deu origem ao Panteão de Paris.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.893,
    longitude: 2.212,
  },
  {
    name: 'Santa Ângela de Foligno',
    slug: 'santa-angela-de-foligno',
    feastMonth: 1,
    feastDay: 4,
    birthDate: '1248-01-01',
    deathDate: '1309-01-04',
    birthPlace: 'Foligno',
    deathPlace: 'Foligno',
    country: 'Itália',
    century: 14,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['viúvas', 'tentados', 'penitentes'],
    biographyShort:
      'Santa Ângela de Foligno foi uma mística franciscana italiana do século XIII. Após uma conversão radical, viveu em profunda penitência e deixou escritos místicos notáveis sobre a vida espiritual.',
    biographyFull:
      'Ângela nasceu em Foligno, na Úmbria, em 1248. Viveu uma juventude mundana, casou-se e teve filhos. Após a morte do marido e dos filhos, passou por uma profunda conversão.\n\nIngressou na Ordem Terceira Franciscana e abraçou uma vida de pobreza radical e penitência. Suas intensas experiências místicas foram ditadas ao frei Arnaldo e compiladas no Memorial, obra fundamental da mística cristã.\n\nSeus escritos descrevem os trinta passos da vida espiritual, desde a consciência do pecado até a união transformante com Deus. Foi chamada de "Mestra dos Teólogos" pela profundidade de sua doutrina.\n\nFaleceu em 4 de janeiro de 1309. Foi canonizada pelo Papa Francisco em 2013.',
    biographyKids: null,
    quotes: [
      {
        text: 'Vi Deus numa treva, porque Ele está além de todo bem que a mente pode conceber.',
        source: 'Memorial',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 42.95,
    longitude: 12.71,
  },
  {
    name: 'São João Neumann',
    slug: 'sao-joao-neumann',
    feastMonth: 1,
    feastDay: 5,
    birthDate: '1811-03-28',
    deathDate: '1860-01-05',
    birthPlace: 'Prachatice',
    deathPlace: 'Filadélfia',
    country: 'República Tcheca',
    century: 19,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['educação católica', 'imigrantes'],
    biographyShort:
      'São João Neumann foi um bispo redentorista de origem boêmia que evangelizou os Estados Unidos no século XIX. Fundou o primeiro sistema de escolas paroquiais católicas da América.',
    biographyFull:
      'João Neumann nasceu em 28 de março de 1811 em Prachatice, na Boêmia. Sentindo-se chamado às missões, emigrou para os Estados Unidos em 1836, onde foi ordenado sacerdote em Nova York.\n\nIngressou na Congregação do Santíssimo Redentor e trabalhou incansavelmente entre os imigrantes alemães. Em 1852, foi nomeado bispo de Filadélfia, tornando-se o primeiro bispo redentorista na América.\n\nComo bispo, fundou quase cem escolas paroquiais e estabeleceu o primeiro sistema diocesano de educação católica nos Estados Unidos. Também construiu igrejas e incentivou a devoção das Quarenta Horas.\n\nFaleceu subitamente em 5 de janeiro de 1860, aos quarenta e oito anos. Foi canonizado pelo Papa Paulo VI em 1977, o primeiro bispo americano a receber essa honra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.012,
    longitude: 13.997,
  },
  {
    name: 'Santos Reis Magos',
    slug: 'santos-reis-magos',
    feastMonth: 1,
    feastDay: 6,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Pérsia',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['viajantes', 'peregrinos', 'fabricantes de cartas'],
    biographyShort:
      'Os Santos Reis Magos — Gaspar, Melquior e Baltazar — foram sábios do Oriente que seguiram uma estrela até Belém para adorar o Menino Jesus. Ofereceram ouro, incenso e mirra como presentes.',
    biographyFull:
      'Os Reis Magos são mencionados no Evangelho de São Mateus como sábios vindos do Oriente que seguiram uma estrela até Belém. A tradição lhes atribuiu os nomes Gaspar, Melquior e Baltazar, representando diferentes povos e idades.\n\nAo chegarem a Jerusalém, perguntaram pelo "rei dos judeus que acaba de nascer". Herodes, perturbado, pediu-lhes que voltassem com informações, mas um anjo os avisou em sonho para retornarem por outro caminho.\n\nOs presentes que ofereceram são ricos em simbolismo: ouro para a realeza de Cristo, incenso para sua divindade e mirra para seu sofrimento e morte.\n\nA solenidade da Epifania celebra a manifestação de Jesus aos povos gentios. Suas supostas relíquias são veneradas na Catedral de Colônia, na Alemanha.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.705,
    longitude: 35.21,
  },
  {
    name: 'São Raimundo de Peñafort',
    slug: 'sao-raimundo-de-penafort',
    feastMonth: 1,
    feastDay: 7,
    birthDate: '1175-01-01',
    deathDate: '1275-01-06',
    birthPlace: 'Vilafranca del Penedès',
    deathPlace: 'Barcelona',
    country: 'Espanha',
    century: 13,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['advogados', 'canonistas'],
    biographyShort:
      'São Raimundo de Peñafort foi um frade dominicano e grande jurista do século XIII. Compilou as Decretais de Gregório IX e foi mestre-geral da Ordem dos Pregadores.',
    biographyFull:
      'Raimundo nasceu por volta de 1175 em Vilafranca del Penedès, na Catalunha. Estudou e ensinou direito em Barcelona e Bolonha, destacando-se como brilhante jurista.\n\nIngressou na Ordem dos Pregadores em 1222 e foi encarregado pelo Papa Gregório IX de compilar as Decretais, o código de direito canônico que serviu de referência por séculos. Também escreveu a Summa de Poenitentia, manual fundamental para confessores.\n\nFoi eleito mestre-geral dos dominicanos em 1238, mas renunciou após dois anos para dedicar-se à evangelização dos muçulmanos e judeus na Espanha. Incentivou São Tomás de Aquino a escrever a Summa contra Gentiles.\n\nFaleceu em Barcelona em 1275, com quase cem anos. Foi canonizado em 1601 e é padroeiro dos canonistas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.347,
    longitude: 1.697,
  },
  {
    name: 'São Severino',
    slug: 'sao-severino',
    feastMonth: 1,
    feastDay: 8,
    birthDate: '410-01-01',
    deathDate: '482-01-08',
    birthPlace: null,
    deathPlace: 'Favianis',
    country: 'Itália',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Áustria', 'prisioneiros'],
    biographyShort:
      'São Severino foi um monge e apóstolo do Norico (atual Áustria) no século V. Evangelizou as populações romanas e germânicas da região do Danúbio durante as invasões bárbaras.',
    biographyFull:
      'As origens de Severino são desconhecidas — ele nunca revelou sua pátria. Apareceu no Norico (atual Áustria) por volta de 453, após a queda de Átila, e dedicou-se a evangelizar e socorrer as populações ameaçadas pelas invasões bárbaras.\n\nFundou mosteiros e organizou a assistência aos pobres e prisioneiros ao longo do Danúbio. Era respeitado tanto pelos romanos quanto pelos chefes germânicos, servindo como mediador em conflitos.\n\nSua vida de oração e austeridade impressionava a todos. Praticava jejuns rigorosos, vestia-se com simplicidade e caminhava descalço mesmo no inverno.\n\nFaleceu em 8 de janeiro de 482 em Favianis. Sua biografia foi escrita por Eugíppio, discípulo que preservou seu legado para a posteridade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.09,
    longitude: 15.63,
  },
  {
    name: 'Santa Juliana',
    slug: 'santa-juliana',
    feastMonth: 1,
    feastDay: 9,
    birthDate: null,
    deathDate: '304-01-01',
    birthPlace: 'Nicomédia',
    deathPlace: 'Nicomédia',
    country: 'Turquia',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['doentes', 'parturientes'],
    biographyShort:
      'Santa Juliana foi uma virgem e mártir de Nicomédia que sofreu o martírio durante a perseguição de Diocleciano. Recusou-se a apostatar da fé e a casar-se com um pagão, permanecendo fiel a Cristo até a morte.',
    biographyFull:
      'Juliana nasceu em Nicomédia, na Ásia Menor, no final do século III. Era filha de um pai pagão que a prometeu em casamento ao prefeito Elêusio.\n\nJuliana, que havia se consagrado a Cristo, recusou o matrimônio a menos que Elêusio se convertesse. Diante da recusa, seu próprio pai a entregou às autoridades durante a perseguição de Diocleciano.\n\nSegundo a tradição, sofreu diversos tormentos — foi flagelada, queimada e mergulhada em chumbo derretido — mas permaneceu firme na fé. Foi finalmente decapitada.\n\nSeu culto espalhou-se tanto no Oriente quanto no Ocidente, e suas relíquias foram veneradas em diversas cidades da Itália.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.763,
    longitude: 29.92,
  },
  {
    name: 'São Gregório de Nissa',
    slug: 'sao-gregorio-de-nissa',
    feastMonth: 1,
    feastDay: 10,
    birthDate: '335-01-01',
    deathDate: '394-01-01',
    birthPlace: 'Cesareia da Capadócia',
    deathPlace: 'Nissa',
    country: 'Turquia',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'filósofos'],
    biographyShort:
      'São Gregório de Nissa foi um dos três grandes Padres Capadócios e bispo de Nissa no século IV. Sua teologia mística e trinitária influenciou profundamente o pensamento cristão oriental.',
    biographyFull:
      'Gregório nasceu por volta de 335 na Capadócia, irmão de São Basílio Magno e de Santa Macrina. Inicialmente professor de retórica, foi atraído à vida eclesiástica pela influência da família.\n\nFoi nomeado bispo de Nissa por volta de 371 pelo irmão Basílio. Enfrentou perseguições dos arianos e chegou a ser deposto temporariamente, mas foi restabelecido após a morte do imperador Valente.\n\nDesempenhou papel fundamental no Concílio de Constantinopla de 381, contribuindo para a formulação do Credo Niceno-Constantinopolitano. Sua obra A Vida de Moisés é um clássico da teologia mística.\n\nFaleceu por volta de 394. É considerado um dos grandes mestres da teologia oriental, especialmente na doutrina da divinização do ser humano.',
    biographyKids: null,
    quotes: [
      {
        text: 'A perfeição consiste em nunca cessar de crescer em direção ao que é melhor.',
        source: 'A Vida de Moisés',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 38.73,
    longitude: 35.48,
  },
  {
    name: 'São Teodósio',
    slug: 'sao-teodosio',
    feastMonth: 1,
    feastDay: 11,
    birthDate: '423-01-01',
    deathDate: '529-01-11',
    birthPlace: 'Mogariassos',
    deathPlace: 'Deserto da Judeia',
    country: 'Turquia',
    century: 6,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'cenobitas'],
    biographyShort:
      'São Teodósio foi o fundador do grande mosteiro cenobítico no deserto da Judeia no século V. É considerado o pai do cenobitismo na Palestina.',
    biographyFull:
      'Teodósio nasceu em Mogariassos, na Capadócia, por volta de 423. Peregrinou à Terra Santa e decidiu permanecer, vivendo como eremita em uma caverna perto de Belém.\n\nDiscípulos reuniram-se ao seu redor e ele fundou um grande mosteiro cenobítico no deserto da Judeia, que chegou a abrigar centenas de monges de diferentes nacionalidades, com igrejas onde se celebrava em grego, armênio e eslavo.\n\nO mosteiro incluía hospedarias para peregrinos, hospitais para doentes e abrigos para idosos, tornando-se um modelo de caridade monástica. Teodósio resistiu bravamente ao imperador Anastácio I quando este tentou impor a heresia monofisita.\n\nFaleceu em 11 de janeiro de 529, com mais de cem anos de idade, venerado como "Cenobiarca", chefe dos cenobitas da Palestina.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.55,
    longitude: 36.4,
  },
  {
    name: 'Santa Margarida Bourgeoys',
    slug: 'santa-margarida-bourgeoys',
    feastMonth: 1,
    feastDay: 12,
    birthDate: '1620-04-17',
    deathDate: '1700-01-12',
    birthPlace: 'Troyes',
    deathPlace: 'Montreal',
    country: 'França',
    century: 17,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['educadores', 'contra a pobreza'],
    biographyShort:
      'Santa Margarida Bourgeoys foi uma religiosa francesa que fundou a Congregação de Notre-Dame em Montreal, no Canadá. Dedicou-se à educação das crianças na Nova França.',
    biographyFull:
      'Margarida nasceu em Troyes, na França, em 17 de abril de 1620. Após uma experiência mística aos vinte anos, consagrou-se ao serviço de Deus e partiu para a Nova França em 1653.\n\nEm Montreal, abriu a primeira escola e fundou a Congregação de Notre-Dame, dedicada à educação das meninas, tanto colonas quanto indígenas. As irmãs viviam sem clausura, inovação para a época.\n\nEnfrentou incêndios, pobreza e dificuldades da vida colonial com fé inabalável. Formou gerações de mulheres e contribuiu para a construção da sociedade canadense.\n\nFaleceu em 12 de janeiro de 1700 em Montreal. Foi canonizada por São João Paulo II em 1982, sendo a primeira santa do Canadá.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.297,
    longitude: 4.074,
  },
  {
    name: 'Santo Hilário de Poitiers',
    slug: 'santo-hilario-de-poitiers',
    feastMonth: 1,
    feastDay: 13,
    birthDate: '315-01-01',
    deathDate: '367-01-13',
    birthPlace: 'Poitiers',
    deathPlace: 'Poitiers',
    country: 'França',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['contra picadas de cobra', 'teólogos'],
    biographyShort:
      'Santo Hilário de Poitiers foi bispo e Doutor da Igreja, chamado de "Atanásio do Ocidente" por sua defesa da fé contra o arianismo. Sua obra De Trinitate é um marco da teologia latina.',
    biographyFull:
      'Hilário nasceu em Poitiers, na Gália, por volta de 315, numa família pagã abastada. Converteu-se ao cristianismo pelo estudo das Escrituras e foi eleito bispo de Poitiers por volta de 350.\n\nTornou-se o principal defensor da fé nicena no Ocidente contra o arianismo. O imperador Constâncio II exilou-o na Frígia, onde aprofundou seu conhecimento da teologia oriental.\n\nDurante o exílio, escreveu sua obra-prima De Trinitate, uma defesa magistral da divindade de Cristo. De volta a Poitiers, continuou combatendo o arianismo e reconciliando bispos que haviam cedido à pressão imperial.\n\nFaleceu em 367 e foi proclamado Doutor da Igreja por Pio IX em 1851. É considerado o maior teólogo latino do século IV.',
    biographyKids: null,
    quotes: [
      {
        text: 'A fé não é matéria de discussão, mas de adoração.',
        source: 'De Trinitate',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 46.58,
    longitude: 0.34,
  },
  {
    name: 'São Félix de Nola',
    slug: 'sao-felix-de-nola',
    feastMonth: 1,
    feastDay: 14,
    birthDate: null,
    deathDate: '260-01-14',
    birthPlace: 'Nola',
    deathPlace: 'Nola',
    country: 'Itália',
    century: 3,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['contra perjúrio', 'animais domésticos'],
    biographyShort:
      'São Félix de Nola foi um sacerdote italiano do século III que sofreu prisão e tortura durante a perseguição de Décio. Escapou milagrosamente e dedicou o resto da vida ao serviço dos pobres.',
    biographyFull:
      'Félix nasceu em Nola, na Campânia, filho de um soldado sírio. Foi ordenado sacerdote e tornou-se auxiliar do bispo Máximo de Nola.\n\nDurante a perseguição de Décio (250-251), foi preso e torturado. Segundo a tradição, um anjo o libertou da prisão e ele resgatou o bispo Máximo, que estava escondido e moribundo nas montanhas.\n\nApós a perseguição, Félix foi escolhido para ser bispo, mas recusou em favor de outro sacerdote mais velho. Viveu na pobreza, cultivando um pequeno campo e distribuindo o excedente aos pobres.\n\nFaleceu em paz por volta de 260. São Paulino de Nola, que viveu um século depois, promoveu intensamente seu culto e compôs poemas em sua honra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.926,
    longitude: 14.528,
  },
  {
    name: 'Santo Arnaldo Janssen',
    slug: 'santo-arnaldo-janssen',
    feastMonth: 1,
    feastDay: 15,
    birthDate: '1837-11-05',
    deathDate: '1909-01-15',
    birthPlace: 'Goch',
    deathPlace: 'Steyl',
    country: 'Alemanha',
    century: 20,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['missionários', 'comunicadores'],
    biographyShort:
      'Santo Arnaldo Janssen foi um sacerdote alemão que fundou três congregações missionárias: os Verbitas, as Servas do Espírito Santo e as Servas do Espírito Santo de Adoração Perpétua.',
    biographyFull:
      'Arnaldo Janssen nasceu em 5 de novembro de 1837 em Goch, na Renânia. Ordenado sacerdote, trabalhou como professor de ciências naturais e editor de uma revista missionária.\n\nEm 1875, fundou em Steyl, na Holanda, a Sociedade do Verbo Divino (Verbitas), primeira congregação missionária masculina da Alemanha moderna. Posteriormente fundou duas congregações femininas missionárias.\n\nApesar de temperamento reservado e enfrentando críticas de contemporâneos que duvidavam de seu projeto, Arnaldo perseverou com fé. Enviou missionários à China, Argentina, Togo e outros países.\n\nFaleceu em 15 de janeiro de 1909 em Steyl. Foi canonizado por Bento XVI em 2003. Hoje seus missionários atuam em mais de setenta países.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.683,
    longitude: 6.157,
  },
  {
    name: 'São Marcelo I',
    slug: 'sao-marcelo-i',
    feastMonth: 1,
    feastDay: 16,
    birthDate: null,
    deathDate: '309-01-16',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['cavalariços', 'estábulos'],
    biographyShort:
      'São Marcelo I foi Papa de 308 a 309, durante a reorganização da Igreja após a perseguição de Diocleciano. Enfrentou conflitos com os lapsi e foi exilado pelo imperador Maxêncio.',
    biographyFull:
      'Marcelo foi eleito bispo de Roma em 308, após um longo período de sede vacante causado pela perseguição de Diocleciano. A Igreja encontrava-se em grave crise interna.\n\nSeu principal desafio foi a questão dos lapsi — cristãos que haviam apostatado durante a perseguição e agora queriam retornar à Igreja. Marcelo exigiu penitência pública, o que provocou conflitos e divisões.\n\nAs disputas internas foram tão violentas que o imperador Maxêncio responsabilizou o Papa pela desordem e o exilou de Roma. Segundo a tradição, foi condenado a servir como escravo num estábulo imperial.\n\nFaleceu no exílio em 309. A reorganização paroquial que iniciou em Roma foi fundamental para a estrutura administrativa da Igreja nos séculos seguintes.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.902,
    longitude: 12.496,
  },
  {
    name: 'Santo Antão do Deserto',
    slug: 'santo-antao-do-deserto',
    feastMonth: 1,
    feastDay: 17,
    birthDate: '251-01-01',
    deathDate: '356-01-17',
    birthPlace: 'Coma',
    deathPlace: 'Monte Colzim',
    country: 'Egito',
    century: 4,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'eremitas', 'contra doenças de pele'],
    biographyShort:
      'Santo Antão é considerado o pai do monaquismo cristão. Viveu como eremita no deserto do Egito por mais de oitenta anos, enfrentando célebres combates espirituais contra o demônio.',
    biographyFull:
      'Antão nasceu em Coma, no Alto Egito, por volta de 251, numa família cristã abastada. Aos vinte anos, ouvindo na igreja o Evangelho sobre o jovem rico, distribuiu todos os seus bens e retirou-se para o deserto.\n\nViveu em solidão crescente, primeiro perto de sua aldeia, depois num forte abandonado e finalmente no monte Colzim, junto ao Mar Vermelho. As tentações e combates espirituais que enfrentou tornaram-se célebres na história da espiritualidade.\n\nSua fama atraiu inúmeros discípulos, e ele organizou comunidades de eremitas, lançando as bases do monaquismo cristão. Saiu do deserto duas vezes: para encorajar os cristãos durante a perseguição e para combater o arianismo em Alexandria.\n\nFaleceu em 356 com mais de cem anos. A biografia escrita por Santo Atanásio espalhou o ideal monástico por todo o mundo cristão e influenciou a conversão de Santo Agostinho.',
    biographyKids: null,
    quotes: [
      {
        text: 'Vi todas as armadilhas do demônio estendidas sobre a terra e gemi: quem poderá escapar? E ouvi uma voz que dizia: a humildade.',
        source: 'Vida de Santo Antão, por Santo Atanásio',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 27.8,
    longitude: 30.9,
  },
  {
    name: 'Santa Prisca',
    slug: 'santa-prisca',
    feastMonth: 1,
    feastDay: 18,
    birthDate: null,
    deathDate: '270-01-18',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['jovens', 'contra a solidão'],
    biographyShort:
      'Santa Prisca foi uma jovem mártir romana do século III. Segundo a tradição, foi martirizada ainda adolescente durante a perseguição do imperador Cláudio II.',
    biographyFull:
      'Prisca viveu em Roma no século III, durante um período de intensa perseguição aos cristãos. As tradições sobre sua vida variam, mas concordam que era muito jovem quando sofreu o martírio.\n\nSegundo relatos antigos, foi presa e levada ao templo de Apolo para oferecer sacrifícios aos ídolos. Ao recusar, foi submetida a diversos tormentos, incluindo flagelação e exposição às feras.\n\nMilagrosamente preservada, foi finalmente decapitada na Via Ostiense. Seu culto é muito antigo em Roma, onde uma igreja no monte Aventino leva seu nome desde o século IV.\n\nA basílica de Santa Prisca no Aventino é uma das mais antigas igrejas titulares de Roma e guarda a memória desta jovem mártir da fé.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.902,
    longitude: 12.496,
  },
  {
    name: 'São Mário',
    slug: 'sao-mario',
    feastMonth: 1,
    feastDay: 19,
    birthDate: null,
    deathDate: '270-01-19',
    birthPlace: 'Pérsia',
    deathPlace: 'Roma',
    country: 'Pérsia',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['casais', 'famílias'],
    biographyShort:
      'São Mário foi um nobre persa que viajou a Roma com sua família para venerar as relíquias dos mártires. Foi martirizado junto com a esposa Marta e os filhos durante a perseguição de Cláudio II.',
    biographyFull:
      'Mário era um nobre persa cristão que viveu no século III. Viajou a Roma com sua esposa Marta e seus filhos Audíface e Ábaco para venerar os túmulos dos mártires.\n\nEm Roma, dedicaram-se a sepultar os corpos dos cristãos martirizados, obra de misericórdia extremamente perigosa durante as perseguições. Foram denunciados e presos pelas autoridades.\n\nLevados diante do imperador Cláudio II, recusaram-se a sacrificar aos deuses pagãos. Toda a família foi condenada à morte e executada na Via Cornélia.\n\nSeu testemunho de fé familiar — marido, esposa e filhos morrendo juntos por Cristo — tornou-os patronos das famílias cristãs.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.0,
    longitude: 52.0,
  },
  {
    name: 'São Sebastião',
    slug: 'sao-sebastiao',
    feastMonth: 1,
    feastDay: 20,
    birthDate: '256-01-01',
    deathDate: '288-01-20',
    birthPlace: 'Narbona',
    deathPlace: 'Roma',
    country: 'França',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['soldados', 'atletas', 'contra a peste'],
    biographyShort:
      'São Sebastião foi um soldado romano e capitão da guarda pretoriana que, ao ser descoberto como cristão, foi condenado ao martírio. Sobreviveu às flechadas e foi morto a pauladas por ordem de Diocleciano.',
    biographyFull:
      'Sebastião nasceu em Narbona, na Gália, por volta de 256, e cresceu em Milão. Alistou-se no exército romano para poder ajudar secretamente os cristãos perseguidos, chegando a capitão da guarda pretoriana.\n\nEnquanto militar, visitava cristãos presos, encorajava-os ao martírio e convertia soldados e nobres. Quando o imperador Diocleciano descobriu sua fé, ordenou que fosse amarrado a um poste e crivado de flechas.\n\nDado como morto, foi resgatado por Santa Irene, que tratou seus ferimentos. Recuperado, apresentou-se novamente ao imperador para denunciar a perseguição. Diocleciano ordenou que fosse espancado até a morte.\n\nSeu corpo foi lançado na Cloaca Máxima, mas cristãos o resgataram e sepultaram nas catacumbas que hoje levam seu nome. É um dos santos mais representados na arte cristã.',
    biographyKids: null,
    quotes: [],
    prayer:
      'Glorioso mártir São Sebastião, soldado de Cristo e defensor da fé, alcançai-nos a coragem de professar nossa fé sem medo e a força para resistir às tentações. Por Cristo, nosso Senhor. Amém.',
    imageUrl: null,
    latitude: 43.184,
    longitude: 3.003,
  },
  {
    name: 'Santa Inês',
    slug: 'santa-ines',
    feastMonth: 1,
    feastDay: 21,
    birthDate: '291-01-01',
    deathDate: '304-01-21',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['jovens', 'noivas', 'pureza'],
    biographyShort:
      'Santa Inês foi uma jovem mártir romana de apenas doze ou treze anos que preferiu a morte a renegar sua consagração a Cristo. É uma das mártires mais célebres da Igreja primitiva.',
    biographyFull:
      'Inês nasceu em Roma por volta de 291, numa família nobre cristã. Consagrou-se a Cristo desde muito jovem e recusou todos os pretendentes ao casamento, incluindo o filho do prefeito de Roma.\n\nRejeitado, o jovem denunciou-a como cristã. O prefeito tentou persuadi-la com promessas e ameaças, mas Inês permaneceu firme. Foi exposta num lupanar, mas milagrosamente preservada em sua pureza.\n\nCondenada à morte, foi executada com um golpe de espada na garganta, à maneira dos cordeiros — daí a associação com o cordeiro (agnus em latim). Tinha apenas doze ou treze anos.\n\nSeu culto difundiu-se rapidamente. Santo Ambrósio, São Jerônimo e o Papa São Dâmaso escreveram sobre ela. A basílica de Sant\'Agnese fuori le Mura, em Roma, guarda suas relíquias.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.902,
    longitude: 12.496,
  },
  {
    name: 'São Vicente de Saragoça',
    slug: 'sao-vicente-de-saragoca',
    feastMonth: 1,
    feastDay: 22,
    birthDate: null,
    deathDate: '304-01-22',
    birthPlace: 'Huesca',
    deathPlace: 'Valência',
    country: 'Espanha',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['vinicultores', 'marinheiros', 'Lisboa'],
    biographyShort:
      'São Vicente de Saragoça foi um diácono espanhol martirizado em Valência durante a perseguição de Diocleciano. É o mártir mais célebre da Espanha e padroeiro de Lisboa.',
    biographyFull:
      'Vicente nasceu em Huesca, na Espanha, e foi educado pelo bispo Valério de Saragoça. Ordenado diácono, tornou-se o principal pregador da diocese, pois o bispo tinha dificuldade de fala.\n\nDurante a perseguição de Diocleciano, ambos foram presos e levados a Valência. O governador Daciano ofereceu liberdade em troca da apostasia, mas Vicente recusou com eloquência e firmeza.\n\nFoi submetido a tormentos terríveis: o ecúleo (instrumento de estiramento), grelhas de ferro em brasa e cacos de cerâmica. Em cada tormento, manteve a serenidade e até consolou seu algoz.\n\nFaleceu na prisão em 22 de janeiro de 304. Seu culto espalhou-se por toda a cristandade. É padroeiro de Lisboa, pois segundo a tradição seus restos foram levados para a cidade por corvos que os protegeram.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.131,
    longitude: -0.408,
  },
  {
    name: 'Santo Ildefonso',
    slug: 'santo-ildefonso',
    feastMonth: 1,
    feastDay: 23,
    birthDate: '607-01-01',
    deathDate: '667-01-23',
    birthPlace: 'Toledo',
    deathPlace: 'Toledo',
    country: 'Espanha',
    century: 7,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Toledo', 'contra heresias'],
    biographyShort:
      'Santo Ildefonso foi arcebispo de Toledo e grande defensor da virgindade perpétua de Maria no século VII. Segundo a tradição, a Virgem Maria apareceu-lhe e presenteou-o com uma casula.',
    biographyFull:
      'Ildefonso nasceu em Toledo por volta de 607, sobrinho de Santo Eugênio, arcebispo da cidade. Contra a vontade do pai, ingressou no mosteiro de Agali, onde se tornou abade.\n\nEm 657, foi eleito arcebispo de Toledo. Seu tratado De Virginitate Perpetua Sanctae Mariae é uma defesa vigorosa do dogma da virgindade de Maria contra hereges da época.\n\nSegundo a tradição, a Virgem Maria apareceu-lhe na catedral e, em agradecimento por sua devoção, vestiu-lhe uma casula milagrosa. Este episódio é um dos mais representados na arte espanhola.\n\nFaleceu em 23 de janeiro de 667. Sob sua liderança, Toledo consolidou-se como centro eclesiástico e cultural da Espanha visigótica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 39.862,
    longitude: -4.027,
  },
  {
    name: 'São Francisco de Sales',
    slug: 'sao-francisco-de-sales',
    feastMonth: 1,
    feastDay: 24,
    birthDate: '1567-08-21',
    deathDate: '1622-12-28',
    birthPlace: 'Thorens-Glières',
    deathPlace: 'Lyon',
    country: 'França',
    century: 17,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['jornalistas', 'escritores', 'surdos'],
    biographyShort:
      'São Francisco de Sales foi bispo de Genebra e Doutor da Igreja, célebre por sua doçura e seus escritos espirituais. Sua Introdução à Vida Devota tornou a espiritualidade acessível aos leigos.',
    biographyFull:
      'Francisco nasceu em 21 de agosto de 1567 no castelo de Sales, na Saboia. Estudou em Paris e Pádua, onde obteve doutorado em direito. Contra a vontade do pai, abraçou a vocação sacerdotal.\n\nFoi enviado como missionário ao Chablais, região dominada pelo calvinismo. Com paciência e folhetos distribuídos porta a porta, reconverteu milhares ao catolicismo. Em 1602, tornou-se bispo de Genebra.\n\nSuas obras Introdução à Vida Devota e Tratado do Amor de Deus revolucionaram a espiritualidade cristã ao ensinar que a santidade é acessível a todos, não apenas a religiosos. Com Santa Joana de Chantal, fundou a Ordem da Visitação.\n\nFaleceu em Lyon em 28 de dezembro de 1622. Foi declarado Doutor da Igreja em 1877 e padroeiro dos jornalistas por Pio XI, em razão de seus escritos apostólicos.',
    biographyKids: null,
    quotes: [
      {
        text: 'Nada por força, tudo por amor.',
        source: 'Máxima de São Francisco de Sales',
      },
    ],
    prayer:
      'Ó Deus, que quisestes que São Francisco de Sales se fizesse tudo para todos na salvação das almas, concedei-nos que, seguindo seu exemplo, manifestemos sempre a mansidão de vossa caridade no serviço dos irmãos. Por Cristo, nosso Senhor. Amém.',
    imageUrl: null,
    latitude: 46.0,
    longitude: 6.32,
  },
  {
    name: 'Conversão de São Paulo',
    slug: 'conversao-de-sao-paulo',
    feastMonth: 1,
    feastDay: 25,
    birthDate: '5-01-01',
    deathDate: '67-06-29',
    birthPlace: 'Tarso',
    deathPlace: 'Roma',
    country: 'Turquia',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['missionários', 'teólogos', 'imprensa católica'],
    biographyShort:
      'A Conversão de São Paulo celebra o encontro de Saulo de Tarso com Cristo ressuscitado no caminho de Damasco. De perseguidor dos cristãos, tornou-se o Apóstolo dos Gentios.',
    biographyFull:
      'Saulo nasceu em Tarso, na Cilícia, por volta do ano 5 d.C., numa família judia da tribo de Benjamim com cidadania romana. Formou-se fariseu em Jerusalém aos pés de Gamaliel e tornou-se feroz perseguidor dos cristãos.\n\nPor volta do ano 36, no caminho de Damasco, uma luz do céu o derrubou e a voz de Cristo perguntou: "Saulo, Saulo, por que me persegues?" Cego por três dias, foi curado por Ananias e batizado, mudando radicalmente de vida.\n\nTornou-se o maior missionário da história cristã, realizando três grandes viagens apostólicas pelo Mediterrâneo. Fundou comunidades na Ásia Menor, Grécia e Roma. Suas treze epístolas formam parte substancial do Novo Testamento.\n\nFoi martirizado em Roma por volta do ano 67, decapitado por ser cidadão romano. A festa de sua conversão, em 25 de janeiro, celebra a graça transformadora de Deus.',
    biographyKids: null,
    quotes: [
      {
        text: 'Já não sou eu que vivo, mas é Cristo que vive em mim.',
        source: 'Gálatas 2,20',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 36.918,
    longitude: 34.891,
  },
  {
    name: 'São Timóteo e São Tito',
    slug: 'sao-timoteo-e-sao-tito',
    feastMonth: 1,
    feastDay: 26,
    birthDate: null,
    deathDate: '97-01-26',
    birthPlace: null,
    deathPlace: null,
    country: 'Grécia',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['bispos', 'pastores de almas'],
    biographyShort:
      'São Timóteo e São Tito foram discípulos e colaboradores de São Paulo. Timóteo governou a Igreja de Éfeso e Tito a de Creta, sendo os primeiros bispos dessas comunidades.',
    biographyFull:
      'Timóteo nasceu em Listra, na Ásia Menor, filho de mãe judia e pai grego. Foi convertido por São Paulo em sua primeira viagem missionária e tornou-se seu companheiro mais fiel. Paulo o constituiu bispo de Éfeso.\n\nTito era grego, convertido por São Paulo, e acompanhou-o ao Concílio de Jerusalém. Foi enviado a Corinto para resolver conflitos na comunidade e depois estabelecido como bispo de Creta.\n\nAmbos receberam epístolas de São Paulo — as chamadas Cartas Pastorais — com instruções sobre o governo das comunidades cristãs. Esses textos são fundamentais para a compreensão da estrutura da Igreja primitiva.\n\nSegundo a tradição, Timóteo morreu mártir em Éfeso e Tito faleceu em paz em Creta, com idade avançada. A Igreja celebra ambos juntos em 26 de janeiro.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 37.727,
    longitude: 32.498,
  },
  {
    name: 'Santa Ângela de Mérici',
    slug: 'santa-angela-de-merici',
    feastMonth: 1,
    feastDay: 27,
    birthDate: '1474-03-21',
    deathDate: '1540-01-27',
    birthPlace: 'Desenzano del Garda',
    deathPlace: 'Bréscia',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['educadoras', 'deficientes físicos', 'doentes'],
    biographyShort:
      'Santa Ângela de Mérici foi a fundadora da Companhia de Santa Úrsula (Ursulinas), primeira ordem feminina dedicada à educação das meninas. Revolucionou a vida religiosa feminina no século XVI.',
    biographyFull:
      'Ângela nasceu em Desenzano del Garda, na Lombardia, em 1474. Órfã desde jovem, ingressou na Ordem Terceira Franciscana e dedicou-se à educação de meninas pobres.\n\nEm 1535, fundou em Bréscia a Companhia de Santa Úrsula, um modelo revolucionário: mulheres consagradas que viviam em suas casas e atuavam no mundo, sem clausura. O objetivo era a educação cristã das jovens.\n\nSua pedagogia baseava-se na doçura, no respeito e na confiança. Dizia às suas companheiras que governassem mais por amor do que por temor, princípio avançado para sua época.\n\nFaleceu em 27 de janeiro de 1540 em Bréscia. Foi canonizada em 1807. As Ursulinas tornaram-se uma das maiores ordens educacionais da Igreja, presentes em todos os continentes.',
    biographyKids: null,
    quotes: [
      {
        text: 'A desordem da sociedade é o resultado da desordem da família.',
        source: 'Atribuída a Santa Ângela de Mérici',
      },
    ],
    prayer: null,
    imageUrl: null,
    latitude: 45.47,
    longitude: 10.53,
  },
  {
    name: 'São Tomás de Aquino',
    slug: 'sao-tomas-de-aquino',
    feastMonth: 1,
    feastDay: 28,
    birthDate: '1225-01-28',
    deathDate: '1274-03-07',
    birthPlace: 'Roccasecca',
    deathPlace: 'Fossanova',
    country: 'Itália',
    century: 13,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['estudantes', 'universidades', 'filósofos'],
    biographyShort:
      'São Tomás de Aquino foi frade dominicano e o maior teólogo da Igreja Católica. Sua Suma Teológica é a obra mais influente da filosofia e teologia cristãs.',
    biographyFull:
      'Tomás nasceu em 1225 no castelo de Roccasecca, no sul da Itália, numa família nobre. Contra a vontade da família, que o queria abade beneditino, ingressou na Ordem dos Pregadores (Dominicanos).\n\nEstudou em Paris e Colônia sob Santo Alberto Magno. Tornou-se professor em Paris e Roma, onde compôs sua obra monumental, a Suma Teológica, síntese entre a fé cristã e a filosofia aristotélica.\n\nChamado de "Doutor Angélico", produziu uma quantidade impressionante de obras filosóficas, teológicas e bíblicas. Também compôs hinos eucarísticos célebres como o Tantum Ergo e o Pange Lingua.\n\nFaleceu em 7 de março de 1274 na abadia de Fossanova, a caminho do Concílio de Lyon. Foi proclamado Doutor da Igreja em 1567 e padroeiro das escolas católicas em 1880.',
    biographyKids: null,
    quotes: [
      {
        text: 'Teme o homem de um só livro.',
        source: 'Atribuída a São Tomás de Aquino',
      },
    ],
    prayer:
      'Concedei-me, Deus misericordioso, desejar ardentemente o que vos agrada, investigá-lo com prudência, reconhecê-lo com verdade e cumpri-lo com perfeição, para louvor e glória do vosso nome. Amém.',
    imageUrl: null,
    latitude: 41.49,
    longitude: 13.66,
  },
  {
    name: 'São Valerio',
    slug: 'sao-valerio',
    feastMonth: 1,
    feastDay: 29,
    birthDate: null,
    deathDate: '315-01-29',
    birthPlace: 'Saragoça',
    deathPlace: 'Saragoça',
    country: 'Espanha',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Saragoça', 'contra o reumatismo'],
    biographyShort:
      'São Valerio foi bispo de Saragoça no início do século IV. Impedido de falar por um defeito de fala, confiou a pregação ao seu diácono São Vicente, que se tornaria mártir célebre.',
    biographyFull:
      'Valerio foi bispo de Saragoça, na Espanha, durante a perseguição de Diocleciano. Sofria de um impedimento na fala que dificultava sua pregação, por isso confiou essa missão ao diácono Vicente.\n\nDurante a perseguição, Valerio e Vicente foram presos e levados a Valência. Enquanto Vicente foi submetido a tormentos cruéis e morreu mártir, Valerio foi condenado ao exílio.\n\nSobreviveu à perseguição e retornou a Saragoça, onde continuou governando sua diocese até a morte, por volta de 315. Sua humildade em reconhecer seus limites e confiar no talento de seu diácono é exemplo de sabedoria pastoral.\n\nÉ venerado junto com São Vicente como um dos grandes santos da Igreja espanhola primitiva.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.649,
    longitude: -0.889,
  },
  {
    name: 'Santa Martinha',
    slug: 'santa-martinha',
    feastMonth: 1,
    feastDay: 30,
    birthDate: null,
    deathDate: '228-01-30',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['Roma', 'amas de leite'],
    biographyShort:
      'Santa Martinha foi uma virgem e mártir romana do século III. Filha de um cônsul, foi martirizada por recusar sacrificar aos ídolos durante a perseguição de Alexandre Severo.',
    biographyFull:
      'Martinha era uma jovem romana de família nobre, filha de um antigo cônsul. Viveu no século III, durante o reinado de Alexandre Severo.\n\nApós a morte dos pais, distribuiu seus bens aos pobres e dedicou-se ao serviço de Deus. Foi denunciada como cristã e levada ao templo para sacrificar aos ídolos.\n\nSegundo a tradição, quando entrou no templo, os ídolos caíram por terra. Foi submetida a vários tormentos e finalmente decapitada. Seu sangue, diz a tradição, jorrou branco como leite.\n\nSuas relíquias foram encontradas em 1634 sob o pontificado de Urbano VIII, que restaurou a igreja dedicada a ela no Fórum Romano e compôs hinos em sua honra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.902,
    longitude: 12.496,
  },
  {
    name: 'São João Bosco',
    slug: 'sao-joao-bosco',
    feastMonth: 1,
    feastDay: 31,
    birthDate: '1815-08-16',
    deathDate: '1888-01-31',
    birthPlace: 'Becchi',
    deathPlace: 'Turim',
    country: 'Itália',
    century: 19,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['jovens', 'aprendizes', 'editores'],
    biographyShort:
      'São João Bosco, conhecido como Dom Bosco, foi o fundador dos Salesianos e grande educador da juventude. Seu sistema preventivo, baseado na razão, religião e amor, revolucionou a pedagogia.',
    biographyFull:
      'João Bosco nasceu em 16 de agosto de 1815 em Becchi, perto de Turim, numa família camponesa pobre. Aos nove anos teve um sonho profético que lhe revelou sua missão de educar os jovens.\n\nOrdenado sacerdote em 1841, dedicou-se aos meninos pobres e abandonados de Turim. Fundou oratórios, escolas profissionais e a Sociedade de São Francisco de Sales (Salesianos) em 1859, junto com o Instituto das Filhas de Maria Auxiliadora.\n\nSeu método educativo — o Sistema Preventivo — baseia-se em três pilares: razão, religião e amorevolezza (amor). Rejeitava o castigo e apostava na presença, no diálogo e na confiança nos jovens.\n\nFaleceu em 31 de janeiro de 1888 em Turim. Foi canonizado em 1934 e declarado "Pai e Mestre da Juventude". Os Salesianos são hoje uma das maiores congregações religiosas do mundo, presentes em 130 países.',
    biographyKids: null,
    quotes: [
      {
        text: 'Basta que sejais jovens para que eu vos ame muito.',
        source: 'Atribuída a São João Bosco',
      },
    ],
    prayer:
      'Ó glorioso São João Bosco, pai e mestre da juventude, que tanto trabalhaste pela salvação das almas, sede nosso guia na busca do bem das almas e na glória de Deus. Por Cristo, nosso Senhor. Amém.',
    imageUrl: null,
    latitude: 44.996,
    longitude: 7.828,
  },
];
