import type { SaintSeedData } from './types';

export const julySaints: SaintSeedData[] = [
  {
    name: 'São Junípero Serra',
    slug: 'sao-junipero-serra',
    feastMonth: 7,
    feastDay: 1,
    birthDate: '1713-11-24',
    deathDate: '1784-08-28',
    birthPlace: 'Petra',
    deathPlace: 'Carmel',
    country: 'Espanha',
    century: 18,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Califórnia', 'vocações religiosas'],
    biographyShort: 'Frade franciscano espanhol que fundou nove das vinte e uma missões da Califórnia, evangelizando os povos indígenas da costa do Pacífico.',
    biographyFull: 'Miguel José Serra nasceu em 24 de novembro de 1713 em Petra, na ilha de Maiorca. Ingressou na Ordem Franciscana aos 16 anos, recebendo o nome Junípero em honra do companheiro de São Francisco. Tornou-se professor de filosofia antes de partir como missionário para o Novo Mundo em 1749.\n\nApós trabalhar no México por quase vinte anos, foi enviado em 1769 para a Alta Califórnia, onde fundou a missão de San Diego, a primeira de nove que estabeleceria ao longo da costa. As missões incluíam San Carlos, San Antonio, San Gabriel, San Luis Obispo e San Francisco.\n\nApesar de uma úlcera crônica na perna que o acompanhou por toda a vida, Junípero percorreu milhares de quilômetros a pé. Faleceu na missão de San Carlos em Carmel em 28 de agosto de 1784 e foi canonizado pelo Papa Francisco em 2015.',
    biographyKids: null,
    quotes: [{ text: 'Sempre em frente, nunca para trás.', source: 'Lema de São Junípero Serra' }],
    prayer: null,
    imageUrl: null,
    latitude: 39.6,
    longitude: 3.01,
  },
  {
    name: 'São Bernardino Realino',
    slug: 'sao-bernardino-realino',
    feastMonth: 7,
    feastDay: 2,
    birthDate: '1530-12-01',
    deathDate: '1616-07-02',
    birthPlace: 'Carpi',
    deathPlace: 'Lecce',
    country: 'Itália',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Lecce', 'magistrados'],
    biographyShort: 'Magistrado e advogado que abandonou brilhante carreira jurídica para entrar na Companhia de Jesus, dedicando os últimos quarenta anos de vida ao povo de Lecce.',
    biographyFull: 'Bernardino nasceu em 1530 em Carpi, na Emília-Romanha. Formou-se em direito e exerceu cargos de magistrado em diversas cidades italianas, ganhando reputação de jurista íntegro. Aos 34 anos, após uma experiência mística, ingressou na Companhia de Jesus.\n\nEm 1574, foi enviado a Lecce, no sul da Itália, onde permaneceu até a morte, por quarenta e dois anos. Dedicou-se à pregação, confissão, catequese das crianças e assistência aos pobres e enfermos. Tornou-se tão querido que os cidadãos o declararam patrono da cidade em vida.\n\nFaleceu em 2 de julho de 1616, aos 85 anos. Em seu leito de morte, o sangue recolhido de uma sangria milagrosamente se liquefazia. Foi canonizado por Pio XII em 1947.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.78,
    longitude: 10.88,
  },
  {
    name: 'São Tomé Apóstolo',
    slug: 'sao-tome-apostolo',
    feastMonth: 7,
    feastDay: 3,
    birthDate: null,
    deathDate: '72-07-03',
    birthPlace: 'Galileia',
    deathPlace: 'Mylapore',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['arquitetos', 'Índia'],
    biographyShort: 'Apóstolo que duvidou da Ressurreição até tocar as chagas de Cristo, tornando-se depois o evangelizador da Índia, onde foi martirizado.',
    biographyFull: 'Tomé, chamado Dídimo (gêmeo), era um dos Doze Apóstolos. Após a Ressurreição, declarou que não acreditaria sem tocar as chagas do Senhor. Oito dias depois, Jesus apareceu e Tomé proclamou: "Meu Senhor e meu Deus!", a mais alta confissão de fé do Evangelho.\n\nSegundo a tradição, Tomé levou o Evangelho até a Índia, onde fundou comunidades cristãs na costa do Malabar. Os cristãos de São Tomé, ainda hoje presentes na Índia, remontam sua origem à pregação do apóstolo.\n\nTomé teria sido martirizado com uma lança em Mylapore, perto de Madrás (atual Chennai), por volta do ano 72. A basílica de São Tomé em Chennai foi construída sobre o local tradicional de seu túmulo.',
    biographyKids: null,
    quotes: [{ text: 'Meu Senhor e meu Deus!', source: 'João 20,28' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.8,
    longitude: 35.5,
  },
  {
    name: 'Santa Isabel de Portugal',
    slug: 'santa-isabel-de-portugal',
    feastMonth: 7,
    feastDay: 4,
    birthDate: '1271-01-04',
    deathDate: '1336-07-04',
    birthPlace: 'Zaragoza',
    deathPlace: 'Estremoz',
    country: 'Portugal',
    century: 14,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['rainhas', 'paz'],
    biographyShort: 'Rainha de Portugal conhecida como a Rainha Santa, dedicou-se à caridade, à oração e à mediação de conflitos entre reis cristãos da Península Ibérica.',
    biographyFull: 'Isabel nasceu em 1271 em Zaragoza, filha do rei Pedro III de Aragão. Aos doze anos casou-se com o rei Dinis de Portugal. Apesar das infidelidades do marido, manteve-se fiel, educou os filhos na fé e mediou a paz entre o rei e o infante herdeiro.\n\nFundou hospitais, albergues e mosteiros, incluindo o convento de Santa Clara em Coimbra. A tradição do milagre das rosas conta que, ao ser surpreendida levando pão aos pobres, os pães se transformaram em rosas.\n\nApós a morte do rei Dinis em 1325, Isabel vestiu o hábito de clarissa e retirou-se para junto do convento de Santa Clara. Faleceu em 4 de julho de 1336 em Estremoz, tentando mediar a paz entre seu neto Afonso IV de Portugal e o rei de Castela. Foi canonizada em 1625.',
    biographyKids: null,
    quotes: [{ text: 'A paz entre os reis é a paz entre os povos.', source: 'Atribuída a Santa Isabel' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.65,
    longitude: -0.88,
  },
  {
    name: 'Santo Antônio Maria Zaccaria',
    slug: 'santo-antonio-maria-zaccaria',
    feastMonth: 7,
    feastDay: 5,
    birthDate: '1502-12-01',
    deathDate: '1539-07-05',
    birthPlace: 'Cremona',
    deathPlace: 'Cremona',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['barnabitas', 'renovação espiritual'],
    biographyShort: 'Médico e sacerdote que fundou a Ordem dos Barnabitas para a reforma do clero e dos fiéis, promovendo a adoração eucarística e a pregação popular.',
    biographyFull: 'Antônio Maria nasceu em 1502 em Cremona, Itália. Formou-se em medicina em Pádua, mas logo sentiu o chamado ao sacerdócio e foi ordenado em 1528. Dedicou-se à catequese e ao cuidado dos doentes em Cremona.\n\nEm 1530, mudou-se para Milão, onde fundou em 1533 a Congregação dos Clérigos Regulares de São Paulo, conhecidos como Barnabitas. A ordem dedicava-se à pregação popular, à reforma dos costumes e à adoração das Quarenta Horas. Fundou também a congregação feminina das Angélicas.\n\nApesar de sua breve vida, Antônio Maria impulsionou uma profunda renovação espiritual na Igreja do norte da Itália. Faleceu em Cremona em 5 de julho de 1539, com apenas 36 anos. Foi canonizado por Leão XIII em 1897.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.13,
    longitude: 10.02,
  },
  {
    name: 'Santa Maria Goretti',
    slug: 'santa-maria-goretti',
    feastMonth: 7,
    feastDay: 6,
    birthDate: '1890-10-16',
    deathDate: '1902-07-06',
    birthPlace: 'Corinaldo',
    deathPlace: 'Nettuno',
    country: 'Itália',
    century: 20,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['juventude', 'vítimas de violência'],
    biographyShort: 'Jovem camponesa italiana martirizada aos onze anos ao resistir a uma tentativa de violação, perdoando seu agressor antes de morrer.',
    biographyFull: 'Maria nasceu em 16 de outubro de 1890 em Corinaldo, nas Marcas italianas, filha de humildes camponeses. Após a morte do pai, a família mudou-se para Nettuno, onde dividia moradia com a família Serenelli.\n\nEm 5 de julho de 1902, o jovem Alessandro Serenelli tentou violentá-la. Maria resistiu, dizendo que era pecado e que Deus não queria. Alessandro a apunhalou quatorze vezes. Levada ao hospital, Maria perdoou seu agressor antes de falecer no dia seguinte, aos onze anos.\n\nAlessandro converteu-se na prisão após uma visão de Maria e, após libertado, tornou-se irmão leigo capuchinho. Esteve presente na canonização de Maria por Pio XII em 1950, junto com a mãe da santa, caso único na história.',
    biographyKids: null,
    quotes: [{ text: 'Eu perdoo Alessandro e o quero comigo no Paraíso.', source: 'Últimas palavras de Santa Maria Goretti' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.65,
    longitude: 13.05,
  },
  {
    name: 'São Vilibrordo',
    slug: 'sao-vilibrordo',
    feastMonth: 7,
    feastDay: 7,
    birthDate: '658-01-01',
    deathDate: '739-11-07',
    birthPlace: 'Northúmbria',
    deathPlace: 'Echternach',
    country: 'Inglaterra',
    century: 8,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Luxemburgo', 'Holanda'],
    biographyShort: 'Monge anglo-saxão que evangelizou os frísios e fundou a diocese de Utrecht, sendo considerado o apóstolo dos Países Baixos.',
    biographyFull: 'Vilibrordo nasceu em 658 na Northúmbria, Inglaterra. Educado no mosteiro de Ripon sob São Vilfrido, partiu para a Irlanda, onde estudou durante doze anos. Em 690, embarcou com onze companheiros para evangelizar os frísios pagãos.\n\nO Papa Sérgio I consagrou-o arcebispo dos frísios em 695, com sede em Utrecht. Com o apoio de Pepino de Herstal, fundou igrejas e mosteiros por toda a Frísia, destruindo ídolos e convertendo milhares de pagãos.\n\nFundou a abadia de Echternach, em Luxemburgo, que se tornou importante centro de cultura e evangelização. Faleceu ali em 7 de novembro de 739, aos 81 anos. A procissão dançante de Echternach, em sua honra, é Patrimônio da Humanidade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 55.0,
    longitude: -1.5,
  },
  {
    name: 'São Adriano III',
    slug: 'sao-adriano-iii',
    feastMonth: 7,
    feastDay: 8,
    birthDate: null,
    deathDate: '885-07-08',
    birthPlace: 'Roma',
    deathPlace: 'San Cesario sul Panaro',
    country: 'Itália',
    century: 9,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['papado', 'Roma'],
    biographyShort: 'Papa de breve pontificado que trabalhou pela paz em Roma e pela defesa da Igreja contra as intrigas políticas do século IX.',
    biographyFull: 'Adriano nasceu em Roma e foi eleito Papa em maio de 884. Seu pontificado durou apenas cerca de um ano, em um período turbulento para o papado e para a Itália, marcado por conflitos entre facções romanas.\n\nTrabalhou para restaurar a ordem em Roma e manter a independência da Igreja frente aos poderes políticos. Estabeleceu que a eleição papal seria prerrogativa exclusiva do clero romano, sem interferência imperial.\n\nEm 885, partiu rumo à Dieta de Worms, convocada pelo imperador Carlos III, mas faleceu durante a viagem em San Cesario sul Panaro, perto de Módena. Seu culto foi confirmado por Leão XIII em 1891.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.5,
  },
  {
    name: 'Santo Agostinho Zhao Rong',
    slug: 'santo-agostinho-zhao-rong',
    feastMonth: 7,
    feastDay: 9,
    birthDate: '1746-01-01',
    deathDate: '1815-01-27',
    birthPlace: 'Wuchuan',
    deathPlace: 'Chengdu',
    country: 'China',
    century: 19,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['China', 'mártires chineses'],
    biographyShort: 'Soldado chinês convertido ao catolicismo que se tornou sacerdote e foi martirizado, representando os 120 mártires da China canonizados em 2000.',
    biographyFull: 'Agostinho Zhao Rong nasceu em 1746 em Wuchuan, na província de Guizhou, China. Era soldado imperial encarregado de escoltar o padre Jean-Martin Moyë, missionário condenado à morte. Impressionado pela fé do missionário, converteu-se ao catolicismo.\n\nApós o batismo, estudou para o sacerdócio e foi ordenado, tornando-se um dos primeiros sacerdotes chineses. Exerceu o ministério na província de Sichuan em condições de perseguição constante.\n\nFoi preso e condenado à morte por professar e pregar a fé cristã. Morreu por estrangulamento em Chengdu em 1815. É o representante principal dos 120 mártires da China — 87 chineses e 33 missionários estrangeiros — canonizados por João Paulo II em 1 de outubro de 2000.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 27.73,
    longitude: 106.95,
  },
  {
    name: 'Santa Verónica Giuliani',
    slug: 'santa-veronica-giuliani',
    feastMonth: 7,
    feastDay: 10,
    birthDate: '1660-12-27',
    deathDate: '1727-07-09',
    birthPlace: 'Mercatello sul Metauro',
    deathPlace: 'Città di Castello',
    country: 'Itália',
    century: 18,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['místicas', 'contra doenças do coração'],
    biographyShort: 'Monja capuchinha e mística italiana que recebeu os estigmas de Cristo e deixou um diário espiritual de mais de 22 mil páginas.',
    biographyFull: 'Úrsula Giuliani nasceu em 27 de dezembro de 1660 em Mercatello sul Metauro, Itália. Aos 17 anos, ingressou no mosteiro capuchinho de Città di Castello, recebendo o nome Verónica. Desde cedo experimentou fenômenos místicos extraordinários.\n\nEm 1697, recebeu os estigmas, que permaneceram visíveis até sua morte. Por ordem dos superiores, manteve um diário espiritual detalhado que alcançou mais de 22 mil páginas, constituindo um dos mais extensos documentos de mística cristã. Foi nomeada abadessa em 1716.\n\nSubmetida a rigorosos exames eclesiásticos que confirmaram a autenticidade de suas experiências, Verónica viveu em profunda humildade e obediência. Faleceu em 9 de julho de 1727 e foi canonizada por Gregório XVI em 1839.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.62,
    longitude: 12.31,
  },
  {
    name: 'São Bento de Núrsia',
    slug: 'sao-bento-de-nursia',
    feastMonth: 7,
    feastDay: 11,
    birthDate: '480-01-01',
    deathDate: '547-03-21',
    birthPlace: 'Núrsia',
    deathPlace: 'Monte Cassino',
    country: 'Itália',
    century: 6,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Europa', 'monges'],
    biographyShort: 'Patriarca do monaquismo ocidental e patrono da Europa, São Bento fundou a Ordem Beneditina e escreveu a Regra que moldou a civilização europeia.',
    biographyFull: 'Bento nasceu por volta de 480 em Núrsia, na Úmbria. Enviado a Roma para estudar, escandalizou-se com a decadência moral e retirou-se para uma gruta em Subiaco, onde viveu como eremita durante três anos. Sua fama de santidade atraiu discípulos.\n\nPor volta de 529, fundou o mosteiro de Monte Cassino, onde escreveu sua célebre Regra, cujo lema é "Ora et Labora" (Reza e Trabalha). A Regra de São Bento equilibra oração, trabalho manual e estudo, tornando-se o fundamento do monaquismo ocidental.\n\nOs mosteiros beneditinos preservaram a cultura clássica, desenvolveram a agricultura e civilizaram a Europa durante a Idade Média. Bento faleceu em Monte Cassino em 21 de março de 547 e foi proclamado patrono da Europa por Paulo VI em 1964.',
    biographyKids: null,
    quotes: [{ text: 'Ora et Labora — Reza e Trabalha.', source: 'Lema beneditino' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.79,
    longitude: 13.09,
  },
  {
    name: 'São João Gualberto',
    slug: 'sao-joao-gualberto',
    feastMonth: 7,
    feastDay: 12,
    birthDate: '995-01-01',
    deathDate: '1073-07-12',
    birthPlace: 'Florença',
    deathPlace: 'Passignano',
    country: 'Itália',
    century: 11,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['guardas florestais', 'parques'],
    biographyShort: 'Nobre florentino que perdoou o assassino de seu irmão e fundou a Congregação de Vallombrosa, dedicada à vida contemplativa e à reforma da Igreja.',
    biographyFull: 'João Gualberto nasceu por volta de 995 em Florença, filho de nobre família. Um dia, ao encontrar o assassino de seu irmão em uma rua estreita, estava prestes a matá-lo quando o homem implorou perdão de braços abertos em forma de cruz. João o perdoou e dirigiu-se a uma igreja, onde o crucifixo inclinou a cabeça em aprovação.\n\nEssa experiência transformou sua vida. Tornou-se monge beneditino em San Miniato, mas buscando maior rigor, fundou por volta de 1036 o mosteiro de Vallombrosa, nos Apeninos toscanos, dando origem à Congregação Vallombrosana.\n\nJoão combateu a simonia na Igreja com grande vigor e promoveu a reforma do clero. Faleceu em Passignano em 12 de julho de 1073 e foi canonizado em 1193. É patrono dos guardas florestais por sua ligação com as florestas dos Apeninos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.77,
    longitude: 11.25,
  },
  {
    name: 'Santa Teresa dos Andes',
    slug: 'santa-teresa-dos-andes',
    feastMonth: 7,
    feastDay: 13,
    birthDate: '1900-07-13',
    deathDate: '1920-04-12',
    birthPlace: 'Santiago',
    deathPlace: 'Los Andes',
    country: 'Chile',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['jovens', 'doentes'],
    biographyShort: 'Primeira santa chilena, carmelita descalça que morreu aos 19 anos, vivendo intensa união mística com Cristo em breve mas fervorosa vida religiosa.',
    biographyFull: 'Juana Fernández Solar nasceu em 13 de julho de 1900 em Santiago do Chile, em família abastada. Desde a adolescência experimentou profunda vida de oração e desejo de consagração. Aos 19 anos, ingressou no Carmelo de Los Andes.\n\nNo convento, viveu apenas onze meses, mas com intensidade espiritual extraordinária. Seu diário e cartas revelam uma mística centrada no amor de Cristo e na alegria do sacrifício. Contraiu tifo e ofereceu seus sofrimentos por pecadores e sacerdotes.\n\nFaleceu em 12 de abril de 1920, aos 19 anos, tendo emitido os votos religiosos em artigo de morte. Foi canonizada por João Paulo II em 1993, tornando-se a primeira santa chilena e a primeira carmelita descalça canonizada fora da Europa.',
    biographyKids: null,
    quotes: [{ text: 'Deus é alegria infinita.', source: 'Diário de Santa Teresa dos Andes' }],
    prayer: null,
    imageUrl: null,
    latitude: -33.45,
    longitude: -70.65,
  },
  {
    name: 'São Camilo de Lellis',
    slug: 'sao-camilo-de-lellis',
    feastMonth: 7,
    feastDay: 14,
    birthDate: '1550-05-25',
    deathDate: '1614-07-14',
    birthPlace: 'Bucchianico',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['enfermeiros', 'hospitais'],
    biographyShort: 'Ex-soldado e jogador convertido que fundou a Ordem dos Ministros dos Enfermos, revolucionando o cuidado hospitalar com a cruz vermelha no peito.',
    biographyFull: 'Camilo nasceu em 25 de maio de 1550 em Bucchianico, nos Abruzos. Após uma juventude dissoluta como soldado mercenário e jogador inveterado, converteu-se aos 25 anos e tentou entrar nos capuchinhos, mas foi recusado por causa de uma ferida crônica na perna.\n\nTrabalhou no hospital de São Tiago em Roma, onde se horrorizou com as condições dos doentes. Em 1582, fundou a Ordem dos Ministros dos Enfermos (Camilianos), cujos membros faziam um quarto voto de servir os enfermos, mesmo com risco de vida. Usavam uma cruz vermelha no hábito, precursora do símbolo da Cruz Vermelha.\n\nCamilo introduziu reformas revolucionárias nos hospitais: isolamento de contagiosos, dieta adequada, ventilação e assistência espiritual. Faleceu em Roma em 14 de julho de 1614 e é patrono dos enfermeiros e hospitais.',
    biographyKids: null,
    quotes: [{ text: 'Mais coração nessas mãos!', source: 'Atribuída a São Camilo de Lellis' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.3,
    longitude: 14.08,
  },
  {
    name: 'São Boaventura',
    slug: 'sao-boaventura',
    feastMonth: 7,
    feastDay: 15,
    birthDate: '1221-01-01',
    deathDate: '1274-07-15',
    birthPlace: 'Bagnoregio',
    deathPlace: 'Lyon',
    country: 'Itália',
    century: 13,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'carregadores'],
    biographyShort: 'Doutor Seráfico da Igreja e ministro geral dos franciscanos, Boaventura uniu teologia e mística em obras que iluminaram a fé cristã no século XIII.',
    biographyFull: 'Giovanni di Fidanza nasceu em 1221 em Bagnoregio, na Itália central. Segundo a tradição, foi curado em criança por São Francisco de Assis, que exclamou "Buona ventura!" — boa sorte — dando-lhe o nome. Ingressou na Ordem Franciscana e estudou em Paris sob Alexandre de Hales.\n\nTornou-se mestre em Paris ao lado de São Tomás de Aquino e, em 1257, foi eleito ministro geral dos franciscanos, governando a ordem por dezessete anos e pacificando suas divisões internas. Suas obras teológicas, como o Itinerarium Mentis in Deum, são marcos da mística cristã.\n\nNomeado cardeal-bispo de Albano, participou do Concílio de Lyon em 1274, trabalhando pela reunificação com os gregos. Faleceu durante o concílio em 15 de julho de 1274. Foi declarado Doutor da Igreja em 1588.',
    biographyKids: null,
    quotes: [{ text: 'Toda criatura é um vestígio da Trindade.', source: 'Itinerarium Mentis in Deum' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.63,
    longitude: 12.09,
  },
  {
    name: 'Nossa Senhora do Carmo',
    slug: 'nossa-senhora-do-carmo',
    feastMonth: 7,
    feastDay: 16,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 13,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['carmelitas', 'almas do purgatório'],
    biographyShort: 'Título mariano ligado à Ordem do Carmo, celebrado desde que a Virgem Maria apareceu a São Simão Stock entregando-lhe o escapulário em 1251.',
    biographyFull: 'A devoção a Nossa Senhora do Carmo tem origem no Monte Carmelo, na Terra Santa, onde eremitas se reuniram no século XII inspirados pelo profeta Elias, formando a Ordem Carmelita sob o patrocínio da Virgem Maria.\n\nEm 16 de julho de 1251, segundo a tradição, a Virgem apareceu ao superior geral São Simão Stock em Cambridge, entregando-lhe o escapulário marrom com a promessa de proteção especial: quem morresse usando-o devotamente não sofreria o fogo eterno.\n\nA festa de Nossa Senhora do Carmo espalhou-se por todo o mundo católico. O escapulário do Carmo é um dos sacramentais mais populares da Igreja e a devoção é particularmente forte no Brasil, em Portugal e na América Latina.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.74,
    longitude: 34.99,
  },
  {
    name: 'Bem-aventurado Inácio de Azevedo',
    slug: 'bem-aventurado-inacio-de-azevedo',
    feastMonth: 7,
    feastDay: 17,
    birthDate: '1527-01-01',
    deathDate: '1570-07-15',
    birthPlace: 'Porto',
    deathPlace: 'Oceano Atlântico',
    country: 'Portugal',
    century: 16,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['missionários', 'Brasil'],
    biographyShort: 'Jesuíta português martirizado com 39 companheiros por corsários calvinistas no Atlântico, enquanto se dirigiam ao Brasil para evangelizar.',
    biographyFull: 'Inácio de Azevedo nasceu no Porto em 1527, de família nobre. Ingressou na Companhia de Jesus e tornou-se reitor do colégio de Braga. Após visitar as missões do Brasil, voltou a Portugal para recrutar missionários.\n\nEm 1570, embarcou rumo ao Brasil com trinta e nove companheiros jesuítas e aspirantes. Ao largo das Ilhas Canárias, o navio foi atacado pelo corsário calvinista Jacques Sourie. Inácio, segurando uma imagem de Nossa Senhora, encorajou os companheiros à fidelidade.\n\nTodos foram massacrados e lançados ao mar em 15 de julho de 1570. Os quarenta mártires do Brasil foram beatificados por Pio IX em 1854. São venerados como protetores das missões no Brasil.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.15,
    longitude: -8.61,
  },
  {
    name: 'São Frederico de Utrecht',
    slug: 'sao-frederico-de-utrecht',
    feastMonth: 7,
    feastDay: 18,
    birthDate: '780-01-01',
    deathDate: '838-07-18',
    birthPlace: 'Utrecht',
    deathPlace: 'Utrecht',
    country: 'Holanda',
    century: 9,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['diocese de Utrecht', 'surdos'],
    biographyShort: 'Bispo de Utrecht que evangelizou os frísios e foi assassinado por defender a moralidade cristã, possivelmente por denunciar o casamento ilícito da imperatriz.',
    biographyFull: 'Frederico nasceu por volta de 780, provavelmente em Utrecht, de família nobre frísia. Foi educado na escola da catedral e ordenado sacerdote. Em 825, foi eleito bispo de Utrecht.\n\nDedicou-se à evangelização dos frísios pagãos na ilha de Walcheren, enviando missionários e construindo igrejas. Como bispo, destacou-se pelo zelo pastoral e pela defesa da moral cristã, repreendendo vícios mesmo entre os poderosos.\n\nFoi assassinado em 18 de julho de 838, esfaqueado por dois sicários enquanto celebrava a Missa. A tradição atribui o crime à vingança da imperatriz Judite, cujo casamento irregular Frederico havia denunciado. Morreu recitando o salmo "Livra-me, Senhor".',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 52.09,
    longitude: 5.12,
  },
  {
    name: 'São Símaco',
    slug: 'sao-simaco',
    feastMonth: 7,
    feastDay: 19,
    birthDate: null,
    deathDate: '514-07-19',
    birthPlace: 'Sardenha',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 6,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['papado', 'pobres'],
    biographyShort: 'Papa de origem sarda que defendeu o primado romano, combateu o cisma laurenciano e construiu igrejas e abrigos para os pobres em Roma.',
    biographyFull: 'Símaco nasceu na Sardenha e converteu-se do paganismo. Foi eleito Papa em 498, mas enfrentou imediatamente o cisma provocado pelo antipapa Lourenço, apoiado por facções da aristocracia romana e pelo governo bizantino.\n\nApós anos de conflito, um sínodo em 502 confirmou Símaco como Papa legítimo e estabeleceu o princípio de que o Papa não pode ser julgado por nenhuma autoridade terrena. Símaco libertou escravos, resgatou prisioneiros e construiu abrigos para os pobres.\n\nEmbeleziu as basílicas romanas, construiu a primeira capela papal no Vaticano e fundou hospitais. Faleceu em 19 de julho de 514 após dezesseis anos de pontificado marcado pela firmeza doutrinária e pela caridade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 39.22,
    longitude: 9.12,
  },
  {
    name: 'Santo Apolinário',
    slug: 'santo-apolinario',
    feastMonth: 7,
    feastDay: 20,
    birthDate: null,
    deathDate: '79-07-20',
    birthPlace: 'Antioquia',
    deathPlace: 'Ravena',
    country: 'Itália',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Ravena', 'contra epilepsia'],
    biographyShort: 'Primeiro bispo de Ravena, discípulo de São Pedro, que evangelizou a região da Emília-Romanha e sofreu o martírio após repetidas perseguições.',
    biographyFull: 'Segundo a tradição, Apolinário era originário de Antioquia e foi discípulo do apóstolo Pedro, que o consagrou bispo e o enviou a Ravena para evangelizar a região. Foi o primeiro bispo da cidade.\n\nDurante seu episcopado, enfrentou diversas perseguições. Foi exilado, espancado e torturado várias vezes por se recusar a sacrificar aos ídolos, mas sempre retornava a Ravena para continuar sua missão pastoral.\n\nFoi martirizado por volta do ano 79, após cerca de vinte e seis anos de episcopado. Duas célebres basílicas em Ravena — Sant\'Apollinare in Classe e Sant\'Apollinare Nuovo — são dedicadas a ele e conservam mosaicos bizantinos de incomparável beleza.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.42,
    longitude: 12.2,
  },
  {
    name: 'São Lourenço de Brindisi',
    slug: 'sao-lourenco-de-brindisi',
    feastMonth: 7,
    feastDay: 21,
    birthDate: '1559-07-22',
    deathDate: '1619-07-22',
    birthPlace: 'Brindisi',
    deathPlace: 'Lisboa',
    country: 'Itália',
    century: 17,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['capuchinhos', 'cervejeiros'],
    biographyShort: 'Doutor da Igreja e capuchinho poliglota, Lourenço de Brindisi pregava em seis idiomas e liderou tropas cristãs contra os turcos otomanos na Hungria.',
    biographyFull: 'Giulio Cesare Russo nasceu em 22 de julho de 1559 em Brindisi. Ingressou nos capuchinhos aos 16 anos, recebendo o nome Lourenço. Dotado de memória prodigiosa, dominava hebraico, grego, siríaco, francês, espanhol e alemão, além do latim e italiano.\n\nFoi cinco vezes ministro provincial, ministro geral dos capuchinhos e diplomata papal. Em 1601, liderou pessoalmente as tropas imperiais na batalha de Székesfehérvár contra os turcos otomanos, marchando à frente com um crucifixo, obtendo vitória decisiva.\n\nSeus sermões e escritos bíblicos totalizam quinze volumes. Faleceu em Lisboa em 22 de julho de 1619, durante missão diplomática. Foi declarado Doutor da Igreja por João XXIII em 1959.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.63,
    longitude: 17.94,
  },
  {
    name: 'Santa Maria Madalena',
    slug: 'santa-maria-madalena',
    feastMonth: 7,
    feastDay: 22,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Magdala',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'FEMALE',
    patronage: ['pecadores arrependidos', 'perfumistas'],
    biographyShort: 'Discípula fiel de Jesus, da qual expulsou sete demônios, Maria Madalena esteve ao pé da Cruz e foi a primeira testemunha da Ressurreição.',
    biographyFull: 'Maria, natural de Magdala, cidade na costa ocidental do lago de Genesaré, foi libertada por Jesus de sete demônios. Tornou-se uma de suas discípulas mais devotas, acompanhando-o e servindo-o com seus bens durante seu ministério público.\n\nEsteve presente ao pé da Cruz quando a maioria dos apóstolos havia fugido. Na manhã de Páscoa, foi a primeira a chegar ao sepulcro vazio e a primeira a ver Jesus ressuscitado, que lhe disse: "Vai dizer aos meus irmãos". Por isso é chamada de Apóstola dos Apóstolos.\n\nSua festa foi elevada à categoria de festa litúrgica pelo Papa Francisco em 2016, equiparando-a às festas dos apóstolos, em reconhecimento de seu papel como primeira anunciadora da Ressurreição.',
    biographyKids: null,
    quotes: [{ text: 'Vi o Senhor!', source: 'João 20,18' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.84,
    longitude: 35.51,
  },
  {
    name: 'Santa Brígida da Suécia',
    slug: 'santa-brigida-da-suecia',
    feastMonth: 7,
    feastDay: 23,
    birthDate: '1303-06-14',
    deathDate: '1373-07-23',
    birthPlace: 'Finsta',
    deathPlace: 'Roma',
    country: 'Suécia',
    century: 14,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['Europa', 'Suécia'],
    biographyShort: 'Mística sueca, mãe de oito filhos e fundadora da Ordem do Santíssimo Salvador, Brígida recebeu revelações divinas e é copadroeira da Europa.',
    biographyFull: 'Brígida nasceu em 1303 em Finsta, Suécia, de família aristocrática. Casou-se aos 13 anos com Ulf Gudmarsson, com quem teve oito filhos, incluindo Santa Catarina da Suécia. Após a morte do marido, dedicou-se inteiramente à vida religiosa.\n\nFundou a Ordem do Santíssimo Salvador (Brigitinas) em Vadstena, com um mosteiro duplo de monjas e monges. Suas Revelações, ditadas por visões místicas, influenciaram a piedade e a política europeia. Mudou-se para Roma em 1349 e nunca mais voltou à Suécia.\n\nEm Roma, trabalhou pela reforma da Igreja, repreendeu papas e reis, e peregrinou à Terra Santa. Faleceu em 23 de julho de 1373 e foi canonizada em 1391. Foi declarada copadroeira da Europa por João Paulo II em 1999.',
    biographyKids: null,
    quotes: [{ text: 'O mundo inteiro é como uma gota de orvalho da manhã diante de Deus.', source: 'Revelações de Santa Brígida' }],
    prayer: null,
    imageUrl: null,
    latitude: 59.65,
    longitude: 18.1,
  },
  {
    name: 'São Charbel Makhlouf',
    slug: 'sao-charbel-makhlouf',
    feastMonth: 7,
    feastDay: 24,
    birthDate: '1828-05-08',
    deathDate: '1898-12-24',
    birthPlace: 'Bekaa Kafra',
    deathPlace: 'Annaya',
    country: 'Líbano',
    century: 19,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Líbano', 'monges maronitas'],
    biographyShort: 'Monge eremita maronita libanês cuja vida de oração e penitência extrema o tornou célebre, especialmente pelos milagres ocorridos em seu túmulo após a morte.',
    biographyFull: 'Youssef Antoun Makhlouf nasceu em 8 de maio de 1828 em Bekaa Kafra, uma aldeia montanhosa do Líbano. Aos 23 anos, ingressou na Ordem Libanesa Maronita, recebendo o nome Charbel em honra de um mártir de Antioquia.\n\nViveu como monge no mosteiro de Annaya e depois como eremita na capela de São Pedro e São Paulo por 23 anos. Sua vida era de rigorosa penitência, oração contínua e silêncio absoluto, alimentando-se uma vez ao dia e dormindo no chão.\n\nFaleceu em 24 de dezembro de 1898. Poucos meses depois, uma luz misteriosa foi vista sobre seu túmulo. Quando o corpo foi exumado, foi encontrado incorrupto e exsudando um líquido oleoso. Milhares de milagres foram relatados. Foi canonizado por Paulo VI em 1977.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 34.24,
    longitude: 36.05,
  },
  {
    name: 'São Tiago Apóstolo',
    slug: 'sao-tiago-apostolo',
    feastMonth: 7,
    feastDay: 25,
    birthDate: null,
    deathDate: '44-07-25',
    birthPlace: 'Betsaida',
    deathPlace: 'Jerusalém',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Espanha', 'peregrinos'],
    biographyShort: 'Filho de Zebedeu e irmão de João, Tiago foi o primeiro apóstolo mártir e patrono da Espanha, cujo túmulo em Santiago de Compostela é meta de peregrinação.',
    biographyFull: 'Tiago, chamado o Maior, era filho de Zebedeu e irmão de João Evangelista. Pescador no lago de Genesaré, foi um dos primeiros chamados por Jesus e pertenceu ao grupo íntimo dos três apóstolos que testemunharam a Transfiguração e a agonia no Getsêmani.\n\nApós Pentecostes, segundo a tradição espanhola, Tiago pregou na Península Ibérica antes de retornar a Jerusalém. Em 44 d.C., foi decapitado por ordem do rei Herodes Agripa I, tornando-se o primeiro apóstolo mártir.\n\nA tradição afirma que seu corpo foi trasladado para a Galiza, onde seu túmulo foi descoberto no século IX em Compostela. O Caminho de Santiago tornou-se a mais célebre rota de peregrinação da cristandade medieval e permanece vivo até hoje.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.91,
    longitude: 35.63,
  },
  {
    name: 'São Joaquim e Santa Ana',
    slug: 'sao-joaquim-e-santa-ana',
    feastMonth: 7,
    feastDay: 26,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: 'Jerusalém',
    country: 'Israel',
    century: 1,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['avós', 'casais estéreis'],
    biographyShort: 'Pais da Virgem Maria e avós de Jesus, Joaquim e Ana conceberam Maria miraculosamente após longa esterilidade, sendo modelos de fé conjugal.',
    biographyFull: 'Segundo o Protoevangelho de Tiago, texto apócrifo do século II, Joaquim e Ana eram um casal piedoso de Nazaré que sofria com a esterilidade, considerada grande provação em Israel. Joaquim, humilhado no Templo por não ter filhos, retirou-se ao deserto para jejuar e orar.\n\nUm anjo apareceu a ambos separadamente, anunciando que Ana conceberia uma filha que seria abençoada entre todas as mulheres. Os esposos reencontraram-se na Porta Dourada de Jerusalém, e Ana concebeu Maria, a futura Mãe de Deus.\n\nA devoção a São Joaquim e Santa Ana é antiquíssima, particularmente forte no Brasil, onde Santa Ana é patrona de inúmeras cidades e paróquias. São invocados como patronos dos avós e dos casais que desejam filhos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.7,
    longitude: 35.3,
  },
  {
    name: 'São Pantaleão',
    slug: 'sao-pantaleao',
    feastMonth: 7,
    feastDay: 27,
    birthDate: null,
    deathDate: '305-07-27',
    birthPlace: 'Nicomédia',
    deathPlace: 'Nicomédia',
    country: 'Turquia',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['médicos', 'contra dores de cabeça'],
    biographyShort: 'Médico do imperador Galério em Nicomédia, Pantaleão foi martirizado durante a perseguição de Diocleciano por curar gratuitamente os pobres em nome de Cristo.',
    biographyFull: 'Pantaleão nasceu em Nicomédia, na Bitínia (atual Turquia), filho de pai pagão e mãe cristã. Estudou medicina e tornou-se médico pessoal do imperador Galério. O sacerdote Hermolau reconduziu-o à fé cristã de sua mãe.\n\nApós a conversão, Pantaleão passou a curar os doentes gratuitamente, invocando o nome de Cristo. Sua fama e generosidade provocaram a inveja de outros médicos, que o denunciaram como cristão durante a perseguição de Diocleciano.\n\nFoi submetido a diversos tormentos — fogo, chumbo derretido, feras — dos quais saiu ileso, segundo a tradição. Foi finalmente decapitado em 305. É venerado como um dos Santos Auxiliadores e patrono dos médicos. Ampolas de seu sangue em Ravello liquefazem-se anualmente.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.76,
    longitude: 29.92,
  },
  {
    name: 'Santos Nazário e Celso',
    slug: 'santos-nazario-e-celso',
    feastMonth: 7,
    feastDay: 28,
    birthDate: null,
    deathDate: '68-07-28',
    birthPlace: 'Roma',
    deathPlace: 'Milão',
    country: 'Itália',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Milão', 'crianças'],
    biographyShort: 'Mártires do primeiro século cujos corpos foram encontrados por Santo Ambrósio em Milão, Nazário era missionário romano e Celso um jovem que o acompanhava.',
    biographyFull: 'Nazário era filho de pai pagão e mãe cristã, Santa Perpétua, que o fez batizar pelo Papa Lino. Dedicou-se à evangelização, percorrendo a Itália e a Gália. Em Cimiez (atual Nice), encontrou o jovem Celso, que o acompanhou em suas missões.\n\nAmbos foram presos em Milão durante a perseguição de Nero. Após serem jogados ao mar e miraculosamente salvos, foram novamente capturados e decapitados, provavelmente em 68 d.C.\n\nEm 395, Santo Ambrósio descobriu seus corpos em um jardim fora de Milão. O corpo de Nazário aparentava estar recém-sepultado e o sangue ainda fresco. Ambrósio trasladou-os para a basílica dos Santos Apóstolos, atual basílica de São Nazário em Milão.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.5,
  },
  {
    name: 'Santa Marta',
    slug: 'santa-marta',
    feastMonth: 7,
    feastDay: 29,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Betânia',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'FEMALE',
    patronage: ['donas de casa', 'cozinheiras'],
    biographyShort: 'Irmã de Maria e Lázaro, Marta acolheu Jesus em sua casa de Betânia e professou fé na Ressurreição antes mesmo da ressurreição de seu irmão.',
    biographyFull: 'Marta vivia em Betânia, aldeia próxima a Jerusalém, com seus irmãos Maria e Lázaro. Sua casa era lugar de acolhida frequente para Jesus e seus discípulos. No episódio célebre narrado por Lucas, Jesus a repreendeu gentilmente por preocupar-se com muitas coisas enquanto Maria escolhera a melhor parte.\n\nQuando Lázaro morreu, Marta foi ao encontro de Jesus e declarou: "Sim, Senhor, eu creio que tu és o Cristo, o Filho de Deus". Esta profissão de fé precedeu a ressurreição de Lázaro, um dos maiores milagres de Jesus.\n\nSegundo a tradição provençal, Marta teria evangelizado o sul da França após a dispersão dos discípulos. É patrona das donas de casa, cozinheiras e hoteleiros, representando o serviço ativo e acolhedor ao próximo.',
    biographyKids: null,
    quotes: [{ text: 'Sim, Senhor, eu creio que tu és o Cristo, o Filho de Deus, que havia de vir ao mundo.', source: 'João 11,27' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.77,
    longitude: 35.25,
  },
  {
    name: 'São Pedro Crisólogo',
    slug: 'sao-pedro-crisologo',
    feastMonth: 7,
    feastDay: 30,
    birthDate: '380-01-01',
    deathDate: '450-07-30',
    birthPlace: 'Ímola',
    deathPlace: 'Ímola',
    country: 'Itália',
    century: 5,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['pregadores', 'diocese de Ravena'],
    biographyShort: 'Arcebispo de Ravena e Doutor da Igreja, Pedro Crisólogo (Palavra de Ouro) destacou-se pela eloquência de seus sermões breves e substanciais.',
    biographyFull: 'Pedro nasceu por volta de 380 em Ímola, na Emília-Romanha. Foi ordenado diácono pelo bispo Cornélio de Ímola e, em 433, nomeado arcebispo de Ravena, então capital do Império Romano do Ocidente, pela imperatriz Gala Placídia.\n\nRecebeu o título de Crisólogo (Palavra de Ouro) pela extraordinária eloquência de seus sermões, dos quais cerca de 170 chegaram até nós. Seus discursos eram breves, claros e profundos, abordando temas cristológicos, marianos e morais com maestria literária.\n\nCombateu o paganismo residual e a heresia monofisita. Quando Eutiques lhe pediu apoio, Pedro respondeu remetendo-o à autoridade do Papa Leão Magno. Faleceu em Ímola por volta de 450 e foi declarado Doutor da Igreja em 1729.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.35,
    longitude: 11.71,
  },
  {
    name: 'Santo Inácio de Loyola',
    slug: 'santo-inacio-de-loyola',
    feastMonth: 7,
    feastDay: 31,
    birthDate: '1491-10-23',
    deathDate: '1556-07-31',
    birthPlace: 'Azpeitia',
    deathPlace: 'Roma',
    country: 'Espanha',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Companhia de Jesus', 'retiros espirituais'],
    biographyShort: 'Soldado basco convertido durante convalescença, Inácio fundou a Companhia de Jesus e escreveu os Exercícios Espirituais que transformaram a espiritualidade cristã.',
    biographyFull: 'Íñigo López de Loyola nasceu em 1491 no castelo de Loyola, em Azpeitia, País Basco. Soldado e cortesão, teve a perna quebrada por uma bala de canhão no cerco de Pamplona em 1521. Durante a convalescença, a leitura de vidas de santos provocou sua conversão radical.\n\nApós uma peregrinação a Montserrat e meses de oração e penitência em Manresa, onde compôs os Exercícios Espirituais, estudou em diversas universidades. Em Paris, reuniu os primeiros companheiros e, em 1534, fizeram os votos que originariam a Companhia de Jesus, aprovada pelo Papa em 1540.\n\nComo primeiro superior geral, Inácio dirigiu a expansão dos jesuítas por todo o mundo, enviando missionários à Ásia, África e Américas, fundando colégios e universidades. Faleceu em Roma em 31 de julho de 1556 e foi canonizado em 1622.',
    biographyKids: null,
    quotes: [{ text: 'Em tudo amar e servir.', source: 'Exercícios Espirituais, Santo Inácio' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.17,
    longitude: -2.27,
  },
];
