import type { SaintSeedData } from './types';

export const juneSaints: SaintSeedData[] = [
  {
    name: 'São Justino Mártir',
    slug: 'sao-justino-martir',
    feastMonth: 6,
    feastDay: 1,
    birthDate: '100-01-01',
    deathDate: '165-06-01',
    birthPlace: 'Nablus',
    deathPlace: 'Roma',
    country: 'Palestina',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['filósofos', 'apologistas'],
    biographyShort: 'Filósofo pagão convertido ao cristianismo, Justino escreveu as mais importantes apologias da fé cristã primitiva e foi decapitado em Roma por recusar sacrificar aos deuses.',
    biographyFull: 'Justino nasceu em Nablus, na Palestina, por volta do ano 100. Estudou diversas correntes filosóficas gregas antes de encontrar no cristianismo a verdade plena que buscava. Sua conversão deu-se após um encontro com um ancião que lhe apresentou os profetas do Antigo Testamento.\n\nEm Roma, abriu uma escola de filosofia cristã e compôs suas célebres Apologias, dirigidas ao imperador, defendendo os cristãos das acusações de ateísmo e imoralidade. Seu Diálogo com Trifão é um dos mais antigos textos de apologética cristã.\n\nDenunciado como cristão durante a perseguição de Marco Aurélio, Justino recusou-se a oferecer sacrifícios aos ídolos. Foi flagelado e decapitado junto com seis companheiros por volta de 165.',
    biographyKids: null,
    quotes: [{ text: 'A verdade é una, e onde quer que se encontre, pertence a nós, cristãos.', source: 'Atribuída a São Justino' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.22,
    longitude: 35.26,
  },
  {
    name: 'Santos Marcelino e Pedro',
    slug: 'santos-marcelino-e-pedro',
    feastMonth: 6,
    feastDay: 2,
    birthDate: null,
    deathDate: '304-06-02',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['prisioneiros', 'contra tempestades'],
    biographyShort: 'Marcelino, sacerdote, e Pedro, exorcista, foram martirizados em Roma durante a perseguição de Diocleciano e são mencionados no Cânon Romano da Missa.',
    biographyFull: 'Marcelino era sacerdote e Pedro exercia o ministério de exorcista na Igreja de Roma no início do século IV. Durante a perseguição de Diocleciano, ambos foram presos por professar a fé cristã.\n\nNa prisão, continuaram evangelizando e convertendo carcereiros e prisioneiros. Suas virtudes e milagres atraíram muitos à fé, o que enfureceu ainda mais as autoridades romanas.\n\nForam condenados à morte e decapitados em uma floresta chamada Silva Negra, por volta de 304. O imperador Constantino ergueu uma basílica sobre seu túmulo na Via Labicana.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.5,
  },
  {
    name: 'São Carlos Lwanga',
    slug: 'sao-carlos-lwanga',
    feastMonth: 6,
    feastDay: 3,
    birthDate: '1860-01-01',
    deathDate: '1886-06-03',
    birthPlace: 'Bulimu',
    deathPlace: 'Namugongo',
    country: 'Uganda',
    century: 19,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['juventude africana', 'convertidos'],
    biographyShort: 'Jovem catequista ugandense que liderou um grupo de pagens cristãos do rei Mwanga II, sendo queimado vivo em Namugongo por recusar renunciar à fé.',
    biographyFull: 'Carlos Lwanga nasceu por volta de 1860 em Bulimu, Uganda. Converteu-se ao cristianismo e tornou-se catequista, assumindo a liderança dos pagens cristãos na corte do rei Mwanga II após o assassinato do catequista José Mkasa.\n\nO rei Mwanga, hostil ao cristianismo e enfurecido pela resistência dos jovens às suas investidas imorais, ordenou a morte de todos os pagens cristãos. Carlos batizou às pressas os catecúmenos e encorajou os companheiros a permanecerem firmes na fé.\n\nEm 3 de junho de 1886, Carlos e seus companheiros foram queimados vivos em Namugongo. Ao todo, vinte e dois mártires ugandenses foram canonizados por Paulo VI em 1964, tornando-se os patronos da juventude africana.',
    biographyKids: null,
    quotes: [{ text: 'Catequista até o fim, continuou rezando e encorajando seus companheiros nas chamas.', source: 'Relato do martírio' }],
    prayer: null,
    imageUrl: null,
    latitude: 0.35,
    longitude: 32.61,
  },
  {
    name: 'São Francisco Caracciolo',
    slug: 'sao-francisco-caracciolo',
    feastMonth: 6,
    feastDay: 4,
    birthDate: '1563-10-13',
    deathDate: '1608-06-04',
    birthPlace: 'Villa Santa Maria',
    deathPlace: 'Agnone',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['adoração eucarística', 'cozinheiros italianos'],
    biographyShort: 'Sacerdote napolitano que cofundou a Ordem dos Clérigos Regulares Menores, dedicando-se à adoração perpétua do Santíssimo Sacramento e ao serviço dos encarcerados.',
    biographyFull: 'Ascanio Caracciolo nasceu em 1563 em Villa Santa Maria, no reino de Nápoles. Após uma grave doença na juventude, prometeu dedicar sua vida a Deus e recebeu o nome Francisco ao ser ordenado sacerdote.\n\nEm 1588, cofundou com João Agostinho Adorno a Ordem dos Clérigos Regulares Menores, cujo carisma incluía um quarto voto de não aceitar dignidades eclesiásticas. A ordem se dedicava à adoração perpétua do Santíssimo Sacramento e ao cuidado dos prisioneiros.\n\nFrancisco viajou por toda a Itália e Espanha expandindo a ordem, vivendo em extrema penitência e devoção eucarística. Faleceu em Agnone em 4 de junho de 1608, sendo canonizado em 1807.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.95,
    longitude: 14.39,
  },
  {
    name: 'São Bonifácio',
    slug: 'sao-bonifacio',
    feastMonth: 6,
    feastDay: 5,
    birthDate: '675-01-01',
    deathDate: '754-06-05',
    birthPlace: 'Crediton',
    deathPlace: 'Dokkum',
    country: 'Inglaterra',
    century: 8,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Alemanha', 'cervejeiros'],
    biographyShort: 'Monge inglês conhecido como o Apóstolo da Alemanha, evangelizou os povos germânicos e reformou a Igreja franca antes de ser martirizado na Frísia.',
    biographyFull: 'Winfrid nasceu em Crediton, na Inglaterra, por volta de 675. Entrou jovem no mosteiro e tornou-se monge beneditino. Em 719, o Papa Gregório II enviou-o como missionário à Germânia, dando-lhe o nome Bonifácio.\n\nDurante décadas, evangelizou os povos pagãos da Turíngia, Hesse e Baviera. O episódio mais célebre foi a derrubada do Carvalho de Thor em Geismar, demonstrando a impotência dos deuses pagãos. Fundou mosteiros, organizou dioceses e reformou a Igreja franca em diversos concílios.\n\nEm 754, já idoso, retornou à Frísia para missionar. Em 5 de junho, foi atacado e morto por pagãos junto com cinquenta e dois companheiros em Dokkum. Seu corpo foi levado para Fulda, onde é venerado até hoje.',
    biographyKids: null,
    quotes: [{ text: 'Em Deus confiamos; nada temos a temer.', source: 'Atribuída a São Bonifácio' }],
    prayer: null,
    imageUrl: null,
    latitude: 50.73,
    longitude: 9.67,
  },
  {
    name: 'São Norberto',
    slug: 'sao-norberto',
    feastMonth: 6,
    feastDay: 6,
    birthDate: '1080-01-01',
    deathDate: '1134-06-06',
    birthPlace: 'Xanten',
    deathPlace: 'Magdeburgo',
    country: 'Alemanha',
    century: 12,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['parturientes', 'paz'],
    biographyShort: 'Nobre alemão convertido após quase morrer atingido por um raio, fundou a Ordem dos Premonstratenses e tornou-se arcebispo de Magdeburgo.',
    biographyFull: 'Norberto nasceu por volta de 1080 em Xanten, na Renânia. Levava vida mundana como cônego da corte imperial até que, em 1115, um raio caiu a seus pés durante uma cavalgada, derrubando-o do cavalo. Converteu-se radicalmente e ordenou-se sacerdote.\n\nApós anos de pregação itinerante, fundou em 1120 a Ordem dos Premonstratenses (ou Norbertinos) no vale de Prémontré, na França. A ordem combinava vida contemplativa com atividade pastoral e espalhou-se rapidamente pela Europa.\n\nEm 1126, foi nomeado arcebispo de Magdeburgo, onde enfrentou oposição ao reformar o clero e defender os direitos da Igreja. Faleceu em 6 de junho de 1134 e foi canonizado em 1582.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.66,
    longitude: 6.46,
  },
  {
    name: 'Bem-aventurada Ana de São Bartolomeu',
    slug: 'bem-aventurada-ana-de-sao-bartolomeu',
    feastMonth: 6,
    feastDay: 7,
    birthDate: '1549-10-01',
    deathDate: '1626-06-07',
    birthPlace: 'Almendral de la Cañada',
    deathPlace: 'Antuérpia',
    country: 'Espanha',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['carmelitas descalças', 'Antuérpia'],
    biographyShort: 'Companheira inseparável de Santa Teresa de Ávila, Ana foi a primeira irmã leiga carmelita descalça a tornar-se priora e levou a reforma teresiana para França e Flandres.',
    biographyFull: 'Ana García nasceu em 1549 em Almendral de la Cañada, Espanha. Pastora na infância, entrou no Carmelo Descalço em 1570 como irmã leiga e tornou-se secretária e enfermeira de Santa Teresa de Ávila, em cujos braços a santa faleceu em 1582.\n\nApós a morte de Teresa, Ana levou a reforma carmelitana para a França e os Países Baixos, fundando carmelos em Paris, Tours, Mons e Antuérpia. Em Antuérpia, a cidade atribuiu a suas orações a libertação de um cerco protestante.\n\nMística e escritora, deixou uma autobiografia e numerosas cartas. Faleceu em Antuérpia em 7 de junho de 1626. Foi beatificada por Bento XV em 1917.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.1,
    longitude: -4.85,
  },
  {
    name: 'São Medardo',
    slug: 'sao-medardo',
    feastMonth: 6,
    feastDay: 8,
    birthDate: '456-01-01',
    deathDate: '545-06-08',
    birthPlace: 'Salency',
    deathPlace: 'Noyon',
    country: 'França',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['bom tempo', 'agricultores'],
    biographyShort: 'Bispo de Noyon no século VI, São Medardo era célebre por sua caridade para com os pobres e pela tradição popular que associa seu dia ao clima dos quarenta dias seguintes.',
    biographyFull: 'Medardo nasceu em Salency, na Picardia, por volta de 456. Filho de nobre franco e mãe galo-romana, foi ordenado sacerdote e dedicou-se à evangelização das populações rurais do norte da Gália.\n\nEm torno de 530, foi consagrado bispo de Vermand-Noyon. Destacou-se pela generosidade extraordinária, chegando a dar cavalos e gado da diocese aos necessitados. Transferiu a sede episcopal para Noyon e trabalhou na conversão dos francos ainda pagãos.\n\nFaleceu em Noyon por volta de 545. O rei Clotário I mandou construir uma basílica sobre seu túmulo em Soissons. Na tradição popular francesa, a chuva no dia de São Medardo anuncia quarenta dias de mau tempo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.58,
    longitude: 3.0,
  },
  {
    name: 'Santo Efrém da Síria',
    slug: 'santo-efrem-da-siria',
    feastMonth: 6,
    feastDay: 9,
    birthDate: '306-01-01',
    deathDate: '373-06-09',
    birthPlace: 'Nísibis',
    deathPlace: 'Edessa',
    country: 'Síria',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['poetas', 'líderes espirituais'],
    biographyShort: 'Diácono e Doutor da Igreja, Efrém é considerado o maior poeta e teólogo da tradição siríaca, conhecido como a Harpa do Espírito Santo.',
    biographyFull: 'Efrém nasceu em Nísibis, na Mesopotâmia, por volta de 306. Batizado na juventude, tornou-se diácono e permaneceu nessa ordem por humildade, recusando o sacerdócio. Estudou sob o bispo Tiago de Nísibis e ensinou na escola teológica da cidade.\n\nQuando Nísibis caiu sob domínio persa em 363, Efrém retirou-se para Edessa, onde fundou a célebre Escola de Edessa. Compôs centenas de hinos, comentários bíblicos e poemas teológicos em siríaco, usando a poesia como instrumento de catequese contra as heresias.\n\nConhecido como a Harpa do Espírito Santo, foi proclamado Doutor da Igreja por Bento XV em 1920. Faleceu em Edessa em 373, após contrair doença enquanto atendia vítimas de uma epidemia.',
    biographyKids: null,
    quotes: [{ text: 'Senhor, dai-me lágrimas, para que eu lave minha alma com elas.', source: 'Hinos de Santo Efrém' }],
    prayer: null,
    imageUrl: null,
    latitude: 37.15,
    longitude: 41.22,
  },
  {
    name: 'Bem-aventurado Eduardo Poppe',
    slug: 'bem-aventurado-eduardo-poppe',
    feastMonth: 6,
    feastDay: 10,
    birthDate: '1890-12-18',
    deathDate: '1924-06-10',
    birthPlace: 'Moerzeke',
    deathPlace: 'Moerzeke',
    country: 'Bélgica',
    century: 20,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['seminaristas', 'catequistas'],
    biographyShort: 'Sacerdote belga que se dedicou à formação eucarística de crianças e à direção espiritual de seminaristas, falecendo jovem aos 33 anos.',
    biographyFull: 'Eduardo Poppe nasceu em 18 de dezembro de 1890 em Moerzeke, Bélgica, filho de um padeiro. Ordenado sacerdote em 1916, foi pároco em um bairro operário de Gante, onde se dedicou à catequese eucarística das crianças, seguindo o decreto de São Pio X sobre a comunhão precoce.\n\nSua saúde frágil obrigou-o a retirar-se do ministério paroquial ativo. Passou seus últimos anos como diretor espiritual de seminaristas e escrevendo obras de espiritualidade centradas na Eucaristia e na devoção ao Sagrado Coração.\n\nFaleceu em 10 de junho de 1924, aos 33 anos, em Moerzeke. Foi beatificado por Bento XVI em 2009, reconhecido por sua vida de intensa união com Cristo na Eucaristia.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.03,
    longitude: 4.05,
  },
  {
    name: 'São Barnabé Apóstolo',
    slug: 'sao-barnabe-apostolo',
    feastMonth: 6,
    feastDay: 11,
    birthDate: null,
    deathDate: '61-06-11',
    birthPlace: 'Chipre',
    deathPlace: 'Salamina',
    country: 'Chipre',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Chipre', 'contra granizo'],
    biographyShort: 'Levita judeu nascido em Chipre, Barnabé foi um dos primeiros discípulos e companheiro de São Paulo em suas viagens missionárias, sendo venerado como apóstolo.',
    biographyFull: 'José, apelidado Barnabé (filho da consolação) pelos apóstolos, era um levita natural de Chipre. Vendeu seu campo e entregou o dinheiro aos apóstolos, conforme narrado nos Atos dos Apóstolos. Foi ele quem apresentou Paulo convertido à comunidade de Jerusalém.\n\nBarnabé foi enviado a Antioquia para confirmar os novos convertidos e trouxe Paulo de Tarso para ajudá-lo. Juntos realizaram a primeira viagem missionária, pregando em Chipre e na Ásia Menor. Separaram-se depois por divergências sobre João Marcos, mas continuaram a missão independentemente.\n\nSegundo a tradição, Barnabé retornou a Chipre, onde fundou a Igreja de Salamina. Teria sido martirizado por apedrejamento por volta do ano 61. É considerado fundador e patrono da Igreja cipriota.',
    biographyKids: null,
    quotes: [{ text: 'Barnabé era homem bom, cheio do Espírito Santo e de fé.', source: 'Atos 11,24' }],
    prayer: null,
    imageUrl: null,
    latitude: 35.17,
    longitude: 33.36,
  },
  {
    name: 'São Gaspar Bertoni',
    slug: 'sao-gaspar-bertoni',
    feastMonth: 6,
    feastDay: 12,
    birthDate: '1777-10-09',
    deathDate: '1853-06-12',
    birthPlace: 'Verona',
    deathPlace: 'Verona',
    country: 'Itália',
    century: 19,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['estigmatinos', 'educadores'],
    biographyShort: 'Sacerdote veronês que fundou a Congregação dos Estigmatinos, dedicando-se à educação da juventude e à formação do clero em tempos de turbulência napoleônica.',
    biographyFull: 'Gaspar Bertoni nasceu em 9 de outubro de 1777 em Verona, Itália. Ordenado sacerdote em 1800, dedicou-se ao ministério paroquial e à educação dos jovens durante o conturbado período das guerras napoleônicas.\n\nEm 1816, fundou a Congregação dos Sagrados Estigmas de Nosso Senhor Jesus Cristo (Estigmatinos), voltada para a formação do clero, a educação e as missões. A espiritualidade da congregação centra-se na contemplação das chagas de Cristo.\n\nApesar de graves enfermidades que o acompanharam durante grande parte da vida, Gaspar manteve intensa atividade pastoral e espiritual. Faleceu em Verona em 12 de junho de 1853 e foi canonizado por Bento XVI em 2009.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.44,
    longitude: 10.99,
  },
  {
    name: 'Santo Antônio de Pádua',
    slug: 'santo-antonio-de-padua',
    feastMonth: 6,
    feastDay: 13,
    birthDate: '1195-08-15',
    deathDate: '1231-06-13',
    birthPlace: 'Lisboa',
    deathPlace: 'Pádua',
    country: 'Portugal',
    century: 13,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['objetos perdidos', 'pobres'],
    biographyShort: 'Doutor da Igreja nascido em Lisboa, Santo Antônio foi frade franciscano célebre por sua pregação poderosa, seus milagres e sua devoção, sendo um dos santos mais populares do mundo.',
    biographyFull: 'Fernando de Bulhões nasceu em Lisboa em 1195. Ingressou nos cônegos regulares de Santo Agostinho, mas ao conhecer os primeiros mártires franciscanos em Marrocos, transferiu-se para a Ordem dos Frades Menores, recebendo o nome Antônio.\n\nSua extraordinária capacidade de pregação foi descoberta casualmente e logo São Francisco de Assis o nomeou mestre de teologia da ordem. Pregou por toda a Itália e sul da França, combatendo heresias com eloquência e sabedoria bíblica, sendo chamado de Arca da Aliança.\n\nEstabeleceu-se em Pádua, onde faleceu em 13 de junho de 1231, aos 35 anos. Foi canonizado menos de um ano depois por Gregório IX e declarado Doutor da Igreja em 1946. É invocado em todo o mundo como intercessor para encontrar objetos perdidos.',
    biographyKids: null,
    quotes: [{ text: 'As ações falam mais alto que as palavras; que as vossas palavras ensinem e as vossas ações falem.', source: 'Sermões de Santo Antônio' }],
    prayer: null,
    imageUrl: null,
    latitude: 38.71,
    longitude: -9.14,
  },
  {
    name: 'São Eliseu',
    slug: 'sao-eliseu',
    feastMonth: 6,
    feastDay: 14,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Abel-Meolá',
    deathPlace: 'Samaria',
    country: 'Israel',
    century: -9,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['profetas', 'agricultores'],
    biographyShort: 'Profeta do Antigo Testamento e discípulo de Elias, Eliseu realizou numerosos milagres e guiou o povo de Israel por mais de cinquenta anos.',
    biographyFull: 'Eliseu era filho de Safat, lavrador em Abel-Meolá, no vale do Jordão. Foi chamado pelo profeta Elias enquanto arava com doze juntas de bois. Deixou tudo, sacrificou os bois e seguiu seu mestre como discípulo.\n\nQuando Elias foi arrebatado ao céu em um carro de fogo, Eliseu recebeu porção dobrada de seu espírito. Realizou numerosos prodígios: purificou as águas de Jericó, multiplicou o azeite da viúva, ressuscitou o filho da sunamita e curou Naamã da lepra.\n\nExerceu seu ministério profético durante os reinados de vários reis de Israel, aconselhando-os e repreendendo-os. Segundo a tradição, faleceu em Samaria após mais de cinquenta anos de atividade profética.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.38,
    longitude: 35.57,
  },
  {
    name: 'Santa Germana Cousin',
    slug: 'santa-germana-cousin',
    feastMonth: 6,
    feastDay: 15,
    birthDate: '1579-01-01',
    deathDate: '1601-06-15',
    birthPlace: 'Pibrac',
    deathPlace: 'Pibrac',
    country: 'França',
    century: 16,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['pastoras', 'pessoas com deficiência'],
    biographyShort: 'Jovem pastora francesa que, apesar de deficiência física e maus-tratos da madrasta, viveu em profunda piedade e caridade, morrendo aos 22 anos.',
    biographyFull: 'Germana nasceu em 1579 em Pibrac, perto de Toulouse, com a mão direita atrofiada e sofrendo de escrófula. Órfã de mãe, foi maltratada pela madrasta, que a fazia dormir no estábulo e cuidar do rebanho.\n\nApesar das privações, Germana vivia em profunda união com Deus. Ia à missa diariamente, fincando sua roca na terra e confiando o rebanho ao anjo da guarda — os animais nunca se dispersavam nem invadiam terras vizinhas. Repartia com os pobres o pouco pão que recebia.\n\nFoi encontrada morta em seu leito de palha em 1601, aos 22 anos. Em 1644, seu corpo foi achado incorrupto. Foi canonizada em 1867 por Pio IX, tornando-se patrona das pessoas com deficiência.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.58,
    longitude: 1.28,
  },
  {
    name: 'São João Francisco Régis',
    slug: 'sao-joao-francisco-regis',
    feastMonth: 6,
    feastDay: 16,
    birthDate: '1597-01-31',
    deathDate: '1640-12-31',
    birthPlace: 'Fontcouverte',
    deathPlace: 'La Louvesc',
    country: 'França',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['rendeiras', 'assistentes sociais'],
    biographyShort: 'Jesuíta francês missionário nas montanhas do Vivarais e Velay, dedicou-se à catequese dos camponeses e ao resgate de mulheres marginalizadas.',
    biographyFull: 'João Francisco Régis nasceu em 31 de janeiro de 1597 em Fontcouverte, no Languedoc. Ingressou na Companhia de Jesus aos 18 anos e, após a ordenação, dedicou-se às missões populares nas regiões montanhosas do sul da França.\n\nPercorria aldeias isoladas em pleno inverno, pregando, catequizando e confessando. Fundou casas de acolhida para mulheres arrependidas e cooperativas de rendeiras para dar sustento às mulheres pobres. Enfrentou oposição de calvinistas e até de alguns católicos.\n\nExausto por suas missões, faleceu em La Louvesc em 31 de dezembro de 1640, aos 43 anos. Seu túmulo tornou-se centro de peregrinação e ali o Santo Cura d\'Ars foi pedir orientação. Foi canonizado em 1737.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.28,
    longitude: 2.84,
  },
  {
    name: 'São Gregório Barbarigo',
    slug: 'sao-gregorio-barbarigo',
    feastMonth: 6,
    feastDay: 17,
    birthDate: '1625-09-16',
    deathDate: '1697-06-18',
    birthPlace: 'Veneza',
    deathPlace: 'Pádua',
    country: 'Itália',
    century: 17,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['bispos', 'diocese de Pádua'],
    biographyShort: 'Cardeal e bispo de Pádua, Gregório Barbarigo foi um dos maiores reformadores do clero no espírito do Concílio de Trento, promovendo a educação sacerdotal.',
    biographyFull: 'Gregório nasceu em 16 de setembro de 1625 em uma nobre família veneziana. Acompanhou o embaixador veneziano ao Congresso de Münster em 1648, onde conheceu o núncio Fabio Chigi, futuro Papa Alexandre VII, que o orientou para a carreira eclesiástica.\n\nNomeado bispo de Bérgamo em 1657 e transferido para Pádua em 1664, aplicou com zelo as reformas tridentinas. Fundou o seminário, reformou a tipografia episcopal para imprimir textos em diversas línguas orientais e visitou pessoalmente todas as paróquias.\n\nSua generosidade com os pobres era imensa, distribuindo quase toda sua renda. Faleceu em 18 de junho de 1697 em Pádua e foi canonizado por João XXIII em 1960.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.44,
    longitude: 12.33,
  },
  {
    name: 'Santa Marina de Bitínia',
    slug: 'santa-marina-de-bitinia',
    feastMonth: 6,
    feastDay: 18,
    birthDate: '540-01-01',
    deathDate: '604-03-12',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 6,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['músicos', 'professores'],
    biographyShort: 'Papa e Doutor da Igreja, Gregório Magno reformou a liturgia, enviou missionários à Inglaterra e deixou obras fundamentais de teologia pastoral e espiritualidade.',
    biographyFull: 'Gregório nasceu em Roma por volta de 540 em família patrícia. Foi prefeito de Roma antes de converter seus palácios em mosteiros e tornar-se monge beneditino. Em 590, foi eleito Papa, o primeiro monge a ocupar o trono de Pedro.\n\nComo Papa, reformou a liturgia (o canto gregoriano leva seu nome), reorganizou as posses da Igreja para alimentar os pobres, enviou Santo Agostinho de Cantuária para evangelizar a Inglaterra e negociou com os lombardos para proteger Roma.\n\nSeus escritos — a Regra Pastoral, os Diálogos, os Morais sobre Jó e centenas de cartas — influenciaram profundamente a Igreja medieval. Faleceu em 12 de março de 604, sendo um dos quatro grandes Doutores da Igreja Ocidental.',
    biographyKids: null,
    quotes: [{ text: 'O pastor de almas deve ser próximo de cada um pela compaixão e elevado acima de todos pela contemplação.', source: 'Regra Pastoral' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.45,
  },
  {
    name: 'São Romualdo',
    slug: 'sao-romualdo',
    feastMonth: 6,
    feastDay: 19,
    birthDate: '951-01-01',
    deathDate: '1027-06-19',
    birthPlace: 'Ravena',
    deathPlace: 'Val di Castro',
    country: 'Itália',
    century: 11,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['camaldulenses', 'monges'],
    biographyShort: 'Nobre ravenaense que abandonou a vida mundana para abraçar a vida eremítica, fundando a Congregação dos Camaldulenses.',
    biographyFull: 'Romualdo nasceu por volta de 951 em Ravena, filho de família ducal. Após presenciar seu pai matar um parente em um duelo, retirou-se para o mosteiro de Sant\'Apollinare in Classe como penitência e ali abraçou a vida monástica.\n\nInsatisfeito com a tibieza de alguns mosteiros, buscou formas mais rigorosas de vida contemplativa. Por volta de 1012, fundou o eremitério de Camaldoli, nos Apeninos toscanos, unindo a vida eremítica com a cenobítica, dando origem à Congregação Camaldulense.\n\nRomualdo fundou numerosos mosteiros e eremitérios pela Itália, sempre buscando maior austeridade e silêncio. Faleceu solitário em Val di Castro em 19 de junho de 1027. Foi canonizado em 1595.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.42,
    longitude: 12.2,
  },
  {
    name: 'São Silvério',
    slug: 'sao-silverio',
    feastMonth: 6,
    feastDay: 20,
    birthDate: '480-01-01',
    deathDate: '537-12-02',
    birthPlace: 'Frosinone',
    deathPlace: 'Ilha Ponza',
    country: 'Itália',
    century: 6,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['ilha de Ponza', 'exilados'],
    biographyShort: 'Papa que defendeu a ortodoxia contra o monofisismo e foi deposto e exilado pela imperatriz Teodora, morrendo mártir na ilha de Ponza.',
    biographyFull: 'Silvério era filho do Papa Hormisdas (ordenado antes de receber as ordens sacras). Nascido em Frosinone, foi eleito Papa em 536 com apoio do rei ostrogodo Teodato.\n\nA imperatriz Teodora de Bizâncio exigiu que Silvério restaurasse o patriarca monofisita Antimo à sé de Constantinopla, mas ele recusou firmemente, defendendo o Concílio de Calcedônia. Teodora então conspirou com o general Belisário para depô-lo.\n\nAcusado falsamente de traição, Silvério foi deposto, despido das vestes papais e exilado na ilha de Ponza, onde morreu de fome e maus-tratos em 537. É venerado como mártir pela defesa da fé ortodoxa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.63,
    longitude: 13.34,
  },
  {
    name: 'São Luís Gonzaga',
    slug: 'sao-luis-gonzaga',
    feastMonth: 6,
    feastDay: 21,
    birthDate: '1568-03-09',
    deathDate: '1591-06-21',
    birthPlace: 'Castiglione delle Stiviere',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['juventude', 'estudantes'],
    biographyShort: 'Jovem príncipe italiano que renunciou ao marquesado para entrar na Companhia de Jesus, morrendo aos 23 anos ao cuidar de vítimas da peste em Roma.',
    biographyFull: 'Luís nasceu em 9 de março de 1568 no castelo de Castiglione delle Stiviere, primogênito do marquês Ferrante Gonzaga. Desde criança mostrou vocação religiosa, fazendo voto de castidade aos nove anos e resistindo aos planos do pai de torná-lo militar e cortesão.\n\nAos 17 anos, renunciou ao marquesado em favor do irmão e entrou no noviciado jesuíta em Roma, sob a direção de São Roberto Belarmino. Distinguiu-se pela oração intensa, penitência e obediência heroica.\n\nEm 1591, quando uma epidemia de peste assolou Roma, Luís dedicou-se ao cuidado dos doentes nos hospitais. Contraiu a doença e faleceu em 21 de junho de 1591, aos 23 anos. Foi declarado patrono da juventude por Bento XIII em 1729.',
    biographyKids: null,
    quotes: [{ text: 'Que importa se conquistamos o mundo inteiro, se perdemos a alma?', source: 'Atribuída a São Luís Gonzaga' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.39,
    longitude: 10.49,
  },
  {
    name: 'São Paulino de Nola',
    slug: 'sao-paulino-de-nola',
    feastMonth: 6,
    feastDay: 22,
    birthDate: '354-01-01',
    deathDate: '431-06-22',
    birthPlace: 'Bordeaux',
    deathPlace: 'Nola',
    country: 'Itália',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Nola', 'sineiros'],
    biographyShort: 'Senador romano que abandonou riqueza e carreira para tornar-se monge e depois bispo de Nola, destacando-se pela caridade imensa e pela poesia cristã.',
    biographyFull: 'Paulino nasceu em 354 em Bordeaux, filho de uma das mais ricas famílias senatoriais da Gália. Aluno de Ausônio, exerceu cargos políticos e governou a Campânia. Após o batismo e a morte de seu filho, ele e a esposa Terásia distribuíram suas imensas posses aos pobres.\n\nEstabeleceu-se junto ao túmulo de São Félix em Nola, vivendo em comunidade monástica. Em 409, foi aclamado bispo de Nola. Segundo a tradição, vendeu-se como escravo para resgatar o filho de uma viúva capturado pelos vândalos.\n\nSeus poemas e cartas, trocadas com Agostinho, Jerônimo e Ambrósio, são testemunhos preciosos da espiritualidade cristã do século V. Faleceu em 431 e é considerado um dos introdutores do uso de sinos nas igrejas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.93,
    longitude: 14.53,
  },
  {
    name: 'São José Cafasso',
    slug: 'sao-jose-cafasso',
    feastMonth: 6,
    feastDay: 23,
    birthDate: '1811-01-15',
    deathDate: '1860-06-23',
    birthPlace: 'Castelnuovo d\'Asti',
    deathPlace: 'Turim',
    country: 'Itália',
    century: 19,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['prisioneiros', 'condenados à morte'],
    biographyShort: 'Sacerdote turinense, mestre espiritual de São João Bosco e capelão dos presos, acompanhou dezenas de condenados à morte ao patíbulo, convertendo-os.',
    biographyFull: 'José Cafasso nasceu em 15 de janeiro de 1811 em Castelnuovo d\'Asti, mesmo vilarejo de São João Bosco. Apesar de uma deformidade física, foi ordenado sacerdote e tornou-se professor e depois reitor do Convitto Eclesiástico de Turim.\n\nComo formador de sacerdotes, combateu o jansenismo e promoveu uma moral baseada na misericórdia. Exerceu profunda influência sobre Dom Bosco, a quem orientou espiritualmente. Dedicou-se também ao apostolado nas prisões, acompanhando mais de sessenta condenados à morte.\n\nFaleceu em Turim em 23 de junho de 1860. Dom Bosco, que o chamava de "meu grande benfeitor", pregou em seu funeral. Foi canonizado por Pio XII em 1947.',
    biographyKids: null,
    quotes: [{ text: 'Ide aos pobres, ide aos pecadores: eis a vossa messe.', source: 'Atribuída a São José Cafasso' }],
    prayer: null,
    imageUrl: null,
    latitude: 44.99,
    longitude: 7.93,
  },
  {
    name: 'São João Batista',
    slug: 'sao-joao-batista',
    feastMonth: 6,
    feastDay: 24,
    birthDate: null,
    deathDate: '29-01-01',
    birthPlace: 'Ain Karem',
    deathPlace: 'Maqueronte',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['batismo', 'cordeiros'],
    biographyShort: 'Precursor de Jesus Cristo, João Batista pregou o arrependimento no deserto da Judeia e batizou o Salvador no rio Jordão, sendo o último e maior dos profetas.',
    biographyFull: 'João nasceu em Ain Karem, filho do sacerdote Zacarias e de Isabel, prima da Virgem Maria. Seu nascimento miraculoso foi anunciado pelo anjo Gabriel. Ainda no ventre materno, exultou ao reconhecer a presença de Jesus na visitação de Maria a Isabel.\n\nRetirou-se ao deserto, onde viveu como asceta, vestindo-se de pele de camelo e alimentando-se de gafanhotos e mel silvestre. Iniciou sua pregação às margens do Jordão, chamando o povo à conversão e batizando como sinal de arrependimento. Ao ver Jesus, proclamou: "Eis o Cordeiro de Deus".\n\nJoão denunciou corajosamente o casamento ilícito de Herodes Antipas com Herodíades, sendo por isso aprisionado na fortaleza de Maqueronte. Por intriga de Salomé, filha de Herodíades, foi decapitado. Jesus declarou que entre os nascidos de mulher não houve maior que João Batista.',
    biographyKids: null,
    quotes: [{ text: 'Eis o Cordeiro de Deus, que tira o pecado do mundo.', source: 'João 1,29' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.73,
    longitude: 35.15,
  },
  {
    name: 'São Guilherme de Vercelli',
    slug: 'sao-guilherme-de-vercelli',
    feastMonth: 6,
    feastDay: 25,
    birthDate: '1085-01-01',
    deathDate: '1142-06-25',
    birthPlace: 'Vercelli',
    deathPlace: 'Goleto',
    country: 'Itália',
    century: 12,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Irpínia', 'monges'],
    biographyShort: 'Peregrino e eremita que fundou a Congregação de Montevirgine nos montes da Campânia, unindo vida contemplativa e acolhida aos peregrinos.',
    biographyFull: 'Guilherme nasceu em 1085 em Vercelli, no Piemonte. Órfão desde cedo, peregrinou a Santiago de Compostela e planejou ir à Terra Santa, mas uma visão divina o direcionou ao monte Partenio, nos Apeninos da Campânia.\n\nAli fundou em 1124 o santuário e mosteiro de Montevirgine, que atraiu numerosos seguidores. Quando alguns monges acharam sua regra demasiado austera, Guilherme deixou Montevirgine e fundou outros mosteiros no sul da Itália, formando a Congregação dos Verginianos.\n\nSeu mosteiro mais importante após Montevirgine foi o de Goleto, onde estabeleceu um mosteiro duplo de monges e monjas. Faleceu em Goleto em 25 de junho de 1142. O santuário de Montevirgine continua sendo importante centro de peregrinação.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.33,
    longitude: 8.42,
  },
  {
    name: 'São Josemaría Escrivá',
    slug: 'sao-josemaria-escriva',
    feastMonth: 6,
    feastDay: 26,
    birthDate: '1902-01-09',
    deathDate: '1975-06-26',
    birthPlace: 'Barbastro',
    deathPlace: 'Roma',
    country: 'Espanha',
    century: 20,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Opus Dei', 'santificação do trabalho'],
    biographyShort: 'Sacerdote espanhol que fundou o Opus Dei em 1928, difundindo a chamada universal à santidade através do trabalho cotidiano e das circunstâncias ordinárias da vida.',
    biographyFull: 'Josemaría Escrivá nasceu em 9 de janeiro de 1902 em Barbastro, Espanha. Ordenado sacerdote em 1925, fundou o Opus Dei em 2 de outubro de 1928, em resposta a uma inspiração divina sobre a santificação do trabalho e da vida ordinária.\n\nDurante a Guerra Civil Espanhola, arriscou a vida para exercer o ministério sacerdotal clandestinamente. Após a guerra, expandiu o Opus Dei por toda a Espanha e, a partir de 1946, estabeleceu-se em Roma para difundir a obra internacionalmente.\n\nSua mensagem central era que todos os cristãos são chamados à santidade em seu estado de vida, santificando o trabalho profissional e as relações familiares e sociais. Faleceu em Roma em 26 de junho de 1975 e foi canonizado por João Paulo II em 2002.',
    biographyKids: null,
    quotes: [{ text: 'Santifica o teu trabalho, santifica-te no trabalho, santifica os outros com o trabalho.', source: 'Caminho, São Josemaría Escrivá' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.04,
    longitude: 0.12,
  },
  {
    name: 'São Cirilo de Alexandria',
    slug: 'sao-cirilo-de-alexandria',
    feastMonth: 6,
    feastDay: 27,
    birthDate: '376-01-01',
    deathDate: '444-06-27',
    birthPlace: 'Alexandria',
    deathPlace: 'Alexandria',
    country: 'Egito',
    century: 5,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'patriarcas'],
    biographyShort: 'Patriarca de Alexandria e Doutor da Igreja, Cirilo presidiu o Concílio de Éfeso que definiu Maria como Theotokos (Mãe de Deus) contra a heresia nestoriana.',
    biographyFull: 'Cirilo nasceu em Alexandria por volta de 376 e era sobrinho do patriarca Teófilo. Sucedeu-o como patriarca em 412, governando a importante sé com firmeza durante trinta e dois anos.\n\nSeu maior contributo foi a defesa da unidade da pessoa de Cristo contra Nestório, patriarca de Constantinopla, que separava as naturezas divina e humana de Cristo. Cirilo presidiu o Concílio de Éfeso em 431, que condenou o nestorianismo e proclamou solenemente Maria como Theotokos — Mãe de Deus.\n\nSeus escritos cristológicos e seus comentários bíblicos são de importância fundamental para a teologia católica. Faleceu em 27 de junho de 444 e foi declarado Doutor da Igreja por Leão XIII em 1882.',
    biographyKids: null,
    quotes: [{ text: 'Maria é Mãe de Deus, pois gerou segundo a carne o Verbo que procede de Deus Pai.', source: 'Carta a Nestório' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.2,
    longitude: 29.92,
  },
  {
    name: 'Santo Ireneu de Lyon',
    slug: 'santo-ireneu-de-lyon',
    feastMonth: 6,
    feastDay: 28,
    birthDate: '130-01-01',
    deathDate: '202-06-28',
    birthPlace: 'Esmirna',
    deathPlace: 'Lyon',
    country: 'França',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['diocese de Lyon', 'apologistas'],
    biographyShort: 'Discípulo de São Policarpo e bispo de Lyon, Ireneu é o mais importante teólogo do século II, combatendo o gnosticismo com sua obra Contra as Heresias.',
    biographyFull: 'Ireneu nasceu em Esmirna, na Ásia Menor, por volta de 130. Na juventude, ouviu a pregação de São Policarpo, discípulo direto do apóstolo João, estabelecendo assim uma ligação viva com a tradição apostólica.\n\nTransferiu-se para Lyon, na Gália, onde tornou-se presbítero e depois bispo, sucedendo São Potino, martirizado em 177. Sua obra principal, Adversus Haereses (Contra as Heresias), é uma refutação sistemática do gnosticismo e uma exposição da fé católica baseada na Tradição apostólica.\n\nIreneu desenvolveu a teologia da recapitulação em Cristo e a importância da sucessão apostólica. Segundo a tradição, sofreu o martírio durante a perseguição de Septímio Severo por volta de 202. Foi declarado Doutor da Igreja pelo Papa Francisco em 2022.',
    biographyKids: null,
    quotes: [{ text: 'A glória de Deus é o homem vivo, e a vida do homem é a visão de Deus.', source: 'Contra as Heresias, IV, 20' }],
    prayer: null,
    imageUrl: null,
    latitude: 38.42,
    longitude: 27.14,
  },
  {
    name: 'São Pedro e São Paulo',
    slug: 'sao-pedro-e-sao-paulo',
    feastMonth: 6,
    feastDay: 29,
    birthDate: null,
    deathDate: '67-06-29',
    birthPlace: 'Betsaida',
    deathPlace: 'Roma',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Roma', 'Igreja Católica'],
    biographyShort: 'Os dois pilares da Igreja: Pedro, o pescador sobre quem Cristo edificou sua Igreja, e Paulo, o apóstolo dos gentios que levou o Evangelho ao mundo pagão.',
    biographyFull: 'Simão Pedro, pescador de Betsaida, foi chamado por Jesus e recebeu o nome de Pedro (Rocha), sobre a qual Cristo edificou sua Igreja. Após a Ressurreição, tornou-se o líder dos apóstolos e primeiro bispo de Roma. Paulo, fariseu de Tarso, perseguia os cristãos até sua conversão no caminho de Damasco.\n\nPedro presidiu o Concílio de Jerusalém e estabeleceu a Igreja em Antioquia e Roma. Paulo realizou três grandes viagens missionárias pelo Mediterrâneo, fundando comunidades e escrevendo as epístolas que formam parte essencial do Novo Testamento.\n\nAmbos foram martirizados em Roma durante a perseguição de Nero, por volta do ano 67. Pedro foi crucificado de cabeça para baixo no Vaticano e Paulo foi decapitado na Via Ostiense. Sua festa conjunta celebra os dois fundamentos da Igreja universal.',
    biographyKids: null,
    quotes: [{ text: 'Tu és o Cristo, o Filho do Deus vivo.', source: 'Mateus 16,16' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.91,
    longitude: 35.63,
  },
  {
    name: 'Santos Primeiros Mártires de Roma',
    slug: 'santos-primeiros-martires-de-roma',
    feastMonth: 6,
    feastDay: 30,
    birthDate: null,
    deathDate: '64-06-30',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['mártires', 'perseguidos pela fé'],
    biographyShort: 'Cristãos anônimos martirizados em Roma após o incêndio de 64 d.C., quando Nero os acusou falsamente de incendiar a cidade.',
    biographyFull: 'Em julho de 64, um grande incêndio devastou Roma durante seis dias. O imperador Nero, para desviar as suspeitas de si mesmo, acusou os cristãos de terem provocado o desastre, desencadeando a primeira perseguição imperial contra a Igreja.\n\nSegundo o historiador Tácito, uma grande multidão de cristãos foi presa e submetida a suplícios atrozes. Alguns foram cobertos com peles de animais e dilacerados por cães, outros crucificados, e muitos untados com resina e queimados vivos nos jardins de Nero como tochas humanas.\n\nEstes mártires anônimos, cuja festa foi introduzida no calendário romano em 1969, representam os incontáveis cristãos que deram a vida pela fé nos primeiros séculos. Sua memória é celebrada no dia seguinte à festa dos apóstolos Pedro e Paulo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9,
    longitude: 12.45,
  },
];
