import type { SaintSeedData } from './types';

export const marchSaints: SaintSeedData[] = [
  {
    name: 'São David de Gales',
    slug: 'sao-david-de-gales',
    feastMonth: 3,
    feastDay: 1,
    birthDate: '500-01-01',
    deathDate: '589-03-01',
    birthPlace: 'Pembrokeshire',
    deathPlace: 'Menevia',
    country: 'País de Gales',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['País de Gales', 'poetas'],
    biographyShort: 'São David foi o mais célebre santo galês, monge e bispo de Menevia no século VI. Viveu com extrema austeridade, alimentando-se apenas de pão e água.',
    biographyFull: 'São David nasceu no País de Gales por volta do ano 500. Tornou-se monge e fundou diversos mosteiros, adotando uma regra de vida extremamente austera. Seus monges trabalhavam a terra sem auxílio de animais e alimentavam-se apenas de pão, ervas e água.\n\nFoi consagrado bispo de Menevia e participou de sínodos importantes para a Igreja galesa. Seu último sermão continha a famosa exortação: "Fazei as pequenas coisas". Faleceu por volta de 589.\n\nÉ o padroeiro do País de Gales, celebrado em 1º de março com grande festividade nacional.',
    biographyKids: null,
    quotes: [{ text: 'Fazei as pequenas coisas que vistes e ouvistes comigo.', source: 'Último sermão de São David' }],
    prayer: null,
    imageUrl: null,
    latitude: 51.882,
    longitude: -5.269,
  },
  {
    name: 'São Simplício',
    slug: 'sao-simplicio',
    feastMonth: 3,
    feastDay: 2,
    birthDate: null,
    deathDate: '483-03-10',
    birthPlace: 'Tívoli',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 5,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['diocese de Tívoli'],
    biographyShort: 'São Simplício foi Papa de 468 a 483, governando a Igreja durante a queda do Império Romano do Ocidente. Combateu heresias e organizou as paróquias de Roma.',
    biographyFull: 'São Simplício nasceu em Tívoli, próximo a Roma, e foi eleito Papa em 468. Seu pontificado coincidiu com o colapso do Império Romano do Ocidente em 476, época de grande instabilidade política.\n\nEnfrentou a heresia monofisita no Oriente e trabalhou para manter a unidade da fé. Organizou a estrutura paroquial de Roma, distribuindo igrejas entre os sacerdotes para melhor atendimento dos fiéis.\n\nFaleceu em 483, deixando uma Igreja mais organizada em meio ao caos das invasões bárbaras.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Santa Cunegunda',
    slug: 'santa-cunegunda',
    feastMonth: 3,
    feastDay: 3,
    birthDate: '975-01-01',
    deathDate: '1033-03-03',
    birthPlace: 'Luxemburgo',
    deathPlace: 'Kaufungen',
    country: 'Alemanha',
    century: 11,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['Luxemburgo', 'crianças doentes'],
    biographyShort: 'Santa Cunegunda foi imperatriz do Sacro Império Romano, esposa de São Henrique II. Após a morte do marido, entrou para um mosteiro beneditino onde viveu em humildade até o fim.',
    biographyFull: 'Santa Cunegunda nasceu por volta de 975 em uma família nobre de Luxemburgo. Casou-se com Henrique II da Baviera, que se tornou imperador do Sacro Império. Juntos, dedicaram-se à reforma da Igreja e à construção de igrejas e mosteiros.\n\nSegundo a tradição, Cunegunda foi acusada de infidelidade e provou sua inocência caminhando sobre brasas incandescentes sem se queimar. Fundou o mosteiro de Kaufungen com recursos próprios.\n\nApós a morte de Henrique II em 1024, retirou-se para o mosteiro que fundara, vivendo como simples religiosa até sua morte em 1033. Foi canonizada em 1200.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.2833,
    longitude: 9.5167,
  },
  {
    name: 'São Casimiro',
    slug: 'sao-casimiro',
    feastMonth: 3,
    feastDay: 4,
    birthDate: '1458-10-03',
    deathDate: '1484-03-04',
    birthPlace: 'Cracóvia',
    deathPlace: 'Vilnius',
    country: 'Polônia',
    century: 15,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['Lituânia', 'jovens'],
    biographyShort: 'São Casimiro foi príncipe da Polônia e Lituânia, conhecido por sua piedade e castidade. Morreu de tuberculose aos 25 anos, recusando tratamentos contrários à sua consciência.',
    biographyFull: 'São Casimiro nasceu em 1458, filho do rei Casimiro IV da Polônia. Apesar da vida na corte, dedicou-se à oração, à penitência e ao cuidado dos pobres desde jovem.\n\nRecusou a coroa da Hungria oferecida por uma facção de nobres e preferiu a vida devota à ambição política. Tinha especial devoção à Virgem Maria e rezava diariamente o hino "Omni die dic Mariae".\n\nFaleceu de tuberculose em 1484, aos 25 anos, em Vilnius. Foi canonizado em 1521 e é padroeiro da Lituânia e da juventude.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.0647,
    longitude: 19.945,
  },
  {
    name: 'São João José da Cruz',
    slug: 'sao-joao-jose-da-cruz',
    feastMonth: 3,
    feastDay: 5,
    birthDate: '1654-08-15',
    deathDate: '1734-03-05',
    birthPlace: 'Ischia',
    deathPlace: 'Nápoles',
    country: 'Itália',
    century: 18,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Ischia', 'franciscanos alcantarinos'],
    biographyShort: 'São João José da Cruz foi um frade franciscano alcantarino italiano, célebre por seus dons místicos e caridade. Viveu em extrema pobreza e penitência em Nápoles.',
    biographyFull: 'São João José da Cruz nasceu Carlo Gaetano Calosirto em 1654 na ilha de Ischia, Itália. Aos 16 anos entrou para os Franciscanos Alcantarinos, adotando vida de rigorosa penitência e oração.\n\nFoi superior de vários conventos e ficou conhecido pelos dons de profecia, levitação e leitura de consciências. Dedicava-se incansavelmente à confissão e à direção espiritual dos fiéis napolitanos.\n\nFaleceu em Nápoles em 1734, aos 79 anos. Foi canonizado por Gregório XVI em 1839.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.7306,
    longitude: 13.8946,
  },
  {
    name: 'Santa Coleta de Corbie',
    slug: 'santa-coleta-de-corbie',
    feastMonth: 3,
    feastDay: 6,
    birthDate: '1381-01-13',
    deathDate: '1447-03-06',
    birthPlace: 'Corbie',
    deathPlace: 'Gand',
    country: 'França',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['mulheres grávidas', 'crianças doentes'],
    biographyShort: 'Santa Coleta foi uma religiosa francesa que reformou a Ordem das Clarissas, restaurando a pobreza radical de Santa Clara. Fundou 17 conventos reformados.',
    biographyFull: 'Santa Coleta nasceu em 1381 em Corbie, na Picardia, França. Após a morte de seus pais, distribuiu todos os bens aos pobres e viveu como reclusa antes de receber a missão de reformar a Ordem das Clarissas.\n\nAutorizada pelo antipapa Bento XIII, que reconheceu sua missão, Coleta reformou conventos existentes e fundou 17 novos, restaurando a regra original de Santa Clara com toda a sua austeridade.\n\nFaleceu em Gand em 1447. Suas reformadas, as Coletinas, continuam existindo até hoje. Foi canonizada em 1807.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.9086,
    longitude: 2.5122,
  },
  {
    name: 'Santas Perpétua e Felicidade',
    slug: 'santas-perpetua-e-felicidade',
    feastMonth: 3,
    feastDay: 7,
    birthDate: '181-01-01',
    deathDate: '203-03-07',
    birthPlace: 'Cartago',
    deathPlace: 'Cartago',
    country: 'Tunísia',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['mães', 'gestantes'],
    biographyShort: 'Santas Perpétua e Felicidade foram mártires cristãs executadas na arena de Cartago em 203. Perpétua era uma nobre e Felicidade, sua escrava grávida.',
    biographyFull: 'Perpétua era uma jovem nobre de Cartago e Felicidade, sua escrava. Ambas foram presas como catecúmenas durante a perseguição do imperador Septímio Severo em 203.\n\nPerpétua deixou um diário comovente, um dos mais antigos textos cristãos escritos por uma mulher, narrando suas visões e a firmeza de sua fé. Felicidade deu à luz na prisão poucos dias antes da execução.\n\nForam martirizadas na arena de Cartago diante de uma multidão. Seu testemunho é celebrado desde os primeiros séculos da Igreja.',
    biographyKids: null,
    quotes: [{ text: 'Agora sou eu que sofro; mas lá, Outro sofrerá por mim.', source: 'Diário de Santa Perpétua' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.8525,
    longitude: 10.3233,
  },
  {
    name: 'São João de Deus',
    slug: 'sao-joao-de-deus',
    feastMonth: 3,
    feastDay: 8,
    birthDate: '1495-03-08',
    deathDate: '1550-03-08',
    birthPlace: 'Montemor-o-Novo',
    deathPlace: 'Granada',
    country: 'Portugal',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['hospitais', 'enfermeiros', 'doentes'],
    biographyShort: 'São João de Deus foi um português que, após uma vida aventureira como soldado e pastor, converteu-se e dedicou-se ao cuidado dos doentes e pobres em Granada, fundando a Ordem Hospitaleira.',
    biographyFull: 'São João de Deus nasceu em 1495 em Montemor-o-Novo, Portugal. Viveu uma juventude errante como soldado e vendedor ambulante até que, aos 42 anos, uma pregação de São João de Ávila provocou sua conversão radical.\n\nEm Granada, começou a recolher doentes e mendigos, fundando um hospital mantido por esmolas. Sua dedicação total aos enfermos atraiu seguidores, formando o núcleo da futura Ordem Hospitaleira dos Irmãos de São João de Deus.\n\nFaleceu em 1550, no dia de seu aniversário, ajoelhado diante do altar. É padroeiro dos hospitais e enfermeiros.',
    biographyKids: null,
    quotes: [{ text: 'Fazei o bem a vós mesmos, irmãos, fazendo o bem aos pobres.', source: 'São João de Deus' }],
    prayer: null,
    imageUrl: null,
    latitude: 38.65,
    longitude: -8.2167,
  },
  {
    name: 'Santa Francisca Romana',
    slug: 'santa-francisca-romana',
    feastMonth: 3,
    feastDay: 9,
    birthDate: '1384-01-01',
    deathDate: '1440-03-09',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['motoristas', 'viúvas'],
    biographyShort: 'Santa Francisca Romana foi uma nobre romana que, após anos de vida matrimonial exemplar, fundou a congregação das Oblatas Beneditinas. É padroeira dos motoristas.',
    biographyFull: 'Santa Francisca nasceu em 1384 em Roma, numa família nobre. Casou-se aos 13 anos com Lorenzo Ponziani, com quem viveu um matrimônio feliz por 40 anos, criando três filhos.\n\nDurante a ocupação de Roma e epidemias, dedicou-se ao cuidado dos pobres e doentes, transformando parte de seu palácio em hospital. Em 1425, fundou a congregação das Oblatas de Maria, ligadas à regra beneditina.\n\nApós a morte do marido, retirou-se para o convento que fundara. Faleceu em 1440 e é conhecida por ter tido visões de seu anjo da guarda, razão pela qual é padroeira dos motoristas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'São Macário de Jerusalém',
    slug: 'sao-macario-de-jerusalem',
    feastMonth: 3,
    feastDay: 10,
    birthDate: null,
    deathDate: '335-01-01',
    birthPlace: 'Jerusalém',
    deathPlace: 'Jerusalém',
    country: 'Palestina',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Jerusalém'],
    biographyShort: 'São Macário foi bispo de Jerusalém no século IV. Participou do Concílio de Niceia e supervisionou a construção da Basílica do Santo Sepulcro.',
    biographyFull: 'São Macário foi bispo de Jerusalém de aproximadamente 312 até sua morte em 335. Foi um dos padres do Concílio de Niceia em 325, onde defendeu a fé ortodoxa contra o arianismo.\n\nSob seu episcopado e com o apoio do imperador Constantino e de Santa Helena, foram descobertas as relíquias da Verdadeira Cruz e construída a Basílica do Santo Sepulcro sobre o local da crucificação e ressurreição de Cristo.\n\nSeu legado perdura na importância dos Lugares Santos para a cristandade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São Sofrônio de Jerusalém',
    slug: 'sao-sofronio-de-jerusalem',
    feastMonth: 3,
    feastDay: 11,
    birthDate: '560-01-01',
    deathDate: '638-03-11',
    birthPlace: 'Damasco',
    deathPlace: 'Jerusalém',
    country: 'Palestina',
    century: 7,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Jerusalém'],
    biographyShort: 'São Sofrônio foi patriarca de Jerusalém no século VII, defensor da fé contra o monotelismo. Testemunhou a conquista de Jerusalém pelos muçulmanos em 637.',
    biographyFull: 'São Sofrônio nasceu em Damasco por volta de 560. Monge erudito, viajou pelo Egito e pela Palestina antes de ser eleito patriarca de Jerusalém em 634.\n\nCombateu vigorosamente a heresia monotelita, que negava a vontade humana de Cristo. Escreveu uma carta sinodal enviada ao Papa Honório I, reafirmando a doutrina das duas vontades em Cristo.\n\nEm 637, negociou pessoalmente a rendição de Jerusalém ao califa Omar, garantindo a proteção dos cristãos e dos lugares santos. Faleceu pouco depois, em 638.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São Luís Orione',
    slug: 'sao-luis-orione',
    feastMonth: 3,
    feastDay: 12,
    birthDate: '1872-06-23',
    deathDate: '1940-03-12',
    birthPlace: 'Pontecurone',
    deathPlace: 'Sanremo',
    country: 'Itália',
    century: 20,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['jovens abandonados', 'deficientes'],
    biographyShort: 'São Luís Orione foi um sacerdote italiano que fundou a Pequena Obra da Divina Providência, dedicada ao cuidado de órfãos, deficientes e marginalizados.',
    biographyFull: 'São Luís Orione nasceu em 1872 em Pontecurone, Piemonte, numa família pobre. Foi aluno de Dom Bosco e ordenou-se sacerdote em 1895.\n\nFundou a Pequena Obra da Divina Providência, que incluía congregações masculinas e femininas dedicadas à educação de jovens e ao cuidado de pessoas com deficiência. Sua obra espalhou-se pela América Latina, especialmente Argentina e Brasil.\n\nFaleceu em 1940 em Sanremo. Seu corpo foi encontrado incorrupto. Foi canonizado por Bento XVI em 2004.',
    biographyKids: null,
    quotes: [{ text: 'Só a caridade salvará o mundo.', source: 'São Luís Orione' }],
    prayer: null,
    imageUrl: null,
    latitude: 44.9617,
    longitude: 8.9967,
  },
  {
    name: 'Santa Eufrásia',
    slug: 'santa-eufrasia',
    feastMonth: 3,
    feastDay: 13,
    birthDate: '1877-10-17',
    deathDate: '1952-08-29',
    birthPlace: 'Kattoor',
    deathPlace: 'Aranattukara',
    country: 'Índia',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['Congregação das Irmãs da Mãe do Carmelo'],
    biographyShort: 'Santa Eufrásia Eluvathingal foi uma carmelita indiana conhecida como "Mãe que Reza", célebre por sua vida de intensa oração e serviço aos pobres em Kerala.',
    biographyFull: 'Santa Eufrásia nasceu Rosa Eluvathingal em 1877 em Kattoor, Kerala, Índia. Desde criança mostrou vocação religiosa e entrou para a Congregação das Irmãs da Mãe do Carmelo.\n\nConhecida como "Mãe que Reza", passava longas horas em adoração eucarística e oferecia sua vida pelos pecadores. Apesar de viver recolhida, muitos a procuravam para conselho espiritual.\n\nFaleceu em 1952 e foi canonizada pelo Papa Francisco em 2014, tornando-se uma das primeiras santas da Igreja Siro-Malabar.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 10.5276,
    longitude: 76.2144,
  },
  {
    name: 'Santa Matilde',
    slug: 'santa-matilde',
    feastMonth: 3,
    feastDay: 14,
    birthDate: '895-01-01',
    deathDate: '968-03-14',
    birthPlace: 'Enger',
    deathPlace: 'Quedlinburgo',
    country: 'Alemanha',
    century: 10,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['viúvas', 'mães de família numerosa'],
    biographyShort: 'Santa Matilde foi rainha da Germânia, esposa de Henrique I. Após enviuvar, dedicou-se à fundação de mosteiros e ao cuidado dos pobres, suportando a ingratidão dos filhos.',
    biographyFull: 'Santa Matilde nasceu por volta de 895 na Saxônia. Casou-se com Henrique I, duque da Saxônia, que se tornou rei da Germânia. Tiveram cinco filhos, entre eles o futuro imperador Otão I.\n\nApós a morte do marido em 936, foi perseguida pelos próprios filhos, que cobiçavam os bens que ela distribuía aos pobres. Suportou tudo com paciência, até que se reconciliaram.\n\nFundou diversos mosteiros e hospitais. Faleceu em 968 no convento de Quedlinburgo, junto ao túmulo do marido.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.789,
    longitude: 11.15,
  },
  {
    name: 'São Clemente Maria Hofbauer',
    slug: 'sao-clemente-maria-hofbauer',
    feastMonth: 3,
    feastDay: 15,
    birthDate: '1751-12-26',
    deathDate: '1820-03-15',
    birthPlace: 'Tasovice',
    deathPlace: 'Viena',
    country: 'Áustria',
    century: 19,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Viena', 'padeiros'],
    biographyShort: 'São Clemente Maria Hofbauer foi um redentorista tcheco-austríaco que evangelizou Varsóvia e Viena. É considerado o segundo fundador da Congregação do Santíssimo Redentor ao norte dos Alpes.',
    biographyFull: 'São Clemente nasceu em 1751 em Tasovice, Morávia. Trabalhou como padeiro antes de entrar para os Redentoristas em Roma. Foi enviado a Varsóvia, onde trabalhou por 20 anos evangelizando e cuidando dos pobres.\n\nExpulso de Varsóvia por Napoleão em 1808, estabeleceu-se em Viena, onde se tornou influente pregador e confessor. Combateu o josefinismo e o racionalismo iluminista, renovando a vida católica na capital austríaca.\n\nFaleceu em 1820 e foi canonizado em 1909. É padroeiro de Viena.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.2082,
    longitude: 16.3738,
  },
  {
    name: 'São Heriberdo de Colônia',
    slug: 'sao-heriberdo-de-colonia',
    feastMonth: 3,
    feastDay: 16,
    birthDate: '970-01-01',
    deathDate: '1021-03-16',
    birthPlace: 'Worms',
    deathPlace: 'Colônia',
    country: 'Alemanha',
    century: 11,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Colônia', 'contra a seca'],
    biographyShort: 'São Heriberdo foi arcebispo de Colônia e chanceler do imperador Otão III. Destacou-se pela caridade aos pobres e pela construção de igrejas e mosteiros.',
    biographyFull: 'São Heriberdo nasceu por volta de 970 em Worms, Alemanha. Educado em Gorze e Lobbes, tornou-se chanceler do imperador Otão III e, em 999, arcebispo de Colônia.\n\nApesar das responsabilidades políticas, dedicou-se intensamente ao cuidado pastoral. Fundou o mosteiro de Deutz e era conhecido por distribuir alimentos aos pobres diariamente.\n\nSegundo a tradição, obteve chuva por meio de suas orações durante uma seca devastadora. Faleceu em 1021 e foi canonizado em 1075.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.9375,
    longitude: 6.9603,
  },
  {
    name: 'São Patrício',
    slug: 'sao-patricio',
    feastMonth: 3,
    feastDay: 17,
    birthDate: '385-01-01',
    deathDate: '461-03-17',
    birthPlace: 'Bannavem Taburniae',
    deathPlace: 'Saul',
    country: 'Irlanda',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Irlanda', 'engenheiros'],
    biographyShort: 'São Patrício é o apóstolo da Irlanda, que evangelizou a ilha no século V. Capturado como escravo na juventude, retornou anos depois como missionário e converteu o país ao cristianismo.',
    biographyFull: 'São Patrício nasceu na Britânia romana por volta de 385. Aos 16 anos foi capturado por piratas irlandeses e escravizado como pastor por seis anos, período em que se converteu profundamente.\n\nApós fugir e retornar à Britânia, sentiu o chamado para evangelizar a Irlanda. Ordenado bispo, retornou à ilha por volta de 432 e dedicou-se à conversão dos chefes tribais e do povo, usando o trevo para explicar a Santíssima Trindade.\n\nFundou igrejas, mosteiros e escolas por toda a Irlanda. Faleceu por volta de 461 e é celebrado no mundo inteiro em 17 de março.',
    biographyKids: null,
    quotes: [{ text: 'Cristo comigo, Cristo diante de mim, Cristo atrás de mim, Cristo em mim.', source: 'Lorica de São Patrício' }],
    prayer: null,
    imageUrl: null,
    latitude: 54.3409,
    longitude: -5.7217,
  },
  {
    name: 'São Cirilo de Jerusalém',
    slug: 'sao-cirilo-de-jerusalem',
    feastMonth: 3,
    feastDay: 18,
    birthDate: '313-01-01',
    deathDate: '386-03-18',
    birthPlace: 'Jerusalém',
    deathPlace: 'Jerusalém',
    country: 'Palestina',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['catequistas'],
    biographyShort: 'São Cirilo foi bispo de Jerusalém e Doutor da Igreja, autor das célebres Catequeses. Exilado três vezes por defender a fé contra o arianismo.',
    biographyFull: 'São Cirilo nasceu por volta de 313, provavelmente em Jerusalém. Foi ordenado bispo da cidade em 350, enfrentando desde o início a oposição dos arianos.\n\nSuas 24 Catequeses, dirigidas aos catecúmenos e neófitos, são uma das mais importantes fontes sobre a liturgia e a doutrina da Igreja primitiva. Foi exilado três vezes de sua sé por imperadores arianos.\n\nRestabelecido definitivamente em 378, participou do Concílio de Constantinopla em 381. Faleceu em 386 e foi declarado Doutor da Igreja por Leão XIII em 1882.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São José',
    slug: 'sao-jose',
    feastMonth: 3,
    feastDay: 19,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Belém',
    deathPlace: 'Nazaré',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['trabalhadores', 'pais de família', 'Igreja Universal'],
    biographyShort: 'São José foi o esposo da Virgem Maria e pai adotivo de Jesus Cristo. Homem justo e silencioso, é padroeiro da Igreja Universal e dos trabalhadores.',
    biographyFull: 'São José, da casa de Davi, foi escolhido por Deus para ser o esposo da Virgem Maria e guardar o mistério da Encarnação. Carpinteiro de ofício, sustentou a Sagrada Família com seu trabalho em Nazaré.\n\nOs Evangelhos o descrevem como "homem justo": aceitou em silêncio a missão de proteger Maria e Jesus, guiado pelos anjos em sonhos. Fugiu com a família para o Egito, escapando da perseguição de Herodes.\n\nÉ padroeiro da Igreja Universal (desde 1870), dos trabalhadores e da boa morte. Sua festa em 19 de março é uma das mais celebradas do calendário católico.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.7015,
    longitude: 35.2979,
  },
  {
    name: 'São Martinho de Braga',
    slug: 'sao-martinho-de-braga',
    feastMonth: 3,
    feastDay: 20,
    birthDate: '520-01-01',
    deathDate: '580-03-20',
    birthPlace: 'Panônia',
    deathPlace: 'Braga',
    country: 'Portugal',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Braga'],
    biographyShort: 'São Martinho de Braga foi um monge da Panônia que evangelizou os suevos no noroeste da Península Ibérica e tornou-se bispo de Braga no século VI.',
    biographyFull: 'São Martinho nasceu por volta de 520 na Panônia (atual Hungria). Peregrinou pela Terra Santa antes de se estabelecer na Galiza, onde converteu o povo suevo do arianismo ao catolicismo.\n\nFundou o mosteiro de Dume e foi nomeado bispo de Braga. Presidiu concílios e escreveu obras de moral e catequese, como "De correctione rusticorum", combatendo superstições pagãs.\n\nFaleceu por volta de 580. É considerado o apóstolo dos suevos e uma das figuras mais importantes do cristianismo na Península Ibérica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.5518,
    longitude: -8.4229,
  },
  {
    name: 'São Nicolau de Flüe',
    slug: 'sao-nicolau-de-flue',
    feastMonth: 3,
    feastDay: 21,
    birthDate: '1417-03-21',
    deathDate: '1487-03-21',
    birthPlace: 'Flüeli-Ranft',
    deathPlace: 'Flüeli-Ranft',
    country: 'Suíça',
    century: 15,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['Suíça', 'paz'],
    biographyShort: 'São Nicolau de Flüe foi um fazendeiro, soldado e magistrado suíço que, aos 50 anos, tornou-se eremita. Seu conselho evitou uma guerra civil na Suíça.',
    biographyFull: 'São Nicolau nasceu em 1417 em Flüeli-Ranft, cantão de Obwalden, Suíça. Casou-se, teve dez filhos e serviu como soldado e juiz. Aos 50 anos, com o consentimento da esposa, retirou-se para uma vida de eremita.\n\nViveu 19 anos em jejum absoluto, alimentando-se apenas da Eucaristia, fato atestado por testemunhas. Em 1481, sua mediação na Dieta de Stans impediu uma guerra civil entre os cantões suíços.\n\nFaleceu em 1487, no dia de seu 70º aniversário. É padroeiro da Suíça, canonizado em 1947.',
    biographyKids: null,
    quotes: [{ text: 'A paz está sempre em Deus, pois Deus é a paz.', source: 'São Nicolau de Flüe' }],
    prayer: null,
    imageUrl: null,
    latitude: 46.88,
    longitude: 8.265,
  },
  {
    name: 'Santa Lea de Roma',
    slug: 'santa-lea-de-roma',
    feastMonth: 3,
    feastDay: 22,
    birthDate: null,
    deathDate: '384-03-22',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['viúvas'],
    biographyShort: 'Santa Lea foi uma nobre romana que, após enviuvar, abandonou a vida mundana e tornou-se superiora de um mosteiro. São Jerônimo elogiou sua santidade em uma carta célebre.',
    biographyFull: 'Santa Lea viveu em Roma no século IV. Após a morte do marido, renunciou à riqueza e às honras da sociedade romana para consagrar-se a Deus num mosteiro.\n\nTornou-se superiora de sua comunidade, vivendo com extrema austeridade: vestia roupas ásperas, dormia no chão e dedicava-se à oração e ao serviço das irmãs.\n\nSão Jerônimo escreveu uma carta (Ep. 23) em seu louvor, contrastando sua morte santa com a do cônsul Pretextato. Faleceu por volta de 384.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'São Turíbio de Mongrovejo',
    slug: 'sao-turibio-de-mongrovejo',
    feastMonth: 3,
    feastDay: 23,
    birthDate: '1538-11-16',
    deathDate: '1606-03-23',
    birthPlace: 'Mayorga',
    deathPlace: 'Saña',
    country: 'Peru',
    century: 16,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['bispos latino-americanos', 'Peru'],
    biographyShort: 'São Turíbio de Mongrovejo foi arcebispo de Lima no século XVI, grande evangelizador da América do Sul. Percorreu seu imenso território a pé, batizando e catequizando os indígenas.',
    biographyFull: 'São Turíbio nasceu em 1538 em Mayorga, Espanha. Leigo e professor de direito, foi nomeado arcebispo de Lima pelo rei Filipe II, precisando ser ordenado às pressas.\n\nNo Peru, percorreu três vezes sua imensa arquidiocese a pé ou em lombo de mula, aprendendo línguas indígenas para catequizar. Defendeu os direitos dos índios contra os abusos dos colonizadores e convocou concílios que organizaram a Igreja na América do Sul.\n\nBatizou e crismou, entre outros, Santa Rosa de Lima e São Martinho de Porres. Faleceu em 1606, durante uma de suas visitas pastorais.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    name: 'São Óscar Romero',
    slug: 'sao-oscar-romero',
    feastMonth: 3,
    feastDay: 24,
    birthDate: '1917-08-15',
    deathDate: '1980-03-24',
    birthPlace: 'Ciudad Barrios',
    deathPlace: 'San Salvador',
    country: 'El Salvador',
    century: 20,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['El Salvador', 'perseguidos pela fé'],
    biographyShort: 'São Óscar Romero foi arcebispo de San Salvador, assassinado enquanto celebrava a Missa em 1980. Tornou-se voz dos pobres e oprimidos, denunciando a violência e a injustiça.',
    biographyFull: 'São Óscar Arnulfo Romero nasceu em 1917 em Ciudad Barrios, El Salvador. Ordenado sacerdote em Roma, foi nomeado arcebispo de San Salvador em 1977, quando o país vivia grave crise política e social.\n\nA morte de seu amigo, o padre Rutílio Grande, assassinado por esquadrões da morte, transformou-o. Passou a denunciar corajosamente as violações de direitos humanos, tornando-se voz dos pobres e marginalizados.\n\nFoi assassinado a tiros enquanto celebrava a Missa em 24 de março de 1980. Canonizado pelo Papa Francisco em 2018, é símbolo da luta pela justiça na América Latina.',
    biographyKids: null,
    quotes: [{ text: 'Se me matam, ressuscitarei no povo salvadorenho.', source: 'São Óscar Romero' }],
    prayer: null,
    imageUrl: null,
    latitude: 13.6929,
    longitude: -88.1733,
  },
  {
    name: 'Anunciação do Senhor',
    slug: 'anunciacao-do-senhor',
    feastMonth: 3,
    feastDay: 25,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['vocações', 'maternidade'],
    biographyShort: 'A Anunciação celebra o momento em que o Anjo Gabriel anunciou a Maria que ela conceberia o Filho de Deus. Com seu "sim", a Encarnação do Verbo tornou-se realidade.',
    biographyFull: 'A Solenidade da Anunciação do Senhor celebra o evento narrado no Evangelho de Lucas (1,26-38): o Anjo Gabriel foi enviado por Deus a Nazaré para anunciar à Virgem Maria que ela conceberia pelo Espírito Santo o Salvador do mundo.\n\nMaria respondeu com fé e obediência: "Eis a serva do Senhor, faça-se em mim segundo a tua palavra." Nesse instante, o Verbo se fez carne, dando início ao mistério da Encarnação.\n\nCelebrada em 25 de março, exatamente nove meses antes do Natal, esta festa une a alegria da maternidade divina de Maria ao início da redenção da humanidade.',
    biographyKids: null,
    quotes: [{ text: 'Eis a serva do Senhor, faça-se em mim segundo a tua palavra.', source: 'Lucas 1,38' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.7015,
    longitude: 35.2979,
  },
  {
    name: 'São Bráulio de Saragoça',
    slug: 'sao-braulio-de-saragoca',
    feastMonth: 3,
    feastDay: 26,
    birthDate: '585-01-01',
    deathDate: '651-03-26',
    birthPlace: 'Saragoça',
    deathPlace: 'Saragoça',
    country: 'Espanha',
    century: 7,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Saragoça', 'universidades de Aragão'],
    biographyShort: 'São Bráulio foi bispo de Saragoça no século VII, discípulo de Santo Isidoro de Sevilha. Destacou-se como escritor, organizador das Etimologias e pastor zeloso.',
    biographyFull: 'São Bráulio nasceu por volta de 585 em Saragoça, Espanha. Estudou com Santo Isidoro de Sevilha em Sevilha e sucedeu seu irmão João como bispo de Saragoça em 631.\n\nFoi responsável por organizar e dividir em 20 livros as célebres Etimologias de Santo Isidoro, a grande enciclopédia medieval. Participou de vários concílios de Toledo e deixou uma rica correspondência.\n\nFaleceu em 651, sendo venerado como um dos mais importantes bispos da Espanha visigótica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.6488,
    longitude: -0.8891,
  },
  {
    name: 'São Ruperto de Salzburgo',
    slug: 'sao-ruperto-de-salzburgo',
    feastMonth: 3,
    feastDay: 27,
    birthDate: '660-01-01',
    deathDate: '710-03-27',
    birthPlace: 'Worms',
    deathPlace: 'Salzburgo',
    country: 'Áustria',
    century: 8,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Salzburgo', 'mineradores de sal'],
    biographyShort: 'São Ruperto foi bispo missionário que evangelizou a Baviera e fundou a cidade de Salzburgo. Estabeleceu mosteiros e desenvolveu as minas de sal da região.',
    biographyFull: 'São Ruperto nasceu por volta de 660, possivelmente em Worms, na Renânia. De origem franca e nobre, foi bispo de Worms antes de partir em missão para a Baviera.\n\nConvidado pelo duque Teodão II, evangelizou a região do Danúbio e estabeleceu-se em Juvavum, que rebatizou de Salzburgo ("cidade do sal"). Fundou o mosteiro de São Pedro e o convento de Nonnberg.\n\nDesenvolveu as minas de sal da região, trazendo prosperidade ao local. Faleceu por volta de 710 e é padroeiro de Salzburgo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.8095,
    longitude: 13.055,
  },
  {
    name: 'São Sisto III',
    slug: 'sao-sisto-iii',
    feastMonth: 3,
    feastDay: 28,
    birthDate: null,
    deathDate: '440-08-19',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 5,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['diocese de Roma'],
    biographyShort: 'São Sisto III foi Papa de 432 a 440, consolidando as definições do Concílio de Éfeso. Reconstruiu a Basílica de Santa Maria Maior em Roma.',
    biographyFull: 'São Sisto III foi eleito Papa em 432, logo após o Concílio de Éfeso (431), que definira Maria como Mãe de Deus (Theotókos). Trabalhou para aplicar e consolidar as decisões conciliares.\n\nSua maior realização foi a reconstrução da Basílica de Santa Maria Maior, adornada com magníficos mosaicos que celebravam a maternidade divina de Maria, visíveis até hoje.\n\nManteve a unidade da Igreja em tempos de controvérsias cristológicas. Faleceu em 440, sucedido por São Leão Magno.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Santa Gladys',
    slug: 'santa-gladys',
    feastMonth: 3,
    feastDay: 29,
    birthDate: '450-01-01',
    deathDate: '500-01-01',
    birthPlace: 'País de Gales',
    deathPlace: 'País de Gales',
    country: 'País de Gales',
    century: 6,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['conversão dos pecadores'],
    biographyShort: 'Santa Gladys foi uma princesa galesa do século V-VI, esposa do rei Gwynllyw. Após uma vida mundana, converteu-se e viveu como eremita com o marido.',
    biographyFull: 'Santa Gladys, também conhecida como Gwladys, foi uma princesa galesa filha do rei Brychan. Casou-se com Gwynllyw, rei de Gwynllwg, que era conhecido como guerreiro violento.\n\nSob a influência do filho, São Cadoc, ambos os esposos converteram-se e abandonaram a vida da corte. Viveram como eremitas em penitência e oração nas colinas do País de Gales.\n\nApós a morte do marido, Gladys continuou sua vida de solidão e ascese. É venerada como santa na tradição galesa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.5882,
    longitude: -3.0222,
  },
  {
    name: 'São João Clímaco',
    slug: 'sao-joao-climaco',
    feastMonth: 3,
    feastDay: 30,
    birthDate: '579-01-01',
    deathDate: '649-03-30',
    birthPlace: 'Palestina',
    deathPlace: 'Monte Sinai',
    country: 'Egito',
    century: 7,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'vida contemplativa'],
    biographyShort: 'São João Clímaco foi abade do Mosteiro de Santa Catarina no Monte Sinai e autor da "Escada do Paraíso", clássico da espiritualidade cristã sobre os graus da perfeição.',
    biographyFull: 'São João nasceu por volta de 579, provavelmente na Palestina. Aos 16 anos entrou para o mosteiro do Monte Sinai, onde viveu como cenobita e depois como eremita por 40 anos numa gruta próxima.\n\nEscreveu a célebre obra "Escada do Paraíso" (Klimax, de onde vem seu sobrenome), que descreve 30 degraus de virtude que o monge deve subir para alcançar a perfeição. O livro tornou-se leitura obrigatória nos mosteiros orientais.\n\nFoi eleito abade do mosteiro do Sinai em idade avançada. Faleceu por volta de 649, venerado tanto no Oriente quanto no Ocidente.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 28.5562,
    longitude: 33.976,
  },
  {
    name: 'São Benjamim',
    slug: 'sao-benjamim',
    feastMonth: 3,
    feastDay: 31,
    birthDate: null,
    deathDate: '424-01-01',
    birthPlace: 'Pérsia',
    deathPlace: 'Pérsia',
    country: 'Pérsia',
    century: 5,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['evangelizadores', 'pregadores'],
    biographyShort: 'São Benjamim foi um diácono persa martirizado no século V por se recusar a parar de pregar o Evangelho. Foi empalado após um ano de prisão.',
    biographyFull: 'São Benjamim era diácono na Pérsia durante a perseguição do rei Iezdegerdes I, que desencadeou uma violenta campanha contra os cristãos no início do século V.\n\nPreso por pregar a fé cristã, ficou encarcerado por um ano. Ao ser libertado com a condição de não mais evangelizar, recusou-se, declarando que não podia calar a verdade de Cristo.\n\nFoi novamente preso e martirizado por empalamento, por volta de 424. Seu testemunho é exemplo de fidelidade à missão evangelizadora mesmo diante da morte.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.6546,
    longitude: 51.668,
  },
];
