import type { SaintSeedData } from './types';

export const maySaints: SaintSeedData[] = [
  {
    name: 'São José Operário',
    slug: 'sao-jose-operario',
    feastMonth: 5,
    feastDay: 1,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['trabalhadores', 'operários'],
    biographyShort: 'São José, esposo da Virgem Maria e pai adotivo de Jesus, é venerado como modelo de trabalho humilde e honesto. Sua festa em 1º de maio foi instituída por Pio XII em 1955 como padroeiro dos trabalhadores.',
    biographyFull: 'São José era carpinteiro em Nazaré e sustentou a Sagrada Família com o trabalho de suas mãos. A Igreja o apresenta como modelo de dignidade no trabalho, unindo fé e vida cotidiana.\n\nO Papa Pio XII instituiu a festa de São José Operário em 1º de maio de 1955, contrapondo o sentido cristão do trabalho às ideologias materialistas. José santificou o labor diário pelo amor a Deus e à sua família.\n\nSua devoção cresceu ao longo dos séculos, sendo declarado padroeiro da Igreja Universal por Pio IX em 1870. É invocado pelos trabalhadores de todo o mundo como intercessor e exemplo de vida justa.',
    biographyKids: null,
    quotes: [{ text: 'José, filho de Davi, não temas receber Maria, tua esposa.', source: 'Mt 1,20' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.6996,
    longitude: 35.3035,
  },
  {
    name: 'Santo Atanásio',
    slug: 'santo-atanasio',
    feastMonth: 5,
    feastDay: 2,
    birthDate: '296-01-01',
    deathDate: '373-05-02',
    birthPlace: 'Alexandria',
    deathPlace: 'Alexandria',
    country: 'Egito',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['teólogos', 'ortodoxia da fé'],
    biographyShort: 'Santo Atanásio foi bispo de Alexandria e grande defensor da divindade de Cristo contra a heresia ariana. Doutor da Igreja, sofreu cinco exílios por sua fidelidade à fé ortodoxa.',
    biographyFull: 'Atanásio nasceu em Alexandria, no Egito, por volta de 296. Participou do Concílio de Niceia em 325 como diácono e tornou-se bispo de Alexandria em 328, dedicando-se ao combate do arianismo.\n\nEnfrentou cinco exílios por defender que Cristo é verdadeiro Deus, consubstancial ao Pai. Sua obra "Sobre a Encarnação do Verbo" é um dos textos teológicos mais importantes da patrística.\n\nFaleceu em 373 e foi proclamado Doutor da Igreja. É considerado o pilar da ortodoxia cristã e patrono dos que defendem a verdade da fé.',
    biographyKids: null,
    quotes: [{ text: 'Deus se fez homem para que o homem se tornasse Deus.', source: 'Sobre a Encarnação do Verbo' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.2001,
    longitude: 29.9187,
  },
  {
    name: 'São Filipe e São Tiago',
    slug: 'sao-filipe-e-sao-tiago',
    feastMonth: 5,
    feastDay: 3,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Betsaida',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['apóstolos', 'Uruguai'],
    biographyShort: 'Filipe e Tiago Menor são apóstolos de Jesus celebrados juntos pela tradição litúrgica. Filipe evangelizou a Ásia Menor e Tiago foi o primeiro bispo de Jerusalém.',
    biographyFull: 'São Filipe, natural de Betsaida, foi um dos primeiros discípulos chamados por Jesus. No Evangelho de João, é ele quem apresenta Natanael ao Senhor e quem pede: "Mostra-nos o Pai".\n\nSão Tiago, chamado Menor, era parente de Jesus e tornou-se líder da comunidade cristã de Jerusalém. É autor da Epístola de Tiago e foi martirizado por volta do ano 62.\n\nA Igreja celebra os dois apóstolos juntos desde a dedicação da Basílica dos Doze Apóstolos em Roma, onde suas relíquias foram depositadas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.9075,
    longitude: 35.6311,
  },
  {
    name: 'São Floriano',
    slug: 'sao-floriano',
    feastMonth: 5,
    feastDay: 4,
    birthDate: '250-01-01',
    deathDate: '304-05-04',
    birthPlace: 'Aelium Cetium',
    deathPlace: 'Lorch',
    country: 'Áustria',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['bombeiros', 'contra incêndios'],
    biographyShort: 'São Floriano foi oficial do exército romano na província de Nórica. Martirizado em 304 por se recusar a perseguir cristãos, é padroeiro dos bombeiros.',
    biographyFull: 'Floriano nasceu por volta de 250 em Aelium Cetium, atual Sankt Pölten, na Áustria. Era oficial do exército romano e converteu-se ao cristianismo em segredo.\n\nDurante a perseguição de Diocleciano, apresentou-se voluntariamente ao governador Aquilino para defender os cristãos presos. Foi torturado e lançado ao rio Enns com uma pedra ao pescoço em 304.\n\nSeu culto espalhou-se pela Europa Central e é invocado contra incêndios e inundações. É padroeiro da Áustria, da Polônia e dos bombeiros em diversos países.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.2082,
    longitude: 14.2389,
  },
  {
    name: 'Santo Ângelo de Sicília',
    slug: 'santo-angelo-de-sicilia',
    feastMonth: 5,
    feastDay: 5,
    birthDate: '1185-01-01',
    deathDate: '1220-05-05',
    birthPlace: 'Jerusalém',
    deathPlace: 'Licata',
    country: 'Itália',
    century: 13,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Licata', 'convertidos'],
    biographyShort: 'Santo Ângelo foi um dos primeiros carmelitas, nascido em Jerusalém de pais judeus convertidos. Foi assassinado em Licata, na Sicília, enquanto pregava contra a heresia.',
    biographyFull: 'Ângelo nasceu em Jerusalém por volta de 1185, filho de judeus convertidos ao cristianismo. Ingressou na Ordem do Carmo no Monte Carmelo e dedicou-se à pregação e à contemplação.\n\nViajou à Sicília para evangelizar e combater heresias. Em Licata, foi atacado e mortalmente ferido por um homem que vivia em pecado público e que Ângelo havia repreendido.\n\nSeu martírio em 1220 consolidou sua fama de santidade. É um dos primeiros santos da Ordem Carmelita e é venerado especialmente na Sicília.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 37.1023,
    longitude: 13.9406,
  },
  {
    name: 'São Domingos Sávio',
    slug: 'sao-domingos-savio',
    feastMonth: 5,
    feastDay: 6,
    birthDate: '1842-04-02',
    deathDate: '1857-03-09',
    birthPlace: 'Riva di Chieri',
    deathPlace: 'Mondonio',
    country: 'Itália',
    century: 19,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['jovens', 'coroinhas'],
    biographyShort: 'São Domingos Sávio foi aluno de Dom Bosco e modelo de santidade juvenil. Faleceu aos 14 anos, tendo vivido com extraordinária pureza e fervor espiritual.',
    biographyFull: 'Domingos Sávio nasceu em 1842 em Riva di Chieri, Itália. Aos 12 anos tornou-se aluno do Oratório de Dom Bosco em Turim, onde se destacou pela piedade e pelo desejo ardente de santidade.\n\nFundou a Companhia da Imaculada entre os colegas e vivia segundo o lema: "A morte, mas não o pecado". Sua saúde frágil agravou-se rapidamente com uma doença pulmonar.\n\nFaleceu em 9 de março de 1857, aos 14 anos, pronunciando palavras de alegria. Foi canonizado por Pio XII em 1954, tornando-se um dos mais jovens santos não mártires da Igreja.',
    biographyKids: null,
    quotes: [{ text: 'A morte, mas não o pecado.', source: 'Lema pessoal' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.0156,
    longitude: 7.8553,
  },
  {
    name: 'Santa Rosa Venerini',
    slug: 'santa-rosa-venerini',
    feastMonth: 5,
    feastDay: 7,
    birthDate: '1656-02-09',
    deathDate: '1728-05-07',
    birthPlace: 'Viterbo',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 18,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['educadoras', 'professoras'],
    biographyShort: 'Santa Rosa Venerini fundou as Mestras Pias Venerini, dedicando sua vida à educação feminina na Itália. Foi pioneira na instrução religiosa e acadêmica das mulheres.',
    biographyFull: 'Rosa Venerini nasceu em 1656 em Viterbo, Itália. Após a morte do noivo e do pai, começou a reunir mulheres para rezar o Rosário e percebeu a necessidade urgente de educação feminina.\n\nEm 1685, abriu sua primeira escola gratuita para meninas em Viterbo. Apesar de oposição e dificuldades, fundou mais de quarenta escolas pela Itália, formando a congregação das Mestras Pias Venerini.\n\nFaleceu em Roma em 1728. Foi canonizada por Bento XVI em 2006, sendo reconhecida como pioneira da educação feminina católica na Itália.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.4174,
    longitude: 12.1046,
  },
  {
    name: 'Nossa Senhora de Luján',
    slug: 'nossa-senhora-de-lujan',
    feastMonth: 5,
    feastDay: 8,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Argentina',
    century: 17,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Argentina', 'Uruguai'],
    biographyShort: 'Nossa Senhora de Luján é a padroeira da Argentina, Uruguai e Paraguai. Sua devoção nasceu em 1630, quando uma imagem de terracota se recusou milagrosamente a prosseguir viagem.',
    biographyFull: 'Em 1630, uma pequena imagem de Nossa Senhora da Conceição era transportada de Buenos Aires ao interior. Ao chegar às margens do rio Luján, os bois pararam e se recusaram a seguir, mesmo após retirada de toda a carga, exceto a imagem.\n\nO fato foi interpretado como sinal divino e a imagem permaneceu ali, onde se ergueu uma capela. A devoção cresceu rapidamente, atraindo peregrinos de toda a região.\n\nA Basílica de Luján, concluída em 1935, é o maior santuário mariano da Argentina. Nossa Senhora de Luján foi proclamada padroeira da Argentina, Uruguai e Paraguai.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: -34.5703,
    longitude: -59.1050,
  },
  {
    name: 'São Pacômio',
    slug: 'sao-pacomio',
    feastMonth: 5,
    feastDay: 9,
    birthDate: '292-01-01',
    deathDate: '348-05-09',
    birthPlace: 'Tebaida',
    deathPlace: 'Tebaida',
    country: 'Egito',
    century: 4,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['monges', 'vida comunitária'],
    biographyShort: 'São Pacômio é o fundador do monaquismo cenobítico cristão, criando a primeira regra para vida monástica em comunidade. Seus mosteiros no Egito reuniram milhares de monges.',
    biographyFull: 'Pacômio nasceu por volta de 292 na Tebaida, Egito. Soldado pagão, converteu-se ao cristianismo após conhecer a caridade dos cristãos e tornou-se discípulo do eremita Palamão.\n\nPor volta de 320, fundou o primeiro mosteiro cenobítico em Tabennisi, estabelecendo uma regra de vida comunitária com oração, trabalho e obediência. Antes dele, os monges viviam isolados como eremitas.\n\nSua regra influenciou São Basílio e São Bento, moldando toda a tradição monástica ocidental e oriental. Ao morrer em 348, seus mosteiros contavam com milhares de monges e monjas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 26.1,
    longitude: 32.3,
  },
  {
    name: 'São João de Ávila',
    slug: 'sao-joao-de-avila',
    feastMonth: 5,
    feastDay: 10,
    birthDate: '1500-01-06',
    deathDate: '1569-05-10',
    birthPlace: 'Almodóvar del Campo',
    deathPlace: 'Montilla',
    country: 'Espanha',
    century: 16,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['sacerdotes diocesanos', 'clero secular espanhol'],
    biographyShort: 'São João de Ávila, o "Apóstolo da Andaluzia", foi mestre espiritual de grandes santos como Teresa de Ávila e João da Cruz. Foi declarado Doutor da Igreja por Bento XVI em 2012.',
    biographyFull: 'João de Ávila nasceu em 1500 em Almodóvar del Campo, Espanha. Estudou em Salamanca e Alcalá, ordenou-se sacerdote e tornou-se pregador itinerante pela Andaluzia, convertendo multidões.\n\nFoi conselheiro espiritual de Santa Teresa de Ávila, São João da Cruz, São Francisco de Bórgia e São João de Deus. Escreveu o "Audi, Filia", obra clássica de espiritualidade, e promoveu a reforma do clero.\n\nFaleceu em 1569 em Montilla. Foi canonizado em 1970 e declarado Doutor da Igreja em 2012, reconhecido como mestre da vida espiritual sacerdotal.',
    biographyKids: null,
    quotes: [{ text: 'Quem tem a Deus, nada lhe falta; quem não tem a Deus, nada possui.', source: 'Audi, Filia' }],
    prayer: null,
    imageUrl: null,
    latitude: 38.7,
    longitude: -4.17,
  },
  {
    name: 'São Mamerto',
    slug: 'sao-mamerto',
    feastMonth: 5,
    feastDay: 11,
    birthDate: null,
    deathDate: '475-05-11',
    birthPlace: null,
    deathPlace: 'Vienne',
    country: 'França',
    century: 5,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['contra calamidades', 'proteção das colheitas'],
    biographyShort: 'São Mamerto foi bispo de Vienne, na França, no século V. É conhecido por instituir as Rogações, três dias de orações e jejum antes da Ascensão para implorar proteção divina.',
    biographyFull: 'Mamerto foi bispo de Vienne, na Gália, em meados do século V. Enfrentou terremotos, incêndios e ataques de animais selvagens que aterrorizavam a população.\n\nDiante dessas calamidades, instituiu as Rogações: três dias de procissões penitenciais, orações e jejum antes da festa da Ascensão. A prática espalhou-se por toda a Igreja do Ocidente.\n\nFaleceu por volta de 475 e é lembrado como pastor zeloso que uniu seu povo pela oração em tempos de adversidade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.5254,
    longitude: 4.8784,
  },
  {
    name: 'São Pancrácio',
    slug: 'sao-pancracio',
    feastMonth: 5,
    feastDay: 12,
    birthDate: '289-01-01',
    deathDate: '304-05-12',
    birthPlace: 'Frígia',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['crianças', 'contra falsos juramentos'],
    biographyShort: 'São Pancrácio foi um jovem mártir romano, decapitado aos 14 anos durante a perseguição de Diocleciano. É um dos santos mais venerados da Roma antiga.',
    biographyFull: 'Pancrácio nasceu na Frígia por volta de 289. Órfão, foi levado a Roma por um tio, onde ambos se converteram ao cristianismo e foram batizados.\n\nDurante a perseguição de Diocleciano, Pancrácio foi preso e levado ao imperador. Apesar de sua juventude, recusou-se a sacrificar aos deuses pagãos e foi decapitado na Via Aurélia em 304, com apenas 14 anos.\n\nUma basílica foi erguida sobre seu túmulo em Roma, e seu nome deu origem à famosa estação ferroviária de Londres, St Pancras. É invocado contra falsos juramentos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.8972,
    longitude: 12.4533,
  },
  {
    name: 'Nossa Senhora de Fátima',
    slug: 'nossa-senhora-de-fatima',
    feastMonth: 5,
    feastDay: 13,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Portugal',
    century: 20,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Portugal', 'paz no mundo'],
    biographyShort: 'Nossa Senhora de Fátima apareceu a três pastorinhos em 1917 na Cova da Iria, Portugal. Pediu oração, penitência e a consagração da Rússia ao seu Imaculado Coração.',
    biographyFull: 'Em 13 de maio de 1917, a Virgem Maria apareceu a Lúcia, Francisco e Jacinta na Cova da Iria, em Fátima, Portugal. As aparições repetiram-se no dia 13 de cada mês até outubro.\n\nNossa Senhora pediu a reza diária do Rosário, penitência pelos pecadores e a devoção ao seu Imaculado Coração. Revelou três segredos, incluindo visões do inferno e profecias sobre guerras mundiais.\n\nO Milagre do Sol, em 13 de outubro de 1917, foi testemunhado por cerca de 70 mil pessoas. Fátima tornou-se um dos maiores santuários marianos do mundo, visitado por milhões de peregrinos anualmente.',
    biographyKids: null,
    quotes: [{ text: 'Rezem o Terço todos os dias para alcançar a paz no mundo.', source: 'Mensagem de Fátima' }],
    prayer: null,
    imageUrl: null,
    latitude: 39.6316,
    longitude: -8.6742,
  },
  {
    name: 'São Matias Apóstolo',
    slug: 'sao-matias-apostolo',
    feastMonth: 5,
    feastDay: 14,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Judeia',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['carpinteiros', 'alfaiates'],
    biographyShort: 'São Matias foi escolhido por sorteio para substituir Judas Iscariotes no colégio dos Doze Apóstolos. Havia acompanhado Jesus desde o batismo até a Ascensão.',
    biographyFull: 'Após a Ascensão de Jesus e a traição de Judas, os apóstolos reuniram-se para escolher um substituto. Matias e José Barsabás foram apresentados como candidatos, ambos tendo seguido Jesus desde o início.\n\nA escolha foi feita por sorteio, e Matias foi agregado aos Onze apóstolos, conforme narrado em Atos dos Apóstolos 1,15-26. A tradição afirma que pregou na Judeia e na Etiópia.\n\nSegundo diversas tradições, foi martirizado por lapidação ou crucificação. Suas relíquias são veneradas na Abadia de São Matias em Tréveris, Alemanha.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'Santo Isidoro Lavrador',
    slug: 'santo-isidoro-lavrador',
    feastMonth: 5,
    feastDay: 15,
    birthDate: '1070-01-01',
    deathDate: '1130-05-15',
    birthPlace: 'Madri',
    deathPlace: 'Madri',
    country: 'Espanha',
    century: 12,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['agricultores', 'lavradores'],
    biographyShort: 'Santo Isidoro Lavrador foi um camponês de Madri que santificou o trabalho agrícola com oração constante. É padroeiro dos agricultores e da cidade de Madri.',
    biographyFull: 'Isidoro nasceu em Madri por volta de 1070, numa família humilde. Trabalhou como lavrador para o senhor Juan de Vargas, dedicando-se à oração antes e durante o trabalho.\n\nSegundo a tradição, anjos aravam em seu lugar enquanto ele rezava, e uma fonte brotou milagrosamente da terra ao golpe de sua vara. Casou-se com Santa Maria de la Cabeza, e juntos viveram em santidade.\n\nFaleceu em 1130 e seu corpo foi encontrado incorrupto. Foi canonizado em 1622 por Gregório XV junto com Teresa de Ávila, Inácio de Loyola, Francisco Xavier e Filipe Neri.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    name: 'São Simão Stock',
    slug: 'sao-simao-stock',
    feastMonth: 5,
    feastDay: 16,
    birthDate: '1165-01-01',
    deathDate: '1265-05-16',
    birthPlace: 'Aylesford',
    deathPlace: 'Bordéus',
    country: 'Inglaterra',
    century: 13,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Ordem Carmelita', 'devoção ao Escapulário'],
    biographyShort: 'São Simão Stock foi prior geral dos carmelitas e recebeu o Escapulário de Nossa Senhora do Carmo em uma visão. Reorganizou a Ordem adaptando-a à vida no Ocidente.',
    biographyFull: 'Simão nasceu em Aylesford, Inglaterra, por volta de 1165. Segundo a tradição, viveu como eremita no tronco de um carvalho antes de ingressar na Ordem Carmelita.\n\nComo prior geral a partir de 1247, transformou os carmelitas de eremitas orientais em ordem mendicante ocidental. A tradição relata que Nossa Senhora lhe apareceu entregando o Santo Escapulário com a promessa de proteção especial.\n\nFaleceu em Bordéus em 1265. A devoção ao Escapulário do Carmo, associada à sua visão, tornou-se uma das práticas marianas mais difundidas na Igreja Católica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.3100,
    longitude: 0.4900,
  },
  {
    name: 'São Pascoal Bailão',
    slug: 'sao-pascoal-bailao',
    feastMonth: 5,
    feastDay: 17,
    birthDate: '1540-05-16',
    deathDate: '1592-05-17',
    birthPlace: 'Torre Hermosa',
    deathPlace: 'Vila Real',
    country: 'Espanha',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['congressos eucarísticos', 'cozinheiros'],
    biographyShort: 'São Pascoal Bailão foi um frade franciscano espanhol de extraordinária devoção eucarística. Foi declarado padroeiro dos congressos e associações eucarísticas por Leão XIII.',
    biographyFull: 'Pascoal nasceu em 1540 em Torre Hermosa, Aragão. Pastor de ovelhas na juventude, aprendeu a ler sozinho e passava horas em oração diante de igrejas onde se celebrava a Missa.\n\nIngressou nos franciscanos alcantarinos em 1564, servindo como porteiro e cozinheiro. Sua devoção à Eucaristia era extraordinária: passava noites inteiras em adoração e defendeu a presença real contra calvinistas na França, arriscando a vida.\n\nFaleceu em 17 de maio de 1592 em Vila Real, durante a elevação da Hóstia na Missa. Foi canonizado em 1690 e declarado padroeiro das associações eucarísticas por Leão XIII em 1897.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.75,
    longitude: -1.65,
  },
  {
    name: 'São João I',
    slug: 'sao-joao-i',
    feastMonth: 5,
    feastDay: 18,
    birthDate: '470-01-01',
    deathDate: '526-05-18',
    birthPlace: 'Toscana',
    deathPlace: 'Ravena',
    country: 'Itália',
    century: 6,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['papas', 'mártires da liberdade religiosa'],
    biographyShort: 'São João I foi papa de 523 a 526 e o primeiro pontífice a visitar Constantinopla. Morreu prisioneiro do rei ariano Teodorico por defender a fé católica.',
    biographyFull: 'João nasceu na Toscana por volta de 470 e tornou-se papa em 523. O rei ostrogodo Teodorico, que era ariano, enviou-o a Constantinopla para negociar com o imperador Justino I em favor dos arianos.\n\nEm Constantinopla, João foi recebido com grandes honras e coroou o imperador, sendo o primeiro papa a visitar o Oriente. Porém, não obteve todas as concessões exigidas por Teodorico.\n\nAo retornar, Teodorico, furioso, prendeu-o em Ravena, onde João morreu de fome e maus-tratos em 526. É venerado como mártir e defensor da liberdade da Igreja.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.4184,
    longitude: 12.2035,
  },
  {
    name: 'São Pedro Celestino',
    slug: 'sao-pedro-celestino',
    feastMonth: 5,
    feastDay: 19,
    birthDate: '1215-01-01',
    deathDate: '1296-05-19',
    birthPlace: 'Isernia',
    deathPlace: 'Fumone',
    country: 'Itália',
    century: 13,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['eremitas', 'fabricantes de livros'],
    biographyShort: 'São Pedro Celestino foi um eremita eleito papa em 1294 como Celestino V. Renunciou ao papado após cinco meses, sendo o caso mais célebre de renúncia papal até Bento XVI.',
    biographyFull: 'Pedro do Morrone nasceu em 1215 em Isernia, no sul da Itália. Viveu como eremita nos montes Abruzos e fundou a congregação dos Celestinos, ramo beneditino de vida austera.\n\nEm 1294, após dois anos de conclave sem resultado, foi eleito papa aos 79 anos, tomando o nome de Celestino V. Inexperiente em política, percebeu-se manipulado e renunciou após cinco meses, declarando sua incapacidade.\n\nSeu sucessor, Bonifácio VIII, temendo cisma, manteve-o preso no castelo de Fumone, onde morreu em 1296. Foi canonizado em 1313 por Clemente V.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.5961,
    longitude: 14.2333,
  },
  {
    name: 'São Bernardino de Sena',
    slug: 'sao-bernardino-de-sena',
    feastMonth: 5,
    feastDay: 20,
    birthDate: '1380-09-08',
    deathDate: '1444-05-20',
    birthPlace: 'Massa Marittima',
    deathPlace: 'Áquila',
    country: 'Itália',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['publicitários', 'pregadores'],
    biographyShort: 'São Bernardino de Sena foi o maior pregador franciscano do século XV, famoso por difundir a devoção ao Santo Nome de Jesus. Percorreu toda a Itália pregando a multidões.',
    biographyFull: 'Bernardino nasceu em 1380 em Massa Marittima, Itália. Ingressou nos franciscanos observantes em 1402 e tornou-se pregador itinerante, percorrendo a Itália a pé durante mais de trinta anos.\n\nPopularizou o monograma IHS (o Santo Nome de Jesus) em placas douradas, exibindo-as ao final de seus sermões. Suas pregações ao ar livre reuniam milhares de ouvintes e promoviam reconciliações entre facções rivais.\n\nRecusou três bispados para continuar pregando. Faleceu em Áquila em 1444 e foi canonizado apenas seis anos depois, em 1450, por Nicolau V.',
    biographyKids: null,
    quotes: [{ text: 'O Nome de Jesus é o esplendor dos pregadores e a luz do mundo.', source: 'Sermão sobre o Santo Nome' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.0167,
    longitude: 11.2833,
  },
  {
    name: 'Santo Eugênio de Mazenod',
    slug: 'santo-eugenio-de-mazenod',
    feastMonth: 5,
    feastDay: 21,
    birthDate: '1782-08-01',
    deathDate: '1861-05-21',
    birthPlace: 'Aix-en-Provence',
    deathPlace: 'Marselha',
    country: 'França',
    century: 19,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Oblatos de Maria Imaculada', 'missões'],
    biographyShort: 'Santo Eugênio de Mazenod fundou os Missionários Oblatos de Maria Imaculada, dedicados à evangelização dos mais pobres. Como bispo de Marselha, renovou a vida da Igreja.',
    biographyFull: 'Eugênio nasceu em 1782 em Aix-en-Provence, numa família nobre. Exilado durante a Revolução Francesa, retornou à França e ordenou-se sacerdote em 1811, dedicando-se aos pobres e prisioneiros.\n\nEm 1816, fundou os Missionários Oblatos de Maria Imaculada para evangelizar os mais abandonados. Como bispo de Marselha a partir de 1837, construiu paróquias, acolheu imigrantes e enviou missionários ao Canadá e à África.\n\nFaleceu em 1861 dizendo: "Praticai entre vós a caridade". Foi canonizado por João Paulo II em 1995, reconhecido como apóstolo dos pobres e pai dos oblatos.',
    biographyKids: null,
    quotes: [{ text: 'Praticai entre vós a caridade, a caridade!', source: 'Últimas palavras' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.2965,
    longitude: 5.3698,
  },
  {
    name: 'Santa Rita de Cássia',
    slug: 'santa-rita-de-cassia',
    feastMonth: 5,
    feastDay: 22,
    birthDate: '1381-01-01',
    deathDate: '1457-05-22',
    birthPlace: 'Roccaporena',
    deathPlace: 'Cássia',
    country: 'Itália',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['causas impossíveis', 'mulheres maltratadas'],
    biographyShort: 'Santa Rita de Cássia é a santa das causas impossíveis. Esposa, mãe e depois religiosa agostiniana, recebeu na fronte um espinho da coroa de Cristo.',
    biographyFull: 'Rita nasceu em 1381 em Roccaporena, Itália. Casou-se contra sua vontade com um homem violento, mas pela paciência e oração conseguiu convertê-lo. Após o assassinato do marido e a morte dos dois filhos, ingressou no convento agostiniano de Cássia.\n\nNa vida religiosa, destacou-se pela penitência e contemplação da Paixão de Cristo. Em 1443, recebeu na fronte a marca de um espinho, ferida que permaneceu aberta até sua morte.\n\nFaleceu em 1457, e seu corpo permanece incorrupto em Cássia. Foi canonizada em 1900 e é uma das santas mais populares do catolicismo, invocada nas causas humanamente impossíveis.',
    biographyKids: null,
    quotes: [{ text: 'Senhor, fazei-me instrumento de vossa paz.', source: 'Oração atribuída' }],
    prayer: null,
    imageUrl: null,
    latitude: 42.7195,
    longitude: 13.0120,
  },
  {
    name: 'São João Batista de Rossi',
    slug: 'sao-joao-batista-de-rossi',
    feastMonth: 5,
    feastDay: 23,
    birthDate: '1698-02-22',
    deathDate: '1764-05-23',
    birthPlace: 'Voltaggio',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 18,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['doentes mentais', 'sem-teto'],
    biographyShort: 'São João Batista de Rossi foi um sacerdote romano que dedicou sua vida ao atendimento dos pobres, mendigos e doentes mentais nas ruas de Roma.',
    biographyFull: 'João Batista nasceu em 1698 em Voltaggio, Ligúria. Ordenado sacerdote em Roma, dedicou-se ao apostolado entre os mais marginalizados: mendigos, doentes mentais e mulheres abandonadas.\n\nTrabalhou no hospício de Santa Gala e percorria as ruas de Roma à noite acolhendo os sem-teto. Apesar de sofrer de epilepsia, nunca diminuiu seu zelo pastoral, confessando por longas horas e pregando incansavelmente.\n\nFaleceu em 1764 em extrema pobreza, tendo dado tudo aos necessitados. Foi canonizado por Leão XIII em 1881.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Nossa Senhora Auxiliadora',
    slug: 'nossa-senhora-auxiliadora',
    feastMonth: 5,
    feastDay: 24,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Itália',
    century: 19,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['salesianos', 'educação cristã'],
    biographyShort: 'Nossa Senhora Auxiliadora é título mariano popularizado por São João Bosco no século XIX. É padroeira da família salesiana e dos cristãos perseguidos.',
    biographyFull: 'O título "Auxiliadora dos Cristãos" remonta à vitória de Lepanto em 1571 e à libertação de Pio VII do cativeiro napoleônico em 1814, quando a festa foi instituída por Pio VII em 24 de maio.\n\nSão João Bosco tornou-se o grande apóstolo desta devoção, construindo a Basílica de Maria Auxiliadora em Turim, inaugurada em 1868. Dom Bosco atribuía à Virgem Auxiliadora todas as graças de sua obra educativa.\n\nA devoção espalhou-se pelo mundo através dos salesianos. Na América Latina, Nossa Senhora Auxiliadora é venerada com particular fervor, sendo padroeira de diversas dioceses e instituições.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.0703,
    longitude: 7.6869,
  },
  {
    name: 'São Beda Venerável',
    slug: 'sao-beda-veneravel',
    feastMonth: 5,
    feastDay: 25,
    birthDate: '672-01-01',
    deathDate: '735-05-25',
    birthPlace: 'Monkton',
    deathPlace: 'Jarrow',
    country: 'Inglaterra',
    century: 8,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['historiadores', 'escritores'],
    biographyShort: 'São Beda Venerável foi monge beneditino e o maior erudito da Inglaterra anglo-saxã. Doutor da Igreja, escreveu a "História Eclesiástica do Povo Inglês".',
    biographyFull: 'Beda nasceu em 672 na Nortúmbria, Inglaterra. Entregue ao mosteiro de Wearmouth-Jarrow aos sete anos, ali permaneceu toda a vida, dedicando-se à oração, ao estudo e ao ensino.\n\nEscreveu mais de sessenta obras sobre teologia, história, ciências naturais e cronologia. Sua "História Eclesiástica do Povo Inglês" é a principal fonte sobre a cristianização da Inglaterra. Popularizou a datação "antes e depois de Cristo".\n\nFaleceu em 735, ditando a tradução do Evangelho de João até seu último suspiro. Foi declarado Doutor da Igreja por Leão XIII em 1899.',
    biographyKids: null,
    quotes: [{ text: 'Orar, trabalhar, ler e ensinar: esta é a vida perfeita do monge.', source: 'Atribuída a São Beda' }],
    prayer: null,
    imageUrl: null,
    latitude: 54.9783,
    longitude: -1.4900,
  },
  {
    name: 'São Filipe Neri',
    slug: 'sao-filipe-neri',
    feastMonth: 5,
    feastDay: 26,
    birthDate: '1515-07-21',
    deathDate: '1595-05-26',
    birthPlace: 'Florença',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 16,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Roma', 'humoristas'],
    biographyShort: 'São Filipe Neri, o "Apóstolo de Roma", fundou a Congregação do Oratório. Conhecido por sua alegria contagiante, renovou a vida espiritual de Roma no século XVI.',
    biographyFull: 'Filipe nasceu em 1515 em Florença. Aos 18 anos mudou-se para Roma, onde viveu como leigo por muitos anos, catequizando nas ruas e visitando doentes nos hospitais. Ordenou-se sacerdote aos 36 anos.\n\nFundou a Congregação do Oratório em 1575, reunindo sacerdotes seculares para oração, pregação e música sacra. Sua abordagem pastoral era marcada pela alegria, pelo humor e pela amizade pessoal com cada penitente.\n\nConfessava por horas diárias e atraía pessoas de todas as classes sociais. Faleceu em 1595 e foi canonizado em 1622. É chamado "segundo apóstolo de Roma" por ter transformado a vida espiritual da cidade.',
    biographyKids: null,
    quotes: [{ text: 'A alegria cristã é um dom de Deus que vem de uma boa consciência.', source: 'Máximas de São Filipe Neri' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.8992,
    longitude: 12.4731,
  },
  {
    name: 'Santo Agostinho de Cantuária',
    slug: 'santo-agostinho-de-cantuaria',
    feastMonth: 5,
    feastDay: 27,
    birthDate: null,
    deathDate: '604-05-26',
    birthPlace: 'Roma',
    deathPlace: 'Canterbury',
    country: 'Inglaterra',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Inglaterra', 'diocese de Canterbury'],
    biographyShort: 'Santo Agostinho de Cantuária foi monge beneditino enviado pelo Papa Gregório Magno para evangelizar a Inglaterra. Tornou-se o primeiro arcebispo de Canterbury em 597.',
    biographyFull: 'Agostinho era prior do mosteiro beneditino de Santo André, em Roma, quando o Papa Gregório Magno o enviou com quarenta monges para evangelizar os anglo-saxões em 596.\n\nChegou ao reino de Kent em 597 e foi acolhido pelo rei Etelberto, cuja esposa Berta era cristã. Em pouco tempo, o rei e milhares de súditos receberam o batismo. Agostinho estabeleceu sua sede em Canterbury.\n\nFundou igrejas e mosteiros, organizou a hierarquia eclesiástica na Inglaterra e ordenou bispos para Londres e Rochester. Faleceu em 604, sendo venerado como o apóstolo da Inglaterra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.2802,
    longitude: 1.0789,
  },
  {
    name: 'São Germano de Paris',
    slug: 'sao-germano-de-paris',
    feastMonth: 5,
    feastDay: 28,
    birthDate: '496-01-01',
    deathDate: '576-05-28',
    birthPlace: 'Autun',
    deathPlace: 'Paris',
    country: 'França',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Paris', 'prisioneiros'],
    biographyShort: 'São Germano foi bispo de Paris no século VI, conselheiro dos reis merovíngios. A famosa abadia de Saint-Germain-des-Prés leva seu nome.',
    biographyFull: 'Germano nasceu em Autun por volta de 496. Ordenado sacerdote e depois abade de São Sinforiano, foi nomeado bispo de Paris em 555 pelo rei Childeberto I.\n\nComo bispo, combateu a simonia, cuidou dos pobres e prisioneiros, e tentou pacificar os conflitos entre os reis merovíngios. Apesar de viver na corte, manteve vida austera de oração e penitência.\n\nFaleceu em 576 e foi sepultado na basílica que se tornaria a célebre Abadia de Saint-Germain-des-Prés, um dos mais antigos monumentos de Paris.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    name: 'Santa Úrsula Ledóchowska',
    slug: 'santa-ursula-ledochowska',
    feastMonth: 5,
    feastDay: 29,
    birthDate: '1865-04-17',
    deathDate: '1939-05-29',
    birthPlace: 'Loosdorf',
    deathPlace: 'Roma',
    country: 'Polônia',
    century: 20,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['Ursulinas do Sagrado Coração Agonizante', 'educação'],
    biographyShort: 'Santa Úrsula Ledóchowska fundou as Ursulinas do Coração de Jesus Agonizante, dedicadas à educação e missões. Trabalhou na Escandinávia, Rússia e Polônia.',
    biographyFull: 'Júlia Maria nasceu em 1865 em Loosdorf, Áustria, numa família nobre polonesa. Ingressou nas Ursulinas em Cracóvia e tornou-se superiora. Em 1907, foi enviada à Rússia para dirigir um internato em São Petersburgo.\n\nApós a Revolução Russa, refugiou-se na Escandinávia, onde trabalhou com órfãos e refugiados. Em 1920, fundou as Ursulinas do Coração de Jesus Agonizante, voltadas para a educação e o apostolado missionário.\n\nEstabeleceu casas na Polônia, Itália e França. Faleceu em Roma em 1939 e foi canonizada por Bento XVI em 2003, reconhecida por sua alegria e criatividade apostólica.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.0647,
    longitude: 19.9450,
  },
  {
    name: 'Santa Joana d\'Arc',
    slug: 'santa-joana-darc',
    feastMonth: 5,
    feastDay: 30,
    birthDate: '1412-01-06',
    deathDate: '1431-05-30',
    birthPlace: 'Domrémy',
    deathPlace: 'Ruão',
    country: 'França',
    century: 15,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['França', 'soldados'],
    biographyShort: 'Santa Joana d\'Arc, a Donzela de Orléans, liderou o exército francês guiada por vozes celestes durante a Guerra dos Cem Anos. Foi queimada viva aos 19 anos e canonizada em 1920.',
    biographyFull: 'Joana nasceu em 1412 em Domrémy, uma aldeia francesa. Aos 13 anos começou a ouvir as vozes de São Miguel, Santa Catarina e Santa Margarida, que lhe ordenaram libertar a França dos ingleses e conduzir o Delfim à coroação.\n\nEm 1429, aos 17 anos, liderou o exército francês na libertação de Orléans e conduziu Carlos VII à coroação em Reims. Capturada pelos borguinhões, foi vendida aos ingleses e julgada por um tribunal eclesiástico corrupto.\n\nCondenada por heresia e feitiçaria, foi queimada viva em Ruão em 30 de maio de 1431, aos 19 anos. Seu processo foi anulado em 1456 e foi canonizada em 1920 por Bento XV, tornando-se padroeira da França.',
    biographyKids: null,
    quotes: [{ text: 'Não tenho medo; para isto nasci.', source: 'Atribuída a Joana d\'Arc' }],
    prayer: null,
    imageUrl: null,
    latitude: 48.4431,
    longitude: 5.1727,
  },
  {
    name: 'Visitação de Nossa Senhora',
    slug: 'visitacao-de-nossa-senhora',
    feastMonth: 5,
    feastDay: 31,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['gestantes', 'visitação aos doentes'],
    biographyShort: 'A Visitação celebra o encontro de Maria com sua prima Isabel, quando o menino João Batista saltou de alegria no ventre materno. Nessa ocasião, Maria proclamou o Magnificat.',
    biographyFull: 'Após a Anunciação, Maria viajou apressadamente às montanhas da Judeia para visitar sua prima Isabel, que estava grávida de João Batista. Ao ouvir a saudação de Maria, o menino saltou no ventre de Isabel, que exclamou: "Bendita és tu entre as mulheres!"\n\nMaria respondeu com o cântico do Magnificat: "Minha alma glorifica o Senhor", um dos textos mais belos da Escritura. Permaneceu com Isabel cerca de três meses, servindo-a até o nascimento de João.\n\nA festa da Visitação celebra a caridade de Maria, que se põe a serviço do próximo, e a alegria do primeiro encontro entre Jesus e seu precursor, ainda no ventre de suas mães.',
    biographyKids: null,
    quotes: [{ text: 'Minha alma glorifica o Senhor e meu espírito exulta em Deus, meu Salvador.', source: 'Lc 1,46-47' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7272,
    longitude: 35.1356,
  },
];
