import type { SaintSeedData } from './types';

export const novemberSaints: SaintSeedData[] = [
  {
    name: 'Todos os Santos',
    slug: 'todos-os-santos',
    feastMonth: 11,
    feastDay: 1,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Igreja universal', 'santos não canonizados'],
    biographyShort:
      'Solenidade que celebra todos os santos conhecidos e desconhecidos, reconhecendo a multidão dos que já alcançaram a glória celeste.',
    biographyFull:
      'A festa de Todos os Santos tem origens no século IV, quando as comunidades cristãs começaram a homenagear coletivamente os mártires. O Papa Bonifácio IV consagrou o Panteão de Roma à Virgem Maria e a todos os mártires em 609.\n\nNo século VIII, o Papa Gregório III fixou a celebração em 1º de novembro, estendendo-a a todos os santos, não apenas aos mártires. O Papa Gregório IV universalizou a festa para toda a Igreja em 835.\n\nA solenidade recorda que a santidade é vocação universal de todos os batizados e celebra a comunhão dos santos que intercedem pela Igreja peregrina na terra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.45,
  },
  {
    name: 'Fiéis Defuntos',
    slug: 'fieis-defuntos',
    feastMonth: 11,
    feastDay: 2,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['almas do purgatório', 'defuntos'],
    biographyShort:
      'Dia dedicado à oração por todos os fiéis falecidos que se purificam antes de entrar na glória eterna.',
    biographyFull:
      'A Comemoração de Todos os Fiéis Defuntos foi instituída pelo abade São Odilo de Cluny em 998, que determinou que todos os mosteiros cluniacenses celebrassem missas pelos defuntos em 2 de novembro.\n\nA prática espalhou-se rapidamente por toda a Igreja ocidental. Fundamenta-se na doutrina do purgatório e na crença de que as orações dos vivos podem auxiliar as almas que se purificam.\n\nNeste dia, os sacerdotes podem celebrar três missas e os fiéis que visitam cemitérios podem lucrar indulgência plenária pelos defuntos. É um dia de esperança na ressurreição e na misericórdia de Deus.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.45,
  },
  {
    name: 'São Martinho de Porres',
    slug: 'sao-martinho-de-porres',
    feastMonth: 11,
    feastDay: 3,
    birthDate: '1579-12-09',
    deathDate: '1639-11-03',
    birthPlace: 'Lima',
    deathPlace: 'Lima',
    country: 'Peru',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['justiça social', 'barbeiros'],
    biographyShort:
      'Irmão leigo dominicano mulato de Lima que dedicou sua vida ao serviço dos pobres e doentes, sendo famoso por seus milagres e caridade heroica.',
    biographyFull:
      'Martinho nasceu em Lima, Peru, em 1579, filho ilegítimo de um nobre espanhol e de uma negra liberta. Sofreu discriminação racial desde a infância. Aprendeu o ofício de barbeiro-cirurgião e ingressou no convento dominicano como terciário.\n\nDedicou-se ao cuidado dos doentes, dos pobres e dos escravos africanos, exercendo uma caridade sem limites. Era dotado de dons extraordinários: bilocação, levitação, curas milagrosas e comunicação com os animais.\n\nFaleceu em 1639, sendo pranteado por toda a cidade de Lima. Foi canonizado por São João XXIII em 1962, tornando-se símbolo da fraternidade e da igualdade racial.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: -12.05,
    longitude: -77.04,
  },
  {
    name: 'São Carlos Borromeu',
    slug: 'sao-carlos-borromeu',
    feastMonth: 11,
    feastDay: 4,
    birthDate: '1538-10-02',
    deathDate: '1584-11-03',
    birthPlace: 'Arona',
    deathPlace: 'Milão',
    country: 'Itália',
    century: 16,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['seminários', 'catequistas'],
    biographyShort:
      'Arcebispo de Milão e figura central da Contra-Reforma, reformou a disciplina eclesiástica e dedicou-se heroicamente aos doentes durante a peste.',
    biographyFull:
      'Carlos nasceu em 1538 na nobre família Borromeu. Sobrinho do Papa Pio IV, foi nomeado cardeal aos 22 anos e desempenhou papel decisivo na conclusão do Concílio de Trento.\n\nComo arcebispo de Milão, implementou rigorosamente as reformas tridentinas: criou seminários, visitou pessoalmente todas as paróquias, reformou conventos e combateu a ignorância religiosa. Durante a grande peste de 1576, cuidou pessoalmente dos doentes.\n\nSua vida austera e seu zelo pastoral tornaram-no modelo para bispos de toda a Igreja. Faleceu em 1584, aos 46 anos, esgotado pelo trabalho. Foi canonizado em 1610.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.76,
    longitude: 8.56,
  },
  {
    name: 'São Guido Maria Conforti',
    slug: 'sao-guido-maria-conforti',
    feastMonth: 11,
    feastDay: 5,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Judeia',
    deathPlace: 'Judeia',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['casais idosos', 'pais'],
    biographyShort:
      'Pais de São João Batista que, apesar da velhice e esterilidade, conceberam por graça divina o precursor de Cristo.',
    biographyFull:
      'Zacarias era sacerdote do Templo de Jerusalém e Isabel, sua esposa, era parenta da Virgem Maria. Ambos eram justos diante de Deus, mas não tinham filhos por causa da esterilidade de Isabel.\n\nDurante o serviço no Templo, o anjo Gabriel apareceu a Zacarias e anunciou o nascimento de um filho que seria "grande diante do Senhor". Zacarias duvidou e ficou mudo até o nascimento de João.\n\nIsabel acolheu Maria durante a Visitação, reconhecendo-a como "Mãe do meu Senhor". Zacarias, ao dar o nome de João ao filho, recuperou a fala e proclamou o cântico do Benedictus.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.72,
    longitude: 35.14,
  },
  {
    name: 'São Leonardo',
    slug: 'sao-leonardo',
    feastMonth: 11,
    feastDay: 6,
    birthDate: null,
    deathDate: '559-01-01',
    birthPlace: 'Orléans',
    deathPlace: 'Noblac',
    country: 'França',
    century: 6,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['prisioneiros', 'parturientes'],
    biographyShort:
      'Eremita francês do século VI que obteve do rei Clóvis o privilégio de libertar prisioneiros, tornando-se padroeiro dos cativos.',
    biographyFull:
      'Leonardo era um nobre franco convertido por São Remígio e afilhado do rei Clóvis. Recusou um bispado e retirou-se para viver como eremita na floresta de Limoges.\n\nClóvis concedeu-lhe o privilégio de libertar prisioneiros que visitasse. Muitos cativos libertos juntaram-se a ele, formando uma comunidade em torno de sua cela, que se tornou a cidade de Saint-Léonard-de-Noblat.\n\nSeu culto espalhou-se por toda a Europa medieval, especialmente após as Cruzadas, quando muitos prisioneiros libertados atribuíram sua soltura à intercessão de São Leonardo. Faleceu por volta de 559.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.84,
    longitude: 1.49,
  },
  {
    name: 'São Vilibrord',
    slug: 'sao-vilibrord',
    feastMonth: 11,
    feastDay: 7,
    birthDate: '658-01-01',
    deathDate: '739-11-07',
    birthPlace: 'Northúmbria',
    deathPlace: 'Echternach',
    country: 'Inglaterra',
    century: 8,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Luxemburgo', 'Países Baixos'],
    biographyShort:
      'Monge anglo-saxão que evangelizou os Países Baixos e tornou-se o primeiro arcebispo de Utrecht, sendo chamado "Apóstolo dos Frísios".',
    biographyFull:
      'Vilibrord nasceu na Northúmbria, Inglaterra, em 658. Formou-se no mosteiro de Ripon e completou seus estudos na Irlanda. Em 690, partiu com onze companheiros para evangelizar os frísios nos Países Baixos.\n\nViajou a Roma, onde o Papa Sérgio I o consagrou arcebispo de Utrecht em 695. Com o apoio dos francos, fundou igrejas, mosteiros e escolas por toda a região.\n\nFundou a abadia de Echternach, no atual Luxemburgo, que se tornou centro de evangelização e cultura. Faleceu em 739 e sua festa é celebrada com grande devoção em Luxemburgo e nos Países Baixos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.81,
    longitude: 6.42,
  },
  {
    name: 'São Godofredo de Amiens',
    slug: 'sao-godofredo-de-amiens',
    feastMonth: 11,
    feastDay: 8,
    birthDate: '1066-01-01',
    deathDate: '1115-11-08',
    birthPlace: 'Soissons',
    deathPlace: 'Soissons',
    country: 'França',
    century: 12,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Amiens', 'contra secas'],
    biographyShort:
      'Bispo reformador de Amiens que combateu a simonia e a imoralidade do clero com firmeza e exemplo de vida austera.',
    biographyFull:
      'Godofredo nasceu em Soissons por volta de 1066. Entrou jovem no mosteiro beneditino de Mont-Saint-Quentin e tornou-se abade de Nogent-sous-Coucy, onde reformou a disciplina monástica.\n\nEm 1104 foi nomeado bispo de Amiens contra sua vontade. Enfrentou forte resistência ao combater a simonia e a indisciplina do clero. Viveu com austeridade extrema, vestindo-se pobremente e doando seus bens aos pobres.\n\nExausto pelas lutas e pela oposição, tentou renunciar ao episcopado e retirar-se à Grande Chartreuse. Faleceu em 1115, sendo reconhecido como modelo de bispo reformador.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.89,
    longitude: 2.30,
  },
  {
    name: 'Dedicação Basílica de São João de Latrão',
    slug: 'dedicacao-basilica-de-sao-joao-de-latrao',
    feastMonth: 11,
    feastDay: 9,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Itália',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['catedral de Roma', 'Igreja universal'],
    biographyShort:
      'Festa litúrgica que celebra a dedicação da catedral do Papa, mãe e cabeça de todas as igrejas do mundo.',
    biographyFull:
      'A Basílica de São João de Latrão foi a primeira igreja pública construída no mundo cristão, doada pelo imperador Constantino ao Papa Milcíades e consagrada por volta de 324.\n\nÉ a catedral do bispo de Roma, ou seja, do Papa, e carrega o título de "mãe e cabeça de todas as igrejas da cidade e do mundo". Precedeu em importância até mesmo a Basílica de São Pedro.\n\nA festa de sua dedicação é celebrada em toda a Igreja como sinal de unidade com a Sé de Roma. A basílica foi reconstruída e restaurada diversas vezes ao longo dos séculos, mantendo sempre sua primazia.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.89,
    longitude: 12.51,
  },
  {
    name: 'São Leão Magno',
    slug: 'sao-leao-magno',
    feastMonth: 11,
    feastDay: 10,
    birthDate: '400-01-01',
    deathDate: '461-11-10',
    birthPlace: 'Toscana',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 5,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['papas', 'contra a heresia'],
    biographyShort:
      'Papa e Doutor da Igreja que definiu a doutrina das duas naturezas de Cristo e salvou Roma do ataque de Átila, o Huno.',
    biographyFull:
      'Leão nasceu na Toscana por volta de 400 e foi eleito Papa em 440. Seu pontificado foi um dos mais importantes da história, consolidando o primado romano e a doutrina cristológica.\n\nNo Concílio de Calcedônia (451), seu "Tomo a Flaviano" definiu a doutrina das duas naturezas de Cristo — divina e humana — unidas numa só pessoa. Os padres conciliares aclamaram: "Pedro falou pela boca de Leão!"\n\nEm 452, saiu ao encontro de Átila e convenceu-o a não invadir Roma. Três anos depois, mitigou o saque da cidade pelos vândalos. Faleceu em 461 e recebeu o título de "Magno" (Grande), um dos poucos papas assim honrados.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.50,
  },
  {
    name: 'São Martinho de Tours',
    slug: 'sao-martinho-de-tours',
    feastMonth: 11,
    feastDay: 11,
    birthDate: '316-01-01',
    deathDate: '397-11-08',
    birthPlace: 'Sabária',
    deathPlace: 'Candes',
    country: 'França',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['soldados', 'mendigos'],
    biographyShort:
      'Soldado romano que partilhou seu manto com um mendigo e viu Cristo vestido com ele, tornando-se monge e bispo de Tours.',
    biographyFull:
      'Martinho nasceu na Panônia (atual Hungria) por volta de 316, filho de um oficial romano. Alistou-se no exército e, numa noite de inverno em Amiens, partilhou seu manto com um mendigo. Naquela noite, viu Cristo vestido com a metade do manto.\n\nBatizou-se, deixou o exército e viveu como eremita. Fundou o mosteiro de Ligugé, o mais antigo da Gália. Em 371, foi aclamado bispo de Tours pelo povo, apesar de sua resistência.\n\nComo bispo, evangelizou as zonas rurais, destruiu templos pagãos e fundou paróquias. Viveu sempre com simplicidade monástica. Faleceu em 397 e seu túmulo em Tours tornou-se o maior centro de peregrinação da Gália.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 47.39,
    longitude: 0.69,
  },
  {
    name: 'São Josafá',
    slug: 'sao-josafa',
    feastMonth: 11,
    feastDay: 12,
    birthDate: '1580-01-01',
    deathDate: '1623-11-12',
    birthPlace: 'Volodymyr',
    deathPlace: 'Vitebsk',
    country: 'Ucrânia',
    century: 17,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Ucrânia', 'unidade dos cristãos'],
    biographyShort:
      'Arcebispo greco-católico de Polotsk martirizado por defender a união de sua Igreja com Roma, primeiro santo oriental canonizado formalmente.',
    biographyFull:
      'João Kuncewicz nasceu em 1580 em Volodymyr, na atual Ucrânia. Ingressou na Ordem de São Basílio e adotou o nome Josafá. Tornou-se fervoroso defensor da União de Brest (1596), que uniu parte da Igreja rutena a Roma.\n\nNomeado arcebispo de Polotsk em 1618, reformou o clero e restaurou a disciplina, enfrentando forte oposição dos que rejeitavam a união com Roma.\n\nEm 1623, uma turba invadiu sua residência em Vitebsk e o assassinou a golpes de machado. Seu corpo foi lançado no rio. Foi canonizado em 1867, primeiro santo da Igreja Oriental a receber canonização formal.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.85,
    longitude: 24.32,
  },
  {
    name: 'Santa Francisca Xavier Cabrini',
    slug: 'santa-francisca-xavier-cabrini',
    feastMonth: 11,
    feastDay: 13,
    birthDate: '1850-07-15',
    deathDate: '1917-12-22',
    birthPlace: 'Sant\'Angelo Lodigiano',
    deathPlace: 'Chicago',
    country: 'Itália',
    century: 20,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['imigrantes', 'órfãos'],
    biographyShort:
      'Religiosa italiana que fundou as Irmãs Missionárias do Sagrado Coração e dedicou sua vida aos imigrantes italianos nos Estados Unidos.',
    biographyFull:
      'Francisca Cabrini nasceu em 1850 na Lombardia, Itália. Sonhava em ser missionária na China, mas o Papa Leão XIII a orientou: "Não ao Oriente, mas ao Ocidente". Partiu para os Estados Unidos em 1889.\n\nFundou a Congregação das Irmãs Missionárias do Sagrado Coração e estabeleceu escolas, hospitais e orfanatos em várias cidades americanas, atendendo os milhares de imigrantes italianos que viviam em condições miseráveis.\n\nNaturalizou-se americana e faleceu em Chicago em 1917. Foi canonizada em 1946, tornando-se a primeira cidadã americana canonizada e padroeira dos imigrantes.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.23,
    longitude: 9.41,
  },
  {
    name: 'São Nicolau Tavelic',
    slug: 'sao-nicolau-tavelic',
    feastMonth: 11,
    feastDay: 14,
    birthDate: '1340-01-01',
    deathDate: '1391-11-14',
    birthPlace: 'Šibenik',
    deathPlace: 'Jerusalém',
    country: 'Croácia',
    century: 14,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Croácia', 'missionários'],
    biographyShort:
      'Frade franciscano croata martirizado em Jerusalém ao tentar pregar o Evangelho aos muçulmanos na Esplanada das Mesquitas.',
    biographyFull:
      'Nicolau nasceu por volta de 1340 em Šibenik, na costa da Dalmácia (atual Croácia). Ingressou na Ordem Franciscana e foi enviado como missionário à Bósnia, onde pregou por vários anos.\n\nEm 1384, partiu para a Terra Santa com três companheiros franciscanos. Ali exerceram o ministério entre os peregrinos cristãos na Custódia da Terra Santa.\n\nEm novembro de 1391, os quatro frades apresentaram-se publicamente na Esplanada das Mesquitas em Jerusalém para pregar o Evangelho. Foram presos, torturados e decapitados. Nicolau Tavelic foi canonizado por Paulo VI em 1970, primeiro santo croata.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.73,
    longitude: 15.90,
  },
  {
    name: 'Santo Alberto Magno',
    slug: 'santo-alberto-magno',
    feastMonth: 11,
    feastDay: 15,
    birthDate: '1200-01-01',
    deathDate: '1280-11-15',
    birthPlace: 'Lauingen',
    deathPlace: 'Colônia',
    country: 'Alemanha',
    century: 13,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['cientistas', 'estudantes de ciências naturais'],
    biographyShort:
      'Dominicano alemão, Doutor da Igreja e mestre de São Tomás de Aquino, chamado "Doutor Universal" por seu vasto conhecimento em filosofia e ciências.',
    biographyFull:
      'Alberto nasceu por volta de 1200 em Lauingen, na Baviera. Ingressou na Ordem Dominicana e estudou em Pádua e Colônia. Tornou-se o maior sábio de seu tempo, dominando teologia, filosofia, botânica, zoologia, química e astronomia.\n\nComo professor em Paris e Colônia, teve como aluno São Tomás de Aquino, a quem reconheceu o gênio e defendeu publicamente. Foi nomeado bispo de Ratisbona, mas renunciou para voltar ao ensino.\n\nIntroduziu o pensamento aristotélico na teologia cristã e insistiu na importância da observação empírica. Faleceu em 1280 e foi declarado Doutor da Igreja e padroeiro dos cientistas em 1931.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.57,
    longitude: 10.43,
  },
  {
    name: 'Santa Margarida da Escócia',
    slug: 'santa-margarida-da-escocia',
    feastMonth: 11,
    feastDay: 16,
    birthDate: '1045-01-01',
    deathDate: '1093-11-16',
    birthPlace: 'Hungria',
    deathPlace: 'Edimburgo',
    country: 'Escócia',
    century: 11,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['Escócia', 'rainhas'],
    biographyShort:
      'Rainha da Escócia que reformou a Igreja escocesa, promoveu a educação e dedicou-se ao serviço dos pobres com exemplar piedade.',
    biographyFull:
      'Margarida nasceu na Hungria por volta de 1045, princesa da casa real anglo-saxã exilada. Após a conquista normanda da Inglaterra, refugiou-se na Escócia, onde casou com o rei Malcolm III.\n\nComo rainha, reformou a Igreja escocesa, alinhando-a com as práticas romanas. Promoveu a educação, construiu igrejas e hospedarias e cuidava pessoalmente dos pobres, lavando os pés de mendigos.\n\nMãe de oito filhos, três dos quais se tornaram reis, faleceu em 1093 ao saber da morte do marido e do filho mais velho em batalha. Foi canonizada em 1250 e é padroeira da Escócia.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 55.95,
    longitude: -3.19,
  },
  {
    name: 'Santa Isabel da Hungria',
    slug: 'santa-isabel-da-hungria',
    feastMonth: 11,
    feastDay: 17,
    birthDate: '1207-07-07',
    deathDate: '1231-11-17',
    birthPlace: 'Bratislava',
    deathPlace: 'Marburgo',
    country: 'Hungria',
    century: 13,
    category: 'LAYPERSON',
    gender: 'FEMALE',
    patronage: ['padeiros', 'obras de caridade'],
    biographyShort:
      'Princesa húngara que, após enviuvar aos 20 anos, dedicou sua vida ao cuidado dos pobres e doentes, falecendo aos 24 anos de caridade heroica.',
    biographyFull:
      'Isabel nasceu em 1207, filha do rei André II da Hungria. Aos 14 anos casou-se com o landgrave Luís IV da Turíngia, com quem viveu um matrimônio feliz e piedoso, tendo três filhos.\n\nApós a morte de Luís nas Cruzadas em 1227, foi expulsa do castelo pela família do marido. Renunciou aos bens, vestiu o hábito franciscano e dedicou-se inteiramente ao cuidado dos pobres e doentes, fundando um hospital em Marburgo.\n\nFaleceu em 1231, aos 24 anos, consumida pelo serviço aos necessitados. Foi canonizada apenas quatro anos depois, em 1235, por Gregório IX. O milagre das rosas é o episódio mais célebre de sua vida.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.14,
    longitude: 17.11,
  },
  {
    name: 'Dedicação Basílicas São Pedro e São Paulo',
    slug: 'dedicacao-basilicas-sao-pedro-e-sao-paulo',
    feastMonth: 11,
    feastDay: 18,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Itália',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['basílicas papais', 'unidade da Igreja'],
    biographyShort:
      'Festa que celebra a dedicação das basílicas construídas sobre os túmulos dos apóstolos Pedro e Paulo em Roma.',
    biographyFull:
      'A Basílica de São Pedro foi construída pelo imperador Constantino sobre o túmulo do apóstolo Pedro na colina do Vaticano, consagrada por volta de 326. A atual basílica renascentista foi consagrada em 1626.\n\nA Basílica de São Paulo Fora dos Muros foi erguida sobre o túmulo de São Paulo na Via Ostiense. Destruída por um incêndio em 1823, foi reconstruída e consagrada em 1854.\n\nA celebração conjunta das duas basílicas recorda a unidade da Igreja fundada sobre o testemunho dos dois grandes apóstolos, pilares da fé cristã em Roma.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.45,
  },
  {
    name: 'São Rafael Kalinowski',
    slug: 'sao-rafael-kalinowski',
    feastMonth: 11,
    feastDay: 19,
    birthDate: '1835-09-01',
    deathDate: '1907-11-15',
    birthPlace: 'Vilnius',
    deathPlace: 'Wadowice',
    country: 'Polônia',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['exilados', 'engenheiros'],
    biographyShort:
      'Engenheiro militar e patriota polonês que, após dez anos de exílio na Sibéria, tornou-se carmelita descalço e restaurou a Ordem na Polônia.',
    biographyFull:
      'José Kalinowski nasceu em 1835 em Vilnius, na Lituânia (então parte da Polônia). Formou-se engenheiro militar e participou da insurreição polonesa de 1863 contra o domínio russo.\n\nCondenado à morte, teve a pena comutada para dez anos de trabalhos forçados na Sibéria. No exílio, aprofundou sua fé e decidiu consagrar-se a Deus. Após a libertação, ingressou no Carmelo em 1877, recebendo o nome Rafael.\n\nDedicou-se à restauração da Ordem Carmelita na Polônia e à direção espiritual. Faleceu em 1907 em Wadowice, cidade natal de São João Paulo II, que o canonizou em 1991.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 54.69,
    longitude: 25.28,
  },
  {
    name: 'São Félix de Valois',
    slug: 'sao-felix-de-valois',
    feastMonth: 11,
    feastDay: 20,
    birthDate: '1127-01-01',
    deathDate: '1212-11-04',
    birthPlace: 'Valois',
    deathPlace: 'Cerfroid',
    country: 'França',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['cativos', 'prisioneiros'],
    biographyShort:
      'Eremita francês que, junto com São João da Mata, fundou a Ordem da Santíssima Trindade para o resgate de cristãos cativos dos muçulmanos.',
    biographyFull:
      'Félix nasceu por volta de 1127, possivelmente aparentado com a família real francesa. Renunciou às honras mundanas e retirou-se para a floresta de Cerfroid, onde viveu como eremita.\n\nSão João da Mata, após sua ordenação sacerdotal, procurou-o para juntos fundarem uma ordem dedicada ao resgate de cristãos prisioneiros dos muçulmanos. Em 1198, o Papa Inocêncio III aprovou a Ordem da Santíssima Trindade.\n\nOs trinitários resgataram milhares de cativos ao longo dos séculos. Félix governou o mosteiro de Cerfroid até sua morte em 1212. Seu culto foi confirmado pela Igreja no século XVII.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.13,
    longitude: 3.16,
  },
  {
    name: 'Apresentação de Nossa Senhora',
    slug: 'apresentacao-de-nossa-senhora',
    feastMonth: 11,
    feastDay: 21,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['vida consagrada', 'crianças'],
    biographyShort:
      'Festa que celebra a apresentação da Virgem Maria no Templo de Jerusalém quando menina, consagrando-se inteiramente a Deus.',
    biographyFull:
      'A festa da Apresentação de Nossa Senhora baseia-se numa tradição do Protoevangelho de Tiago, segundo a qual os pais de Maria, Joaquim e Ana, levaram-na ao Templo de Jerusalém aos três anos de idade para consagrá-la a Deus.\n\nA celebração originou-se no Oriente, onde uma igreja dedicada a Maria foi consagrada em Jerusalém em 543. No Ocidente, foi introduzida no século XIV e confirmada pelo Papa Sisto V em 1585.\n\nA festa convida à reflexão sobre a total disponibilidade de Maria à vontade de Deus desde a infância, modelo para todos os consagrados e consagradas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.77,
    longitude: 35.23,
  },
  {
    name: 'Santa Cecília',
    slug: 'santa-cecilia',
    feastMonth: 11,
    feastDay: 22,
    birthDate: null,
    deathDate: '230-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['músicos', 'cantores'],
    biographyShort:
      'Virgem e mártir romana do século III, padroeira dos músicos, que converteu seu esposo e cunhado antes de ser martirizada por sua fé.',
    biographyFull:
      'Cecília era uma jovem patrícia romana que consagrou sua virgindade a Deus. Obrigada a casar com o pagão Valeriano, convenceu-o a respeitar seu voto e converteu-o ao cristianismo, junto com seu cunhado Tibúrcio.\n\nValeriano e Tibúrcio foram martirizados primeiro. Cecília foi condenada a morrer sufocada nos banhos de sua casa, mas sobreviveu. Um soldado tentou decapitá-la com três golpes, mas ela sobreviveu ainda três dias.\n\nA tradição de que "cantava no coração para o Senhor" em seu casamento fez dela padroeira dos músicos. Sua basílica no Trastevere, em Roma, é uma das mais antigas da cidade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.89,
    longitude: 12.47,
  },
  {
    name: 'São Clemente I',
    slug: 'sao-clemente-i',
    feastMonth: 11,
    feastDay: 23,
    birthDate: null,
    deathDate: '99-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Crimeia',
    country: 'Itália',
    century: 1,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['marinheiros', 'marmoreístas'],
    biographyShort:
      'Terceiro sucessor de São Pedro e Padre Apostólico, autor de uma importante carta à comunidade de Corinto sobre a ordem na Igreja.',
    biographyFull:
      'Clemente foi o quarto Papa da Igreja, governando de aproximadamente 88 a 99. A tradição o identifica como o Clemente mencionado por São Paulo na Carta aos Filipenses (4,3).\n\nSua Carta aos Coríntios, escrita por volta de 96, é o mais antigo documento cristão fora do Novo Testamento. Nela, exorta a comunidade à unidade, à obediência aos presbíteros e à boa ordem eclesiástica.\n\nSegundo a tradição, foi exilado para a Crimeia pelo imperador Trajano e martirizado sendo atirado ao mar com uma âncora presa ao pescoço. A basílica de São Clemente em Roma preserva vestígios desde o século I.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.89,
    longitude: 12.50,
  },
  {
    name: 'Santo André Dung-Lac',
    slug: 'santo-andre-dung-lac',
    feastMonth: 11,
    feastDay: 24,
    birthDate: '1795-01-01',
    deathDate: '1839-12-21',
    birthPlace: 'Bắc Ninh',
    deathPlace: 'Hanói',
    country: 'Vietnã',
    century: 19,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Vietnã', 'perseguidos pela fé'],
    biographyShort:
      'Sacerdote vietnamita martirizado por decapitação, representante dos 117 mártires do Vietnã canonizados em 1988.',
    biographyFull:
      'André Dung-Lac nasceu em 1795 numa família pagã e pobre do Vietnã. Convertido ao catolicismo por catequistas, foi batizado e ordenado sacerdote, destacando-se como pregador zeloso.\n\nDurante as violentas perseguições aos cristãos no Vietnã, foi preso diversas vezes. Os fiéis pagaram resgates para libertá-lo, mas ele foi finalmente preso definitivamente em 1839.\n\nFoi decapitado em Hanói em dezembro de 1839. Em 1988, São João Paulo II canonizou 117 mártires do Vietnã, mortos entre os séculos XVII e XIX, tendo André Dung-Lac como representante principal do grupo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 21.04,
    longitude: 106.07,
  },
  {
    name: 'Santa Catarina de Alexandria',
    slug: 'santa-catarina-de-alexandria',
    feastMonth: 11,
    feastDay: 25,
    birthDate: null,
    deathDate: '305-01-01',
    birthPlace: 'Alexandria',
    deathPlace: 'Alexandria',
    country: 'Egito',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['filósofos', 'estudantes'],
    biographyShort:
      'Virgem e mártir de Alexandria que venceu cinquenta filósofos em debate e foi martirizada na roda dentada durante a perseguição de Maximino.',
    biographyFull:
      'Catarina era uma jovem nobre e culta de Alexandria, no Egito, que se converteu ao cristianismo. Durante a perseguição do imperador Maximino, apresentou-se diante dele e refutou publicamente os argumentos pagãos.\n\nO imperador convocou cinquenta filósofos para debater com ela, mas todos foram convencidos por seus argumentos e se converteram. Furiosa, a imperatriz e o general Porfírio também se converteram ao visitar Catarina na prisão.\n\nCondenada ao suplício da roda dentada, o instrumento se quebrou milagrosamente. Foi então decapitada por volta de 305. Seu culto espalhou-se enormemente na Idade Média e o Mosteiro de Santa Catarina no Sinai guarda suas relíquias.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.20,
    longitude: 29.92,
  },
  {
    name: 'São Silvestre Gozzolini',
    slug: 'sao-silvestre-gozzolini',
    feastMonth: 11,
    feastDay: 26,
    birthDate: '1177-01-01',
    deathDate: '1267-11-26',
    birthPlace: 'Osimo',
    deathPlace: 'Montefano',
    country: 'Itália',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Congregação Silvestrina', 'eremitas'],
    biographyShort:
      'Sacerdote italiano que, após contemplar um cadáver em decomposição, retirou-se ao deserto e fundou a Congregação Beneditina Silvestrina.',
    biographyFull:
      'Silvestre nasceu em 1177 em Osimo, na região das Marcas, Itália. Estudou Direito e Teologia em Bolonha e Pádua, tornando-se cônego da catedral de Osimo.\n\nAo contemplar o cadáver em decomposição de um homem outrora belo, foi profundamente abalado pela vaidade do mundo. Retirou-se para viver como eremita em diversas grutas nas montanhas.\n\nEm 1231, fundou o mosteiro de Montefano, origem da Congregação Beneditina Silvestrina, que seguia a Regra de São Bento com especial ênfase na austeridade e na oração contemplativa. Faleceu em 1267, aos 90 anos. Foi canonizado em 1598.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.49,
    longitude: 13.48,
  },
  {
    name: 'Nossa Senhora das Graças',
    slug: 'nossa-senhora-das-gracas',
    feastMonth: 11,
    feastDay: 27,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'França',
    century: 19,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Medalha Milagrosa', 'conversões'],
    biographyShort:
      'Festa que recorda as aparições da Virgem Maria a Santa Catarina Labouré em Paris, originando a Medalha Milagrosa em 1830.',
    biographyFull:
      'Em 27 de novembro de 1830, a Virgem Maria apareceu à noviça Catarina Labouré na capela da Rue du Bac, em Paris. Maria mostrou-se em pé sobre um globo, com raios de luz saindo de suas mãos, e pediu que se cunhasse uma medalha com aquela imagem.\n\nA medalha trazia a inscrição "Ó Maria concebida sem pecado, rogai por nós que recorremos a Vós". No verso, a letra M encimada pela cruz e os corações de Jesus e Maria.\n\nA medalha espalhou-se rapidamente pelo mundo, acompanhada de numerosas graças e milagres, sendo chamada pelo povo de "Medalha Milagrosa". Catarina manteve segredo sobre as aparições até pouco antes de sua morte.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.85,
    longitude: 2.32,
  },
  {
    name: 'São Tiago da Marca',
    slug: 'sao-tiago-da-marca',
    feastMonth: 11,
    feastDay: 28,
    birthDate: '1393-09-01',
    deathDate: '1476-11-28',
    birthPlace: 'Monteprandone',
    deathPlace: 'Nápoles',
    country: 'Itália',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['contra heresias', 'pregadores'],
    biographyShort:
      'Frade franciscano italiano e pregador itinerante que combateu heresias e fundou os "Montes de Piedade" para ajudar os pobres.',
    biographyFull:
      'Tiago nasceu em 1393 em Monteprandone, nas Marcas italianas. Estudou Direito em Perúgia, mas ingressou na Ordem Franciscana sob a influência de São Bernardino de Sena.\n\nTornou-se um dos maiores pregadores de seu tempo, percorrendo a Itália, a Alemanha, a Hungria e a Bósnia combatendo heresias e promovendo a reforma dos costumes. Os papas confiaram-lhe diversas missões diplomáticas.\n\nFoi pioneiro na criação dos "Montes de Piedade", instituições de crédito para proteger os pobres da usura. Faleceu em Nápoles em 1476 e foi canonizado em 1726.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.94,
    longitude: 13.84,
  },
  {
    name: 'São Saturnino de Toulouse',
    slug: 'sao-saturnino-de-toulouse',
    feastMonth: 11,
    feastDay: 29,
    birthDate: null,
    deathDate: '257-01-01',
    birthPlace: null,
    deathPlace: 'Toulouse',
    country: 'França',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Toulouse', 'toureiros'],
    biographyShort:
      'Primeiro bispo de Toulouse, martirizado ao ser arrastado por um touro selvagem pelas ruas da cidade no século III.',
    biographyFull:
      'Saturnino (ou Sernin) foi enviado a Toulouse como missionário no século III, tornando-se o primeiro bispo da cidade. Evangelizou a região com grande sucesso, convertendo muitos pagãos.\n\nSeu caminho diário passava pelo Capitólio, templo pagão. Os sacerdotes pagãos atribuíram o silêncio de seus oráculos à presença do bispo cristão. Em 257, exigiram que ele sacrificasse aos ídolos.\n\nAo recusar, foi amarrado a um touro selvagem e arrastado pelas escadarias do Capitólio até a morte. A basílica de Saint-Sernin em Toulouse, construída sobre seu túmulo, é uma das maiores igrejas românicas da Europa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.61,
    longitude: 1.44,
  },
  {
    name: 'Santo André Apóstolo',
    slug: 'santo-andre-apostolo',
    feastMonth: 11,
    feastDay: 30,
    birthDate: null,
    deathDate: '60-01-01',
    birthPlace: 'Betsaida',
    deathPlace: 'Patras',
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['pescadores', 'Escócia'],
    biographyShort:
      'Primeiro apóstolo chamado por Jesus, irmão de São Pedro, martirizado numa cruz em forma de X na cidade grega de Patras.',
    biographyFull:
      'André era pescador em Betsaida, na Galileia, e discípulo de João Batista. Foi o primeiro a seguir Jesus e trouxe seu irmão Simão Pedro ao Mestre, sendo por isso chamado "Protokletos" (o primeiro chamado).\n\nApós Pentecostes, segundo a tradição, pregou na Grécia, na Ásia Menor e na região do Mar Negro. É considerado fundador da Igreja de Constantinopla, o que lhe confere posição especial no ecumenismo.\n\nFoi crucificado em Patras, na Grécia, numa cruz em forma de X (cruz de Santo André), por volta do ano 60. É padroeiro da Escócia, da Grécia e da Rússia. Sua festa encerra o Tempo Comum do ano litúrgico.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.91,
    longitude: 35.53,
  },
];
