import type { SaintSeedData } from './types';

export const octoberSaints: SaintSeedData[] = [
  {
    name: 'Santa Teresinha do Menino Jesus',
    slug: 'santa-teresinha-do-menino-jesus',
    feastMonth: 10,
    feastDay: 1,
    birthDate: '1873-01-02',
    deathDate: '1897-09-30',
    birthPlace: 'Alençon',
    deathPlace: 'Lisieux',
    country: 'França',
    century: 19,
    category: 'DOCTOR',
    gender: 'FEMALE',
    patronage: ['missionários', 'floristas'],
    biographyShort:
      'Carmelita francesa que desenvolveu o "Caminho Pequenino" de santidade, tornando-se Doutora da Igreja aos 24 anos de idade.',
    biographyFull:
      'Santa Teresinha nasceu em Alençon, França, em 1873. Desde criança desejava a vida religiosa e entrou no Carmelo de Lisieux aos 15 anos, com dispensa especial.\n\nNo convento, viveu com simplicidade radical, oferecendo pequenos sacrifícios diários por amor a Deus. Desenvolveu a espiritualidade do "Caminho Pequenino", baseada na confiança e no abandono total à misericórdia divina.\n\nFaleceu de tuberculose em 1897, aos 24 anos. Sua autobiografia "História de uma Alma" tornou-se um clássico espiritual. Foi canonizada em 1925 e declarada Doutora da Igreja em 1997.',
    biographyKids: null,
    quotes: [{ text: 'Minha vocação é o amor!', source: 'História de uma Alma' }],
    prayer: null,
    imageUrl: null,
    latitude: 48.75,
    longitude: 0.19,
  },
  {
    name: 'Santos Anjos da Guarda',
    slug: 'santos-anjos-da-guarda',
    feastMonth: 10,
    feastDay: 2,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['policiais', 'segurança'],
    biographyShort:
      'Festa litúrgica que celebra os anjos designados por Deus para proteger e guiar cada pessoa ao longo de sua vida.',
    biographyFull:
      'A devoção aos Anjos da Guarda tem raízes nas Escrituras. Jesus afirmou que as crianças têm anjos que contemplam a face do Pai celeste (Mt 18,10).\n\nDesde os primeiros séculos, a Igreja reconhece que Deus designa anjos para acompanhar, proteger e guiar cada ser humano. A festa foi estabelecida no calendário romano em 1615 pelo Papa Paulo V.\n\nA celebração convida os fiéis a reconhecer a presença amorosa de Deus que, por meio dos anjos, cuida de seus filhos em todos os momentos da vida.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.77,
    longitude: 35.23,
  },
  {
    name: 'São Francisco de Borja',
    slug: 'sao-francisco-de-borja',
    feastMonth: 10,
    feastDay: 3,
    birthDate: '1510-10-28',
    deathDate: '1572-09-30',
    birthPlace: 'Gandia',
    deathPlace: 'Roma',
    country: 'Espanha',
    century: 16,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['contra terremotos', 'nobreza'],
    biographyShort:
      'Duque de Gandia que, ao ver o cadáver desfigurado da imperatriz Isabel, renunciou às vaidades do mundo e tornou-se terceiro Superior Geral dos Jesuítas.',
    biographyFull:
      'Francisco nasceu em Gandia, Espanha, em 1510, bisneto do Papa Alexandre VI e do rei Fernando de Aragão. Serviu na corte de Carlos V e foi nomeado Duque de Gandia.\n\nA morte da imperatriz Isabel em 1539 marcou sua conversão. Ao contemplar seu cadáver desfigurado, jurou nunca mais servir a um senhor que pudesse morrer. Após enviuvar, ingressou na Companhia de Jesus e tornou-se seu terceiro Superior Geral.\n\nComo líder jesuíta, expandiu as missões nas Américas e na Ásia, fundou colégios e reformou a formação dos religiosos. Faleceu em Roma em 1572 e foi canonizado em 1671.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.97,
    longitude: -0.18,
  },
  {
    name: 'São Francisco de Assis',
    slug: 'sao-francisco-de-assis',
    feastMonth: 10,
    feastDay: 4,
    birthDate: '1181-01-01',
    deathDate: '1226-10-03',
    birthPlace: 'Assis',
    deathPlace: 'Assis',
    country: 'Itália',
    century: 13,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['animais', 'ecologia'],
    biographyShort:
      'Filho de rico comerciante italiano que abraçou a pobreza radical, fundou a Ordem Franciscana e recebeu os estigmas de Cristo.',
    biographyFull:
      'Francisco nasceu em Assis, Itália, em 1181, filho de um próspero mercador de tecidos. Após uma juventude mundana e uma experiência de guerra, ouviu o crucifixo de São Damião pedir-lhe que reparasse sua Igreja.\n\nRenunciou a todos os bens diante do bispo, abraçou a pobreza absoluta e começou a pregar o Evangelho. Atraiu seguidores e fundou a Ordem dos Frades Menores, aprovada pelo Papa Inocêncio III em 1209.\n\nEm 1224 recebeu os estigmas no Monte Alverna, primeiro caso documentado na história. Faleceu em 1226 cantando louvores ao Criador. Foi canonizado apenas dois anos depois por Gregório IX.',
    biographyKids: null,
    quotes: [{ text: 'Senhor, fazei-me instrumento de vossa paz.', source: 'Oração atribuída a São Francisco' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.07,
    longitude: 12.62,
  },
  {
    name: 'Santa Faustina Kowalska',
    slug: 'santa-faustina-kowalska',
    feastMonth: 10,
    feastDay: 5,
    birthDate: '1905-08-25',
    deathDate: '1938-10-05',
    birthPlace: 'Głogowiec',
    deathPlace: 'Cracóvia',
    country: 'Polônia',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['devoção à Divina Misericórdia', 'almas sofredoras'],
    biographyShort:
      'Religiosa polonesa que recebeu revelações de Jesus sobre a Divina Misericórdia e registrou-as em seu célebre Diário.',
    biographyFull:
      'Helena Kowalska nasceu em 1905 numa família camponesa polonesa. Desde jovem sentia o chamado à vida religiosa e em 1925 ingressou na Congregação das Irmãs da Mãe de Deus da Misericórdia, recebendo o nome Irmã Faustina.\n\nA partir de 1931, recebeu visões de Jesus que lhe pediu para difundir a devoção à Divina Misericórdia. Registrou tudo em seu Diário, que se tornou um dos textos espirituais mais lidos do século XX.\n\nFaleceu de tuberculose em 1938, aos 33 anos. Foi canonizada por São João Paulo II em 2000, que instituiu o Domingo da Divina Misericórdia no calendário universal.',
    biographyKids: null,
    quotes: [{ text: 'Jesus, eu confio em Vós!', source: 'Diário de Santa Faustina' }],
    prayer: null,
    imageUrl: null,
    latitude: 51.84,
    longitude: 19.86,
  },
  {
    name: 'São Bruno',
    slug: 'sao-bruno',
    feastMonth: 10,
    feastDay: 6,
    birthDate: '1030-01-01',
    deathDate: '1101-10-06',
    birthPlace: 'Colônia',
    deathPlace: 'Serra San Bruno',
    country: 'Alemanha',
    century: 11,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['cartuxos', 'contra possessão demoníaca'],
    biographyShort:
      'Teólogo alemão que abandonou uma brilhante carreira eclesiástica para fundar a Ordem dos Cartuxos, dedicada ao silêncio e à contemplação.',
    biographyFull:
      'Bruno nasceu em Colônia, Alemanha, por volta de 1030. Estudou e lecionou teologia em Reims, onde foi chanceler da diocese e renomado mestre.\n\nEm 1084, retirou-se com seis companheiros para o maciço da Chartreuse, nos Alpes franceses, onde fundou a Ordem dos Cartuxos, consagrada à oração contemplativa e ao silêncio perpétuo.\n\nChamado a Roma pelo Papa Urbano II, seu antigo aluno, recusou dignidades eclesiásticas e retirou-se para a Calábria, onde fundou outro eremitério. Faleceu em 1101 em Serra San Bruno.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.94,
    longitude: 6.96,
  },
  {
    name: 'Nossa Senhora do Rosário',
    slug: 'nossa-senhora-do-rosario',
    feastMonth: 10,
    feastDay: 7,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Nazaré',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['oração do Rosário', 'vitória em batalhas'],
    biographyShort:
      'Festa que celebra a Virgem Maria sob o título do Rosário, instituída após a vitória cristã na Batalha de Lepanto em 1571.',
    biographyFull:
      'A festa de Nossa Senhora do Rosário foi instituída pelo Papa Pio V em 1571 para comemorar a vitória da frota cristã sobre o Império Otomano na Batalha de Lepanto, atribuída à intercessão de Maria pelo Rosário.\n\nA tradição atribui a São Domingos de Gusmão, no século XIII, a difusão do Rosário como forma de meditação dos mistérios da vida de Cristo e de Maria.\n\nO Rosário tornou-se uma das devoções mais populares do catolicismo. Diversos papas o recomendaram, e Nossa Senhora em Fátima pediu sua recitação diária pela paz do mundo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.70,
    longitude: 35.30,
  },
  {
    name: 'Santa Pelágia',
    slug: 'santa-pelagia',
    feastMonth: 10,
    feastDay: 8,
    birthDate: null,
    deathDate: '457-01-01',
    birthPlace: 'Antioquia',
    deathPlace: 'Jerusalém',
    country: 'Israel',
    century: 5,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['atrizes', 'penitentes'],
    biographyShort:
      'Atriz e cortesã de Antioquia que, tocada por um sermão do bispo Nono, converteu-se e viveu como eremita no Monte das Oliveiras.',
    biographyFull:
      'Pelágia era uma célebre atriz e cortesã em Antioquia, conhecida por sua beleza e vida mundana. Ao ouvir um sermão do bispo Nono sobre o juízo final, foi profundamente tocada.\n\nPediu o batismo, distribuiu todos os seus bens aos pobres e partiu em segredo para Jerusalém. Ali, vestida como homem, viveu como eremita numa gruta no Monte das Oliveiras, sendo conhecida como "Pelágio, o monge".\n\nSua verdadeira identidade só foi descoberta após sua morte, por volta de 457. Sua história tornou-se um dos relatos de conversão mais populares da antiguidade cristã.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.78,
    longitude: 35.24,
  },
  {
    name: 'São Denis',
    slug: 'sao-denis',
    feastMonth: 10,
    feastDay: 9,
    birthDate: null,
    deathDate: '272-01-01',
    birthPlace: 'Itália',
    deathPlace: 'Paris',
    country: 'França',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Paris', 'contra dores de cabeça'],
    biographyShort:
      'Primeiro bispo de Paris, martirizado por decapitação no século III. Segundo a tradição, carregou a própria cabeça após o martírio.',
    biographyFull:
      'Denis foi enviado da Itália para evangelizar a Gália no século III. Estabeleceu-se em Paris, onde se tornou o primeiro bispo da cidade, convertendo muitos ao cristianismo.\n\nDurante a perseguição do imperador Décio, foi preso juntamente com o padre Rústico e o diácono Eleutério. Os três foram decapitados na colina de Montmartre (Monte dos Mártires).\n\nSegundo a tradição, Denis levantou-se após a decapitação, carregou a própria cabeça e caminhou vários quilômetros pregando. É padroeiro de Paris e a Basílica de Saint-Denis tornou-se necrópole dos reis franceses.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.94,
    longitude: 2.36,
  },
  {
    name: 'São Daniel Comboni',
    slug: 'sao-daniel-comboni',
    feastMonth: 10,
    feastDay: 10,
    birthDate: '1831-03-15',
    deathDate: '1881-10-10',
    birthPlace: 'Limone sul Garda',
    deathPlace: 'Cartum',
    country: 'Itália',
    century: 19,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['missões na África', 'missionários'],
    biographyShort:
      'Missionário italiano que dedicou sua vida à evangelização da África Central, fundando os Missionários Combonianos.',
    biographyFull:
      'Daniel Comboni nasceu em 1831 em Limone sul Garda, norte da Itália. Aos 26 anos partiu para sua primeira missão na África, onde ficou profundamente marcado pelo sofrimento do povo.\n\nElaborou o "Plano para a Regeneração da África", propondo formar africanos como evangelizadores de seu próprio continente. Fundou os Missionários Combonianos e as Irmãs Missionárias Combonianas.\n\nFoi nomeado primeiro bispo da África Central em 1877. Lutou contra o tráfico de escravos e promoveu a educação. Faleceu em Cartum em 1881, aos 50 anos. Foi canonizado por Bento XVI em 2003.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 45.81,
    longitude: 10.79,
  },
  {
    name: 'São João XXIII',
    slug: 'sao-joao-xxiii',
    feastMonth: 10,
    feastDay: 11,
    birthDate: '1881-11-25',
    deathDate: '1963-06-03',
    birthPlace: 'Sotto il Monte',
    deathPlace: 'Vaticano',
    country: 'Itália',
    century: 20,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['diplomatas', 'delegados apostólicos'],
    biographyShort:
      'O "Papa Bom" que convocou o Concílio Vaticano II, abrindo as janelas da Igreja para o mundo moderno com simplicidade e bondade.',
    biographyFull:
      'Angelo Giuseppe Roncalli nasceu em 1881 numa família camponesa de Bérgamo, Itália. Ordenado sacerdote em 1904, serviu como diplomata pontifício na Bulgária, Turquia e França.\n\nEleito Papa em 1958 aos 76 anos, surpreendeu o mundo ao convocar o Concílio Vaticano II para renovar a Igreja. Publicou encíclicas históricas como "Pacem in Terris" sobre a paz mundial.\n\nConquistou o mundo por sua simplicidade, humor e bondade pastoral, sendo chamado de "Papa Bom". Faleceu em 1963 durante o Concílio. Foi canonizado pelo Papa Francisco em 2014.',
    biographyKids: null,
    quotes: [{ text: 'Procurai aquilo que nos une, não o que nos divide.', source: 'Discurso de abertura do Concílio' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.72,
    longitude: 9.50,
  },
  {
    name: 'Nossa Senhora Aparecida',
    slug: 'nossa-senhora-aparecida',
    feastMonth: 10,
    feastDay: 12,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Brasil',
    century: 18,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Brasil', 'pescadores'],
    biographyShort:
      'Padroeira do Brasil, cuja imagem foi encontrada por pescadores no rio Paraíba do Sul em 1717, tornando-se o maior símbolo da fé católica brasileira.',
    biographyFull:
      'Em outubro de 1717, três pescadores lançaram suas redes no rio Paraíba do Sul, em São Paulo, e encontraram uma pequena imagem de terracota de Nossa Senhora da Conceição, sem a cabeça. Logo depois, pescaram a cabeça.\n\nApós a descoberta, a pesca tornou-se abundante. A imagem escura, de cerca de 36 centímetros, passou a ser venerada na região. Uma capela foi construída e os milagres multiplicaram-se.\n\nEm 1930, Pio XI proclamou Nossa Senhora Aparecida Padroeira do Brasil. O Santuário Nacional em Aparecida é o segundo maior templo católico do mundo e recebe milhões de peregrinos anualmente.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: -22.85,
    longitude: -45.23,
  },
  {
    name: 'São Eduardo Confessor',
    slug: 'sao-eduardo-confessor',
    feastMonth: 10,
    feastDay: 13,
    birthDate: '1003-01-01',
    deathDate: '1066-01-05',
    birthPlace: 'Islip',
    deathPlace: 'Londres',
    country: 'Inglaterra',
    century: 11,
    category: 'LAYPERSON',
    gender: 'MALE',
    patronage: ['reis', 'matrimônios difíceis'],
    biographyShort:
      'Rei da Inglaterra conhecido por sua piedade e justiça, construtor da Abadia de Westminster, canonizado em 1161.',
    biographyFull:
      'Eduardo nasceu por volta de 1003, filho do rei Etelredo II. Passou a juventude exilado na Normandia durante a dominação dinamarquesa. Retornou à Inglaterra e foi coroado rei em 1042.\n\nGovernou com justiça e piedade, sendo conhecido pela generosidade com os pobres e pela devoção religiosa. Sua maior realização foi a construção da Abadia de Westminster, consagrada em 1065.\n\nFaleceu em janeiro de 1066, pouco após a consagração da Abadia. Foi canonizado pelo Papa Alexandre III em 1161 e permanece como um dos santos mais venerados da Inglaterra.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 51.75,
    longitude: -1.26,
  },
  {
    name: 'São Calisto I',
    slug: 'sao-calisto-i',
    feastMonth: 10,
    feastDay: 14,
    birthDate: null,
    deathDate: '222-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['coveiros', 'cemitérios'],
    biographyShort:
      'Papa e mártir do século III, antigo escravo que organizou as catacumbas romanas e defendeu a misericórdia para os pecadores arrependidos.',
    biographyFull:
      'Calisto nasceu em Roma, provavelmente de origem escrava. Após uma juventude turbulenta, converteu-se e foi ordenado diácono pelo Papa Zeferino, que lhe confiou a administração do cemitério cristão na Via Ápia.\n\nEleito Papa em 217, defendeu a possibilidade de reconciliação para pecadores graves, enfrentando a oposição rigorista de Hipólito. Também reconheceu a validade de casamentos entre pessoas de diferentes classes sociais.\n\nFoi martirizado por volta de 222 durante um tumulto popular. As catacumbas que administrou levam seu nome e são um dos mais importantes sítios arqueológicos cristãos de Roma.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.50,
  },
  {
    name: 'Santa Teresa de Jesus',
    slug: 'santa-teresa-de-jesus',
    feastMonth: 10,
    feastDay: 15,
    birthDate: '1515-03-28',
    deathDate: '1582-10-04',
    birthPlace: 'Ávila',
    deathPlace: 'Alba de Tormes',
    country: 'Espanha',
    century: 16,
    category: 'DOCTOR',
    gender: 'FEMALE',
    patronage: ['escritores', 'pessoas doentes'],
    biographyShort:
      'Mística espanhola e Doutora da Igreja que reformou a Ordem Carmelita e deixou obras-primas da literatura espiritual como "O Castelo Interior".',
    biographyFull:
      'Teresa de Cepeda y Ahumada nasceu em Ávila, Espanha, em 1515. Ingressou no Carmelo da Encarnação aos 20 anos e, após anos de vida morna, experimentou uma profunda conversão que a levou a altas experiências místicas.\n\nEm 1562, fundou o primeiro convento carmelita reformado, iniciando a reforma que deu origem aos Carmelitas Descalços, com o apoio de São João da Cruz. Fundou 17 conventos apesar de constante oposição e problemas de saúde.\n\nSuas obras — "O Livro da Vida", "Caminho de Perfeição" e "O Castelo Interior" — são clássicos da mística cristã. Faleceu em 1582, foi canonizada em 1622 e declarada Doutora da Igreja em 1970, primeira mulher a receber o título.',
    biographyKids: null,
    quotes: [{ text: 'Nada te perturbe, nada te espante. Tudo passa. Deus não muda.', source: 'Poesia de Santa Teresa' }],
    prayer: null,
    imageUrl: null,
    latitude: 40.66,
    longitude: -4.70,
  },
  {
    name: 'Santa Margarida Maria Alacoque',
    slug: 'santa-margarida-maria-alacoque',
    feastMonth: 10,
    feastDay: 16,
    birthDate: '1647-07-22',
    deathDate: '1690-10-17',
    birthPlace: 'Lauthecourt',
    deathPlace: 'Paray-le-Monial',
    country: 'França',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['devoção ao Sagrado Coração', 'pessoas doentes'],
    biographyShort:
      'Religiosa visitandina francesa que recebeu de Jesus as revelações do Sagrado Coração, promovendo a devoção que se espalhou por toda a Igreja.',
    biographyFull:
      'Margarida Maria nasceu em 1647 na Borgonha, França. Desde criança sentia atração pela oração e pelo sofrimento. Ingressou na Ordem da Visitação em Paray-le-Monial em 1671.\n\nEntre 1673 e 1675, recebeu revelações de Jesus pedindo a devoção ao Seu Sagrado Coração, com práticas como a Comunhão nas primeiras sextas-feiras e a Hora Santa. Enfrentou grande incompreensão, mas foi apoiada por seu diretor espiritual, São Cláudio de la Colombière.\n\nFaleceu em 1690 aos 43 anos. A devoção ao Sagrado Coração propagou-se por toda a Igreja. Foi canonizada em 1920 por Bento XV.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.45,
    longitude: 4.12,
  },
  {
    name: 'Santo Inácio de Antioquia',
    slug: 'santo-inacio-de-antioquia',
    feastMonth: 10,
    feastDay: 17,
    birthDate: '35-01-01',
    deathDate: '107-01-01',
    birthPlace: 'Síria',
    deathPlace: 'Roma',
    country: 'Síria',
    century: 2,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Igreja do Oriente', 'contra doenças da garganta'],
    biographyShort:
      'Bispo de Antioquia e Padre Apostólico que escreveu sete cartas teológicas a caminho do martírio no Coliseu de Roma.',
    biographyFull:
      'Inácio foi o terceiro bispo de Antioquia, possivelmente discípulo direto do apóstolo João. Governou a comunidade cristã durante décadas de crescimento e perseguição.\n\nCondenado ao martírio pelo imperador Trajano, foi levado acorrentado de Antioquia a Roma. Durante a viagem, escreveu sete cartas às comunidades cristãs, nas quais defendeu a autoridade episcopal, a presença real de Cristo na Eucaristia e a unidade da Igreja.\n\nFoi devorado por leões no Coliseu de Roma por volta de 107. Suas cartas são documentos preciosos da teologia cristã primitiva e o primeiro uso registrado do termo "Igreja Católica".',
    biographyKids: null,
    quotes: [{ text: 'Sou trigo de Deus, moído pelos dentes das feras.', source: 'Carta aos Romanos' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.20,
    longitude: 36.16,
  },
  {
    name: 'São Lucas Evangelista',
    slug: 'sao-lucas-evangelista',
    feastMonth: 10,
    feastDay: 18,
    birthDate: null,
    deathDate: '84-01-01',
    birthPlace: 'Antioquia',
    deathPlace: 'Beócia',
    country: 'Grécia',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['médicos', 'pintores'],
    biographyShort:
      'Médico grego, companheiro de São Paulo e autor do Evangelho de Lucas e dos Atos dos Apóstolos.',
    biographyFull:
      'Lucas era um médico grego de Antioquia que se converteu ao cristianismo e tornou-se companheiro inseparável de São Paulo em suas viagens missionárias. Paulo o chamava de "médico amado" (Cl 4,14).\n\nEscreveu o terceiro Evangelho, dedicado a Teófilo, destacando a misericórdia de Jesus para com os pecadores, os pobres e as mulheres. Também escreveu os Atos dos Apóstolos, narrando a expansão da Igreja primitiva.\n\nA tradição o associa à pintura de ícones da Virgem Maria. Faleceu por volta do ano 84 na Beócia, Grécia. É padroeiro dos médicos e dos artistas.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 36.20,
    longitude: 36.16,
  },
  {
    name: 'São João de Brébeuf',
    slug: 'sao-joao-de-brebeuf',
    feastMonth: 10,
    feastDay: 19,
    birthDate: '1593-03-25',
    deathDate: '1649-03-16',
    birthPlace: 'Condé-sur-Vire',
    deathPlace: 'Saint-Ignace',
    country: 'França',
    century: 17,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Canadá', 'missionários'],
    biographyShort:
      'Jesuíta francês que evangelizou os índios hurões no Canadá e sofreu terrível martírio nas mãos dos iroqueses em 1649.',
    biographyFull:
      'João de Brébeuf nasceu na Normandia em 1593 e ingressou na Companhia de Jesus. Em 1625 partiu para a Nova França (Canadá), onde dedicou-se à evangelização do povo hurão.\n\nAprendeu a língua nativa, compilou um dicionário hurão e adaptou-se ao estilo de vida indígena. Foi respeitado pelos hurões por sua coragem e resistência física.\n\nEm 1649, foi capturado pelos iroqueses junto com o padre Gabriel Lalemant. Sofreu torturas horríveis antes de morrer. É um dos oito Mártires Canadenses, canonizados em 1930 e padroeiros do Canadá.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.90,
    longitude: -1.05,
  },
  {
    name: 'São Paulo da Cruz',
    slug: 'sao-paulo-da-cruz',
    feastMonth: 10,
    feastDay: 20,
    birthDate: '1694-01-03',
    deathDate: '1775-10-18',
    birthPlace: 'Ovada',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 18,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['Congregação dos Passionistas', 'contra a solidão'],
    biographyShort:
      'Místico italiano que fundou a Congregação dos Passionistas, dedicada à pregação da Paixão de Cristo como caminho de salvação.',
    biographyFull:
      'Paulo Francisco Danei nasceu em 1694 em Ovada, Itália. Após uma experiência mística profunda, recebeu a inspiração de fundar uma congregação dedicada à meditação e pregação da Paixão de Cristo.\n\nEm 1720 redigiu a Regra dos Passionistas durante um retiro de quarenta dias. Após anos de dificuldades, obteve aprovação papal e fundou o primeiro retiro no Monte Argentário. A congregação cresceu e dedicou-se às missões populares.\n\nPaulo era famoso como pregador e diretor espiritual, dotado de dons místicos extraordinários. Faleceu em Roma em 1775, aos 81 anos. Foi canonizado por Pio IX em 1867.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 44.64,
    longitude: 8.65,
  },
  {
    name: 'Santa Úrsula',
    slug: 'santa-ursula',
    feastMonth: 10,
    feastDay: 21,
    birthDate: null,
    deathDate: '383-01-01',
    birthPlace: 'Britânia',
    deathPlace: 'Colônia',
    country: 'Alemanha',
    century: 4,
    category: 'MARTYR',
    gender: 'FEMALE',
    patronage: ['estudantes', 'educadoras'],
    biographyShort:
      'Princesa cristã britânica martirizada com suas companheiras pelos hunos em Colônia, tornando-se padroeira das estudantes e educadoras.',
    biographyFull:
      'Segundo a tradição, Úrsula era uma princesa cristã da Britânia que, prometida em casamento a um príncipe pagão, fez uma peregrinação a Roma com suas companheiras virgens.\n\nNo retorno, ao passarem por Colônia, a cidade estava sitiada pelos hunos. Úrsula e suas companheiras foram capturadas. Úrsula recusou casar com o chefe huno e todas foram martirizadas por volta do século IV.\n\nSeu culto espalhou-se por toda a Europa medieval. A Ordem das Ursulinas, fundada por Santa Ângela Merici em 1535, adotou-a como padroeira, dedicando-se à educação feminina.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.94,
    longitude: 6.96,
  },
  {
    name: 'São João Paulo II',
    slug: 'sao-joao-paulo-ii',
    feastMonth: 10,
    feastDay: 22,
    birthDate: '1920-05-18',
    deathDate: '2005-04-02',
    birthPlace: 'Wadowice',
    deathPlace: 'Vaticano',
    country: 'Polônia',
    century: 20,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['jovens', 'famílias'],
    biographyShort:
      'Papa polonês cujo pontificado de 27 anos transformou a Igreja e o mundo, sendo protagonista na queda do comunismo e no diálogo inter-religioso.',
    biographyFull:
      'Karol Wojtyła nasceu em 1920 em Wadowice, Polônia. Sobreviveu à ocupação nazista, ordenou-se sacerdote em 1946 e tornou-se arcebispo de Cracóvia. Foi eleito Papa em 1978, o primeiro não italiano em 455 anos.\n\nSeu pontificado foi marcado por 104 viagens internacionais, o papel decisivo na queda do comunismo, o encontro inter-religioso de Assis e a criação das Jornadas Mundiais da Juventude. Sobreviveu a um atentado em 1981 e perdoou publicamente seu agressor.\n\nFaleceu em 2005 após longa luta contra o Parkinson, testemunhando o valor redentor do sofrimento. Foi canonizado pelo Papa Francisco em 2014.',
    biographyKids: null,
    quotes: [{ text: 'Não tenhais medo! Abri as portas a Cristo!', source: 'Homilia de inauguração do pontificado' }],
    prayer: null,
    imageUrl: null,
    latitude: 49.88,
    longitude: 19.49,
  },
  {
    name: 'São João de Capistrano',
    slug: 'sao-joao-de-capistrano',
    feastMonth: 10,
    feastDay: 23,
    birthDate: '1386-06-24',
    deathDate: '1456-10-23',
    birthPlace: 'Capestrano',
    deathPlace: 'Ilok',
    country: 'Itália',
    century: 15,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['juristas', 'capelães militares'],
    biographyShort:
      'Jurista italiano que se tornou franciscano e pregador itinerante, liderando a defesa de Belgrado contra o avanço otomano em 1456.',
    biographyFull:
      'João nasceu em 1386 em Capestrano, nos Abruzos. Estudou Direito em Perúgia e tornou-se governador da cidade. Preso durante um conflito, teve uma visão de São Francisco e ingressou na Ordem Franciscana.\n\nTornou-se um dos maiores pregadores de sua época, percorrendo a Europa combatendo heresias e promovendo a reforma dos costumes. São Bernardino de Sena foi seu mestre espiritual.\n\nEm 1456, aos 70 anos, liderou a cruzada que venceu o cerco otomano de Belgrado, ao lado de João Hunyadi. Faleceu poucos meses depois em Ilok. Foi canonizado em 1724.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 42.27,
    longitude: 13.78,
  },
  {
    name: 'Santo Antônio Maria Claret',
    slug: 'santo-antonio-maria-claret',
    feastMonth: 10,
    feastDay: 24,
    birthDate: '1807-12-23',
    deathDate: '1870-10-24',
    birthPlace: 'Sallent',
    deathPlace: 'Fontfroide',
    country: 'Espanha',
    century: 19,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['editores', 'tecelões'],
    biographyShort:
      'Arcebispo espanhol que fundou os Missionários Claretianos e promoveu intensamente a imprensa católica como instrumento de evangelização.',
    biographyFull:
      'Antônio Claret nasceu em 1807 em Sallent, Catalunha. Após trabalhar como tecelão, foi ordenado sacerdote e dedicou-se à pregação missionária por toda a Espanha.\n\nEm 1849 fundou os Missionários Filhos do Imaculado Coração de Maria (Claretianos). Foi nomeado arcebispo de Santiago de Cuba, onde enfrentou a escravidão, a corrupção e sofreu quinze atentados contra sua vida.\n\nDe volta à Espanha, serviu como confessor da rainha Isabel II. Foi pioneiro no uso da imprensa para a evangelização, publicando centenas de obras. Faleceu exilado na França em 1870. Foi canonizado em 1950.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.83,
    longitude: 1.89,
  },
  {
    name: 'São Crispim e São Crispiniano',
    slug: 'sao-crispim-e-sao-crispiniano',
    feastMonth: 10,
    feastDay: 25,
    birthDate: null,
    deathDate: '286-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Soissons',
    country: 'França',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['sapateiros', 'curtidores'],
    biographyShort:
      'Irmãos romanos que evangelizaram a Gália trabalhando como sapateiros e foram martirizados em Soissons durante a perseguição de Diocleciano.',
    biographyFull:
      'Crispim e Crispiniano eram irmãos nobres romanos que partiram para a Gália no século III para evangelizar. Estabeleceram-se em Soissons, onde trabalhavam como sapateiros durante o dia e pregavam o Evangelho à noite.\n\nSeu testemunho de vida simples e trabalho honesto atraiu muitos convertidos. Durante a perseguição de Diocleciano, foram presos pelo governador Rictiovaro.\n\nSegundo a tradição, resistiram a diversas torturas antes de serem decapitados por volta de 286. Tornaram-se padroeiros dos sapateiros e sua festa foi imortalizada por Shakespeare em "Henrique V".',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 49.38,
    longitude: 3.32,
  },
  {
    name: 'São Evaristo',
    slug: 'sao-evaristo',
    feastMonth: 10,
    feastDay: 26,
    birthDate: null,
    deathDate: '105-01-01',
    birthPlace: 'Belém',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 2,
    category: 'POPE',
    gender: 'MALE',
    patronage: ['diocese de Roma', 'papas'],
    biographyShort:
      'Quinto Papa da Igreja, de origem grega, que organizou as paróquias de Roma e governou durante as perseguições do imperador Trajano.',
    biographyFull:
      'Evaristo nasceu em Belém, de família grega judaica. Tornou-se o quinto Papa da Igreja, sucedendo a São Clemente I, governando aproximadamente de 97 a 105.\n\nSegundo a tradição, dividiu Roma em paróquias e designou sacerdotes para cada uma, organizando a estrutura pastoral da cidade. Também teria instituído o costume de sete diáconos acompanharem o bispo durante a pregação.\n\nGovernou a Igreja durante a perseguição do imperador Trajano. Embora a tradição o considere mártir, os detalhes de sua morte são incertos. É venerado como santo desde os primeiros séculos.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.90,
    longitude: 12.50,
  },
  {
    name: 'São Frumêncio',
    slug: 'sao-frumencio',
    feastMonth: 10,
    feastDay: 27,
    birthDate: null,
    deathDate: '383-01-01',
    birthPlace: 'Tiro',
    deathPlace: 'Axum',
    country: 'Etiópia',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['Etiópia', 'evangelização da África'],
    biographyShort:
      'Apóstolo da Etiópia que, após ser capturado na infância, converteu o rei de Axum e tornou-se o primeiro bispo do país.',
    biographyFull:
      'Frumêncio era um jovem de Tiro que, durante uma viagem com seu tio, foi capturado por piratas na costa do Mar Vermelho e levado como escravo ao reino de Axum, na Etiópia.\n\nGraças à sua inteligência, ganhou a confiança do rei e tornou-se tutor do príncipe Ezana. Quando Ezana assumiu o trono, Frumêncio influenciou sua conversão ao cristianismo.\n\nViajou a Alexandria, onde Santo Atanásio o consagrou bispo. Retornou à Etiópia e evangelizou o reino, estabelecendo a Igreja que perdura até hoje. É venerado como "Abba Salama" (Pai da Paz) pela Igreja Etíope.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 14.13,
    longitude: 38.72,
  },
  {
    name: 'São Simão e São Judas Tadeu',
    slug: 'sao-simao-e-sao-judas-tadeu',
    feastMonth: 10,
    feastDay: 28,
    birthDate: null,
    deathDate: '65-01-01',
    birthPlace: 'Galileia',
    deathPlace: 'Pérsia',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['causas impossíveis', 'situações desesperadas'],
    biographyShort:
      'Apóstolos de Jesus que, segundo a tradição, evangelizaram juntos a Pérsia e ali foram martirizados. Judas Tadeu é invocado nas causas impossíveis.',
    biographyFull:
      'Simão, chamado "o Zelote", e Judas Tadeu, parente de Jesus e autor de uma epístola canônica, foram dois dos doze apóstolos escolhidos por Cristo.\n\nApós Pentecostes, segundo a tradição, pregaram separadamente no Oriente Médio e na Pérsia, onde se encontraram e evangelizaram juntos. Ali conquistaram muitos convertidos pela pregação e pelos milagres.\n\nForam martirizados juntos na Pérsia, por volta do ano 65. Judas Tadeu tornou-se especialmente popular como intercessor nas causas impossíveis e desesperadas, sendo um dos santos mais invocados no Brasil.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 32.70,
    longitude: 35.30,
  },
  {
    name: 'São Narciso de Jerusalém',
    slug: 'sao-narciso-de-jerusalem',
    feastMonth: 10,
    feastDay: 29,
    birthDate: null,
    deathDate: '212-01-01',
    birthPlace: 'Jerusalém',
    deathPlace: 'Jerusalém',
    country: 'Israel',
    century: 2,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Jerusalém', 'idosos'],
    biographyShort:
      'Bispo de Jerusalém que, caluniado injustamente, retirou-se ao deserto e retornou na velhice para governar a diocese com sabedoria.',
    biographyFull:
      'Narciso tornou-se bispo de Jerusalém por volta do ano 185, já em idade avançada. Era conhecido por sua austeridade e firmeza na disciplina eclesiástica.\n\nFalsamente acusado por clérigos descontentes, retirou-se voluntariamente ao deserto para viver como eremita. Seus acusadores sofreram castigos providenciais, e a comunidade pediu seu retorno.\n\nVoltou a governar a diocese com mais de cem anos de idade, auxiliado pelo coadjutor Alexandre. Segundo Eusébio de Cesareia, realizou milagres, incluindo a transformação de água em óleo para as lâmpadas litúrgicas. Faleceu por volta de 212.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.77,
    longitude: 35.23,
  },
  {
    name: 'São Germano de Cápua',
    slug: 'sao-germano-de-capua',
    feastMonth: 10,
    feastDay: 30,
    birthDate: null,
    deathDate: '540-01-01',
    birthPlace: 'Cápua',
    deathPlace: 'Cápua',
    country: 'Itália',
    century: 6,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Cápua', 'diplomatas eclesiásticos'],
    biographyShort:
      'Bispo de Cápua e amigo de São Bento, enviado pelo Papa como embaixador a Constantinopla para resolver o Cisma Acaciano.',
    biographyFull:
      'Germano foi bispo de Cápua no início do século VI, período de grandes tensões entre Roma e Constantinopla. O Papa Hormisdas o enviou como legado ao imperador bizantino para negociar o fim do Cisma Acaciano.\n\nSuas missões diplomáticas, embora difíceis, contribuíram para a eventual reconciliação entre as igrejas do Oriente e do Ocidente em 519.\n\nSão Gregório Magno relata nos "Diálogos" que São Bento viu a alma de Germano sendo levada ao céu por anjos no momento de sua morte, por volta de 540. Essa visão atesta a santidade reconhecida do bispo.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.21,
    longitude: 14.25,
  },
  {
    name: 'São Wolfgang de Ratisbona',
    slug: 'sao-wolfgang-de-ratisbona',
    feastMonth: 10,
    feastDay: 31,
    birthDate: '924-01-01',
    deathDate: '994-10-31',
    birthPlace: 'Pfullingen',
    deathPlace: 'Pupping',
    country: 'Alemanha',
    century: 10,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['diocese de Ratisbona', 'lenhadores'],
    biographyShort:
      'Monge beneditino e bispo de Ratisbona que reformou a vida religiosa e eclesiástica na Baviera do século X.',
    biographyFull:
      'Wolfgang nasceu por volta de 924 em Pfullingen, na Suábia. Estudou na famosa escola de Reichenau e tornou-se monge beneditino no mosteiro de Einsiedeln, na Suíça.\n\nApós uma missão evangelizadora entre os magiares na Hungria, foi nomeado bispo de Ratisbona em 972. Reformou mosteiros, restaurou a disciplina do clero e dedicou-se pessoalmente à educação e à pregação.\n\nEra conhecido por sua humildade, vivendo com simplicidade apesar da dignidade episcopal. Faleceu em 994 durante uma viagem pastoral. Foi canonizado em 1052 pelo Papa Leão IX.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 48.52,
    longitude: 9.23,
  },
];
