import type { SaintSeedData } from './types';

export const septemberSaints: SaintSeedData[] = [
  {
    name: 'São Gideão',
    slug: 'sao-gideao',
    feastMonth: 9,
    feastDay: 1,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Ofra',
    deathPlace: 'Ofra',
    country: 'Israel',
    century: -12,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['guerreiros', 'líderes'],
    biographyShort: 'Juiz de Israel, Gideão derrotou os midianitas com apenas trezentos homens, confiando na força de Deus e não no número de soldados.',
    biographyFull: 'Gideão foi um dos juízes de Israel, chamado por Deus para libertar seu povo da opressão dos midianitas. Quando o anjo do Senhor apareceu-lhe, Gideão estava malhando trigo escondido, com medo dos invasores.\n\nDeus mandou-o reduzir seu exército de 32.000 para apenas 300 homens, para que Israel reconhecesse que a vitória vinha do Senhor. Com trombetas, tochas e cântaros, os trezentos derrotaram o exército inimigo.\n\nGideão governou Israel com sabedoria por quarenta anos de paz. Sua história, narrada no livro dos Juízes (capítulos 6-8), é exemplo de fé e obediência à vontade de Deus.',
    biographyKids: null,
    quotes: [{ text: 'A espada do Senhor e de Gideão!', source: 'Jz 7,20' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.1800,
    longitude: 35.2600,
  },
  {
    name: 'Bem-aventurada Ingrid da Suécia',
    slug: 'bem-aventurada-ingrid-da-suecia',
    feastMonth: 9,
    feastDay: 2,
    birthDate: '1220-01-01',
    deathDate: '1282-09-02',
    birthPlace: 'Skänninge',
    deathPlace: 'Skänninge',
    country: 'Suécia',
    century: 13,
    category: 'RELIGIOUS',
    gender: 'FEMALE',
    patronage: ['vida religiosa', 'penitentes'],
    biographyShort: 'Nobre sueca que, após peregrinação à Terra Santa, fundou o primeiro convento dominicano feminino da Escandinávia.',
    biographyFull: 'Ingrid nasceu por volta de 1220 em Skänninge, na Suécia, numa família nobre. Após a morte de seu marido, peregrinou a Roma e à Terra Santa, experiência que transformou sua vida espiritual.\n\nDe volta à Suécia, fundou o primeiro convento de dominicanas da Escandinávia em Skänninge, dedicando-se à oração contemplativa e à penitência. Sua comunidade tornou-se centro de devoção na região.\n\nFaleceu em 2 de setembro de 1282. Seu culto foi confirmado e é venerada como bem-aventurada, sendo figura importante na história religiosa da Suécia medieval.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 58.3943,
    longitude: 15.0853,
  },
  {
    name: 'São Gregório Magno',
    slug: 'sao-gregorio-magno',
    feastMonth: 9,
    feastDay: 3,
    birthDate: '540-01-01',
    deathDate: '604-03-12',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 6,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['músicos', 'professores'],
    biographyShort: 'Papa e Doutor da Igreja, Gregório reformou a liturgia, enviou missionários à Inglaterra e é pai do canto gregoriano.',
    biographyFull: 'Gregório nasceu em Roma por volta de 540, numa família senatorial. Após brilhante carreira como prefeito de Roma, abandonou tudo para se fazer monge beneditino, transformando sua casa no mosteiro de Santo André.\n\nEleito papa em 590, governou a Igreja em tempos de peste, invasões lombardas e fome. Organizou a defesa e o abastecimento de Roma, negociou com os bárbaros e enviou monges para evangelizar a Inglaterra.\n\nReformou a liturgia e a música sacra — o canto gregoriano leva seu nome. Suas obras pastorais e teológicas, especialmente a Regra Pastoral, influenciaram toda a Idade Média. Faleceu em 604.',
    biographyKids: null,
    quotes: [{ text: 'O pastor de almas deve ser próximo de todos pela compaixão.', source: 'Regra Pastoral' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Santa Rosália de Palermo',
    slug: 'santa-rosalia-de-palermo',
    feastMonth: 9,
    feastDay: 4,
    birthDate: '1130-01-01',
    deathDate: '1166-09-04',
    birthPlace: 'Palermo',
    deathPlace: 'Monte Pellegrino',
    country: 'Itália',
    century: 12,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['Palermo', 'contra epidemias'],
    biographyShort: 'Eremita siciliana, Rosália viveu em oração solitária no Monte Pellegrino e é invocada como protetora de Palermo contra as pestes.',
    biographyFull: 'Rosália nasceu em Palermo por volta de 1130, possivelmente de família nobre ligada aos reis normandos da Sicília. Ainda jovem, abandonou a vida mundana para se retirar como eremita.\n\nViveu em cavernas nos montes próximos a Palermo, primeiro em Quisquina e depois no Monte Pellegrino, onde passou seus últimos anos em oração e penitência solitária. Ali faleceu por volta de 1166.\n\nEm 1624, durante uma terrível peste em Palermo, seus restos foram descobertos no Monte Pellegrino. Após uma procissão com suas relíquias, a epidemia cessou. Desde então é padroeira de Palermo e invocada contra pestilências.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 38.1157,
    longitude: 13.3615,
  },
  {
    name: 'Santa Teresa de Calcutá',
    slug: 'santa-teresa-de-calcuta',
    feastMonth: 9,
    feastDay: 5,
    birthDate: '1910-08-26',
    deathDate: '1997-09-05',
    birthPlace: 'Escópia',
    deathPlace: 'Calcutá',
    country: 'Macedônia',
    century: 20,
    category: 'FOUNDER',
    gender: 'FEMALE',
    patronage: ['missionários', 'voluntários'],
    biographyShort: 'Fundadora das Missionárias da Caridade, Madre Teresa dedicou sua vida aos mais pobres dos pobres nas ruas de Calcutá.',
    biographyFull: 'Anjezë Gonxhe Bojaxhiu nasceu em Escópia em 1910, de família albanesa. Aos 18 anos entrou nas Irmãs de Loreto e foi enviada à Índia. Em 1946, num trem para Darjeeling, sentiu o chamado a servir os mais pobres.\n\nEm 1950 fundou as Missionárias da Caridade, que se dedicam aos moribundos, leprosos, órfãos e abandonados. A congregação espalhou-se por mais de 130 países. Recebeu o Nobel da Paz em 1979.\n\nApesar de décadas de aridez espiritual interior, manteve sua fé e serviço inabaláveis. Faleceu em Calcutá em 1997 e foi canonizada pelo papa Francisco em 2016.',
    biographyKids: null,
    quotes: [{ text: 'Se você julgar as pessoas, não terá tempo para amá-las.', source: 'Santa Teresa de Calcutá' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.9973,
    longitude: 21.4280,
  },
  {
    name: 'São Zacarias e Santa Isabel',
    slug: 'sao-zacarias-e-santa-isabel',
    feastMonth: 9,
    feastDay: 6,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Ain Karim',
    deathPlace: 'Ain Karim',
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['casais idosos', 'pais'],
    biographyShort: 'Pais de São João Batista, Zacarias e Isabel eram justos diante de Deus e receberam o filho na velhice como sinal da fidelidade divina.',
    biographyFull: 'Zacarias era sacerdote da classe de Abias e Isabel descendente de Aarão. Ambos eram justos e irrepreensíveis, mas não tinham filhos e já eram idosos. O Evangelho de Lucas narra sua história.\n\nEnquanto Zacarias oferecia incenso no Templo, o anjo Gabriel apareceu-lhe anunciando o nascimento de um filho que seria grande diante do Senhor. Por ter duvidado, Zacarias ficou mudo até o nascimento da criança.\n\nIsabel acolheu Maria grávida de Jesus, proclamando: "Bendita és tu entre as mulheres!" No nascimento de João, Zacarias recuperou a fala e entoou o cântico do Benedictus, profetizando a missão do filho.',
    biographyKids: null,
    quotes: [{ text: 'Bendito o Senhor, Deus de Israel, porque visitou e redimiu o seu povo.', source: 'Lc 1,68' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7544,
    longitude: 35.1544,
  },
  {
    name: 'São Régino',
    slug: 'sao-regino',
    feastMonth: 9,
    feastDay: 7,
    birthDate: null,
    deathDate: '260-01-01',
    birthPlace: 'Autun',
    deathPlace: 'Autun',
    country: 'França',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['diocese de Autun', 'mártires'],
    biographyShort: 'Bispo de Autun, Régino sofreu o martírio durante as perseguições do século III por sua fidelidade à fé cristã.',
    biographyFull: 'São Régino foi bispo de Autun, na Borgonha, durante o século III. Governou sua diocese com zelo pastoral num período de intensas perseguições contra os cristãos no Império Romano.\n\nDedicou-se à evangelização da região, convertendo muitos pagãos ao cristianismo. Sua pregação corajosa atraiu a atenção das autoridades romanas, que o prenderam.\n\nFoi martirizado por volta do ano 260, provavelmente durante a perseguição de Valeriano. Seus restos são venerados na catedral de Autun e é celebrado como padroeiro da diocese.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.9514,
    longitude: 4.2994,
  },
  {
    name: 'Natividade de Nossa Senhora',
    slug: 'natividade-de-nossa-senhora',
    feastMonth: 9,
    feastDay: 8,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['nascimentos', 'grávidas'],
    biographyShort: 'A festa celebra o nascimento da Virgem Maria, filha de Joaquim e Ana, aurora da salvação e mãe do Redentor.',
    biographyFull: 'A Natividade de Nossa Senhora é uma das festas marianas mais antigas, celebrada desde o século V. Recorda o nascimento de Maria, que a tradição situa em Jerusalém ou Nazaré, filha dos santos Joaquim e Ana.\n\nO nascimento de Maria marca o início da realização das promessas divinas de salvação. Ela foi concebida sem pecado original, preparada por Deus desde o primeiro instante para ser a Mãe do Salvador.\n\nA liturgia celebra este dia com alegria, pois o nascimento de Maria anuncia a proximidade da vinda de Cristo. Como diz a antífona: "Teu nascimento, ó Virgem Mãe de Deus, anunciou alegria ao mundo inteiro."',
    biographyKids: null,
    quotes: [{ text: 'Teu nascimento, ó Virgem Mãe de Deus, anunciou alegria ao mundo inteiro.', source: 'Antífona litúrgica' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São Pedro Claver',
    slug: 'sao-pedro-claver',
    feastMonth: 9,
    feastDay: 9,
    birthDate: '1580-06-26',
    deathDate: '1654-09-08',
    birthPlace: 'Verdú',
    deathPlace: 'Cartagena das Índias',
    country: 'Espanha',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['missões entre africanos', 'direitos humanos'],
    biographyShort: 'Jesuíta espanhol que se declarou "escravo dos escravos para sempre", Pedro Claver dedicou quarenta anos ao cuidado dos africanos escravizados em Cartagena.',
    biographyFull: 'Pedro Claver nasceu em Verdú, Catalunha, em 1580. Entrou na Companhia de Jesus e, inspirado pelo irmão Alonso Rodríguez, partiu para a América, estabelecendo-se em Cartagena das Índias, principal porto negreiro das Américas.\n\nAssinou seu voto como "Pedro Claver, escravo dos escravos para sempre." Durante quarenta anos, subia aos navios negreiros para cuidar dos africanos recém-chegados, oferecendo comida, remédios, catequese e batismo. Estima-se que batizou mais de 300 mil pessoas.\n\nNos últimos anos, paralítico e esquecido, sofreu abandono e negligência. Faleceu em 1654 e foi canonizado em 1888, sendo proclamado padroeiro das missões entre os povos africanos.',
    biographyKids: null,
    quotes: [{ text: 'Pedro Claver, escravo dos escravos para sempre.', source: 'Voto de São Pedro Claver' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.6090,
    longitude: 1.1450,
  },
  {
    name: 'São Nicolau de Tolentino',
    slug: 'sao-nicolau-de-tolentino',
    feastMonth: 9,
    feastDay: 10,
    birthDate: '1245-01-01',
    deathDate: '1305-09-10',
    birthPlace: 'Sant\'Angelo in Pontano',
    deathPlace: 'Tolentino',
    country: 'Itália',
    century: 14,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['almas do purgatório', 'mães'],
    biographyShort: 'Frade agostiniano célebre por suas visões das almas do purgatório, Nicolau dedicou-se à pregação e à oração pelos defuntos em Tolentino.',
    biographyFull: 'Nicolau nasceu em Sant\'Angelo in Pontano, na região das Marcas, Itália, por volta de 1245. Seus pais, idosos e sem filhos, fizeram uma peregrinação a Bari pedindo a intercessão de São Nicolau, e em sua honra deram o nome ao filho.\n\nEntrou na Ordem dos Agostinianos e foi ordenado sacerdote. Estabeleceu-se em Tolentino, onde viveu por trinta anos pregando, confessando e assistindo os doentes e pobres. Tinha grande devoção pelas almas do purgatório.\n\nFoi favorecido com visões místicas e operou muitos milagres. Faleceu em 10 de setembro de 1305 e foi canonizado em 1446, sendo o primeiro santo agostiniano oficialmente canonizado.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 43.2083,
    longitude: 13.2847,
  },
  {
    name: 'São Proto e São Jacinto',
    slug: 'sao-proto-e-sao-jacinto',
    feastMonth: 9,
    feastDay: 11,
    birthDate: null,
    deathDate: '257-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Roma',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['servos fiéis', 'mártires'],
    biographyShort: 'Irmãos romanos martirizados no século III, Proto e Jacinto eram servidores cristãos que deram a vida pela fé durante as perseguições imperiais.',
    biographyFull: 'Proto e Jacinto eram irmãos romanos do século III, possivelmente servidores ou libertos de uma família nobre. Segundo a tradição, eram eunucos que serviam a Santa Eugênia e se converteram ao cristianismo.\n\nForam martirizados em Roma durante as perseguições do século III, provavelmente sob o imperador Valeriano, por volta do ano 257. Recusaram-se a oferecer sacrifícios aos deuses pagãos.\n\nSeus túmulos foram descobertos na catacumba de São Hermes, na Via Salária. Em 1845, o arqueólogo Giuseppe Marchi encontrou o sarcófago de São Jacinto com a inscrição original, confirmando a historicidade de seu culto.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Santíssimo Nome de Maria',
    slug: 'santissimo-nome-de-maria',
    feastMonth: 9,
    feastDay: 12,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['devoção mariana', 'vitória sobre inimigos da fé'],
    biographyShort: 'A festa do Santo Nome de Maria celebra a doçura e o poder do nome da Mãe de Deus, invocado como auxílio e proteção dos cristãos.',
    biographyFull: 'A festa do Santíssimo Nome de Maria foi celebrada pela primeira vez na Espanha em 1513 e estendida à Igreja universal pelo papa Inocêncio XI em 1683, em ação de graças pela vitória na Batalha de Viena contra os turcos otomanos.\n\nO nome Maria, em hebraico Miriam, tem sido interpretado como "estrela do mar", "senhora" ou "amada de Deus". É o nome mais venerado depois do de Jesus na tradição cristã.\n\nA celebração convida os fiéis a invocar com confiança o nome de Maria em todas as necessidades, reconhecendo nela a mãe e intercessora que Deus concedeu à Igreja.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São João Crisóstomo',
    slug: 'sao-joao-crisostomo',
    feastMonth: 9,
    feastDay: 13,
    birthDate: '349-01-01',
    deathDate: '407-09-14',
    birthPlace: 'Antioquia',
    deathPlace: 'Comana Pôntica',
    country: 'Turquia',
    century: 4,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['pregadores', 'oradores'],
    biographyShort: 'Patriarca de Constantinopla e Doutor da Igreja, João recebeu o título "Crisóstomo" (Boca de Ouro) por sua eloquência incomparável na pregação.',
    biographyFull: 'João nasceu em Antioquia por volta de 349. Formou-se em retórica com o célebre Libânio e viveu anos como monge e eremita antes de ser ordenado sacerdote. Seus sermões em Antioquia atraíam multidões.\n\nEm 398 foi nomeado patriarca de Constantinopla contra sua vontade. Reformou o clero, combateu o luxo da corte e denunciou os abusos da imperatriz Eudóxia, o que lhe custou o exílio duas vezes.\n\nMorreu exausto durante uma marcha forçada para o exílio em 407. Suas homilias e comentários bíblicos são considerados obra-prima da patrística. É um dos quatro grandes Doutores da Igreja Oriental.',
    biographyKids: null,
    quotes: [{ text: 'A glória de Deus é o homem vivo.', source: 'São João Crisóstomo' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.2000,
    longitude: 36.1500,
  },
  {
    name: 'Exaltação da Santa Cruz',
    slug: 'exaltacao-da-santa-cruz',
    feastMonth: 9,
    feastDay: 14,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Jerusalém',
    deathPlace: null,
    country: 'Israel',
    century: 4,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['carpinteiros', 'lenhadores'],
    biographyShort: 'A festa celebra a descoberta da Santa Cruz por Santa Helena em 326 e sua recuperação pelo imperador Heráclio em 628 após o roubo pelos persas.',
    biographyFull: 'A Exaltação da Santa Cruz é celebrada em 14 de setembro desde o século IV. Recorda dois eventos: a descoberta da Cruz de Cristo por Santa Helena em 326 e a dedicação da Basílica do Santo Sepulcro em Jerusalém em 335.\n\nA festa ganhou novo significado em 628, quando o imperador Heráclio recuperou a relíquia da Cruz, que havia sido roubada pelos persas em 614. Heráclio carregou-a pessoalmente de volta a Jerusalém, descalço e em trajes simples.\n\nA liturgia convida os fiéis a contemplar a Cruz não como instrumento de tortura, mas como sinal de vitória e salvação. Como diz o hino: "Eis o madeiro da Cruz, do qual pendeu a salvação do mundo."',
    biographyKids: null,
    quotes: [{ text: 'Nós pregamos Cristo crucificado, escândalo para os judeus e loucura para os gentios.', source: '1Cor 1,23' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7785,
    longitude: 35.2296,
  },
  {
    name: 'Nossa Senhora das Dores',
    slug: 'nossa-senhora-das-dores',
    feastMonth: 9,
    feastDay: 15,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['enlutados', 'alfaiates'],
    biographyShort: 'A memória de Nossa Senhora das Dores contempla as sete dores de Maria, unida ao sofrimento redentor de seu Filho na Cruz.',
    biographyFull: 'A memória de Nossa Senhora das Dores, celebrada no dia seguinte à Exaltação da Santa Cruz, convida os fiéis a contemplar as sete dores de Maria: a profecia de Simeão, a fuga para o Egito, a perda de Jesus no Templo, o encontro no caminho do Calvário, a crucificação, a descida da Cruz e a sepultura.\n\nA devoção às dores de Maria desenvolveu-se especialmente a partir do século XII, promovida pela Ordem dos Servitas. A festa foi estendida à Igreja universal pelo papa Pio VII em 1814.\n\nMaria, ao pé da Cruz, uniu seu sofrimento ao sacrifício redentor de Cristo, tornando-se mãe espiritual de todos os discípulos. Sua dor não é desespero, mas oblação amorosa.',
    biographyKids: null,
    quotes: [{ text: 'Uma espada de dor transpassará a tua alma.', source: 'Lc 2,35' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7785,
    longitude: 35.2296,
  },
  {
    name: 'São Cornélio e São Cipriano',
    slug: 'sao-cornelio-e-sao-cipriano',
    feastMonth: 9,
    feastDay: 16,
    birthDate: null,
    deathDate: '258-01-01',
    birthPlace: 'Roma',
    deathPlace: 'Cartago',
    country: 'Itália',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['contra febres', 'animais domésticos'],
    biographyShort: 'O papa Cornélio e o bispo Cipriano de Cartago, unidos na defesa da unidade da Igreja, morreram mártires durante a perseguição de Valeriano.',
    biographyFull: 'Cornélio foi papa de 251 a 253, enfrentando o cisma de Novaciano sobre a readmissão dos cristãos que haviam apostatado durante as perseguições. Defendeu a misericórdia para os arrependidos.\n\nCipriano, bispo de Cartago, apoiou Cornélio na defesa da unidade eclesial. Autor de tratados fundamentais sobre a Igreja, afirmou: "Não pode ter Deus como Pai quem não tem a Igreja como Mãe."\n\nCornélio morreu no exílio em Civitavecchia em 253. Cipriano foi decapitado em Cartago em 258 durante a perseguição de Valeriano. São celebrados juntos por sua comunhão na defesa da fé.',
    biographyKids: null,
    quotes: [{ text: 'Não pode ter Deus como Pai quem não tem a Igreja como Mãe.', source: 'São Cipriano' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: 'Santa Hildegarda de Bingen',
    slug: 'santa-hildegarda-de-bingen',
    feastMonth: 9,
    feastDay: 17,
    birthDate: '1098-01-01',
    deathDate: '1179-09-17',
    birthPlace: 'Bermersheim',
    deathPlace: 'Bingen',
    country: 'Alemanha',
    century: 12,
    category: 'DOCTOR',
    gender: 'FEMALE',
    patronage: ['músicos', 'naturalistas'],
    biographyShort: 'Abadessa beneditina, mística, compositora e naturalista, Hildegarda foi proclamada Doutora da Igreja por Bento XVI em 2012.',
    biographyFull: 'Hildegarda nasceu em Bermersheim, Alemanha, em 1098. Desde a infância tinha visões místicas. Aos oito anos foi confiada à reclusa Jutta no mosteiro de Disibodenberg, onde recebeu educação monástica.\n\nTornou-se abadessa e fundou dois mosteiros. Aos 42 anos, por ordem divina, começou a registrar suas visões na obra Scivias. Compôs música litúrgica, escreveu sobre medicina natural e manteve correspondência com papas, imperadores e bispos.\n\nSua autoridade intelectual e espiritual era reconhecida em toda a Europa. Faleceu em 1179 em Bingen. Bento XVI proclamou-a Doutora da Igreja em 2012, a quarta mulher a receber o título.',
    biographyKids: null,
    quotes: [{ text: 'O ser humano é a obra completa de Deus.', source: 'Santa Hildegarda de Bingen' }],
    prayer: null,
    imageUrl: null,
    latitude: 49.7913,
    longitude: 7.8021,
  },
  {
    name: 'São José de Cupertino',
    slug: 'sao-jose-de-cupertino',
    feastMonth: 9,
    feastDay: 18,
    birthDate: '1603-06-17',
    deathDate: '1663-09-18',
    birthPlace: 'Cupertino',
    deathPlace: 'Ósimo',
    country: 'Itália',
    century: 17,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['estudantes', 'aviadores'],
    biographyShort: 'Frade franciscano célebre por suas levitações extáticas, José de Cupertino superou grandes dificuldades intelectuais para tornar-se sacerdote.',
    biographyFull: 'José nasceu em Cupertino, na Apúlia, em 1603, numa família pobre. De inteligência limitada, foi rejeitado por várias ordens religiosas antes de ser aceito como oblato pelos franciscanos conventuais.\n\nOrdenado sacerdote quase por milagre — na prova oral, foi perguntado sobre o único tema que conhecia — José tornou-se famoso por seus fenômenos místicos extraordinários, especialmente levitações durante a Missa e a oração.\n\nSuas levitações causaram tanto alvoroço que foi transferido de convento em convento pela Inquisição. Viveu com humildade e obediência até falecer em Ósimo em 1663. Foi canonizado em 1767.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 40.4689,
    longitude: 18.0693,
  },
  {
    name: 'São Januário',
    slug: 'sao-januario',
    feastMonth: 9,
    feastDay: 19,
    birthDate: '272-01-01',
    deathDate: '305-09-19',
    birthPlace: 'Benevento',
    deathPlace: 'Pozzuoli',
    country: 'Itália',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Nápoles', 'doadores de sangue'],
    biographyShort: 'Bispo de Benevento e mártir, Januário é famoso pelo milagre da liquefação de seu sangue, que ocorre três vezes ao ano em Nápoles.',
    biographyFull: 'Januário foi bispo de Benevento no início do século IV. Durante a perseguição de Diocleciano, visitou diáconos presos em Pozzuoli, foi reconhecido como cristão e preso junto com eles.\n\nSegundo a tradição, foi lançado às feras no anfiteatro, mas os animais não o tocaram. Foi então decapitado em Pozzuoli por volta de 305. Uma mulher recolheu seu sangue em duas ampolas.\n\nDesde o século XIV, o sangue coagulado de São Januário liquefaz-se milagrosamente três vezes ao ano na Catedral de Nápoles. O fenômeno nunca foi explicado pela ciência e é acompanhado por multidões de fiéis.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.0492,
    longitude: 14.6822,
  },
  {
    name: 'Santos André Kim e Paulo Chong',
    slug: 'santos-andre-kim-e-paulo-chong',
    feastMonth: 9,
    feastDay: 20,
    birthDate: '1821-08-21',
    deathDate: '1846-09-16',
    birthPlace: 'Solmoe',
    deathPlace: 'Seul',
    country: 'Coreia do Sul',
    century: 19,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['Coreia', 'clero coreano'],
    biographyShort: 'André Kim, primeiro sacerdote coreano, e Paulo Chong, catequista leigo, representam os 103 mártires da Coreia, martirizados entre 1839 e 1867.',
    biographyFull: 'André Kim Taegon nasceu em 1821 numa família cristã coreana. Estudou no seminário de Macau e foi ordenado o primeiro sacerdote coreano. Voltou clandestinamente à Coreia para evangelizar e foi preso e decapitado em 1846.\n\nPaulo Chong Hasang era um catequista leigo que organizou a comunidade católica coreana e buscou trazer sacerdotes estrangeiros ao país. Foi martirizado em 1839.\n\nJuntos representam os 103 mártires coreanos — 10 missionários franceses e 93 coreanos, incluindo bispos, sacerdotes, catequistas e leigos — canonizados por João Paulo II em Seul em 1984.',
    biographyKids: null,
    quotes: [{ text: 'Somos vinte mil católicos e todos estamos prontos para morrer pela fé.', source: 'André Kim Taegon' }],
    prayer: null,
    imageUrl: null,
    latitude: 36.7900,
    longitude: 127.0050,
  },
  {
    name: 'São Mateus Apóstolo',
    slug: 'sao-mateus-apostolo',
    feastMonth: 9,
    feastDay: 21,
    birthDate: null,
    deathDate: null,
    birthPlace: 'Cafarnaum',
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['contadores', 'banqueiros'],
    biographyShort: 'Cobrador de impostos chamado por Jesus a ser apóstolo, Mateus é autor do primeiro Evangelho e modelo de conversão radical.',
    biographyFull: 'Mateus, também chamado Levi, era cobrador de impostos em Cafarnaum, profissão desprezada pelos judeus por servir ao poder romano. Jesus passou pela sua banca e disse simplesmente: "Segue-me." Mateus levantou-se e o seguiu.\n\nEm sua casa, ofereceu um banquete a Jesus, reunindo outros publicanos e pecadores. Quando os fariseus criticaram, Jesus respondeu: "Não vim chamar os justos, mas os pecadores."\n\nMateus é autor do primeiro Evangelho, escrito para a comunidade judaico-cristã, demonstrando que Jesus é o Messias prometido. A tradição conta que pregou na Etiópia e na Pérsia, onde sofreu o martírio.',
    biographyKids: null,
    quotes: [{ text: 'Não são os sadios que precisam de médico, mas os doentes.', source: 'Mt 9,12' }],
    prayer: null,
    imageUrl: null,
    latitude: 32.8808,
    longitude: 35.5750,
  },
  {
    name: 'São Maurício',
    slug: 'sao-mauricio',
    feastMonth: 9,
    feastDay: 22,
    birthDate: null,
    deathDate: '286-01-01',
    birthPlace: 'Tebas',
    deathPlace: 'Agauno',
    country: 'Suíça',
    century: 3,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['soldados', 'tintureiros'],
    biographyShort: 'Comandante da Legião Tebana, Maurício e seus companheiros foram massacrados por recusarem sacrificar aos deuses pagãos durante uma campanha militar.',
    biographyFull: 'Maurício era comandante da Legião Tebana, composta por soldados cristãos do Egito a serviço do Império Romano. A legião foi enviada à Gália sob o imperador Maximiano por volta de 286.\n\nQuando o imperador ordenou que a tropa oferecesse sacrifícios aos deuses antes da batalha, Maurício e seus companheiros recusaram. Maximiano mandou dizimar a legião (executar um em cada dez), mas os sobreviventes mantiveram-se firmes.\n\nO imperador ordenou então o massacre de toda a legião em Agauno (atual Saint-Maurice, Suíça). Cerca de 6.600 soldados foram mortos por sua fé. O local tornou-se centro de peregrinação e ali foi fundada uma das mais antigas abadias da Europa.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 46.2189,
    longitude: 7.0033,
  },
  {
    name: 'São Pio de Pietrelcina',
    slug: 'sao-pio-de-pietrelcina',
    feastMonth: 9,
    feastDay: 23,
    birthDate: '1887-05-25',
    deathDate: '1968-09-23',
    birthPlace: 'Pietrelcina',
    deathPlace: 'San Giovanni Rotondo',
    country: 'Itália',
    century: 20,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['enfermos', 'confessores'],
    biographyShort: 'Frade capuchinho que carregou os estigmas de Cristo por cinquenta anos, Padre Pio atraiu milhões de fiéis pelo dom da confissão e dos milagres.',
    biographyFull: 'Francesco Forgione nasceu em Pietrelcina, sul da Itália, em 1887. Entrou na Ordem dos Capuchinhos aos 15 anos e foi ordenado em 1910. Em 1918, recebeu os estigmas das cinco chagas de Cristo, que carregou até a morte.\n\nEstabeleceu-se no convento de San Giovanni Rotondo, onde passava até 16 horas por dia no confessionário. Possuía dons extraordinários: bilocação, leitura de consciências, perfume sobrenatural e curas inexplicáveis.\n\nFundou a Casa Alívio do Sofrimento, grande hospital moderno. Sofreu incompreensões e restrições da Santa Sé, que foram depois revogadas. Faleceu em 1968 e foi canonizado por João Paulo II em 2002.',
    biographyKids: null,
    quotes: [{ text: 'Reza, espera e não te preocupes.', source: 'São Pio de Pietrelcina' }],
    prayer: null,
    imageUrl: null,
    latitude: 41.2040,
    longitude: 14.8490,
  },
  {
    name: 'Nossa Senhora das Mercês',
    slug: 'nossa-senhora-das-merces',
    feastMonth: 9,
    feastDay: 24,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Espanha',
    century: 13,
    category: 'VIRGIN',
    gender: 'FEMALE',
    patronage: ['cativos', 'prisioneiros'],
    biographyShort: 'Nossa Senhora das Mercês apareceu a São Pedro Nolasco, São Raimundo de Peñafort e ao rei Jaime I, inspirando a fundação da Ordem da Mercê para resgate de cativos.',
    biographyFull: 'A devoção a Nossa Senhora das Mercês nasceu em Barcelona no século XIII, quando a Espanha vivia sob ameaça constante dos mouros que escravizavam cristãos. Segundo a tradição, Maria apareceu na mesma noite a São Pedro Nolasco, a São Raimundo de Peñafort e ao rei Jaime I de Aragão.\n\nA Virgem pediu a fundação de uma ordem religiosa dedicada ao resgate de cristãos cativos dos muçulmanos. Em 1218, Pedro Nolasco fundou a Ordem de Nossa Senhora da Mercê (Mercedários), cujos membros faziam voto de se entregar como reféns se necessário.\n\nA festa foi estendida à Igreja universal pelo papa Inocêncio XII em 1696. Nossa Senhora das Mercês é invocada como protetora dos cativos e de todos os que sofrem privação de liberdade.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 41.3874,
    longitude: 2.1686,
  },
  {
    name: 'São Sérgio de Radonej',
    slug: 'sao-sergio-de-radonej',
    feastMonth: 9,
    feastDay: 25,
    birthDate: '1314-05-03',
    deathDate: '1392-09-25',
    birthPlace: 'Rostov',
    deathPlace: 'Sergiev Posad',
    country: 'Rússia',
    century: 14,
    category: 'RELIGIOUS',
    gender: 'MALE',
    patronage: ['Rússia', 'estudantes'],
    biographyShort: 'Maior santo da Rússia medieval, Sérgio fundou o Mosteiro da Trindade e foi conselheiro espiritual dos príncipes russos na luta contra os mongóis.',
    biographyFull: 'Sérgio nasceu em Rostov por volta de 1314. Após a morte dos pais, retirou-se para a floresta, onde viveu como eremita. Outros monges juntaram-se a ele e fundaram o Mosteiro da Santíssima Trindade, perto de Moscou.\n\nIntroduziu a vida cenobítica (comunitária) na Rússia, reformando o monasticismo russo. Seus discípulos fundaram mais de quarenta mosteiros, evangelizando vastas regiões. Recusou o cargo de metropolita de Moscou por humildade.\n\nAbençoou o príncipe Demétrio Donskoi antes da Batalha de Kulikovo (1380), primeira vitória russa contra os mongóis. Faleceu em 1392 e é venerado como o padroeiro espiritual da Rússia.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 56.3106,
    longitude: 38.1326,
  },
  {
    name: 'Santos Cosme e Damião',
    slug: 'santos-cosme-e-damiao',
    feastMonth: 9,
    feastDay: 26,
    birthDate: null,
    deathDate: '303-01-01',
    birthPlace: 'Egeia',
    deathPlace: 'Egeia',
    country: 'Síria',
    century: 4,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['médicos', 'farmacêuticos'],
    biographyShort: 'Irmãos gêmeos médicos que curavam gratuitamente, Cosme e Damião foram martirizados na Síria e são padroeiros dos profissionais de saúde.',
    biographyFull: 'Cosme e Damião eram irmãos gêmeos nascidos na Síria, possivelmente na cidade de Egeia (atual Cilícia). Estudaram medicina e exerceram a profissão gratuitamente, sendo chamados de "anárgiros" (sem dinheiro).\n\nCuravam tanto males do corpo como da alma, convertendo muitos ao cristianismo por meio de sua caridade. Durante a perseguição de Diocleciano, foram presos pelo governador Lísias.\n\nSofreram diversas tentativas de execução — afogamento, fogo, flechas — antes de serem finalmente decapitados por volta de 303. São muito venerados no Brasil, especialmente no Nordeste, onde sua festa é celebrada com grande devoção popular.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 36.7794,
    longitude: 35.8036,
  },
  {
    name: 'São Vicente de Paulo',
    slug: 'sao-vicente-de-paulo',
    feastMonth: 9,
    feastDay: 27,
    birthDate: '1581-04-24',
    deathDate: '1660-09-27',
    birthPlace: 'Pouy',
    deathPlace: 'Paris',
    country: 'França',
    century: 17,
    category: 'FOUNDER',
    gender: 'MALE',
    patronage: ['obras de caridade', 'prisioneiros'],
    biographyShort: 'Apóstolo da caridade, Vicente de Paulo fundou os Lazaristas e as Filhas da Caridade, revolucionando o atendimento aos pobres na França.',
    biographyFull: 'Vicente nasceu em Pouy, na Gasconha, em 1581, de família camponesa. Ordenado sacerdote, passou anos buscando uma boa posição eclesiástica até que uma profunda conversão o voltou para os pobres.\n\nFundou a Congregação da Missão (Lazaristas) em 1625 para missões rurais e formação do clero, e as Filhas da Caridade em 1633 com Santa Luísa de Marillac, primeira congregação feminina de vida ativa. Organizou assistência a crianças abandonadas, galeotes, refugiados de guerra e doentes.\n\nSua influência na Igreja e na sociedade francesa foi imensa. Faleceu em Paris em 1660 e foi proclamado padroeiro de todas as obras de caridade por Leão XIII.',
    biographyKids: null,
    quotes: [{ text: 'Os pobres são nossos senhores e mestres.', source: 'São Vicente de Paulo' }],
    prayer: null,
    imageUrl: null,
    latitude: 43.7230,
    longitude: -1.0580,
  },
  {
    name: 'São Venceslau',
    slug: 'sao-venceslau',
    feastMonth: 9,
    feastDay: 28,
    birthDate: '907-01-01',
    deathDate: '935-09-28',
    birthPlace: 'Praga',
    deathPlace: 'Stará Boleslav',
    country: 'República Tcheca',
    century: 10,
    category: 'MARTYR',
    gender: 'MALE',
    patronage: ['República Tcheca', 'cervejeiros'],
    biographyShort: 'Duque da Boêmia, Venceslau governou com piedade cristã e foi assassinado por seu irmão Boleslau, tornando-se padroeiro do povo tcheco.',
    biographyFull: 'Venceslau nasceu por volta de 907, neto de Santa Ludmila, que o educou na fé cristã. Assumiu o governo da Boêmia e promoveu a evangelização de seu povo, construindo igrejas e favorecendo os missionários.\n\nSeu governo piedoso e sua submissão ao imperador germânico desagradaram à facção pagã da nobreza, liderada por seu irmão Boleslau. Em 28 de setembro de 935, Boleslau convidou-o para uma festa e o assassinou à porta da igreja.\n\nVenceslau tornou-se imediatamente venerado como mártir e santo padroeiro da Boêmia. A praça principal de Praga leva seu nome e sua coroa é símbolo do Estado tcheco.',
    biographyKids: null,
    quotes: [],
    prayer: null,
    imageUrl: null,
    latitude: 50.0755,
    longitude: 14.4378,
  },
  {
    name: 'São Miguel São Rafael São Gabriel',
    slug: 'sao-miguel-sao-rafael-sao-gabriel',
    feastMonth: 9,
    feastDay: 29,
    birthDate: null,
    deathDate: null,
    birthPlace: null,
    deathPlace: null,
    country: 'Israel',
    century: 1,
    category: 'CONFESSOR',
    gender: 'MALE',
    patronage: ['policiais', 'padeiros', 'comunicadores'],
    biographyShort: 'A festa dos três Arcanjos celebra Miguel, o defensor; Rafael, o curador; e Gabriel, o mensageiro — os três anjos nomeados na Sagrada Escritura.',
    biographyFull: 'A festa dos Santos Arcanjos Miguel, Rafael e Gabriel reúne numa única celebração os três anjos nomeados na Bíblia. Miguel ("Quem como Deus?") é o chefe dos exércitos celestes que derrotou Satanás; Rafael ("Deus cura") acompanhou Tobias em sua jornada; Gabriel ("Força de Deus") anunciou a Maria a encarnação do Verbo.\n\nAntes da reforma litúrgica de 1969, cada arcanjo tinha festa própria. A unificação numa única celebração em 29 de setembro manteve a data tradicional de São Miguel, a mais antiga.\n\nOs arcanjos representam a ação protetora, curadora e reveladora de Deus junto à humanidade. Sua festa convida os fiéis a reconhecer a presença dos anjos como servidores de Deus a nosso favor.',
    biographyKids: null,
    quotes: [{ text: 'Quem como Deus?', source: 'Significado do nome Miguel' }],
    prayer: null,
    imageUrl: null,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'São Jerônimo',
    slug: 'sao-jeronimo',
    feastMonth: 9,
    feastDay: 30,
    birthDate: '347-01-01',
    deathDate: '420-09-30',
    birthPlace: 'Estridão',
    deathPlace: 'Belém',
    country: 'Croácia',
    century: 5,
    category: 'DOCTOR',
    gender: 'MALE',
    patronage: ['tradutores', 'bibliotecários'],
    biographyShort: 'Doutor da Igreja e maior biblista da antiguidade cristã, Jerônimo traduziu a Bíblia para o latim (Vulgata), obra que serviu a Igreja por mais de mil anos.',
    biographyFull: 'Jerônimo nasceu em Estridão, na fronteira da Dalmácia e Panônia (atual Croácia), por volta de 347. Estudou em Roma com o gramático Donato e converteu-se ao ascetismo após uma visão em que Cristo o repreendeu por ser "ciceroniano, não cristão".\n\nViveu anos como eremita no deserto da Síria, onde aprendeu hebraico. Foi secretário do papa Dâmaso em Roma, que lhe confiou a revisão da tradução latina da Bíblia. O resultado, a Vulgata, tornou-se a Bíblia oficial da Igreja por séculos.\n\nRetirou-se a Belém em 386, onde fundou mosteiros e dedicou-se à tradução e aos comentários bíblicos até sua morte em 420. De temperamento combativo, polemizou com hereges e até com outros santos.',
    biographyKids: null,
    quotes: [{ text: 'Ignorar as Escrituras é ignorar a Cristo.', source: 'São Jerônimo' }],
    prayer: null,
    imageUrl: null,
    latitude: 45.0500,
    longitude: 15.2700,
  },
];
